### ISSUE TITLE
Change the default download path for all or multiple favorites at once

### ISSUE THREAD

**Issue by SalarG** [fmd-project-team/FMD#10]
Hi.
FMD has an option to choose the default download path for new mangas, but if we wanted to change the download path of our favorites, we had to do it one by one manually. Can you add an option to simply change the download path for multiple or all mangas at once in favorites?
(For example, I want to change my default saving location from partition E:\ to F:\)

Thanks.

**Comment by admiralmikan** [comment]
> Hi.
> FMD has an option to choose the default download path for new mangas, but if we wanted to change the download path of our favorites, we had to do it one by one manually. Can you add an option to simply change the download path for multiple or all mangas at once in favorites?
> (For example, I want to change my default saving location from partition E:\ to F:)
> 
> Thanks.

For temporary solution, you can use DB Browser for SQLite program, open favorites.db, copy all entries on saveto tab to notepad, replace all original download path to newer one, copy it, and paste it back to DB Browser for SQLite saveto tab.

That's what I do in the past. I actually lost all my favorites once because I only used Notepad to open favorites.db.

**Comment by SalarG** [comment]
> 
> 
> > Hi.
> > FMD has an option to choose the default download path for new mangas, but if we wanted to change the download path of our favorites, we had to do it one by one manually. Can you add an option to simply change the download path for multiple or all mangas at once in favorites?
> > (For example, I want to change my default saving location from partition E:\ to F:)
> > Thanks.
> 
> For temporary solution, you can use DB Browser for SQLite program, open favorites.db, copy all entries on Browse Data tab-->saveto column to notepad, replace all original download path to newer one, copy it, and paste it back to DB Browser for SQLite saveto column.
> 
> That's what I do in the past. Don't use Notepad/Notepad++ to open favorites.db tho, only the file path. I actually lost all my favorites once because I used Notepad to open favorites.db, not DB Browser.
> 
> For safety measures, be sure to backup your favorites.db first before modifying it.
> 
> ![2019-04-04 17_39_20-DB Browser for SQLite - K__FMD x64_works_favorites db](https://user-images.githubusercontent.com/17843605/55549890-217dff00-5701-11e9-80df-a8269e34808b.jpg)

Thanks.
Actually, that's exactly what I did too, but I don't like to edit files using third-party apps even if it's something as reliable as SQLite.

**Comment by admiralmikan** [comment]
> Thanks.
> Actually, that's exactly what I did too, but I don't like to modify files using third-party apps even if it's something as reliable as DB Browser for SQLite.
> but thank you for mentioning this workaround.

Sure. No probs. I just don't want people got same experience like me. I learned it the hard way.

**Comment by SDXC** [comment]
implemented, wait for release.

**Comment by SDXC** [comment]
Free Manga Downloader (0.9.167.0) has been released.
