### ISSUE TITLE
Can't download from nettruyen.com

### ISSUE THREAD

**Issue by thanhminh30** [fmd-project-team/FMD#1000]
i try download from nettruyen.com but fail, check log
19:25:23:889 TTaskThread, checkforfinish failed=24/24 [NetTruyen]"Ore no Genjitsu wa Renai Game?? ka to Omottara Inochigake no Game datta" > "/truyen-tranh/ore-no-genjitsu-wa-renai-game-ka-to-omottara-inochigake-no-game-datta/chap-29.1/572690"
http://imageinstant.com/data/images/18549/572690/001.jpg
http://imageinstant.com/data/images/18549/572690/002.jpg
http://imageinstant.com/data/images/18549/572690/003.jpg
http://imageinstant.com/data/images/18549/572690/004.jpg
http://imageinstant.com/data/images/18549/572690/005.jpg
http://imageinstant.com/data/images/18549/572690/006.jpg
http://imageinstant.com/data/images/18549/572690/007.jpg
http://imageinstant.com/data/images/18549/572690/008.jpg
http://imageinstant.com/data/images/18549/572690/009.jpg
...

all link is ok but FMD can't download. I already tried https://github.com/fmd-project-team/FMD/wiki#troubleshooting-guides and https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation but not working.

**Comment by Tmp341** [comment]
I can open website, check chapters and even get direct links. But i couldn't open the links you gave above. Uses CF, probably needs a manual workaround with imageinstant, not with nettruyen.

**Comment by Slasar41** [comment]
Should be fixed.
