### ISSUE TITLE
problem with long titles

### ISSUE THREAD

**Issue by muto4013** [fmd-project-team/FMD#1007]
Maybe i am doing something wrong, but can't download mangas with long titles.
so let's say i have this title:
"Kouryakuhon o Kushi Suru Saikyou no Mahoutsukai ~< Meirei sa sero > to wa Iwa Senai Oreryuu Mao Tobatsu Saizen Ruuto ~"
I renamed this in favorites to title "Kouryakuhon o Kushi Suru Saikyou" and save-to "D:\manga\Kouryakuhon o Kushi Suru Saikyou no Mahoutsukai" 
but during download i get the shorten name as folder but the chapter name is the full (unedited) name.
What did i do wrong?
My settings in options/save to are:
![fmd_N0dcM6Jahm](https://user-images.githubusercontent.com/25901885/83357287-cfb81f80-a36b-11ea-9163-cab428edeab6.png)

**Comment by Tmp341** [comment]
Your chaptername contains both ``manga`` and ``chapter``.

**Comment by muto4013** [comment]
yes, because if i use only %chapter i got only the chapter count (e.g ch.11), 
i would like something like eg "Kouryakuhon o Kushi Suru Saikyou - ch11",
If i use only %manga% in the chapter name i got "0011Kouryakuhon o Kushi Suru Saikyou no Mahoutsukai ~ Meirei sa sero  to wa Iwa Senai Oreryuu Mao Tobatsu Saizen Ruuto ~" which seems also wrong.  
My question is: why didn't i get the same "short name" line in the manga folder name?
Shouldn't the %manga% value in "chapter name" not be the same as in "Manga folder name" ?

**Comment by Tmp341** [comment]
No, it generates again since you use ``%manga%``, which FMD gets from website, not use your created folder. But, you can manually set it before downloading.

**Comment by muto4013** [comment]
Oh, i see. Thanks a lot for the explanation. 
And since i have only few "long titles" i solved it with two different FMD installations and a little bit help of a batch.
