### ISSUE TITLE
add to turkish scan seri manga please

### ISSUE THREAD

**Issue by McMaster68** [fmd-project-team/FMD#1015]
https://serimanga.com/?a=a can you add seri manga with turkish manga site?

**Comment by Tmp341** [comment]
It is already on the main requests list #351

**Comment by McMaster68** [comment]
seri manga eklenmemiş türk sitelerine tekrar ekler misiniz teşekkürler.

**Comment by Tmp341** [comment]
Bu siteleri ekleyecek kodlayıcı lazım. Varolan kodlayıcılardan biri "benim işim gücüm var" dedi ama gitti kendine fmd klonu açtı, birinci kodlayıcı ilgisini kaybettiğini söylüyor, kalan tek kodlayıcı da çok iyi bilmiyor (muhtemelen onun da ilgisi kaybolmuştur).

Ayrılan kodlayıcının FMD klonu burada, onu dene : https://github.com/dazedcat19/FMD2
