### ISSUE TITLE
Website changed domain [MangaKu]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#102]
from http://mangaku.in/ to https://mgku.net

![fmd6](https://user-images.githubusercontent.com/45929526/56087092-68e95580-5e8e-11e9-82fd-7a3d420ea7dc.PNG)
![Uploading fmd7.PNG…]()
![Uploading fmd8.PNG…]()
![fmd4](https://user-images.githubusercontent.com/45929526/56087090-5d962a00-5e8e-11e9-87ec-88a0739e1af2.PNG)
![fmd5](https://user-images.githubusercontent.com/45929526/56087091-67b82880-5e8e-11e9-8bf1-501c8ed9c6c9.PNG)

**Comment by MIRVOUS** [comment]
![fmd7](https://user-images.githubusercontent.com/45929526/56087112-aea61e00-5e8e-11e9-83e0-8629e573c038.PNG)
![fmd8](https://user-images.githubusercontent.com/45929526/56087114-af3eb480-5e8e-11e9-8378-de9a56bfb92a.PNG)

**Comment by AbidZakaria** [comment]
that website change domain and change template

**Comment by SDXC** [comment]
mgku.net is part of MangaShiro.lua
MangaKu has it's own lua file.

MangaKu will be removed. Users have to move their favorites to MangaKid instead.

**Comment by SDXC** [comment]
I can still access MangaKu, so I guess it's not actually down.

**Comment by SDXC** [comment]
MangaKu definitely is still available. Both domains work with FMD, so I'll close this issue.
