### ISSUE TITLE
Martial Scans now works perfectly fine now

### ISSUE THREAD

**Issue by azraei97** [fmd-project-team/FMD#1020]
Previously adding this code simply not enouge for this site but now _it just works_. 
Just add this code in Madara.lua it will good to go.

  AddWebsiteModule('MartialScans', 'https://martialscans.com', cat)

Please add it to official support. Thank you

![Capture](https://user-images.githubusercontent.com/40983245/83914629-2d9d9a80-a7a4-11ea-82c1-1868a061bef5.PNG)

**Comment by azraei97** [comment]
By the way, ManhuaPlus almost work but unable to get chapter list.

Hope you can fix it because I just using COPY PASTE lua with just modified link website

[https://drive.google.com/file/d/1BLAH-jXGH526M2Oo1KhWXJmix2XnEekw/view?usp=sharing](url)
![Capture](https://user-images.githubusercontent.com/40983245/83916388-b0742480-a7a7-11ea-9d97-458aca8b8ba1.PNG)

**Comment by Tmp341** [comment]
@azraei97 Your link isn't public.

**Comment by azraei97** [comment]
@Tmp341 ? It open just fine. Try again.

**Comment by Tmp341** [comment]
Created a PR for you. Waiting for a review.
