### ISSUE TITLE
New Module creation

### ISSUE THREAD

**Issue by 10lalib** [fmd-project-team/FMD#1026]
Hello
I am trying to create a new module for a website called ManhwaPool with a link https://www.manhwapool.com/ by using different kind of templates (the one in the folder template) and some of the already working modules but with no luck

Could you please help? i have attached the text of the last try module.

Thank you

Best regads
[ManhwaPool.txt](https://github.com/fmd-project-team/FMD/files/4761252/ManhwaPool.txt)

**Comment by 10lalib** [comment]
Hello Slara41
I tried using madara.lua with replacing all madara words in the lua to manhwapool and added the m.rooturl = https://www.manhwapool.com/ 
When i try to get update manga list it starts preparing at the bottom and that is it. no update and no database created

**Comment by 10lalib** [comment]
I have posted the code in this link

https://pastebin.com/Ss1nzHc2

**Comment by Slasar41** [comment]
No, I mean add it like this:
![image](https://user-images.githubusercontent.com/28888646/84527933-f16cbb80-ad08-11ea-82ec-1fd11d60b8dc.png)
![image](https://user-images.githubusercontent.com/28888646/84527947-f7fb3300-ad08-11ea-82a4-bae19bb7b20a.png)

**Comment by 10lalib** [comment]
Yes it worked now
would you mind adding it to the server?

**Comment by 10lalib** [comment]
i could also upload the database

**Comment by Slasar41** [comment]
You can create a pull request.

**Comment by 10lalib** [comment]
Okay thank you for your help :)
