### ISSUE TITLE
Add website mangasushi.net

### ISSUE THREAD

**Issue by SalarG** [fmd-project-team/FMD#1030]
Hi there. 
Could you please add this website to FMD
https://mangasushi.net

**Comment by Tmp341** [comment]
Follow your request via main requests issue #351.

**Comment by jogger420** [comment]
mangasushi is checked as implemented, but it isn't - it's not even on a list of supported ones

**Comment by Tmp341** [comment]
It is supported, as there is an entry in Madara lua module. That list is outdated though. But probably site changed.
