### ISSUE TITLE
[CF Workaround] Kissmanga....again

### ISSUE THREAD

**Issue by Souravi785** [fmd-project-team/FMD#1040]
Kissmanga is causing issues again at least for me. If using the workaround i can open the chapters but cant download them.

![sample fmd](https://user-images.githubusercontent.com/24958560/85627841-fd556780-b690-11ea-8f2e-b060d97bda6a.PNG)

![sample fmd 3](https://user-images.githubusercontent.com/24958560/85627979-2e359c80-b691-11ea-8725-0c876c64c756.PNG)

 
![sample fmd 2](https://user-images.githubusercontent.com/24958560/85627898-11996480-b691-11ea-8fe7-446c14447342.PNG)

P.S. Do I need to make an account on Kissmanga now?

**Comment by garybempo** [comment]
u need visit the kissmanga and solve the verification(select two pictures) in order to download(that site getting annoying so I transitioning to mangadex).
I always download kissmanga without account.
