### ISSUE TITLE
Can't download from website [MangaHasu]

### ISSUE THREAD

**Issue by gfhghfghfh** [fmd-project-team/FMD#105]
I can not download from MangaHasu

**Comment by Tmp341** [comment]
- Have you checked the website?
- It seems the website is behind CF. Have you tried the workaround?

**Comment by gfhghfghfh** [comment]
Sorry,l am not good at English,so it is difficult for me to understand,but l still try to the workaround

but i want to ask for whether it can be fixed in future

**Comment by Tmp341** [comment]
What is your default language?

**Comment by gfhghfghfh** [comment]
Chinese

**Comment by Tmp341** [comment]
![1](https://user-images.githubusercontent.com/1683388/56089954-5a596900-5ea3-11e9-9255-9be19c496617.jpg)
![2](https://user-images.githubusercontent.com/1683388/56089955-5a596900-5ea3-11e9-9c16-28ec8a89fa36.jpg)
![3](https://user-images.githubusercontent.com/1683388/56089990-19ae1f80-5ea4-11e9-8ef5-52bf8773b75a.jpg)
![4](https://user-images.githubusercontent.com/1683388/56089957-5af1ff80-5ea3-11e9-978c-744c583aaf1e.jpg)

I'm not Chinese, Google translate : 😄 
第一张和第二张照片正在拍卖。对于第三个，您必须粘贴它并使其看起来像标记的一个。您从第2张照片复制了2行。我已经把这张照片让你明白了。

**Comment by gfhghfghfh** [comment]
Thank you.  It's very nice of you. 
I can not use my computer now,so l will try in a few more days.but I want if l still have a problem ,I hope you will help me.

Thank you for the information,again

**Comment by leoteesh** [comment]
hi ,
the work around doesn't seem to work for me anymore. keep getting the error messages. kindly advise?
many thanks

**Comment by Tmp341** [comment]
You can open the site, read chapters normally right? What kinda error messages you get?

**Comment by leoteesh** [comment]
Yes I can read the chapter online. The downloads just fails.

**Comment by Tmp341** [comment]
`16:37:27:416 WARNING: TTaskThread, download failed. "Meido no Koi wa Enma Shidai!" "Meido no Koi wa Enma Shidai! Chapter 001 Trial 1 - The King of Hell" "/meido-no-koi-wa-enma-shidai/vol-1-chapter-1-trial-1---the-king-of-hell-c518552.html"`
`16:37:27:554 ERROR: Error: TypeError: undefined not callable (property 'italics' of '')`
`16:37:27:698 ERROR: Error: ReferenceError: identifier 'document' undefined`

**Comment by SDXC** [comment]
MangaHasu works and there was no feedback for more than 20 days.
Issue will be closed.

**Comment by gfhghfghfh** [comment]
@SDXC 
it can not  work again

**Comment by SDXC** [comment]
Currently the cf_bypass can't handle second-tier Cloudflare pages, so you still have to do the manual workaround ("cf_clearance" cookie and the user agent are enough).

**Comment by gfhghfghfh** [comment]
@SDXC 
ok,thank you

I want to make sure the thing.
you fix it a few weeks ago,but it doesn't work again now.
the answer is yes or no

Hope I won't offend you due to my poor English.
