### ISSUE TITLE
Please Add Manhuaplus

### ISSUE THREAD

**Issue by xx255q** [fmd-project-team/FMD#1050]
Root URL: https://manhuaplus.com/

Example series:  https://manhuaplus.com/comics/martial-peak/

Example Chapter:  https://manhuaplus.com/chapter/martial-peak-chapter-592/

**Comment by Tmp341** [comment]
Asked in #903 and still in our main requests issue #351

**Comment by Slasar41** [comment]
@Tmp341 You've added the website. https://github.com/fmd-project-team/FMD/pull/1022

**Comment by Tmp341** [comment]
@Slasar41 It was in an issue, so i forgot i created a PR.
