### ISSUE TITLE
No search results on Mangakaklot

### ISSUE THREAD

**Issue by xx255q** [fmd-project-team/FMD#1051]
To be more specific if you search for martial peak you get this search result: https://manganelo.com/manga/martial_peak
and no other information will load, you have to switch to manganelo then search again for info and chapters to populate

**Comment by Tmp341** [comment]
I don't get what you mean.

**Comment by xx255q** [comment]
> I don't get what you mean.

so you load the mangakaklot library then search for example martial peak, on the left where manga series are listed you double click "martial Peak" on the wrtie using this information is desplayed: URL, Cover, series info, chapters in series. But in this case the only thing on the right is the URL for the series and the rest of the areas are blank

**Comment by Slasar41** [comment]
Ah, it's because the link redirect to MangaNelo website.
If you click the arrow, the info will show correctly.
![image](https://user-images.githubusercontent.com/28888646/86159317-552e1b80-bb34-11ea-9f4e-1b2a312d8510.png)
