### ISSUE TITLE
Wrong URL in manganelo for series

### ISSUE THREAD

**Issue by xx255q** [fmd-project-team/FMD#1052]
Examples:
Default (D) Actual (A)

God of Martial Arts:
D: https://manganelo.com/manga/god_of_martial_arts
A: https://manganelo.com/manga/huku267071576897767

Versatile Mage
D: https://manganelo.com/manga/versatile_mage
A: https://manganelo.com/manga/vrin278571580265812

**Comment by Tmp341** [comment]
It might be some kinda url protection.

**Comment by Slasar41** [comment]
The link in the database is outdate.
I've updated it, you can redownload from server.
