### ISSUE TITLE
Can't download from jaiminisbox

### ISSUE THREAD

**Issue by jokosablenk** [fmd-project-team/FMD#1055]
cant download this manhwa

https://jaiminisbox.com/reader/read/red-storm

![error](https://user-images.githubusercontent.com/36765223/86311953-80ac2580-bc5c-11ea-807a-4d96e5cd47ed.png)

**Comment by 7h3Cub3** [comment]
They put in place anticrawler mesures, you will not be able to download with FMD, just go on their website and DL the zip.

**Comment by Tmp341** [comment]
Have you checked FMD2? Maybe that one can work with it.

**Comment by jokosablenk** [comment]
Thanks, i can download with FMD2
