### ISSUE TITLE
Manhuascan keeps loading

### ISSUE THREAD

**Issue by Souravi785** [fmd-project-team/FMD#1058]
It was fine till now but suddenly I can't access any manga info in manhuascan.

![sample fmd 4](https://user-images.githubusercontent.com/24958560/86350480-91709180-bc84-11ea-8e7d-d46fb7bcaa6a.PNG)

Been a few minutes since it started loading. 

No problem with my connection.

![sample fmd 5](https://user-images.githubusercontent.com/24958560/86350566-b402aa80-bc84-11ea-9043-5ff435f79f92.PNG)

**Comment by Tmp341** [comment]
Is it working now?
