### ISSUE TITLE
Wuxiaworld.site not working (Cloudflare)

### ISSUE THREAD

**Issue by azraei97** [fmd-project-team/FMD#1059]
Wuxiaworld.site adding Cloudflare in their site. Now FMD unable to cache anything from wuxia

**Comment by azraei97** [comment]
Other thing I want to report is FMD now unable to detect/read any tags from nhentai. Hope you can fix it

![Capture](https://user-images.githubusercontent.com/40983245/86467334-cdc8ee00-bd67-11ea-81a2-7e3eb1bfdb92.PNG)

**Comment by Tmp341** [comment]
Your screenshot is NSFW tho. @azraei97

**Comment by azraei97** [comment]
Done cheap way "blur"

**Comment by azraei97** [comment]
Any update for website that has Cloudflare? Current temporary solution was manually add Cookies and UserAgent but cookies change time to time. So it not perfect solution like previous Cloudflare Bypass

**Comment by Tmp341** [comment]
FMD is needed to be rewritten in different language, or other embeded solutions. FMD2 can bypass cloudflare solutions i think. Try it.

**Comment by azraei97** [comment]
I try FMD 2 and yea it able to bypass cloudflare. I have few question:

1. I remember FMD 1 also has cloudflare bypass in older version but why it gone now?
2. Doesn't that mean FMD 2 is superior and better use it compare to FMD 1?
3. Why FMD 2 is like 1 man project meanwhile FMD 1 have TEAM?

**Comment by Tmp341** [comment]
> 
> 
> I try FMD 2 and yea it able to bypass cloudflare. I have few question:
> 
>     1. I remember FMD 1 also has cloudflare bypass in older version but why it gone now?
> 
>     2. Doesn't that mean FMD 2 is superior and better use it compare to FMD 1?
> 
>     3. Why FMD 2 is like 1 man project meanwhile FMD 1 have TEAM?

1. FMD2's author removed it from FMD1 with some excuses while he was contributor.

2. Well, author doesn't share "changelog infos", so i dunno what is fixed, what isn't. Also, people say some sites don't work on FMD2. So, use both and figure out which one works well.

3. FMD2's author was working with FMD1's team, but he left after saying his irl is busy. But at the same time, he created his repo it seems. He is working on it now. Use it while it is still getting updated. FMD1's main author SDXC is busy irl, he lost his interest in FMD it seems (as there is a more active repo now). Until one party officially archives/deletes their repo, there will be 2 for now.

**Comment by azraei97** [comment]
Thanks for answering. I will keep using FMD 1 as main and use FMD 2 only on website that have cloudflare.
