### ISSUE TITLE
Add support for website [TranslateWebtoons]

### ISSUE THREAD

**Issue by rs3mk** [fmd-project-team/FMD#106]
Site: https://translate.webtoons.com/

Spanish:
https://translate.webtoons.com/webtoonVersion?webtoonNo=780&language=SPA&teamVersion=0

English:
https://translate.webtoons.com/webtoonVersion?webtoonNo=780&episodeNo=111&language=ENG&teamVersion=0

Portuguese:
https://translate.webtoons.com/webtoonVersion?webtoonNo=780&episodeNo=111&language=POR&teamVersion=17

![tttaa](https://user-images.githubusercontent.com/19628943/56093500-355afb00-5e8f-11e9-87b8-454c140da1d4.png)

Thanks

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
