### ISSUE TITLE
MangaParkNet can't be loaded

### ISSUE THREAD

**Issue by Qizmo** [fmd-project-team/FMD#1066]
Today MangaPark was downed for several hours. After the website work, FMD can't access any of their manga pages.

**Comment by Slasar41** [comment]
They have cloudflare now. You need to do cloudflare workaround or try [FMD2](https://github.com/dazedcat19/FMD2) the cloudflare bypass has been fixed.

**Comment by Qizmo** [comment]
oh ok thank you very much

**Comment by fales13** [comment]
already tried fmd2, somehow it didn't work too

**Comment by Slasar41** [comment]
![image](https://user-images.githubusercontent.com/28888646/87149950-5f41de00-c2db-11ea-9410-9866f0664de2.png)
Ah, the cloudflare captcha need to be solved manually from browser and then you still need to do cookies workaround.
But when there's no need to solve the captcha, FMD2 can normally access it without doing cookies workaround.
FMD2 doesn't support auto solving the captcha yet.

**Comment by fales13** [comment]
thanks.

**Comment by AltPlus248** [comment]
I tried the CF work around and downloaded FMD2 but I still can't access MangaPark.

**Comment by Tmp341** [comment]
You should create issue on FMD2's repo.

**Comment by AltPlus248** [comment]
Never mind, it turns out I had downloaded a different version of FMD2 instead of the one you linked so I tried that one and its working for me.

**Comment by Tmp341** [comment]
I was talking this one https://github.com/dazedcat19/FMD2
