### ISSUE TITLE
Can't download if the website uses DDoS protection by Cloudflare?

### ISSUE THREAD

**Issue by jagatnime** [fmd-project-team/FMD#1067]
Can't download if the website uses DDoS protection by Cloudflare?

**Comment by Tmp341** [comment]
Generally, you can use [Cloudflare workarounds](https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation), but lately, that workaround doesn't work on some sites (like Kissmanga etc).
