### ISSUE TITLE
Site changed url [MangaKid]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#1075]
from : "https://mgku.me/"
to : "https://mangakid.club/"

**Comment by MIRVOUS** [comment]
i'm sorry it not work for me :
![mangakyou-1](https://user-images.githubusercontent.com/45929526/87846290-0a185480-c8f9-11ea-9925-068132c33b69.png)
any idea?

**Comment by Tmp341** [comment]
Probably database update needed too.
