### ISSUE TITLE
Site changed url [MangaCeng]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#1076]
from : "https://mangaceng.com/"
to : "https://mangaxin.com/"

**Comment by MIRVOUS** [comment]
sorry but, mangaceng still exist and mangaxin also exist?
![mangaceng-mangaxin](https://user-images.githubusercontent.com/45929526/87846723-2ec1fb80-c8fc-11ea-875a-4f300cea5b69.png)
and i try update manga list in mangaxin but it not work too

**Comment by Tmp341** [comment]
I can't see Mangaceng on my list. About the list, probably some new codes are needed, i just updated urls.
