### ISSUE TITLE
Huge performance hit while updating manga list

### ISSUE THREAD

**Issue by sombra2077** [fmd-project-team/FMD#108]
every-time I use update manga list, it causes my pc to slow down so much, its even disturbing other process, like idm downloads, when I check with task manager, sometimes fmd.exe spikes on ram usage up to 5gb (I have 8gb ram and fx-4300)

**Comment by Tmp341** [comment]
Have you checked your system with an antivirus?

**Comment by Von07** [comment]
I've tried that before and all I did was to lower the "Number of Downloaded Task" and Number of Downloaded Files" in [ Options > Conections tab ]

**Comment by Tmp341** [comment]
Oh, if you try to download too many tasks at the same time, you might have a performance issue. but never tested more than ``1`` task at a time.

**Comment by sombra2077** [comment]
@Tmp341 sorry for the late reply, I'm using fmd_0.9.163.0_Win64, and didn't change any connection setting before updating the manga list, the only setting I've changed is downloaded manga directory, I'm placing the fmd files on C: system drive and saving the downloaded manga on D:, but those partition are still within the same hdd (1tb hdd), and I'm just using always updated windows defender on windows 10 for the antivirus

**Comment by Tmp341** [comment]
You can upload FMD.exe to Virustotal.com and check it.

Now that i think about it, there was an issue like that. https://github.com/riderkick/FMD/issues/1175

I've advised the issuer to do a [Fress Install](https://github.com/fmd-project-team/FMD/wiki#fresh-install), and he said the problem gone after doing so. I've explained what to do and what files to backup before doing fresh install. Try that.

**Comment by sombra2077** [comment]
@Tmp341 file is clean with virustotal check

and yes its exactly the same issue as one you reference

I've tried fresh install and even place the fmd files on different partition and different hdd, still the problem happens, and with huge usage like this, I fear for the safety of my hardware
![3](https://user-images.githubusercontent.com/49628510/56324651-a2c1a100-6199-11e9-92fb-43f723c617f9.jpg)

I'm gonna try a few things today, maybe some of them will fix my problems, will post here again for the updates

**Comment by sombra2077** [comment]
I think I found a fix, @Tmp341 I think there's something wrong with the x64 version of newest fmd as this point (fmd_0.9.163.0_Win64), or maybe some compability issue with certain pc specs (especially mine), because I remember there was the same memory leak problem of a certain game from steam a few years back, the game released in 32 and 64 version, and the fix was simply use the 32 ver of the game, and it works just like that with fmd, I downloaded 32 ver and so far no memory leaks while updating the manga list.

here's my dxdiag is case you might need it
![1](https://user-images.githubusercontent.com/49628510/56330860-29837780-61b4-11e9-84d2-0065c0818b5d.jpg)
![2](https://user-images.githubusercontent.com/49628510/56330869-2e482b80-61b4-11e9-8e2d-c9af80e20216.jpg)


although the only problem that I encounter right now is some website on fmd is unable to update its list, and the updating list is super slow, I check using netlimiter, fmd.exe only use like 11-20KB/s, and the one that could update sometimes it isn't really updating, like there's some of manga title that didn't included in the fmd, the sites are mangago, mangakakalot, and manganelo.
mangago simply stuck at getting directory when pressing update manga list, while mangakakalot and manganelo simply won't update, like the update process on fmd says its done but it isn't updating.

**Comment by Tmp341** [comment]
Can you send your log?

Also your fmd (the whole package) files.

**Comment by sombra2077** [comment]
sorry I've already deleted the extracted x64 files, but the rar is from here:
https://github.com/fmd-project-team/FMD/releases/tag/0.9.163.0

but I still have the rar files in my pc:
https://drive.google.com/open?id=1WCXdle_1vegWrnwRlf2di5B0tdONlg-z

**Comment by Tmp341** [comment]
That is official release. I was asking for your files.

**Comment by sombra2077** [comment]
oh you mean these files?
https://drive.google.com/file/d/1BfuzhvK2U_0zWNI4_7ZpkSk2vFF8WVG2/view?usp=sharing
that's all the files in my FMD win64 ver folder

I even managed to reproduce the huge performance hits a while ago with fmd_0.9.163.0_Win64 just by doing the update manga list thing
![12212](https://user-images.githubusercontent.com/49628510/56449189-71370a00-6340-11e9-86f8-11580ac04d2d.jpg)

**Comment by Tmp341** [comment]
![dddassss](https://user-images.githubusercontent.com/1683388/56452615-6f1e7c80-633b-11e9-814f-34ac3af7eb06.jpg)

No problem at all.

**Comment by Josexv1** [comment]
I can't reproduce the bug with the files you uploaded. Can you use Process Explorer and check the Resource usage? Also maybe you can use [Hook Explorer](https://github.com/dzzie/HookExplorer) to check what the software is doing that stress the ram.

**Comment by SDXC** [comment]
What I can see is that the disk seems to be the issue here. It looks to me like the disk is too slow in writing down the data it gets from FMD and/or IDM or other processes and pushes the data into the RAM sometimes.

The "Processes" tab would be interesting. Also, which disk do you have?

**Comment by Tmp341** [comment]
> 
> 
> What I can see is that the disk seems to be the issue here. It looks to me like the disk is too slow in writing down the data it gets from FMD and/or IDM or other processes and pushes the data into the RAM sometimes.
> 
> The "Processes" tab would be interesting. Also, which disk do you have?

I'm using FMD on a 5400 rpm HDD. :D But we need other processes running behind too.

**Comment by SDXC** [comment]
@sombra2077 Do you still have this issue? Did you check your processes? Did you also check the S.M.A.R.T. values of your HDD?
