### ISSUE TITLE
adress change

### ISSUE THREAD

**Issue by pavkor5** [fmd-project-team/FMD#1081]
Hello, I just found out that "mangasee.us" changed his address to "mangaseeus123.us". So I started looking for a new version of the plugin and found out that it is a new version of the whole application, so I downloaded it. Unfortunately, it doesn't work either. Is there any chance that the address will be rewritten? Or I have the database I have to create from just again with another source. Thank you in advance for your reply.

**Comment by Tmp341** [comment]
Mangasee is working over here:

![ssssss](https://user-images.githubusercontent.com/1683388/87821675-ead9e280-c878-11ea-9cec-77139f520d1f.jpg)

**Comment by pavkor5** [comment]
Thank you for the advice with copying, after about the fourth rewrite the program started to work thank you.
