### ISSUE TITLE
Add site TheNonames Scans

### ISSUE THREAD

**Issue by Geese1** [fmd-project-team/FMD#1088]
I was just wondering if it's possible to add the English scanlation group site: The Nonames Scans

[https://the-nonames.com/home](url)

They do release on Mangadex, but it's usually a while after they release on the reader on their own site so I was wondering if it's possible to grab chapters directly from the group's site.

**Comment by Tmp341** [comment]
It is supported already with b1bb423 commit.

**Comment by Geese1** [comment]
Thanks for the link to the module, but I keep getting a 404 error when I try to download the list of titles. Any idea what could be the issue?

**Comment by Tmp341** [comment]
Probably website changed.
