### ISSUE TITLE
Getting a 404 error when trying to download the manga list from The Noname Scans 

### ISSUE THREAD

**Issue by Geese1** [fmd-project-team/FMD#1089]
I was able to add the lua module for the noname scans to the downloader, but whenever I try to download the list from the server, I keep getting a: Failed to finish 404 error.

Any idea what could be causing the issue, and more importantly how to fix it?

**Comment by Tmp341** [comment]
Wait, you can't download list from server, since it is not there. You need to manually update it.

**Comment by Tmp341** [comment]
Ok, i've updated database repo. Try downloading from server again.

**Comment by Geese1** [comment]
Thanks, but unfortunately I'm still getting the same error.

**Comment by Tmp341** [comment]
> 
> 
> Thanks, but unfortunately I'm still getting the same error.

Then download [this](https://github.com/fmd-project-team/FMD-WebsiteDatabases/raw/master/packages/TheNonamesScans.7z), extract in ``data`` folder.

**Comment by Geese1** [comment]
> > Thanks, but unfortunately I'm still getting the same error.
> 
> Then download [this](https://github.com/fmd-project-team/FMD-WebsiteDatabases/raw/master/packages/TheNonamesScans.7z), extract in `data` folder.

I did that, but now when I click on a title to get the info it give me the error message: Cannot get manga info. Please check your internet connection and try again.

I also tried updating the list since I noticed it doesn't have all their titles, but nothing seems to happen.

Would this have anything to do with the module itself? I had to remove lines 1-22 of the script in order for it to work in the program (otherwise it wouldn't give me the option to select the website under the English-Scanlator tab). I didn't think it was an issue, as looking at the scripts for the other, working modules, they all start with the first line being: function GetInfo()

But maybe there's something I'm missing that's causing the problems?

**Comment by Tmp341** [comment]
Something wrong with your FMD. It worked for me when i tried.

Try [fresh install](https://github.com/fmd-project-team/FMD/wiki#fresh-install).

**Comment by Geese1** [comment]
> Something wrong with your FMD. It worked for me when i tried.
> 
> Try [fresh install](https://github.com/fmd-project-team/FMD/wiki#fresh-install).

Thanks for the help; a fresh install did the trick!

I noticed that I had been on an older version of FMD: 0.9.167.2 - not sure if that is what was causing the issue, or it was something else, but the fresh install seemed to solve the problems. I've been able to see, and download, from the Noname Scans database.

Thanks again!

**Comment by Tmp341** [comment]
Since that version, a lot of things changed. So yeah, it was the cause.
