### ISSUE TITLE
Can't download older chapters on Mangadex and Mangakakalot

### ISSUE THREAD

**Issue by lin4t** [fmd-project-team/FMD#1090]
So I've been noticing for a while now that I've been unable to download any of the older chapters on Mangadex and Mangakakalot. New, recently uploaded chapters are fine to up to about 3 months where they suddenly can't load chapter pages which results in downloads not working. Loading the chapter on the websites works fine.

Is this an issue on the websites themselves or is there something wrong with my client?

**Comment by Tmp341** [comment]
* Mangadex's older chapters were implemented as mangadex@home (dunno how many pages are moved), but they are distributed via users now. Probably FMD needs new codes for those.

* Mangakakalot still works? It was redirecting some mangas before.

**Comment by muto4013** [comment]
mangadex and older chapters works for me, but i did few steps. don't know which was the ultimate fix but here you go:
1. update your lua's (fmd 1.3.3.0, mangadex lua from around 9.6.20)
2. enter your account in fmd (options/accounts/mangadex)
3. go to mangadex webpage, in your user settings (md@home/options) disable md@home
4. optional: do the cookie workaround and enter the cookie and user agent in fmd/option/websites/advanced/mangadex

those steps has helped me, if it doesn't work for you then GG

**Comment by lin4t** [comment]
It was the md@home option! Finding it was a bit of a hassle (since I thought it was in settings and not it's own tab) but after I disabled it, I could download older chapters again. Thanks for the help.
