### ISSUE TITLE
TenManga info not loading

### ISSUE THREAD

**Issue by GeckoPrime** [fmd-project-team/FMD#1093]
All of the manga wont load any info and gives me check my connection and as a result the new chapters wont download

**Comment by Slasar41** [comment]
Link example?
I tried with random title and it's working and able to download.
![image](https://user-images.githubusercontent.com/28888646/88419598-a964ac80-ce0f-11ea-88fd-6186afe17cc8.png)

**Comment by GeckoPrime** [comment]
Yeah nvm when I was trying to do it it kept telling me to check my connection but the website was working but now it's loading and the chapters are downloading.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
