### ISSUE TITLE
Failed to download [Komikcast]

### ISSUE THREAD

**Issue by admiralmikan** [fmd-project-team/FMD#11]
So today Komikcast failed to download again, only 0 zero current chapter. When I open the website, all it has was only __cfduid. Any fix for that?
![2019-04-02 08_14_48-](https://user-images.githubusercontent.com/17843605/55369153-8b3eb300-551f-11e9-90e2-6df73102298d.jpg)
![2019-04-02 08_12_47-Free Manga Downloader](https://user-images.githubusercontent.com/17843605/55369154-8b3eb300-551f-11e9-83c2-bbda443079f1.jpg)

**Comment by SDXC** [comment]
Please try again with this version. If it doesn't work, please provide your MangaShiro.lua and the favorites.db.

[fmd_0.9.160.1.zip](https://github.com/fmd-project-team/FMD/files/3032392/fmd_0.9.160.1.zip)

**Comment by AbidZakaria** [comment]
> Please try again with this version. If it doesn't work, please provide your MangaShiro.lua and the favorites.db.
> 
> [fmd_0.9.160.1.zip](https://github.com/fmd-project-team/FMD/files/3032392/fmd_0.9.160.1.zip)

![image](https://user-images.githubusercontent.com/19544118/55382510-03bd6800-5550-11e9-9740-de3a86741144.png)

okay, work fine

![image](https://user-images.githubusercontent.com/19544118/55382559-294a7180-5550-11e9-9da8-d9233e1c18a0.png)

but a little languange indo not complete
Completed => Selesai
Stoped => Berhenti
Disabled => Dimatikan

**Comment by admiralmikan** [comment]
> Please try again with this version. If it doesn't work, please provide your MangaShiro.lua and the favorites.db.
> 
> [fmd_0.9.160.1.zip](https://github.com/fmd-project-team/FMD/files/3032392/fmd_0.9.160.1.zip)

Nice, works perfectly. Although I have to moved my data and config since I was still using old .152 build fmd

**Comment by SDXC** [comment]
@AbidZakaria Language files are fixed in the official release (coming up any moment). I can re-add MangaID, but why?

@admiralmikan Thanks for the feedback.

**Comment by SDXC** [comment]
@admiralmikan Official release is out now. The updater in the version 0.9.160.0 and the hotfix 0.9.160.1 doesn't work. You have to update manually. Updater should work for the future releases though.

**Comment by AbidZakaria** [comment]
@SDXC MangaID is my favorite Manga source

**Comment by SDXC** [comment]
@AbidZakaria I removed it because it was like that in the lua script I merged and because I only get a blank page when I try to go to MangaID, that's why I thought that it's offline. Just to be sure: Should I re-add MangaID even thouhh it's not accessible?

**Comment by AbidZakaria** [comment]
just add it, I'll send the script file later

**Comment by AbidZakaria** [comment]
[MangaID.zip](https://github.com/fmd-project-team/FMD/files/3038683/MangaID.zip)

that lua for MangaID
please add

**Comment by Tmp341** [comment]
There might be regional lock. @AbidZakaria can you please send a screenshot, a working mangaid page maybe?

**Comment by AbidZakaria** [comment]
> > Please try again with this version. If it doesn't work, please provide your MangaShiro.lua and the favorites.db.
> > > > File removed
> 
> ![image](https://user-images.githubusercontent.com/19544118/55382510-03bd6800-5550-11e9-9740-de3a86741144.png)
> 
> okay, work fine
> 
> ![image](https://user-images.githubusercontent.com/19544118/55382559-294a7180-5550-11e9-9da8-d9233e1c18a0.png)
> 
> but a little languange indo not complete
> Completed => Selesai
> Stoped => Berhenti
> Disabled => Dimatikan
> 
> and please don't remove MangaID [ID]

This my screenshot

**Comment by SDXC** [comment]
@AbidZakaria lua is added now. Should be available through the lua update check now.

**Comment by Tmp341** [comment]
> This my screenshot @Tmp341

I've added your ``lua`` again and @SDXC approved it.

**Comment by SDXC** [comment]
Issue will be closed. If any there are any problems with MangaID, please open a new issue.

**Comment by AbidZakaria** [comment]
Okay, I will check it later

**Comment by AbidZakaria** [comment]
![image](https://user-images.githubusercontent.com/19544118/55518979-36767600-56a0-11e9-9dda-80e53e6f1380.png)

![image](https://user-images.githubusercontent.com/19544118/55519004-5c9c1600-56a0-11e9-8061-4dad6ef48bbe.png)

Thanks

**Comment by Tmp341** [comment]
This approves my "regional lock/block" idea then.
