### ISSUE TITLE
Add support for website [3asq]

### ISSUE THREAD

**Issue by 3MROO96** [fmd-project-team/FMD#110]
Website: http://3asq.org/
Thanks in advance.

**Comment by Tmp341** [comment]
It does have support.

**Comment by 3MROO96** [comment]
URL not supported!
![1](https://user-images.githubusercontent.com/18348292/56206355-75b3a800-604c-11e9-9ffd-b0d1bfaf042b.jpg)

**Comment by Tmp341** [comment]
Fmd supports ``3asq.info`` it seems.

**Comment by SDXC** [comment]
Website added by AbidZakaria as 3asqOrg so it doesn't conflict with the old 3asq which is at least for now still available.
