### ISSUE TITLE
Add Funlist Online Scans website support in Madara.lua

### ISSUE THREAD

**Issue by azraei97** [fmd-project-team/FMD#1106]
Just add this line for Funlist Scans and it work fine. Thank you

  AddWebsiteModule('FunlistScans', 'https://funlist.online', cat)

![Capture](https://user-images.githubusercontent.com/40983245/89858695-dec01700-dbd1-11ea-8485-afcef93ca6f3.PNG)

**Comment by azraei97** [comment]
By the way, can you add manhuaes.com support? The template almost like MangaReader and NineManga but I personally think it more likely using MangaShiro template.

Hope you can check it out because ManhuaES has few manhua that already far more chapter then other website

**Comment by Slasar41** [comment]
Both sites has been added.
