### ISSUE TITLE
Mangadex Module, Info loaded but Empty Chapter

### ISSUE THREAD

**Issue by N-Gine111** [fmd-project-team/FMD#1112]
The **Info page is still working** albeit with **empty chapter**, but my download from the previous session is still working tho.

- _Default Settings, all threads at 1, Logged in (Mangadex)_
- _Series I'm currently downloading: https://mangadex.org/title/12108/mushoku-tensei-isekai-ittara-honki-dasu_
- _Also I can read the manga just find from the website_

![image](https://user-images.githubusercontent.com/69748816/90330023-e4539d80-dfd3-11ea-84de-ebcc6eb5f272.png)
![image](https://user-images.githubusercontent.com/69748816/90330031-f33a5000-dfd3-11ea-9dfe-8f1f25c2c445.png)
![image](https://user-images.githubusercontent.com/69748816/90330413-bc196e00-dfd6-11ea-99d0-96ed3d1bac9e.png)

**Comment by Slasar41** [comment]
It show the chapters just fine on my end:
![image](https://user-images.githubusercontent.com/28888646/90342230-aafd4b00-e030-11ea-87ab-300a96ce4e88.png)
Make sure the language is set to English in MangaDex option:
![image](https://user-images.githubusercontent.com/28888646/90342187-75f0f880-e030-11ea-8e5b-807b9191c95e.png)

**Comment by N-Gine111** [comment]
Oh yea HAHA sorry about that, for some reason it became Ch Traditional
