### ISSUE TITLE
Adding ~300 manga to favorites

### ISSUE THREAD

**Issue by gin9980** [fmd-project-team/FMD#1116]
Is there a way to add around 300-400 manga that I am already up to date on and is on my Mangadex follows without having to individually type in the url in the MangaInfo tab then download the latest chapter then add to favorites 300 times?

**Comment by Tmp341** [comment]
You can't directly mark downloaded chapters. I mean, you can just check all chapters, remove check marks from ``unwanted/not downloaded yet`` chapters, add paused, remove from the list. So, that manga's mangadex chapter list will be updated.

FMD uses databases per manga site, it doesn't see already downloaded chapters directly.
