### ISSUE TITLE
Can't download from Heroscan

### ISSUE THREAD

**Issue by MagicalAmber** [fmd-project-team/FMD#1117]
I can update the manga list without issue. Entries come up just fine when I view manga info. Going to the site is no problem; the images load just fine.

But if I try to download anything from HeroScan through FMD, it fruitlessly attempts to give it a few tries, and eventually gives up with nothing downloaded. They don't SEEM to be Cloudflared, but who knows. I even tried imitating the Kissmanga workaround, but to no avail.

Any clues?

**Comment by Tmp341** [comment]
Maybe something changed in the code. You need to wait for Slasar41 to check, and if he can, fix it.

**Comment by Slasar41** [comment]
Should be fixed.
