### ISSUE TITLE
In Lhscans some chapters fail to download, changes in site.

### ISSUE THREAD

**Issue by GDXN** [fmd-project-team/FMD#1119]
Lhscan has made some changes that makes some chanters not to download as its stores them under 2 domains:
Normal chapters in loveheaven.net downloads ok.
H chapters in loveha.net this don't download (like: Hoshi Gari Sugidesho? Inaba-san).

**Comment by Slasar41** [comment]
Still works fine on my end.
![Untitled-1](https://user-images.githubusercontent.com/28888646/91347848-27501500-e80d-11ea-885c-889c7037885f.jpg)

**Comment by GDXN** [comment]
Now works, it's possible that it was a temporal issue with their servers.

**Comment by GDXN** [comment]
Now works, it's possible that it was a temporal issue with their servers.

**Comment by GDXN** [comment]
Now works, it's possible that it was a temporal issue with their servers.
