### ISSUE TITLE
Manhuaus not working

### ISSUE THREAD

**Issue by spamtaztik** [fmd-project-team/FMD#1123]
I can open the site, read chapters, etc from Chrome just fine. In FMD I can only display the series screenshot and description, but not the chapter list. When checking favorites, all my favorite series from them came up as 0 chapters.

I tried the cookies & useragent workaround, still no go. I used maxthreadlimit=1, maxthreadpertasklimit=1, maxconnectionlimit=2, updatelistnumberofthread=1, and updatelistdirectorypagenumber=0 (unchanged).

A mismatched LUA, perhaps?
Can someone help?

**Comment by Slasar41** [comment]
Works fine on my end, no need to enable advanced options for manhuaus.
![image](https://user-images.githubusercontent.com/28888646/92286426-36337780-ef31-11ea-8960-48e7f0addf81.png)
Try to delete `Madara.lua` file from `lua\modules` folder and let FMD redownload it.

**Comment by spamtaztik** [comment]
UPDATE: it worked fine when I checked again this morning. Must've been a temporary hiccup.
Thanks for checking.
