### ISSUE TITLE
Add support for website [CiayoEN, CiayoID, GoKomik, KomikZone, NGomik, ReonComics, MangaDropout, WebToonsID, WebComics]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#113]
previously thank you for all work.
please. add this site
english :
https://www.ciayo.com/en
https://www.webtoons.com/en
![ciayo_en](https://user-images.githubusercontent.com/45929526/56201514-3b0d3800-606b-11e9-80fc-3c6be07594f1.PNG)
![linewebtoons_en](https://user-images.githubusercontent.com/45929526/56201515-3ba5ce80-606b-11e9-80e1-1c8f1ad05d7a.PNG)

Indonesian : 
https://www.ciayo.com/id
![ciayo_id](https://user-images.githubusercontent.com/45929526/56201659-832c5a80-606b-11e9-946b-7340654b91ce.PNG)
http://gokomik.com/
![gokomik](https://user-images.githubusercontent.com/45929526/56201708-a6efa080-606b-11e9-8f2f-89e60fdd9cef.PNG)
https://klikmanga.com/
![klikmanga](https://user-images.githubusercontent.com/45929526/56201735-bff85180-606b-11e9-904e-2dfdb8d930c3.PNG)
https://www.komikzone.com/
![komikzone](https://user-images.githubusercontent.com/45929526/56201815-e1f1d400-606b-11e9-9542-1353f8a0421b.PNG)
https://www.webtoons.com/id
![linewebtoons_id](https://user-images.githubusercontent.com/45929526/56201875-02ba2980-606c-11e9-8c9b-ab5643a434f6.PNG)
Ahh ... wait it is included in the English language website! so, please fix that
![fmd1](https://user-images.githubusercontent.com/45929526/56202087-7f4d0800-606c-11e9-9421-c485156b7e8f.PNG)
![fmd2](https://user-images.githubusercontent.com/45929526/56202089-7fe59e80-606c-11e9-9e83-44f0d2079d4d.PNG)
https://www.ngomik.in/
![ngomik](https://user-images.githubusercontent.com/45929526/56202221-c3400d00-606c-11e9-828c-b0350949ce27.PNG)
http://www.reoncomics.com
![reoncomics](https://user-images.githubusercontent.com/45929526/56202267-df43ae80-606c-11e9-9bac-ff332d4e9daa.PNG)
https://www.webcomics.co.id
![webcomics](https://user-images.githubusercontent.com/45929526/56202336-04d0b800-606d-11e9-89ff-217e1b67a45c.PNG)

https://mangadropout.net/

**Comment by MIRVOUS** [comment]
Add one more.
- https://mangadropout.net/
![mangadropout](https://user-images.githubusercontent.com/45929526/56333905-42922580-61c0-11e9-91ac-a89f6f4020d5.PNG)

**Comment by SDXC** [comment]
All WebToons languages are already implemented.

![WebToons options](https://user-images.githubusercontent.com/5290260/56462349-5ad19280-63c2-11e9-998e-b89eaf8f8295.png)

**Comment by DaniAjalah** [comment]
Request web https://klikmanga.com/ 
thank you for all work.

**Comment by SDXC** [comment]
KlikManga has been added.

**Comment by MIRVOUS** [comment]
changed domain :
- "https://www.ngomik.in" to "https://ngomik.in/"

**Comment by MIRVOUS** [comment]
-  "https://www.komikzone.com/" to "https://www.komikgue.com/"
and "https://www.komikgue.com/" is already exists

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
