### ISSUE TITLE
Site moving: Nettruyen moving to Nhattruyen

### ISSUE THREAD

**Issue by DejaSentj** [fmd-project-team/FMD#1131]
Just let you know www.nettruyen.com gonna move to nhattruyen.com

some title already move to this new site

**Comment by Slasar41** [comment]
Is it gonna move to the new website or that website just another copy?
I see the contents is the same.

**Comment by Slasar41** [comment]
The new website has been added.

**Comment by DejaSentj** [comment]
Some titles had been moved from nettruyen to nhattruyen and some new chapters had been link to nhattruyen from nettruyen.

they gonna move and I do not know why they didn't told anyone about that yet. 

so exemple I have download a tittle Đô Thị Kiêu Hùng Hệ Thống from nettruyen weeks ago. now when we check update the title had been gone from nettruyen. 

and we always have trouble to download some new chapters because they link to nhattruyen or change file extension from jpg to img

**Comment by Slasar41** [comment]
Okay, since the website has been added and NetTruyen still works, we will let it be for now.
