### ISSUE TITLE
Chibi Manga manga list & chapter list broken

### ISSUE THREAD

**Issue by ElectroShade** [fmd-project-team/FMD#1132]
Chibi Manga seems to have changed their site a bit and the manga list and chapter lists don't appear work anymore.

It does pick up the manga info when a url is pasted in still.

http://www.cmreader.info/

I think they are currently under https://github.com/fmd-project-team/FMD/blob/master/lua/modules/Madara.lua

**Comment by Slasar41** [comment]
Should be fixed.
