### ISSUE TITLE
asurascans not loading

### ISSUE THREAD

**Issue by inheritno** [fmd-project-team/FMD#1135]
Asurascans not loading anything
![Untitled-1](https://user-images.githubusercontent.com/56203943/94051358-17156080-fde0-11ea-868f-475406d419f7.jpg)

https://asurascans.com/

**Comment by Tmp341** [comment]
Have you tried [Cloudflare workarounds](https://github.com/fmd-project-team/FMD/wiki#cloudflare-workarounds)?

**Comment by inheritno** [comment]
I don't see a Cloudflare  protection and cookies for the workaround
![Untitlejd-1](https://user-images.githubusercontent.com/56203943/94173860-2c03f980-fe9d-11ea-9bfa-dd326282b443.jpg)

**Comment by Tmp341** [comment]
I saw a CF cookie under **F12->Storage->Cookies->asurascans.com**

**Comment by Slasar41** [comment]
Should be fixed.
