### ISSUE TITLE
How to export/import bookmark list?

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#114]
I tried importing a list of bookmarks but this happened :
![fmd3](https://user-images.githubusercontent.com/45929526/56232378-cfe35600-60aa-11e9-8f3a-5833dd8d17d4.PNG)
![fmd4](https://user-images.githubusercontent.com/45929526/56232379-cfe35600-60aa-11e9-820e-44700c148419.PNG)
![fmd5](https://user-images.githubusercontent.com/45929526/56232381-d07bec80-60aa-11e9-98e5-5e0c5678e6b0.PNG)

maybe I don't understand how it works. so there is a tutorial?

**Comment by Tmp341** [comment]
What are you trying to do exactly? I have never used that feature, so not sure what it does.

**Comment by MIRVOUS** [comment]
i tried to importing a list of bookmark in "favorite tab" => "import list"

but I think it's okay for now.

if later I have a problem again, I will open the issue

**Comment by Tmp341** [comment]
I think it was Domdomsoft list importer, but i might be wrong though.
