### ISSUE TITLE
Can't get manga info [GManga]

### ISSUE THREAD

**Issue by 7a9o** [fmd-project-team/FMD#115]
Website = Gmanga
URL = https://gmanga.me/
Category = Arabic

**Comment by Tmp341** [comment]
It is already supported with ``GMangaMe.lua`` file. What is wrong with it?

**Comment by 7a9o** [comment]
![dddddddddddddddzzreztrezrezrezr gfdgfd g456456](https://user-images.githubusercontent.com/42692659/56298984-0cef2d00-612b-11e9-8344-0ed190e3f3df.PNG)
can't download

**Comment by SDXC** [comment]
@7a9o You sure you have the latest version of FMD and all lua files? I just tested your link and it worked...

**Comment by 7a9o** [comment]
yes >> 0.9.163.0_Win64
and lua file as well >> ![gmang](https://user-images.githubusercontent.com/42692659/56301133-18445780-612f-11e9-95c1-9461d4e7c801.PNG)

**Comment by Tmp341** [comment]
Have you done [Fress Install](https://github.com/fmd-project-team/FMD/wiki#fresh-install) while moving to new FMD?

**Comment by 7a9o** [comment]
Now it works after the fresh install 
Thank you @SDXC & @Tmp341

**Comment by Tmp341** [comment]
Ok. I'm closing this issue. If you have any problems with this, please reopen it.
