### ISSUE TITLE
Manga list is not match with sites

### ISSUE THREAD

**Issue by uhruhri** [fmd-project-team/FMD#116]
Hi,

So I just moved from riderkick version to SDXC version and decide to do clean installation. I only backup my configuration and favorites. 

After installation and making sure config for MangaDex and KissManga (CF Workaround) is still there, I tried to update the manga list for both sites. But after I'm done, manga that I'm looking for is not available (Solo Leveling).

I tried to re-update again by deleting .db files, then I saw mangadex only update 5 manga as you can see in screenshot

![update manga list](https://user-images.githubusercontent.com/49753654/56359620-477cc680-620c-11e9-8145-49a780b5d71b.png)

CF workaround is fine and working, as you can see in the next screenshot.
![mangadex](https://user-images.githubusercontent.com/49753654/56359658-62e7d180-620c-11e9-9160-808fbb85f3d5.PNG)

Meanwhile if I check mangadex site, Solo Leveling is there
![solo leveling](https://user-images.githubusercontent.com/49753654/56359756-a93d3080-620c-11e9-890d-6ce84cb391f0.PNG)

Thank you,

**Comment by Tmp341** [comment]
I'm getting chapter list. 

``Options\Websites\Options`` ``Mangadex\Language\" What is selected here?

**Comment by uhruhri** [comment]
> I'm getting chapter list.
> 
> `Options\Websites\Options\Mangadex\Language\` What is selected here?

English

It seems I found what affect it, CF Workaround...

![CF Workaround](https://user-images.githubusercontent.com/49753654/56361313-3f735580-6211-11e9-8747-6c336bcbedfb.PNG)

Can I have suggestion what's the best values there for updating manga list and downloading the manga?

Because it seems it will affect my download task too based on parameter there.

**Comment by Tmp341** [comment]
My settings are all ``1`` for mangadex, except ``UpdateListDirecortyPageNumber``, which is ``0``.

**Comment by uhruhri** [comment]
Yeah my original config was 1 too...but back there i never need to update my manga list so I didnt know CF workaround setting can affect update manga list command.

If I set UpdateListDirecortyPageNumber to 0 it won't update manga list....

**Comment by Tmp341** [comment]
> If I set UpdateListDirecortyPageNumber to 0 it won't update manga list....

Wait what?

**Comment by uhruhri** [comment]
> > If I set UpdateListDirecortyPageNumber to 0 it won't update manga list....
> 
> Wait what? It says `316` for me. Try that.

It's only 1/1 for me...
![mangalist11](https://user-images.githubusercontent.com/49753654/56361951-d987cd80-6212-11e9-9d49-aef0d647848f.png)

CF Setting
![cfsetting](https://user-images.githubusercontent.com/49753654/56361978-eb697080-6212-11e9-9b70-cee17a646f0b.PNG)

**Comment by Tmp341** [comment]
Well, I'm out of options other than asking for your FMD files.

**Comment by uhruhri** [comment]
> Well, I'm out of options other than asking for your FMD files.
> 
> Have you tried `316` for the last one?

Sorry for delay answer. Was trying few things.
Task will work as long I set `UpdateListDirecortyPageNumber` other than `0` or `1` as you can see in screenshot. But I don't know the result yet, since it's quite slow

![cf316](https://user-images.githubusercontent.com/49753654/56362764-d2fa5580-6214-11e9-8b95-1a6d9e5203f7.PNG)

**Comment by Tmp341** [comment]
It is slow because of those ``4`` limits set to **1**. I'm using these settings since the first day Mangadex opened. Never banned (well i can't bypass CF from time to time, but it is a needed feature on FMD's side).

**Comment by uhruhri** [comment]
Hi @Tmp341 thanks for your help
I think the culprit was because I set `UpdateListDirecortyPageNumber` to `1`

Checking again CF Workaround in other thread it didn't mention to set `UpdateListDirecortyPageNumber` to `1`. So yeah it's my mistake, back there I never need to update manga list so I never found this problem and think I used correct configuration

Tried to install in other PC it's working fine.  We can close this

**Comment by Tmp341** [comment]
That ``UpdateListDirecortyPageNumber`` has nothing to do with workarounds etc. It changes from site to site. And it is not "how many mangas that site have". For example, if it didn't change, it was ``267`` for kissmanga. FMD shows it before updating.
