### ISSUE TITLE
Adding multiple favorites at once doesn't work

### ISSUE THREAD

**Issue by Aaron2550** [fmd-project-team/FMD#118]
Would it be possible to make a "Download all from list" feature? For example: The user specifies a .txt or .list or .whatever file and FMD scrapes all the URLs from it and downloads them. Also, would it be possible to add a "Redownload" feature like on torrent clients where it rescans the files and if theyre corrupt/dont exist they get redownloaded?

**Comment by Aaron2550** [comment]
Also, IDK if this is a feature atm but it would be nice to have a "check for new chapters" button

**Comment by Slasar41** [comment]
Someone already request multi download from text file https://github.com/fmd-project-team/FMD/issues/27

**Comment by Aaron2550** [comment]
What about the other two features?

**Comment by Josexv1** [comment]
![image](https://user-images.githubusercontent.com/12077848/56462345-60b27e00-6398-11e9-9f47-cdd03496c650.png)
We already have the "Check for new chapters" button.

The redownload would be cool.

**Comment by SDXC** [comment]
Re-download has already been requested in issue #25 as well.

Slasar41 mentioned #27 for downloads by list files and Josexv1 answered the "Check for new chapters" button. So I'll close this issue as a duplicate. Just check the changelogs when new versions of FMD are being released.

**Comment by Aaron2550** [comment]
> We already have the "Check for new chapters" button.

Yeah but you have to use the favorites system for it and it would be much easier to use if it would just be a button you press and it instantly downloads all new chapters from all mangas ever downloaded. Not gonna add 300+ mangas to my favorites list

**Comment by Josexv1** [comment]
So, what you're asking is that FMD detect the manga that's already in your device, and then check if there are updates for those manga, **also they're not in your favorites?**

**Comment by SDXC** [comment]
@Aaron2550 The favorites are exactly for that. Tracking chapter counts, etc. is only implemented for favorites and it will stay like this. But: You can select multiple entries in the manga list and add them to favorites at once.

**Comment by Aaron2550** [comment]
> @Aaron2550 But: You can select multiple entries in the manga list and add them to favorites at once.

Nope, doesnt work as far as i know. Neither via the dropbox nor Right click > view info > Add to fav. Is there another way?

**Comment by SDXC** [comment]
I'll check it later. If it's really not working, then I'll fix it so my statement will be correct ;)

**Comment by SDXC** [comment]
It does work if you do it like that:
Go to "Manga Info" tab -> Select all manga titles in the list you want to add -> Right click on the selection and click on the "Add to Favorites" menu button.

Now all the titles will be checked for manga info and added to the favorites. The progress is shown on the bottom of FMD.
