### ISSUE TITLE
Favorites UI column bug

### ISSUE THREAD

**Issue by phage80** [fmd-project-team/FMD#12]
Somewhere in the fork this bug is regressed.
https://github.com/riderkick/FMD/issues/1167

**Comment by SDXC** [comment]
Yep, one of the components is not fully compatible with my fork. As I don't know which versions were used in old FMD I have to try different versions Virtual TreeView.

**Comment by SDXC** [comment]
I probably made the exact same mistake as the devs before me. Using v5 of Virtual TreeView. Backporting to v4 fixed it. The fix will be in the next release.

**Comment by SDXC** [comment]
Free Manga Downloader 0.9.162.0 has been released:
https://github.com/fmd-project-team/FMD/releases/tag/0.9.162.0

Issue will be closed.
