### ISSUE TITLE
Download doesn't work [KomikCast]

### ISSUE THREAD

**Issue by JunkCreek** [fmd-project-team/FMD#122]
just get this error recently

Komikcast didn't download any pics, only the chapter

here is the log

`12:30:56:086 WARNING: TTaskThread, checkforfinish failed=28/28 [KomikCast]"Umi no Misaki" > "/chapter/umi-no-misaki-chapter-127-bahasa-indonesia-tamat/"
https://i0.wp.com/lh3.googleusercontent.com/-hdguGdQuqng/W5kRuoVoDMI/AAAAAAAC4fA/SOhG0lVBjdcpe4wcxf6NgR0OTmGW9j8LQCLcBGAs/s1600/00.jpg
https://i0.wp.com/lh3.googleusercontent.com/-CWeFHviRLNY/W5kRvfQXQ0I/AAAAAAAC4fI/hMi7Nvy-FUMRIxw1msTtIb0j7xAkRJ35ACLcBGAs/s1600/01.jpg
https://i0.wp.com/lh3.googleusercontent.com/-Oshgn8pLyVs/W5kRu_yvQ8I/AAAAAAAC4fE/qWFkHT-C0B0Zc-ODI4NmEqMwG6w5Sn5GgCLcBGAs/s1600/02.jpg
https://i0.wp.com/lh3.googleusercontent.com/-n79xmLYKX-U/W5kRvl0VhGI/AAAAAAAC4fM/d6HjDNCgYWg7ZupWGDR1F2AXZAwawFbRQCLcBGAs/s1600/03.jpg
https://i0.wp.com/lh3.googleusercontent.com/-hbfSF6N1_cY/W5kRwDAL8zI/AAAAAAAC4fQ/iTVF-05wbZ8FEMn7edKBi678cZSeQOSqACLcBGAs/s1600/04.jpg
https://i0.wp.com/lh3.googleusercontent.com/-IrfQ0bAap5I/W5kRwkpzmpI/AAAAAAAC4fU/NXSp2628T0g1o-mkfo5LsPG0-gxk8vDngCLcBGAs/s1600/05.jpg
https://i0.wp.com/lh3.googleusercontent.com/-6FCQunSF2Wc/W5kRxPV4ciI/AAAAAAAC4fY/GEj0cfVQBkcxTX5-qtoFG9fKTRC0LA6ygCLcBGAs/s1600/06.jpg
https://i0.wp.com/lh3.googleusercontent.com/-_02IJsOlL40/W5kRx37vU5I/AAAAAAAC4fg/nIr9oLhmESox_-pQRproOIWQiGPvFACwACLcBGAs/s1600/07.jpg
https://i0.wp.com/lh3.googleusercontent.com/-zkdZf22t-0Y/W5kRxzlTpbI/AAAAAAAC4fc/NNwfjuuHMFUhMxZHNyaP1Igih7NMce_MACLcBGAs/s1600/08.jpg
https://i0.wp.com/lh3.googleusercontent.com/-Z5umwUZzrws/W5kRyYprodI/AAAAAAAC4fk/B00umWnXEr0XpBAXymKSmT7AWCI44HPuwCLcBGAs/s1600/09.jpg
https://i0.wp.com/lh3.googleusercontent.com/-hBi61IZ9zqo/W5kRzYvc4BI/AAAAAAAC4fs/DY-bP3T1GKQgV274xi2V5QJjKIJu4FG6QCLcBGAs/s1600/10.jpg
https://i0.wp.com/lh3.googleusercontent.com/-ddT74UzJUFc/W5kRzP9deMI/AAAAAAAC4fo/PSZN_VNKH4w6hgHJnYX0PE0jOh3UmWAOwCLcBGAs/s1600/11.jpg
https://i0.wp.com/lh3.googleusercontent.com/-y1owZ4rJA6I/W5kRzjVjE7I/AAAAAAAC4fw/PQHq0nXrEh8MDyItV-uKmP7uPXht_tNUgCLcBGAs/s1600/12.jpg
https://i0.wp.com/lh3.googleusercontent.com/-bftXEh4sz4c/W5kR0AAxg1I/AAAAAAAC4f0/n9M92wUvpdoBo0-JBX8bj2EmXra5z4DrQCLcBGAs/s1600/13.jpg
https://i0.wp.com/lh3.googleusercontent.com/-WwUhU6agJJg/W5kR0kJcL8I/AAAAAAAC4f4/HMsPIrkKmf4WLy8EVLNQlpSdK5yMoqIwwCLcBGAs/s1600/14.jpg
https://i0.wp.com/lh3.googleusercontent.com/-XJ-OyEaSK4Q/W5kR0pLOLRI/AAAAAAAC4f8/_v4v58V5sTw5ZQ9Sd40Q6BszIo03YrOOgCLcBGAs/s1600/15.jpg
https://i0.wp.com/lh3.googleusercontent.com/-WFelw0tJhzU/W5kR0xoHpLI/AAAAAAAC4gA/0nhgsRPHqCEgSdtZ6i882ZHrHGoSxzBYwCLcBGAs/s1600/16.jpg
https://i0.wp.com/lh3.googleusercontent.com/-mH-VsFLE8w8/W5kR1pl-vpI/AAAAAAAC4gI/pO2AAMKnv4wOfJlysMLi9mlZBEM9UOt5QCLcBGAs/s1600/17.jpg
https://i0.wp.com/lh3.googleusercontent.com/-9oE6wJWQAT4/W5kR1n6uWAI/AAAAAAAC4gE/qZI3-5WT6IoOuDu4tSoO47J-o2pVPH_cACLcBGAs/s1600/18.jpg
https://i0.wp.com/lh3.googleusercontent.com/-QyNNG8UZmic/W5kR2INGgRI/AAAAAAAC4gM/G23JKLrp5XApC_M13gk0eWOrsKzNBx7vwCLcBGAs/s1600/19.jpg
https://i0.wp.com/lh3.googleusercontent.com/-pe2LPNYgbn0/W5kR2kvYaSI/AAAAAAAC4gQ/wgODEpE2nlADq2WZk6zGWqIfpqVBrvdhQCLcBGAs/s1600/20.jpg
https://i0.wp.com/lh3.googleusercontent.com/-ViN6TUpkwAQ/W5kR26Vo6pI/AAAAAAAC4gU/_lB2jX0PkswK1ArFhSsfspRHaWXWltVywCLcBGAs/s1600/21.jpg
https://i0.wp.com/lh3.googleusercontent.com/-jD4jVZ3CIaM/W5kR3SB3L3I/AAAAAAAC4gY/M_DO-WGvDwojEO2b0vvCgDMvOrbRNSq_QCLcBGAs/s1600/22.jpg
https://i0.wp.com/lh3.googleusercontent.com/-e9tfZh-6XNg/W5kR4NQUrfI/AAAAAAAC4gg/knrSiM9A-3siLBNklWQeoBqMTRnmRSJkQCLcBGAs/s1600/23.jpg
https://i0.wp.com/lh3.googleusercontent.com/-Fb6Nitj4BZU/W5kR31GbgUI/AAAAAAAC4gc/iBhFzxREyDErzLEVd7rYGDyqPftaa96-ACLcBGAs/s1600/24.jpg
https://i0.wp.com/lh3.googleusercontent.com/-a0MrKO18ecs/W5kR4Rn0xEI/AAAAAAAC4gk/P5BBx714TJAlO_AyxqK_qipViJ6_qCR9ACLcBGAs/s1600/25.jpg
https://i0.wp.com/lh3.googleusercontent.com/-C9qN_k-dmvk/W5kR5AVubrI/AAAAAAAC4gs/Q92zI_v9zhIyHUy7FPRmoB21CEFWxUT-gCLcBGAs/s1600/26.jpg
https://i0.wp.com/lh3.googleusercontent.com/-1qJzUGO1trw/W5kR40flTOI/AAAAAAAC4go/zPJlqgu_WM8Q2S1j9uiOcBkWePr-nA8PgCLcBGAs/s1600/27.jpg`

Would you please fix the problem?

thanx in advanced.

**Comment by Tmp341** [comment]
It is behind CloudFlare protection. You need to use this workaround explained in Wiki:

https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation

**Comment by AbidZakaria** [comment]
@Tmp341 the site is indeed problematic,
sometimes there are several chapters that don't exist,
so just close this issue

**Comment by Tmp341** [comment]
> 
> 
> @Tmp341 the site is indeed problematic,
> sometimes there are several chapters that don't exist,
> so just close this issue

I'm waiting that from the issuer.

**Comment by JunkCreek** [comment]
can't get something similiar on the work around cf

I get this instead

![screenshot_32](https://user-images.githubusercontent.com/31476117/56602974-df254f00-6628-11e9-925e-e4152d01bfae.png)

**Comment by Tmp341** [comment]
Maybe a ``tampermonkey script`` or ``adblock/ublock filter`` might be blocking it. You're not getting ``cf_clearance=xxxxxxxxxxxxxxxxxxxxxxx`` cookie it seems.

**Comment by JunkCreek** [comment]
> 
> 
> Maybe a `tampermonkey script` or `adblock/ublock filter` might be blocking it. You're not getting `cf_clearance=xxxxxxxxxxxxxxxxxxxxxxx` cookie it seems. I've tried again, i couldn't reproduce your problem.
> 
> Delete komikast's cookies (with or without [this](https://addons.mozilla.org/tr/firefox/addon/a-cookie-manager/)) and try again.

I've deleted adblockplus, clear cache dan cookies via Cookies and Site Data in mozilla option, restrat mozilla, still cf_clearance not apperaing. T_T

Using avast as my AV

Here is the result
![screenshot_33](https://user-images.githubusercontent.com/31476117/56647489-c0b46780-66ab-11e9-946b-c7d2e5ac4bd2.png)

Here is my add-ons
![screenshot_34](https://user-images.githubusercontent.com/31476117/56647528-d2960a80-66ab-11e9-9810-9fb80ed8f2ce.png)

**Comment by Tmp341** [comment]
> The challenge system Cloudflare uses is cookie-based. If you solve a challenge correctly, Cloudflare will set a cookie called CF_CLEARANCE for the domain that presented the challenge. Clearance cookies are like authentication cookies, but instead of being tied to an identity, they are tied to the fact that you solved a challenge sometime in the past.

https://blog.cloudflare.com/cloudflare-supports-privacy-pass/

So, according to CloudFlare, you haven't passed it's ``captcha`` challenge some time ago.

**Comment by JunkCreek** [comment]
trying "random" manga. they worked, but again, I don't know, if it "partially".

may be it just the site (?)

i'd give you another update about my "experiment" with the site.

![screenshot_35](https://user-images.githubusercontent.com/31476117/56648325-54d2fe80-66ad-11e9-923d-e6f80b332a4e.png)

**Comment by Tmp341** [comment]
Try disabling your AV.

**Comment by AbidZakaria** [comment]
> trying "random" manga. they worked, but again, I don't know, if it "partially".
> 
> may be it just the site (?)
> 
> i'd give you another update about my "experiment" with the site.
> 
> ![screenshot_35](https://user-images.githubusercontent.com/31476117/56648325-54d2fe80-66ad-11e9-923d-e6f80b332a4e.png)
> ![screenshot_36](https://user-images.githubusercontent.com/31476117/56648446-8d72d800-66ad-11e9-8f53-85efa3511cef.png)

yes, site problem
try using BacaManga for download your favorit manga

**Comment by Tmp341** [comment]
> yes, site problem

It has nothing to do with FMD?

**Comment by JunkCreek** [comment]
> 
> 
> > yes, site problem
> 
> It has nothing to do with FMD?

I don't know for sure. But, may be it just because the site. Some manga can be downloaded, but some "partially" downloaded (empty chapter)

I don't have another manga client on PC.

But KomikCast had their own app reader on phone.

**Comment by Tmp341** [comment]
> I don't know for sure. But, may be it just because the site. Some manga can be downloaded, but some "partially" downloaded (empty chapter)

Is there a pattern? Like that happens on certain manga or chapter etc? Or completely random?

**Comment by AbidZakaria** [comment]
only happens in old manga and chapter

**Comment by SDXC** [comment]
AbidZakaria fixed the module for KomikCast.
When CF workaround is correctly configured, everything works.

Issue will be closed. If you still get problems, you can re-open it anytime.
