### ISSUE TITLE
Add support for website [ComicWalker]

### ISSUE THREAD

**Issue by ChocolateOtaku** [fmd-project-team/FMD#124]
The website officially publishes comics and is available in different languages EN, JP and TW

https://comic-walker.com/set_lang/en/, https://comic-walker.com/set_lang/jp/, https://comic-walker.com/set_lang/tw/

**Comment by Tmp341** [comment]
#313 Contains more requests.

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
