### ISSUE TITLE
Manga downloading into other manga folder

### ISSUE THREAD

**Issue by Vantageright** [fmd-project-team/FMD#126]
Downloads are saved into the incorrect folder, I don't know what the cause is - its happened with update downloads for faves (which had the correct folder set) and manually selected chapters though the info view. 
Expected folder structure: A:\Manga\XYZ when it ends up A:\Manga\BeeMovieScript\XYZ

**Comment by Tmp341** [comment]
Can you show us what are your settings?

**Comment by Vantageright** [comment]
https://imgur.com/a/ubrpMU3
THose are the save to settings, if you want something else, say but its all default.

**Comment by Josexv1** [comment]
Acoording to your settings it will be saved as:  **A:\Manga\One Piece_MangaDex\756.pdf** you can check if the favorites have another directory set for download.  You can check where it will be saved in the favorites module.

**Comment by Vantageright** [comment]
I check whenever something downloads to somewhere wrong and I fix it. The issue is it ignores the settings at random and will create another manga folder in the preexisting folder- example Naruto\Naruto rather than just putting the chapter in the normal Naruto folder.

**Comment by Tmp341** [comment]
Try doing a fresh install explained here : 

https://github.com/fmd-project-team/FMD/wiki#fresh-install

**Comment by SDXC** [comment]
@Vantageright Has this issue been ever solved for you somehow?
