### ISSUE TITLE
Mangas with missing images [Holymanga]

### ISSUE THREAD

**Issue by molitar** [fmd-project-team/FMD#129]
No matter what manga I read even on the website is always missing images. Users will think it's the fault of FMD but it is not.  
   
I vote to drop support of Holymanga as the site itself does not even listen to the readers and never fixes broken chapters.

**Comment by Tmp341** [comment]
Are they having an issue? Or they don't care about missing parts at all?

**Comment by molitar** [comment]
They do not care.. readers report it and the chapters never get fixed.

**Comment by SDXC** [comment]
For now we let the website in our list.
