### ISSUE TITLE
Downloads not progressing for some links [Hitomi.la]

### ISSUE THREAD

**Issue by gooreat** [fmd-project-team/FMD#13]
Have no problem fetching links from Hitomi.la, but for some reason some of them just won't progress (stuck at 0/total images). Usually happen to galleries with 1k+ images.  

Been happening since the old version (0.9.158), thought this has been fixed since the changelogs mentioned the site :P

Glad someone decided to continue this project :D

**Comment by SDXC** [comment]
Hi, please provide some examples that failed and one that didn't fail. I will look into it today evening (GMT +1h).

**Comment by gooreat** [comment]
NSFW obviously, but here's one with >1k images that didn't work: https://hitomi.la/galleries/1371641.html
and this one is working for some reason (almost 2k images): https://hitomi.la/galleries/1389147.html

Thanks!

**Comment by SDXC** [comment]
@gooreat I think the problem is, that the images don't even load on the website itself... I was checking the gallery you couldn't download and I can't even see the images in the browser. That would be a website problem.

**Comment by SDXC** [comment]
I just re-checked. One thing I had to fix when I forked FMD was, that Hitomi uses a second image server called ba.hitomi.la which wasn't being checked against. The old image server called aa.hitomi.la is currently having problems. That's where all the galleries reside in, that can't be properly loaded.

Let's wait abit, if it's only a temporary problem. It's also possible, tha Hitomi is migrating from aa to ba.

**Comment by gooreat** [comment]
@SDXC well, I just downloaded the new FMD (and had to install it manually due to some error :P) and guess what, the download is now working lol (at least for the first link, haven't tried other links yet)  

Should I close the issue now? or wait after few more testing?

**Comment by SDXC** [comment]
@gooreat I'll close the ticket. You can reopen it anytime if it happens again. Like I said before. It's possible that one of the image servers just had some temporary problems.
