### ISSUE TITLE
Download doesn't work [MangaChanRu]

### ISSUE THREAD

**Issue by makharius** [fmd-project-team/FMD#130]
A few days ago the program stopped receiving the list of chapters from [mangachan.me](https://mangachan.me) I hope you can help me. Thanks in advance!
![2019-04-23_190822](https://user-images.githubusercontent.com/49916865/56597637-89867d80-65fb-11e9-920c-721399c276ae.jpg)

**Comment by Tmp341** [comment]
https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation

Try the workaround above.

I got a ``PHPSESSID=xxxxxxxxxxxxxxxxxxxxxxxxx`` cookie. Try getting that and adding explained here:

**Comment by makharius** [comment]
I tried this solution, but unfortunately nothing has changed.

**Comment by Tmp341** [comment]
It seems FMD only gets something else (like 1 chapter), even though the manga I've tested has ``49`` chapters.

**Comment by imKota** [comment]
@SDXC Any news?

**Comment by SDXC** [comment]
It's now a lua script and should work after you updated your lua scripts.

Issue will be closed. Re-open it, if you still have some issues.
