### ISSUE TITLE
FMD Update doesn't work

### ISSUE THREAD

**Issue by hilmanfaiz** [fmd-project-team/FMD#133]
I see the current version is v0.9.163.0 and I'm using v0.9.162.0 and the button `Check for latest version` on `About FMD` doesn't auto-update the app.

Please fix, thanks

**Comment by SDXC** [comment]
Can you please attach the "base.ini" from your "config" folder?

**Comment by hilmanfaiz** [comment]
oh I see the problem, and it's on my side.
so I back then I when I migrate from riderkick to this fork, I copied `config` and `works` folder to keep my FMD download history, favorites, etc..
`base.ini` is also replaced. I've tried replacing it back to original `base.ini` and now it works

thanks
