### ISSUE TITLE
Download doesn't work [MangaLib]

### ISSUE THREAD

**Issue by Tosterr1** [fmd-project-team/FMD#140]
![57013169-ee9d2d00-6c12-11e9-858b-482574100359](https://user-images.githubusercontent.com/42684479/57079088-4e213880-6cf8-11e9-8ee9-85c7e097835e.jpg)
![57013167-ee9d2d00-6c12-11e9-95dc-e0a2b5db13b7](https://user-images.githubusercontent.com/42684479/57079090-4eb9cf00-6cf8-11e9-9c15-25065cde46e8.jpg)

**Comment by SDXC** [comment]
AbidZakaria fixed it. New lua script should be available on next restart.

Issue will be closed. If you still have problems, just re-open this issue.
