### ISSUE TITLE
Download Fails [NewType]

### ISSUE THREAD

**Issue by ChocolateOtaku** [fmd-project-team/FMD#141]
Cannot download chapters from e.g.
https://comic.webnewtype.com/contents/zone/

**Comment by Tmp341** [comment]
Probably needs fixes within -> [NewType.pas](https://github.com/fmd-project-team/FMD/blob/master/baseunits/modules/NewType.pas), it is in ``Lualize`` project #37.

**Comment by SDXC** [comment]
Finally came around to fix it. There were many faults in the original parsing which I fixed as well (for example the manga and chapter names)
