### ISSUE TITLE
Add support for website [Toomics, ValhallaScans]

### ISSUE THREAD

**Issue by yoshiro12** [fmd-project-team/FMD#144]
Hello please add 
https://global.toomics.com
https://manytoon.com
https://valhallascans.com
please thank you.

**Comment by SDXC** [comment]
ManyToon has already been asked for #125
It will be handled there.

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
