### ISSUE TITLE
List index out of Range when downloading all lists at once [ManhwaCo]

### ISSUE THREAD

**Issue by molitar** [fmd-project-team/FMD#145]
Windows 10 64-bit
32GB DDR4 Memory

When I am downloading all list at once I get this error after some time.

> 19:15:46:078 VALUE: Loaded modules from WPManga.lua = Authrone, EyeOnManga, MangaDeep, Manga99, ReadHentaiManga, HentaiRead, 3asq
> 19:24:08:146 INFO: 3100
> 21:10:56:555 EXCEPTION: EStringListError - List index (0) out of bounds
> 
>   Website : ManhwaCo
>   CS      : CS_DIRECTORY_PAGE
> 
>                  $000000010005326F
>                  $0000000100053EBD
>                  $0000000100003B96
>                  $0000000100015067
>                  $00007FFDE47A3034
>                  $00007FFDE4B31551

**Comment by AbidZakaria** [comment]
you try download from ManhwaCo?

**Comment by molitar** [comment]
I was just doing the update lists and got that error.

**Comment by SDXC** [comment]
Can you update the manga list only for ManhwaCo? Do you still get that error?

**Comment by SDXC** [comment]
That's a ManhwaCo module specific error. Will look into it.

**Comment by SDXC** [comment]
Should be fixed now. Issue will be closed.
