### ISSUE TITLE
Some downloads fail [Kumanga]

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#146]
http://www.kumanga.com

**Comment by Tmp341** [comment]
Wait, title says ``Newtype`` but you've asked for ``Kumanga``. Which one is it?

Newtype is needed to be implemented in **Lua** language. If kumanga isn't working, we should check it.

**Comment by AbidZakaria** [comment]
@Tmp341 can you remove Newtype from list project lualize
because that site not manga reader

**Comment by AbidZakaria** [comment]
i can access and download from `kumanga`

![image](https://user-images.githubusercontent.com/19544118/57182361-5f20a400-6ec8-11e9-8304-033d540d7fda.png)

![image](https://user-images.githubusercontent.com/19544118/57182366-6a73cf80-6ec8-11e9-96d0-67bb4c968c77.png)

**Comment by SDXC** [comment]
For NewType there already exists an issue.

For KuManga there is actually a problem with their website and nothing we can fix.
Downloads that fail are also failing when loading on their website.

Issue will be closed.

**Comment by djgerman10** [comment]
> i can access and download from `kumanga`
> 
> ![image](https://user-images.githubusercontent.com/19544118/57182361-5f20a400-6ec8-11e9-8304-033d540d7fda.png)
> 
> ![image](https://user-images.githubusercontent.com/19544118/57182366-6a73cf80-6ec8-11e9-96d0-67bb4c968c77.png)

It's weird because on the page I could read the magician but I can not download it.
Thank you for taking the trouble to see the problem

sorry for my English
I am using the translator
Greetings from Argentina

**Comment by SDXC** [comment]
@djgerman10 Do you still have trouble with downloading some chapters? It works fine for me. Can you give me an example that doesn't work for you?

Just asking because of your name: Do you understand German?

**Comment by djgerman10** [comment]
![1](https://user-images.githubusercontent.com/48584512/57980233-ead51d00-79fe-11e9-982f-0f50b1bcb9c8.png)

http://www.kumanga.com/manga/2534/seirei-tachi-no-rakuen-to-risou-no-isekai-seikatsu

no download remains at 0 bps

**Comment by rs3mk** [comment]
Some chapters use external links that are "encrypted" as a source, it is possible that this is the cause of the error.

![link_external](https://user-images.githubusercontent.com/19628943/58952541-9bf6e980-8759-11e9-9aa6-fa5ea6abc65f.png)

**Comment by ChocolateOtaku** [comment]
Where is this encrypted?
These are perfectly valid URLs...
`/img.php?src=68655645...`

**Comment by rs3mk** [comment]
yes, they are Google Drive links.

son enlaces de google drive o blogger tras esos enlaces.

**Comment by ChocolateOtaku** [comment]
No, these are links pointing to ‘img.php’ which is hosted on KuManga and will redirect to wherever the image is stored (e.g. google, imgur, ...)

**Comment by SDXC** [comment]
should be okay now.

**Comment by inkanime** [comment]
@SDXC Hi, I also have the same download problem, and I have noticed that the user "solosubo" does not allow downloads in the program, the other users of the web do not have errors in the download.

![image](https://user-images.githubusercontent.com/45970408/63570942-51a92b80-c544-11e9-8592-b2a4b9fa149f.png)

![image](https://user-images.githubusercontent.com/45970408/63571091-cbd9b000-c544-11e9-984e-744e6fb96e81.png)

I hope you can find the solution to this case, thanks for your attention and time.
