### ISSUE TITLE
Website change domain [otakuindo]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#149]
From https://otakuindo.net/ to https://otakuindo.co/
![otakuindo co](https://user-images.githubusercontent.com/45929526/57190353-5f11ba00-6f43-11e9-8863-8d5888d0d006.PNG)
![otakuindo net](https://user-images.githubusercontent.com/45929526/57190354-5f11ba00-6f43-11e9-9041-c599624402f8.PNG)

**Comment by SDXC** [comment]
Url changed.
