### ISSUE TITLE
Missing chapters [ComicExtra]

### ISSUE THREAD

**Issue by Von07** [fmd-project-team/FMD#151]
Ex:
Site: Has all chapters
https://www.comicextra.com/comic/the-walking-dead 

FMD: Missing Chapters from the site
![Problem2](https://user-images.githubusercontent.com/21298898/57245730-1e628f80-706e-11e9-93ef-dbc554db211a.png)

Version	:	0.9.163.0

**Comment by SDXC** [comment]
Maybe we should also invert the chapter list like the other websites.

**Comment by SDXC** [comment]
AbidZakaria fixed it.
