### ISSUE TITLE
Help for lua script [MangaTr, Puzzmos]

### ISSUE THREAD

**Issue by AbidZakaria** [fmd-project-team/FMD#153]
@SDXC i can't handle cookie request @_@
[manga-tr.zip](https://github.com/fmd-project-team/FMD/files/3151344/manga-tr.zip)

**Comment by SDXC** [comment]
I released the script, as it seems to work fine. I'll close this issue. If you have anything that has still to be fixed, let me know in Discord. Thanks for your work.
