### ISSUE TITLE
Getting or updating manga list doesn't work [PervEden]

### ISSUE THREAD

**Issue by molitar** [fmd-project-team/FMD#156]
Ok as there is many inactive files when using Download list from server I thought I would start fresh.  So I used Update manga list and it failed to update most of the chapters that are available. For example Cartoonist not found.

**Comment by AbidZakaria** [comment]
Give me link perveden

**Comment by AbidZakaria** [comment]
it's not bug (maybe)
but perveden is offline website or change domain

can you access that website in your browser?

![image](https://user-images.githubusercontent.com/19544118/57343452-a9767f00-716d-11e9-9b9d-4f1be79bcc7c.png)

**Comment by molitar** [comment]
Yes I can reach the website just fine. I have attached a screenshot of what I get when I update from the manga list and not download from server.

http://www.perveden.com/eng/

![Screenshot_1](https://user-images.githubusercontent.com/16074561/57344781-8ec4eb80-7116-11e9-85cc-d904917cfaeb.png)

**Comment by Tmp341** [comment]
My update list found ``100``, i guess that is not the exact number though.

**Comment by SDXC** [comment]
Fixed.
