### ISSUE TITLE
Wrong number on new chapters window's title bar

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#159]
The number on this window's title bar is wrong, this happened in other language too.
![image](https://user-images.githubusercontent.com/28888646/57529034-1badb600-735e-11e9-97ec-254a093000e6.png)

**Comment by SDXC** [comment]
@Slasar41 Strings have been changed. The translations have to be redone for these strings:
https://github.com/fmd-project-team/FMD/commit/afc3c8e382a4644a278ca184c32a47d9a4269d97

I'll close this issue. Just create the usual pull-request for the translation.
