### ISSUE TITLE
Default bar size vertically too short

### ISSUE THREAD

**Issue by RoudoRora** [fmd-project-team/FMD#167]
![image](https://user-images.githubusercontent.com/50617023/57707141-add4f780-7699-11e9-997a-7473fc74821d.png)
Adjustable vertical expansion like the horizontal expansion function would be good.

**Comment by Slasar41** [comment]
I think it has something to do with DPI scaling.
Try changing these options:
![image](https://user-images.githubusercontent.com/28888646/57716465-4623aa00-76a3-11e9-95bd-3d0067dff08e.png)
