### ISSUE TITLE
Missing French translation - Manque traduction française

### ISSUE THREAD

**Issue by jsoudeer** [fmd-project-team/FMD#169]
Hello,

Did a french translation is in progress? If not can i propose my help?
Une traduction française est-elle en préparation? sinon puis-je proposer mon aide?

Regards
Cordialement

Johan

**Comment by Tmp341** [comment]
I haven't seen any. You can always translate and create PR.

**Comment by jsoudeer** [comment]
Hello,
I'v tried a PR, my request was in riderkick repo.
I follow this https://help.github.com/en/articles/creating-a-pull-request  and i'm stuck, i'm not allow to upload.

Any clues?

johan

**Comment by Tmp341** [comment]
You have to fork this repo first, then create a pull request. Or, just zip and upload it here.

**Comment by Tmp341** [comment]
I've accepted your PR. If you have any problem, you can reopen this issue.
