### ISSUE TITLE
New download jobs are not sorted when adding to the list

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#17]
I sort Added column in descending order but the new downloads always added at the bottom list so I must manually refresh it by changing to ascending order then descending order again and the new downloads will be at top list as it should be.
This issue been happening for a long time I've just been too lazy to log an issue.

**Comment by SDXC** [comment]
It's like that for me as well (sometimes this behavior is useful to me).
I will look into it.

**Comment by SDXC** [comment]
@Slasar41 I added an option to sort the downloads list automatically when adding a new download task.

Keep in mind, that if you enable this option, the complete download list will be sorted. I guess that's not really an issue for you, but just so you know.

To enable that option, see the screenshot (don't forget to "Apply"):

![SortDownloadsOption](https://user-images.githubusercontent.com/5290260/55578260-c30f4b80-5715-11e9-881a-967441580d1a.png)

**Comment by Slasar41** [comment]
Alright, thank you.

**Comment by SDXC** [comment]
New version will be up on the weekend. Still trying to implement some more things :)

**Comment by Slasar41** [comment]
Ok, nice to see FMD project still alive :)
One question, isn't it should be default the new download jobs to be at the top list when the Added column sorted by descending order?

**Comment by SDXC** [comment]
More like resurrected :P 

For now I think we should let the default be appending at the end of the list.
The new option let's you sort by ANY order you set, even if you sort by Status.

Technically it's less complex if you just add new tasks at the end of the list. The downloads are being processed from top to bottom as well, so always adding at the top could be pretty strange, so it should be an option a user explicitly wants.

**Comment by Slasar41** [comment]
I have IDM app and sorted the Last Try Date column by descending order and the newest download will always be at the top list. I like it so I don't have to scroll down through many list to find the new download.
Anyway thanks to the new option. :D 
Will you add what changes to the code in commits?

**Comment by SDXC** [comment]
> Would you add what changes to the code in commits?

Just did ;)

**Comment by Slasar41** [comment]
Nice. :)

**Comment by SDXC** [comment]
Free Manga Downloader 0.9.162.0 has been released:
https://github.com/fmd-project-team/FMD/releases/tag/0.9.162.0

Issue will be closed.
