### ISSUE TITLE
Not really an issue, but more like a report [KissManga]

### ISSUE THREAD

**Issue by ayanamichie** [fmd-project-team/FMD#170]
After some time without trying like 2 weeks more, it was not working just getting the cookies and user agent. to work again i had to get:
![image](https://user-images.githubusercontent.com/48865118/57737596-9dfde900-7682-11e9-9273-659c0bbd1bef.png)
the initialization vector did not change, but the key did:
![image](https://user-images.githubusercontent.com/48865118/57737716-09e05180-7683-11e9-85e1-bf3a2c429e08.png)
how to if people need to get.

After that getting the user agent and cookie worked.
![image](https://user-images.githubusercontent.com/48865118/57737760-31371e80-7683-11e9-9bcd-0eaf6b4a02eb.png)

**Comment by Tmp341** [comment]
It is always good to know that, until it is deprecated.

**Comment by Slasar41** [comment]
Yup, three days ago I also need to change the Key content to get KissManga working again.
@Tmp341 You should put back the KissManga workaround to Wiki.

**Comment by Tmp341** [comment]
@Slasar41 Done. 🙂

**Comment by SDXC** [comment]
@ayanamichie Thanks for your report. I'll close this issue now.
