### ISSUE TITLE
Add support for website [MangaHost, MangaMX, ZManga, HeavenManga]

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#171]
Hello please add
**Portugues**
http://br.mangahost.com

**Spanish**
https://manga-mx.com
https://zmanga.org
http://heavenmanga.com

**Comment by djgerman10** [comment]
Thank you **AbidZakaria**

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
