### ISSUE TITLE
Can't get latest Lua modules

### ISSUE THREAD

**Issue by ragna0011** [fmd-project-team/FMD#173]
yeah, i'm new to this, and idk about any programming languages. im only asking, what is the latest version for this? cuz sumhow i cant update the fmd, is v 0.9.163 the latest? can anyone just give me the lua file for all available sites? thank you

**Comment by Tmp341** [comment]
v0.9.163.0 is the latest, you can track [here](https://github.com/fmd-project-team/FMD/releases).

Lua files are up to date, FMD downloads them automatically if you have a connection (unless you, your av or isp blocks github servers).

**Comment by ragna0011** [comment]
well, i dont really know, i tried disabling my avast, but still wont update my lua, maybe firewall? havnt tried it. idk about my isp tho...may latest lua was updated 1/18/2019. so im asking if can u zip ur lua files guys then share it to me? :)

**Comment by SDXC** [comment]
@ragna0011 Did you update to our forked version? If you still use riderkick's version you won't get the new lua files.

**Comment by Renvix** [comment]
How do I update manually?
