### ISSUE TITLE
The text link is overlapping the Abort button

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#176]
The text link is overlapping the button for aborting the FMD update.
And maybe use icon instead of text and make the proggress bar like on Manga Info tab.
![image](https://user-images.githubusercontent.com/28888646/57971724-e63b4500-79bb-11e9-9bc2-a3d552b438b6.png)

**Comment by dazedcat19** [comment]
I did some changes to the button. It's already included in 1.1.2.0
https://github.com/fmd-project-team/FMD/commit/126e93950cead40e2475b8b1629a3f66a8bc2f98
I'm too lazy to do the custom draw at the moment. It needs carefully calculating for high dpi device.
