### ISSUE TITLE
FMD freeze and causing HDD active time to spike

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#177]
Some files are being written into works folder:
`downloads.db-journal`
`favorites.db-journal`
And then those files just vanished.
This happened within 2 minutes interval and causing FMD to freeze, you can see the close button on FMD became red color for a few seconds.
See: https://i.imgur.com/IxRdBl0.gifv
FMD version: 0.9.164.0

**Comment by SDXC** [comment]
Do you have other hardware to test on?
How large are your db files?
What was FMD doing at the time?
Did this also happen in older versions of FMD or even Riderkick's version?

The db-journal files are temporary and is an expected behavior.

**Comment by Slasar41** [comment]
Yes, also happened on my desktop with the same content of FMD folder on my laptop.
Here's the size:
![image](https://user-images.githubusercontent.com/28888646/57972354-57322b00-79c3-11e9-9904-1a3dda690e6d.png)
Contains 5333 downloads and 492 favorites.
The issue consitent happened within 2 minutes interval.
Whatever FMD do, even when FMD doing nothing also causing that.
Yes, this also happened on older version even riderkick's version.

Maybe you can test my db files on yours?

**Comment by SDXC** [comment]
Zip your complete installation and upload it here.

**Comment by Tmp341** [comment]
Those files are temp files, while FMD running, those files are created. When you close FMD, those files become the original ones.

**Comment by Slasar41** [comment]
Here's my FMD folder:
[FMD.zip](https://github.com/fmd-project-team/FMD/files/3194309/FMD.zip)

**Comment by Tmp341** [comment]
Are you downloading something while testing that?

**Comment by Slasar41** [comment]
No, I zipped it when still downloading.
While downloading or doing nothing, the freeze and spike still happened.

**Comment by Tmp341** [comment]
You have:

- w10 installed while using 2GB ram. w10 uses system ram more than w7.
- You have a 5400rpm hdd. I was having stutters with games, because w10 uses hdd too.
- I can't say anything about cpu load. Let me test your fmd.

**Comment by Tmp341** [comment]
![sssssbsss](https://user-images.githubusercontent.com/1683388/57978394-cafd2380-7a15-11e9-94d6-72532eba5bab.jpg)

Here is the test I've done with ``Senryuu Shoujo``. Normal CPU load, normal Ram usage. Only almost similar thing is, my 2nd hdd is 5400rpm too, and you can see 89% spike is there.

**Comment by Slasar41** [comment]
Within 2 minutes interval too?

My desktop HDD use 7200RPM but the same thing happened.
Maybe using HDD is more apparent than using SSD?
I not yet moving my FMD folder to SSD to test it.

**Comment by Slasar41** [comment]
The thing is when those HDD spike happened, FMD also freeze. It's kinda annoying.

**Comment by Tmp341** [comment]
![ssssscsss](https://user-images.githubusercontent.com/1683388/57978474-4f03db00-7a17-11e9-819e-07037d67006d.jpg)

**Comment by Tmp341** [comment]
Windows already uses hdd too much, and when you try to do a massive read/write operation (like gaming or downloading multiple manga like this etc), it becomes a hassle for the slow rpm hdds. Like i said, i was using my second hdd as primary, it was a mess. Then i've bought an ssd, connected my hdd as secondary. It works like a charm.

I don't see any problem on fmd's end, probably resource usage is causing that. Let @SDXC check it too.

**Comment by Slasar41** [comment]
You can see C: drive on my gif, that SSD.
I was also use my HDD 5400RPM as primary drive, it was horrible until I bought SSD.
I will put FMD on my SSD to test it

**Comment by Slasar41** [comment]
Well after I move it to SSD, the freeze and spike still happened but only last for a second.
Maybe the resource can be reduced so that thing never happened?

**Comment by Tmp341** [comment]
> You can see C: drive on my gif, that SSD.

Well, your FMD writes to your D drive.

**Comment by Slasar41** [comment]
Yes, that's why then I try to test it on C drive but it still happened only less freeze time.

**Comment by dazedcat19** [comment]
@Slasar41 I can't reproduce this issue. I downloaded your file, everything seems normal. There's no spike on io reads/writes. You can try to use performance monitor or procmon by sysinternal to see what file accessed when io use is high. 
By reading some comments above my suspect is your lack of ram. Win 10 needs at least 4gb. Even though they advertise the min is 1gb. If the ram is lower than 4gb it will force you to use pagefile. Which is virtual ram with your hard disk. Ram access is very frequent. Read and write all the time. Even when you did nothing, it will make a cache etc. Especially if your ram is low. It will aggressively accessing the pagefile. It will move the background process to pagefile and only load the foreground process in ram. When you move the focus to other app it will do all of that again. That's what make it sluggish.

There's no routine in fmd to write to file every 2 minutes or so. Databases loaded to ram. And written back at close.

**Comment by Slasar41** [comment]
@dazedcat19 Do you already see my imgur link? It's shows the recording of procmon.
Hmm… I have PC with 8GB of RAM and 1TB 7200RPM HDD, with FMD 1.0.0.0 the issue still persist. I can see my HDD usage goes up every 2 minutes in Task Manager.

**Comment by dazedcat19** [comment]
@Slasar41 oh I see. Can you build FMD by yourself?

**Comment by Slasar41** [comment]
I want to try it but have errors installing some components like multilog and internettools.

**Comment by dazedcat19** [comment]
Just download the zip file from github for multilog and Internettools (clone or download button). Extract it somewhere like lazarus\mycomponents\internettools. Internettools needs flre and pucu so you need that file too. Get it from https://github.com/BeRo1985/flre and https://github.com/BeRo1985/pucu respectively. Put flre.pas and pucu.pas in Internettools\data then open internettools.lpk with Lazarus(package>open package). And compile. For multilog just open multilog lpk file and compile. Then build the project.

**Comment by Slasar41** [comment]
Thanks, InternetTools success compiled. That file should be mentioned on readme too.
MultiLog error:
![image](https://user-images.githubusercontent.com/28888646/73482482-6c73ac00-43d0-11ea-91f7-11d3473db2fd.png)

**Comment by dazedcat19** [comment]
@Slasar41 just remove the outputchannel from package inspector. That file doesn't exist. It seems the author planning to add that file but never push the commit for some reason.
Note that you have to remove that file from package file list not from the source. The window that opened when you open the package. There is should be a red mark in the file list that indicating file not found. Then save and compile the multilog package.

**Comment by Slasar41** [comment]
@dazedcat19 success compiled multilog.
Now I have this error when opening the md.lpi file:
![image](https://user-images.githubusercontent.com/28888646/73530499-3293bb80-444b-11ea-9e6c-c59cc8e9b80a.png)

**Comment by dazedcat19** [comment]
@slazar41 just change the build-mode to win64. To build the win32 version you need the cross-compiler.  When you download the lazarus setup there's another file called '-cross-'. Download and install it at the same location where you install lazarus.

**Comment by Slasar41** [comment]
@dazedcat19 Thanks.
Now I got this error when trying to build it.
I'm using latest commit.
![image](https://user-images.githubusercontent.com/28888646/73590985-9eddf000-451b-11ea-9eea-3ed145c1eea2.png)

**Comment by dazedcat19** [comment]
I pushed a change, please try again.

**Comment by Slasar41** [comment]
Thanks, I can build it now.
And I don't see any freezing every 2 minutes anymore.
When I'm hovering the list now it's looks like this:
![image](https://user-images.githubusercontent.com/28888646/73603817-2ed27700-45ba-11ea-90c9-eea001e38e40.png)
Is this a new change or I still missing something?
If this a new change, could you remove the underline marker?

**Comment by dazedcat19** [comment]
That's new. Yeah I forgot about that. Please do more test. I did some changes to improve the performance. Startup and shutdown should be faster. Cleaned up some database routines, using multi-threding to load the lua files, etc. I hope there's no side effect. Just do more test before releasing an update.

**Comment by Slasar41** [comment]
I didn't find any issue, tested downloading from Favorites, add, remove, enable, disable the list on Download & Favorites.
Now the exit is instantaneous I like it. :)
