### ISSUE TITLE
How to manually update FMD

### ISSUE THREAD

**Issue by Renvix** [fmd-project-team/FMD#178]
How do I update fmd manually?

**Comment by SDXC** [comment]
Just to be on the safe side, make a copy of your FMD installation (zip it or simply copy it into a new folder).

The fastest way to update is going into the "config" folder and open "base.ini" with a text editor (Notepad).
Change the line with "UPDATE_URL=........" as following:

`UPDATE_URL=https://raw.githubusercontent.com/fmd-project-team/FMD/master/update`

When you restart FMD, it will look for the new version in our repository and asks you to install the update.

**Comment by Renvix** [comment]
![error](https://user-images.githubusercontent.com/29302760/57972921-ee4eb100-79ca-11e9-8bdc-32023466e688.jpg)
line with the same contents already in the file, and also an error occurred after the update to v164

**Comment by SDXC** [comment]
Did you try if FMD works if you make a fresh installation?
Maybe the favorites.db was being updated when you updated FMD. Do you have a backup of your files like I recommended?

**Comment by Renvix** [comment]
the backup is there and fresh installation can work.

from fresh installation I realized that a possible error occurred because many manga sites on version 163 were missing on version 164

**Comment by Renvix** [comment]
after some time after the fresh installation program error again, the problem is likely to be in the favorite tab section in v164
![Untitled](https://user-images.githubusercontent.com/29302760/58183106-ecd9fd00-7cd8-11e9-862d-f5570d98c1f3.jpg)

**Comment by SDXC** [comment]
Does this still occur?

**Comment by Tmp341** [comment]
It is most likely your ``Favorites.db`` file is problematic here. Can you send it?
