### ISSUE TITLE
Only first image is downloading [MangaToon]

### ISSUE THREAD

**Issue by amit34521** [fmd-project-team/FMD#180]
Mangatoon only downloading first image of the chapter. Please check. I checked with Wu dong qian kun and the god of martial arts.

**Comment by Von07** [comment]
I always experience this problem before so I hope this will fix too

**Comment by SDXC** [comment]
Just asking, but you do know that this is a problem with the website, right? The first chapter for example is fully available and can be downloaded, but the newer chapters are locked and only available through their app. Nothing we can do here.

**Comment by ChocolateOtaku** [comment]
I tested and [God of Martial Arts](https://mangatoon.mobi/en/detail/1816) not have all episodes for free.
FMD can download the first 20 episodes.
With HakuNeko i was possible to get the first 36 episodes.
