### ISSUE TITLE
Website changed domain [PecintaKomik]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#181]
from "https://www.pecintakomik.com" to "https://www.pecintakomik.net/"

![fmdpecintakomik](https://user-images.githubusercontent.com/45929526/57977940-c1cb8100-7a2c-11e9-9627-6aee2068cdf3.PNG)
![pecintakomik net](https://user-images.githubusercontent.com/45929526/57977941-c2641780-7a2c-11e9-90d6-6b8f981220d8.PNG)

**Comment by SDXC** [comment]
Website url has been changed.
