### ISSUE TITLE
Add support for website [Daum]

### ISSUE THREAD

**Issue by gfhghfghfh** [fmd-project-team/FMD#186]
http://webtoon.daum.net/

**Comment by AbidZakaria** [comment]
@gfhghfghfh maybe site problem

@SDXC can you test in your browser
![image](https://user-images.githubusercontent.com/19544118/58036484-6b0d9680-7b55-11e9-85db-348ead015ca9.png)

**Comment by gfhghfghfh** [comment]
@AbidZakaria 
<img width="523" alt="1" src="https://user-images.githubusercontent.com/42042168/58037567-3fdc7480-7b60-11e9-993e-588be67bd1c4.PNG">

**Comment by AbidZakaria** [comment]
region lock maybe

**Comment by Slasar41** [comment]
@AbidZakaria I also can open it.
Coba buka lagi
![image](https://user-images.githubusercontent.com/28888646/58046658-2cd1a080-7b70-11e9-986e-0b3f16c15fad.png)

**Comment by Tmp341** [comment]
@AbidZakaria deleting cookies might help (you can use cookie manager to just delete that site's cookies).

**Comment by AbidZakaria** [comment]
@Tmp341 not work it's provider lock
i can access using other provider
but can't access using Hutchison provider (three)

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
