### ISSUE TITLE
Add support for website [WebcomicsApp]

### ISSUE THREAD

**Issue by gfhghfghfh** [fmd-project-team/FMD#187]
https://www.webcomicsapp.com/

**Comment by AbidZakaria** [comment]
i can create lua for this site
but i can't get all manga chapter because blocked / premium chapter

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
