### ISSUE TITLE
Add support for website [MangaTensei]

### ISSUE THREAD

**Issue by yoshiro12** [fmd-project-team/FMD#188]
Please add mangatensei.com

**Comment by AbidZakaria** [comment]
Note:
Multiple language same like mangadex

**Comment by SDXC** [comment]
https://github.com/fmd-project-team/FMD/issues/217#issuecomment-506950219

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
