### ISSUE TITLE
Banned by Cloudflare [TumangaOnline]

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#191]
it's normal that cloudflare me banned?

![dened](https://user-images.githubusercontent.com/48584512/58156225-fc5f3480-7c4b-11e9-9a7a-f865b0b9279f.png)

![2](https://user-images.githubusercontent.com/48584512/58156233-02edac00-7c4c-11e9-9559-88c2c615292d.png)

**Comment by Tmp341** [comment]
You have probably made too much request.

**Comment by djgerman10** [comment]
![x](https://user-images.githubusercontent.com/48584512/58157814-8957bd00-7c4f-11e9-97f0-f0ab26f15b4f.png)

**Comment by djgerman10** [comment]
![x](https://user-images.githubusercontent.com/48584512/58157960-d2a80c80-7c4f-11e9-9a97-f14ae0c7891f.png)

**Comment by Tmp341** [comment]
Also ``Options -> Connections`

**Comment by djgerman10** [comment]
![x](https://user-images.githubusercontent.com/48584512/58158280-7e515c80-7c50-11e9-9380-b19391ec49e4.png)

**Comment by Tmp341** [comment]
You don't have a problem on your settings it seems.

**Comment by djgerman10** [comment]
activate vps pshipon 3

and go well to https://tmofans.com/
but I can not download from the free manga downloader program


sorry for my english I am using the translator

**Comment by Tmp341** [comment]
I can understand what you're trying to tell. 👍

**Comment by djgerman10** [comment]
![x](https://user-images.githubusercontent.com/48584512/58159091-2c113b00-7c52-11e9-8db2-fbacde676301.png)

the page with the vps does not work in the program, but in the google browser if

cable clarify that I'm using psiphon 3

**Comment by djgerman10** [comment]
![x](https://user-images.githubusercontent.com/48584512/58159355-b22d8180-7c52-11e9-919d-5315d6b72bb8.png)

**Comment by djgerman10** [comment]
![x](https://user-images.githubusercontent.com/48584512/58159440-e5701080-7c52-11e9-8ec2-f75b9a99bd33.png)

**Comment by Tmp341** [comment]
Delete your tumanga cookies with a cookie manager, restart your router, add these numbers to ``Options -> Websites -> Advanced -> Tumangaonline`` : 

- ``MaxTaskLimit`` : ``1``
- ``MaxThreadPerTaskLimit`` : ``1``
- ``MaxConnectionLimit`` : ``1``
- ``UpdateListNumberOfThread`` : ``1``
- ``UpdateListDirectoryPageNumber`` : ``0``

**Comment by djgerman10** [comment]
still not walking.
the cookies do not know how to erase.


**Thanks for everything and sorry for the inconvenience**

**Comment by Tmp341** [comment]
Which browser are you using?

**Comment by djgerman10** [comment]
Google Chrome

**Comment by SDXC** [comment]
Please don't do anything with tumanga as long as 0.9.165.0 is not released. There are two things I'll change:

* If cf_bypass fails 5 times, it won't be called again until you restart FMD.
* If more than 1 cf_bypass processes are still running, FMD will kill them first before creating a new process.

I will also look into why the cf_bypass doesn't work with tumanga.

**Comment by djgerman10** [comment]
![x](https://user-images.githubusercontent.com/48584512/58160780-7fd15380-7c55-11e9-86e8-e4b06057e274.png)
activating psiphon 3 activates these options.
I do not know if I have something to do but I throw the data just in case haha.

**Comment by Tmp341** [comment]
Just wait until next release.
Solo espera hasta el próximo lanzamiento.

**Comment by rs3mk** [comment]
usa un proxy, tmo siempre me ha bloqueado al leer los favoritos (tengo muchos): https://free-proxy-list.net/

![proxyy](https://user-images.githubusercontent.com/19628943/58225540-13ebfb00-7ce8-11e9-9bf2-6ddd96242ca7.png)

**Comment by djgerman10** [comment]
perfecto voy a usar de ahora en mas 

Gracias fiera

**Comment by SDXC** [comment]
I just checked and it doesn't seem to be a problem with FMD itself or with the cf_bypass. It's possible that it was just too many requests for some reason.

I'll still implement the mentioned features for cf_bypass though.

**Comment by SDXC** [comment]
I'll close this ticket. The things I will be implementing are listed in issue #233 
Like we said in previous posts, it wasn't a problem with cf_bypass but too many requests itself that blocked you.
