### ISSUE TITLE
Add support for website [HeavenManga]

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#192]
please add
http://heavenmanga.com/

**Comment by AbidZakaria** [comment]
HeavenManga already exists

**Comment by djgerman10** [comment]
![x](https://user-images.githubusercontent.com/48584512/58226992-70a6e000-7cff-11e9-9467-85df0eb7a8b5.png)

it is not in the list

**Comment by Tmp341** [comment]
We have that in ``HeavenManga.lua`` as ``heavenmanga.vip``, but this request is ``heavenmanga.com``. They look like seperate.

**Comment by SDXC** [comment]
You already requested this in issue #171 
We will track this in the other issue and close this one.
