### ISSUE TITLE
"File not open" error in Favorites tab

### ISSUE THREAD

**Issue by Renvix** [fmd-project-team/FMD#193]
An error occurs when entering a previous version of a favorite file to a new version, or updating a program that has favorite data
![Untitled](https://user-images.githubusercontent.com/29302760/58188562-0c762300-7ce3-11e9-9000-ed686dcc9901.jpg)
here is my favorite tab
![Untitled2](https://user-images.githubusercontent.com/29302760/58188985-cd949d00-7ce3-11e9-92e6-6623e6829ea0.jpg)

**Comment by Tmp341** [comment]
Can you rename your favorites to something else, or move file some place else and try again?

**Comment by Renvix** [comment]
if the favorite file is removed the error does not appear

**Comment by Tmp341** [comment]
Your fmd route is on ``D:\`` drive, so no admin rights needed.

Your Favorites.db might be corrupted. Have you changed it with an app? 

If not, please send it to us, so we can check it.

**Comment by SDXC** [comment]
I'll close this issue as we didn't get any feedback anymore. Probably the problem has been fixed on the users' side.

**Comment by Tmp341** [comment]
Same happened to me today, as i'd changed a manga from active to passive. Then restarted FMD and this time i didn't get that error.
