### ISSUE TITLE
cf_bypass freezes FMD if a HTTPS certificate is obsolete

### ISSUE THREAD

**Issue by typhoe** [fmd-project-team/FMD#195]
Hi,

today I encounter a freeze in FMD while it was checking my manga list.

By looking at the process running (I'm using FMD under Wine/Linux), it looks like the problem is the Cloud Flare protection bypass program.
The Scanlation Group HatigarmScans uses an obsolete Comodo SSL cert for their web site (expiration on 22 mai 2018) and thus, cf_bypass.exe seems to run in an error but doesn't exit correctly, and FMD stays frozen.

`typhoe    7043  0.1  0.2 1790636 40680 tty2    S+   11:23   0:00 Z:\media\typhoe\ebooks\fmd\cf_bypass.exe https://www.hatigarmscans.net` 
(I have 5 process stuck for this website)

Killing all cf_bypass.exe threads (regarding Hatigarmscans) let FMD resume it's checking of my Manga list, and even download te Manga from Hatigarmscans (lot of process killing involved ;-) ).
`killall cf_bypass.exe`

Not sur if it really is a problem with FMD, but the result is a freeze of it.

Regards

**Comment by SDXC** [comment]
The next release should fix that behavior. If it will occur again, you can always re-open this issue or create a new one.

**Comment by typhoe** [comment]
Thank you!
