### ISSUE TITLE
cf_bypass does not work [MangaHasu]

### ISSUE THREAD

**Issue by Thrieze** [fmd-project-team/FMD#199]
I think the issue is that they do not have Cloudflare protection on their main frontpage, only once you pick a manga do you get the normal "Cloudflare Checking" Bypassing using the manual method works fine, so its just an issue of having the bypass script pick a manga first randomly to get the CF info.

**Comment by SDXC** [comment]
This is a problem with the second tier Cloudflare instance, meaning that it's only enabled for the image servers. cf_bypass checks gets the cookie from the webserver instance and doesn't re-check this when trying to download images.

**Comment by SDXC** [comment]
I implemented a workaround for websites that have Cloudflare on their imageservers like MangaHasu and PsychoPlay. In the advanced settings you can set a custom url ("BypassURL"). You can set an url from one of the chapters and FMD will get the cf-cookies from there.

![BypassURL](https://user-images.githubusercontent.com/5290260/59208073-aa556300-8ba8-11e9-98f3-54ccad77d502.png)

**Comment by Thrieze** [comment]
Excellent, Thank you.

**Comment by SDXC** [comment]
FMD 0.9.165.0 has been released.
