### ISSUE TITLE
cf_bypass.exe - Entry point not found

### ISSUE THREAD

**Issue by ErkkiSven** [fmd-project-team/FMD#200]
Running FMD.
Then trying {update mangalist, or update favorite list, or see manga info, or download chapter } see this  

![164](https://user-images.githubusercontent.com/50970936/58293950-57ba2f80-7dd0-11e9-92aa-e8b53fe1de2d.JPG)

Translate text :
cf_bypass.exe - entry point not found.
procedure entry point ucrtbase.abort not found in dll api-ms-win-crt-runtime-l1-1-0.dll 

Fmd - 0.9.164.0 (64bit )/ Windows 7 (64bit)

**Comment by SDXC** [comment]
Please install the Visual C++ package and try again (restart FMD):
https://aka.ms/vs/15/release/vc_redist.x64.exe (this is an official download link from Microsoft)

**Comment by SDXC** [comment]
I'll close this issue. If you still have problems with this error, you can re-open this issue anytime.

**Comment by ErkkiSven** [comment]
Thank you for your reply
No need re-open  / install vc 2012-201x .
Temporary solution - return to 163 .
PS: add information - vc (5-8-10).
