### ISSUE TITLE
cf_bypass does not work [PsychoPlay]

### ISSUE THREAD

**Issue by zing269** [fmd-project-team/FMD#201]
Relevant lines from the log

20:53:34:561 ERROR: Error: TypeError: undefined not callable (property 'italics' of '')
20:53:34:951 ERROR: Error: TypeError: undefined not callable (property 'italics' of '')
20:53:35:295 ERROR: Error: ReferenceError: identifier 'document' undefined
20:53:37:108 WARNING: TTaskThread, checkforfinish failed=1/1 [PsychoPlay]"Minamoto-kun Monogatari" > "/read/Minamoto-kun-Monogatari/279"
W
20:53:37:108 WARNING: TTaskThread, download failed. "Minamoto-kun Monogatari" "Minamoto-kun Monogatari_0034_Chapter 279" "/read/Minamoto-kun-Monogatari/279"
20:53:37:498 ERROR: Error: TypeError: undefined not callable (property 'italics' of '')
20:53:37:873 ERROR: Error: ReferenceError: identifier 'document' undefined
20:53:38:279 ERROR: Error: ReferenceError: identifier 'document' undefined
20:53:40:108 WARNING: TTaskThread, checkforfinish failed=1/1 [PsychoPlay]"Minamoto-kun Monogatari" > "/read/Minamoto-kun-Monogatari/279"
W
20:53:40:108 WARNING: TTaskThread, download failed. "Minamoto-kun Monogatari" "Minamoto-kun Monogatari_0034_Chapter 279" "/read/Minamoto-kun-Monogatari/279"

**Comment by Tmp341** [comment]
It seems cf_bypass cant get cookies for this site too. #191

**Comment by Tmp341** [comment]
So, these sites doesn't work as cf_bypass doesn't get CF cookie infos:
- [ ] FallenAngels
- [ ] PsychoPlay
- [ ] TuMangaOnline

* I've updated PsychoPlay manga list, but haven't tried downloading.
* Both FallenAngels and TuMangaOnline keeps on update list function, never finds anything or fails.

**Comment by SDXC** [comment]
I implemented a workaround for websites that have Cloudflare on their imageservers like MangaHasu and PsychoPlay. In the advanced settings you can set a custom url ("BypassURL"). You can set an url from one of the chapters and FMD will get the cf-cookies from there.

![BypassURL](https://user-images.githubusercontent.com/5290260/59208073-aa556300-8ba8-11e9-98f3-54ccad77d502.png)

**Comment by SDXC** [comment]
FMD 0.9.165.0 has been released.
