### ISSUE TITLE
Show selection count also in Downloads and Favorites tab

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#202]
![image](https://user-images.githubusercontent.com/28888646/58367825-f7310c80-7f0d-11e9-831a-944320e59040.png)
It should be works on Downloads and Favorites tab too.
Maybe also on Options -> Websites -> Websites.
And the text should be disappear when changing to other tab.

**Comment by SDXC** [comment]
Has been implemented.

**Comment by SDXC** [comment]
FMD v0.9.166.0 has been released!
https://github.com/fmd-project-team/FMD/releases/tag/0.9.166.0
