### ISSUE TITLE
Show/Hide entries in Favorites tab

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#203]
So I can see all the disabled items at once.
Like on transfer websites:
![image](https://user-images.githubusercontent.com/28888646/58367969-103abd00-7f10-11e9-8d01-4f3bf242d703.png)
◉All(#) ○Enabled(#) ○Disabled(#)
Maybe put it next to Check for new chapter button.

**Comment by SDXC** [comment]
Implemented. Will come with the next release.

**Comment by SDXC** [comment]
FMD v0.9.166.0 has been released!
https://github.com/fmd-project-team/FMD/releases/tag/0.9.166.0
