### ISSUE TITLE
Website won't retain "Add to favorites" on any manga

### ISSUE THREAD

**Issue by ratbunuts** [fmd-project-team/FMD#205]
Hello the website champion scans can't retain the add to favorites button. Even if I try adding it back all the time it still wont retain it

**Comment by Tmp341** [comment]
I've just tried it and FMD favorited ``No Game No Life`` manga.

**Comment by Tmp341** [comment]
They've removed some mangas from the list (approximately 8 of them). Delete your ``ChampionScans.db`` file from ``Data`` folder, and update the list manually again.

**Comment by SDXC** [comment]
I'll close this issue as it seems to be a problem with the db file which can be easily be rebuild.
