### ISSUE TITLE
Add support for website [Wecomics]

### ISSUE THREAD

**Issue by Von07** [fmd-project-team/FMD#206]
Please support this site, Thank you ^^
m.wecomics.com

**Comment by Von07** [comment]
ohh I see wecomics is only usable through their app ;-;

**Comment by Tmp341** [comment]
No, actually i saw this before [Hakuneko | add wecomics #103](https://github.com/manga-download/hakuneko/issues/103).

**Comment by Von07** [comment]
hmm so it has nothing to do with their app. Just region lock if that's the case we can just change the proxy in connection tab

**Comment by Slasar41** [comment]
I think no need to use VPN/Proxy anymore.
Yesterday I can't access it, but now I can.
![image](https://user-images.githubusercontent.com/28888646/58428095-b0891100-80cb-11e9-865f-3d8032ade7aa.png)

**Comment by Tmp341** [comment]
I have region lock here.

**Comment by AbidZakaria** [comment]
@Tmp341 don't close this issue,
I'm trying to make a lua file for that site
And add label javascript for this issue

**Comment by Tmp341** [comment]
Well, im locked out doesn't mean i should close this issue.

**Comment by AbidZakaria** [comment]
![image](https://user-images.githubusercontent.com/19544118/58529269-66577b00-8204-11e9-8a84-83f68fd5811c.png)

in progress

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
