### ISSUE TITLE
Add websites [OtakuIndo, KomikManga, Komiku], fix [Kiryuu]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#21]
https://otakuindo.net/
https://komikmanga.com/
https://kiryuu.co/
https://komiku.co/

**Comment by AbidZakaria** [comment]
@SDXC i created lua for [OtakuIndo, KomikManga, Komiku] i will upload later

**Comment by AbidZakaria** [comment]
[myReaderMangaCMS.zip](https://github.com/fmd-project-team/FMD/files/3042115/myReaderMangaCMS.zip)
that lua for KomikManga

[MangaShiro.zip](https://github.com/fmd-project-team/FMD/files/3042119/MangaShiro.zip)
that lua for OtakuIndo and Komiku

please @Tmp341 or @SDXC  add it

**Comment by AbidZakaria** [comment]
Wait for lua realease @MIRVOUS ,and test that website in your FMD

**Comment by Tmp341** [comment]
Im going to add a PR in a couple of minutes.

**Comment by AbidZakaria** [comment]
Really, how?
I'm Not familiar
Using git
@Tmp341 can you teach me

**Comment by Tmp341** [comment]
1. Go to the file you want to change, like https://github.com/fmd-project-team/FMD/blob/master/lua/modules/MangaID.lua file,
2.  Then use pen button explained here :https://help.github.com/en/articles/editing-files-in-your-repository, change it.
3. Then follow up with this https://help.github.com/en/articles/creating-a-pull-request

**Comment by Tmp341** [comment]
Okay. Closing this for now. If you have any problem, reopen this issue.

**Comment by SDXC** [comment]
@Tmp341 Don't close the issue yet. I have to update the changelog first, but can't because I'm not home right now.

**Comment by SDXC** [comment]
Changelog updated.
