### ISSUE TITLE
Can't get latest chapter if it's freshly uploaded [MangaRock]

### ISSUE THREAD

**Issue by rndconroy** [fmd-project-team/FMD#211]
If i try to download newly (upload about 5 hours ago)chapter in mangarock, if that manga have 5 uploaded chapters in mangarock but it show 4 chapters in FMD. If i try to download newly (upload about 12 hours ago or more (sometimes 8 hours) )chapter in mangarock it has no problem, so i need to wait about 12 hours (sometimes 8 hours) to download new chapter. if it is upload less than 12 hours (sometimes 8 hours) ago most manga's new chapter not show in FMD. 
Sorry for my bad in english language
![image](https://user-images.githubusercontent.com/51146453/58528509-c34f3300-81fc-11e9-8dc6-803647d74ece.png)
![image](https://user-images.githubusercontent.com/51146453/58528520-cea25e80-81fc-11e9-95fe-3ee18b80dd63.png)

**Comment by SDXC** [comment]
Yeah, that's because the module doesn't handle the blue "new" dot next to the chapter entry, so the module doesn't find it with the current query. Will be fixed soon.

**Comment by rndconroy** [comment]
thanks you, and waiting

**Comment by SDXC** [comment]
Don't close it until we fixed it :)

**Comment by SDXC** [comment]
Thanks to the issue also being reported and already been fixed for HakuNeko, it could be fixed the same way for FMD. So you can indirectly thank ronny1982 for that.

You can expect the release tomorrow or Monday.

**Comment by ronny1982** [comment]
The fix in HakuNeko has been reverted due to country based licensing issues and related API problems...

https://github.com/manga-download/hakuneko/commit/641a7f169853856bf7063d73e16f512f65dcc0a5
https://github.com/manga-download/hakuneko/commit/24352921f4c88c75a2bbcfae457680e07ac60c24

**Comment by SDXC** [comment]
@ronny1982 In case of FMD I already changed it to a user setting. Default is United States but the user can change it to any other country and it will work for the licensed titles. Not sure if it's the best way to do it, but at least we can try our way around it with that :)

**Comment by ronny1982** [comment]
It will not work for titles that are licensed everywhere, those cannot be aquired through the API but for now through the website.

See:
#225
manga-download/hakuneko#184

**Comment by SDXC** [comment]
Thanks for that hint.
Hmm.. I don't really like to make a backstep if an API is available, but well.

**Comment by ronny1982** [comment]
Currently there are only 7 mangas affected...

**Comment by SDXC** [comment]
FMD 0.9.165.0 has been released.

@ronny1982 It seems that licensing locks exist for some countries even on the normal webpages. It looks like it's not the end of it and might be even more restricted in the near future.
