### ISSUE TITLE
FMD creating folders with partial manga titles

### ISSUE THREAD

**Issue by farahnur42** [fmd-project-team/FMD#214]
It shows up in the download list like this, I thought it'd just be because the title is too long to show on the list itself but would be fine in the folder title. It isn't, and I already have a Kaguya-sama full title folder **in** that same directory with the rest of what I've downloaded previously so the total path character limit hasn't been hit yet. ![image](https://user-images.githubusercontent.com/37258115/58662251-8fceee80-834b-11e9-90cc-2c8db656aa04.png)
![image](https://user-images.githubusercontent.com/37258115/58662390-df151f00-834b-11e9-9e8d-cfedbb0305b7.png)

**Comment by SDXC** [comment]
Did you temper with your favorites.db somehow or tried to change some paths in there?

**Comment by farahnur42** [comment]
I copied my favorites.db over from riderkick's FMD, but other than that, no. Could that be the reason why?

**Comment by farahnur42** [comment]
So, uhm, the issue still persists. I don't mean to sound entitled or anything but is this going to get solved anytime soon? An update/solution would be very much appreciated.

**Comment by SDXC** [comment]
Please upload you FMD-Folder so I can check your settings/favorites/etc.

**Comment by NhKPaNdA** [comment]
I have noticed the same thing but I think it's more so related to what website you are downloading from. I specifically noticed this happened when I changed from KissManga to MangaDex. MangaDex tends to cut off long manga names therefore creating a second download folder for the same manga after I transferred my favorites from KissManga to MangaDex.

**Comment by farahnur42** [comment]
@NhKPaNdA Yeah they're all in MangaDex, the mangas that are causing issues. Is a Mega link ok @SDXC ? If so, here 
https://mega.nz/#!4jZhXYJB!VyqF0GcuO_bByCQwT6NExfNUKtvp_LbWkhAqALOoKTc [I am on the latest version, just that I didn't update the folder name]
