### ISSUE TITLE
Can't download almost any manga [KuManga]

### ISSUE THREAD

**Issue by JhonnySetnom** [fmd-project-team/FMD#215]
Hallo. 
I can't download almost anything from KuManga, I could only download 2 of like 30 series from the site.
It stayed like downloading, and create the folders of chapters but doesn't download anything.
![image](https://user-images.githubusercontent.com/46911980/58744388-a8044380-8407-11e9-936f-e7cc55445bdb.png)

Thanks for the keeping the app updated.
Cheers.

**Comment by djgerman10** [comment]
te recomiendo que bajes en (tumangaonline o submanga) nomas, kumanga la pagina tiene errores en cargar y demas

**Comment by djgerman10** [comment]
a y recuerda usar un proxi para tumanga online porque te banea si haces muchas descarga #191.

**Comment by Tmp341** [comment]
Duplicate of #146

**Comment by SDXC** [comment]
I'll close this issue. We will work on that problem in issue #146
