### ISSUE TITLE
fails to load page [LeoManga]

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#216]
### fails to load page [https://leomanga.xyz](url)
![1](https://user-images.githubusercontent.com/48584512/58746673-3b08a200-8437-11e9-9708-32b47d097c90.png)

![2](https://user-images.githubusercontent.com/48584512/58746675-422fb000-8437-11e9-81bc-58ce215a735e.png)

**Comment by SDXC** [comment]
Remove the "/2/1" at the end of the url, then it will work.
