### ISSUE TITLE
Add support for website [RawMangaZuki, MangaTensei]

### ISSUE THREAD

**Issue by sadeghp88** [fmd-project-team/FMD#217]
Please support this site, Thank you
Site; beta.mangazuki.co
beta.mangazuki.co/raws

and btw i know that this site (mangatensei.com) has been requested before but it seems it has been forgotten to be added to the library.
thanks again

~~beta.mangazuki.co/raws -> https://raws.mangazuki.co~~
https://mangatensei.com

**Comment by SDXC** [comment]
We didn't forget any of the issues/requests. It's just that we don't always have enough time to do it right away. Issues are normally higher priority than site requests.

**Comment by AbidZakaria** [comment]
maybe site problem
![image](https://user-images.githubusercontent.com/19544118/59217955-4f902b80-8be9-11e9-8587-d0fb9e1df229.png)

**Comment by AbidZakaria** [comment]
@SDXC can you access that site?

**Comment by SDXC** [comment]
nope, maybe it's not in beta anymore?

**Comment by Tmp341** [comment]
It seems there is another (mangatensei) site request in there.

Also, i can't reach beta site too.

**Comment by AbidZakaria** [comment]
beta.mangazuki.co/raws => https://raws.mangazuki.co
beta site close

**Comment by AbidZakaria** [comment]
for RawMangaZuki we already have it
@Tmp341

**Comment by Tmp341** [comment]
It was probably a testing for the new design.

**Comment by SDXC** [comment]
MangaTensei = Batoto (the fake one).

Batoto has to be ported to lua first, MangaTensei can be added new module afterwards. But really, why not just use Batoto directly?

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
