### ISSUE TITLE
Add support for website [Piccoma] 

### ISSUE THREAD

**Issue by su0su0** [fmd-project-team/FMD#218]
https://piccoma.com/
This is a popular **Japanese webtoon site** by Kakao (a big Korean corporation)
It contains both free & paid contents. There's also a WUF (wait-until-free) system (usually a day), which requires an account.

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
