### ISSUE TITLE
Add support for website [mhKan]

### ISSUE THREAD

**Issue by su0su0** [fmd-project-team/FMD#219]
https://www.mhkan.com/
This website is called ManhuaKan (漫画看), which contains **manga & webtoons in Chinese**. I hope you'll consider it 🙏 Thank you for making FMD <3

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
