### ISSUE TITLE
Can't access sqlite database file

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#22]
![fmd1](https://user-images.githubusercontent.com/45929526/55467563-c4fce000-562b-11e9-93ff-879ac86f8465.PNG)
![fmd3](https://user-images.githubusercontent.com/45929526/55467564-c4fce000-562b-11e9-8d8c-fbd7ac2e9b18.PNG)

**Comment by Tmp341** [comment]
Seems like you're running fmd from ``C:\`` drive. Try again with right click and ``Run as admin`` option.

**Comment by Tmp341** [comment]
If my statement won't fix it, send us your database file.

**Comment by MIRVOUS** [comment]
okay its work
thanks

**Comment by SDXC** [comment]
Thanks for the feedback.
