### ISSUE TITLE
Can't get latest chapters [TonariNoYoungJump]

### ISSUE THREAD

**Issue by Ever4engel** [fmd-project-team/FMD#221]
![Sans titre](https://user-images.githubusercontent.com/47645041/58815584-29d2b780-8628-11e9-9739-4bf32d4216ea.jpg)

**Comment by Tmp341** [comment]
Please don't use special characters in folder names.

``é `` in ``Logéciels`` is probably making this. Fmd isn't working with those letters.

**Comment by Ever4engel** [comment]
Yes it fixed my bug, but at the same time it don't show all chapters specialy the 3 last.
for exmple [
![image](https://user-images.githubusercontent.com/47645041/58837870-1d1c8680-865d-11e9-921a-c456f8e64784.png)
One punch man don"t apear in the list below

**Comment by SDXC** [comment]
FMD 0.9.165.0 has been released.
