### ISSUE TITLE
Can't get manga info [ReadComicOnline]

### ISSUE THREAD

**Issue by angelo93** [fmd-project-team/FMD#224]
Hi, I just recently found out that ReadComicsOnline is on the list of websites supported, but when I click on any of the comics the manga info page is empty. I tried the older cloudfare cookie and user-agent workaround, but haven't had any luck and I'm not sure what to do at this point. Any help would be appreciated, thank you!

**Comment by SDXC** [comment]
I just tested some titles and all of them worked perfectly fine.
Do you have some examples that didn't work?
Or upload your FMD install folder (as zip) so we can test with your configuration.

**Comment by angelo93** [comment]
None of the titles are loading on my laptop or desktop. I'll try and upload my installation as soon as possible. Di you do the cloudfare workaround? or did it work for you out of the box?

**Comment by SDXC** [comment]
I didn't have to do the manual workaround, cf_bypass worked perfectly fine.

**Comment by angelo93** [comment]
Apparently the zip is too big to upload directly, here's is a google link of it on my drive. 
https://drive.google.com/file/d/17mOKCl5MqPssCoot1oiurWKuWRKrdQ5s/view?usp=sharing

**Comment by SDXC** [comment]
@angelo93 Remove the cookies and the user agent in the advanced website settings.
It worked for me with your FMD installation after I removed them.

**Comment by angelo93** [comment]
Still doesn't work on my end, might be my ISP or something. That's very unfortunate :(
Thanks for taking the time to help though!

**Comment by angelo93** [comment]
Here's something interesting that may or may not help, but the list of titles for the website doesn't renew either. It works fine on the browser, but something is happening on my end with FMD so that it doesn't even make a connection to the website. I found another issue post with a user experiencing similar problems, the last comment on that post is dated the 24th of April.

**Comment by Tmp341** [comment]
Try adding proxy on FMD.

**Comment by angelo93** [comment]
Just went through like 7 proxies and none of them did anything. One took forever and got my hopes up, but struck out on that one too :/

**Comment by Tmp341** [comment]
I'm updating manga database now, it seems working on my end. When it is finished, i will check a manga too.

**Comment by angelo93** [comment]
Tried it again this morning, still no luck. ComicExtra is working though so I'll just use that. I did some more digging and it seems like CF is banning me with a script detector of sorts perhaps. I feel bad for taking up so much of ya'lls time already so you can go ahead and close this since it seems to be an error on my end not easily remedied. Thanks again for trying though, greatly appreciate it!

**Comment by Tmp341** [comment]
> 
> 
> Tried it again this morning, still no luck. ComicExtra is working though so I'll just use that. I did some more digging and it seems like CF is banning me with a script detector of sorts perhaps. I feel bad for taking up so much of ya'lls time already so you can go ahead and close this since it seems to be an error on my end not easily remedied. Thanks again for trying though, greatly appreciate it!

Download this file and check again [FMD-Unofficial-Data/ReadComicOnline.db](https://github.com/Tmp341/FMD-Unofficial-Data/blob/master/Data/ReadComicOnline.db)

**Comment by angelo93** [comment]
Sorry for the late reply, freak weather knocked out power in my area for most of yesterday. Just downloaded and checked and unfortunately it's still not working. I checked it on both my PC and laptop and no luck :(

**Comment by Tmp341** [comment]
Restart your router (keep it closed for around 10 seconds) and clear your cookies. 

Try with and without a VPN.

**Comment by angelo93** [comment]
Good news! I got it to work with hotspot shield, other vpns or proxies didn't work. Guess I'll have to subscribe to hotspot for the foreseeable future haha. Thanks so much for sticking with me for the long haul!

**Comment by SDXC** [comment]
Thanks for the feedback. Glad it works somehow for you now.
