### ISSUE TITLE
Can't download some Manhwa [MangaRock]

### ISSUE THREAD

**Issue by sadeghp88** [fmd-project-team/FMD#225]
hello
would you please explain why i can't download this manhwa from mangarock
https://mangarock.com/manga/mrs-serie-264761
when i paste it to there is no download link

thanks in advance

**Comment by SDXC** [comment]
Thanks to ronny1982 we now know, that the API from MangaRock has a slight region lock (regarding some licensing message) which blocks some of the titles. Funny thing is, that these titles are available on the page itself.

We have to rewrite some parts of the code to change from the API to the classic DOM which is a backstep.... I'll let you know as soon as we "fixed" it.

**Comment by SDXC** [comment]
@sadeghp88 Some titles (around 7) aren't available through MangaRocks API but can still be viewed and downloaded through their website.

Unless many more titles become unavailable through the API, we won't change our script. Sorry, but at the moment it's too much work if it's just for so less affected titles.
