### ISSUE TITLE
Add support for website [ReadComicsOnlineRU]

### ISSUE THREAD

**Issue by angelo93** [fmd-project-team/FMD#226]
Don't mean to spam the issues board, but if possible could y'all add support to this site as well? There's a similarly named site already added that ends in ".to" this is a different site to that... not very original names lol. Please and thank you!

https://readcomicsonline.ru/

**Comment by AbidZakaria** [comment]
@SDXC not close?

**Comment by SDXC** [comment]
@AbidZakaria I just forgot^^
