### ISSUE TITLE
New url [MangaChanRU, HentaiChanRU, YaoiChanRU]

### ISSUE THREAD

**Issue by Tosterr1** [fmd-project-team/FMD#228]
All of this site were shut down today at 2 PM. and reopen on new address. Fix problem when all of this site been fully recover.

Text on picture:
Urgently !!! This is a new site address.
manga-chan.me
Redirect will soon stop working, manage to save a new address and tell everyone !!!
http://manga-chan.me/catalog
http://anime-chan.me/
http://yaoi-chan.me/
http://h-chan.me/

![image](https://user-images.githubusercontent.com/42684479/59150177-f9c05580-8a27-11e9-8f6f-45f7094cb809.png)

**Comment by SDXC** [comment]
URLs have been changed. Currently most of the images aren't available on their new websites.
