### ISSUE TITLE
Add support for website [DoujinDesu, DoujinYosh, MangaCeng]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#230]
In this list no VPN or proxy is needed

doujindesu.biz
- [x] https://mangaceng.com/
- [x] https://doujinyosh.com/

**Comment by AbidZakaria** [comment]
https://www.doujindesu.biz/ 
Not reading manga
@SDXC

**Comment by SDXC** [comment]
I can't access it.

**Comment by AbidZakaria** [comment]
if you are blocked by blogger, click yes

**Comment by SDXC** [comment]
my ISP says it's a malicious site, so I'd say we won't add that

**Comment by SDXC** [comment]
doujindesu.biz will not be added. the rest is available. Issue will be closed.

**Comment by Tmp341** [comment]
I can access the site. But, got ``Please remove your adblocker`` error. 😅

**Comment by MIRVOUS** [comment]
I am sorry  for not participating in this issue.
FOR Doujindesu.biz
. @AbidZakaria "this is a reading site manga"
check this
![Capture2](https://user-images.githubusercontent.com/45929526/59411471-8468d200-8de5-11e9-960a-cc307a173356.PNG)
![Capture3](https://user-images.githubusercontent.com/45929526/59411472-85016880-8de5-11e9-8753-48042e68c9fe.PNG)
. @SDXC  "Have you checked the site with this url"
https://www.doujindesu.biz/?zx=d001a6e218942a0d
and like abidzakaria say if you are blocked by blogger, click yes.
. @Tmp341 "if you want so that there is no error. like Please remove your adblocker"
please use tampermonkey extension and use this script (I just wrote the name) :
- Anti-Adblock Killer | Reek

**Comment by SDXC** [comment]
So is it correct, that DoujinDesu only links to other reading websites?

**Comment by MIRVOUS** [comment]
yes, but the site reading it is the same.
please check the two images above
in the url link all images

**Comment by Tmp341** [comment]
@MIRVOUS I won't use that site, so that script is not necessary for me.

**Comment by MIRVOUS** [comment]
OK. if the website has a virus. I think it's better not to enter
