### ISSUE TITLE
Misleading "PDF compression level"?

### ISSUE THREAD

**Issue by Alwaysin** [fmd-project-team/FMD#231]
[I've just discovered the fork, thanks for taking care of this!]

This option is a bit misleading, isn't it? Because 100 "comrpession level" means it  won't be compressed, and 0 means it will have the most compression level. Instinctively, I'd have thought the contrary.
Furthermore, the [?] is not working, at least in my computer. Maybe fixing this should be enough to correct the issue.
EDIT: yes it is working... I was clicking whereas you just have to hover over the sign.

**Comment by Tmp341** [comment]
It states that 100% quality, lossless file. I know it can be the other way around.

**Comment by SDXC** [comment]
I'll rename that to "PDF Quality Level". That should make it clearer.

**Comment by SDXC** [comment]
FMD 0.9.165.0 has been released.
