### ISSUE TITLE
How to merge databases?

### ISSUE THREAD

**Issue by shimizurei** [fmd-project-team/FMD#232]
My other computer bit the dust and I thought I lost all my data for fmd, so I bought a new comp and started from scratch. Then I was able to recover the data from the dead computer, but now I have 2 different databases of info. How do I merge them? Trying to import my list results in nothing happening (same as in #114). I read this issue #3, but it doesn't apply to my case.

**Comment by Tmp341** [comment]
You have to merge them manually with apps like SQLite Database Browser.

**Comment by shimizurei** [comment]
The rows wouldn't save for me, so I just did it in the program one-by-one, unfortunately.

**Comment by Tmp341** [comment]
Select all, then paste or select and paste eache column.
