### ISSUE TITLE
[cf_bypass] Optimizations

### ISSUE THREAD

**Issue by SDXC** [fmd-project-team/FMD#233]
This issue exists to track planned optimizations for the cf_bypass. It's only meant for me to write in it.

**Planned Optimizations (short term):**
- [x] Disable cf_bypass globally.
- [x] Disable cf_bypass per website in advanced settings.
- [x] Handle cf_bypass calls if more than 1 task is running.
- [x] Handle 2nd-tier Cloudflare pages (for example MangaHasu).
- [ ] Renew cf_clearance cookie without needing to restart FMD.
- [x] If cf_bypass fails disable it in the advanced settings.
- [ ] Support Proxy settings.

**Planned Optimizations (long term):**
- [ ] Use either a cf_scrape script for Node.JS or handle Cloudflare directly.
- [ ] Handle 2nd-tier Cloudflare pages without workaround.

**Comment by SDXC** [comment]
Temporary Beta with cf_bypass optimizations:

[FMD_cf_optimization.zip](https://github.com/fmd-project-team/FMD/files/3272289/FMD_cf_optimization.zip)

**Comment by SDXC** [comment]
New test build for CF optimizations:
[FMD_cf_optimization2.zip](https://github.com/fmd-project-team/FMD/files/3272896/FMD_cf_optimization2.zip)

**Comment by dazedcat19** [comment]
This can be closed

**Comment by SDXC** [comment]
cf_bypass has been removed with version 0.9.168.0, issue is obsolete.
