### ISSUE TITLE
Can't update manga list [MangaKakalot, MangaNelo]

### ISSUE THREAD

**Issue by molitar** [fmd-project-team/FMD#235]
MangaNelo is working for other manga chapters just fine but this one manga I have in favorites shows 0 chapters but able to read chapters online just fine.
 
Manga:  Sekkaku Cheat wo Moratte Isekai ni Teni shita n dakara, Suki na you ni Ikitemitai
Found at https://manganelo.com/manga/jwsi274001559874061
 
```Title:
N/A

Author(s):
Munmun, Butcha U

Genre(s):
Ecchi, Fantasy, Harem

Status:
Ongoing

Summary:
An official manga adaption by Butcha-U of a Light Novel by Munmun with Character Designs by Mizuryu Kei.The 30-year-old office worker Satou Tarou accidentally dies and gets transferred into another world by god. After receiving a curing cheat ability, Satou Taro changes his name into Tauro and begins a fresh life
```

**Comment by Slasar41** [comment]
I can download it just fine
![image](https://user-images.githubusercontent.com/28888646/59210364-a3921480-8bd7-11e9-8be5-038ceb61bbf6.png)
![image](https://user-images.githubusercontent.com/28888646/59210368-a7be3200-8bd7-11e9-924c-94b6837f2ace.png)
Version: 0.9.164.0

**Comment by SDXC** [comment]
The problem is that FMD can't update the website database correctly, so the correct/new urls can't be fetched. Will be fixed.

**Comment by SDXC** [comment]
You can now update the list once again. It probably would be a good idea to make a new db file.
