### ISSUE TITLE
Can't download 7 specific titles [MangaRock]

### ISSUE THREAD

**Issue by sadeghp88** [fmd-project-team/FMD#249]
hello
it still doesn't work
https://mangarock.com/manga/mrs-serie-264761

btw by typing another country name that's gonna work?

**Comment by Tmp341** [comment]
According to @SDXC, you should type a country name other than USA.

**Comment by Tmp341** [comment]
4 days passed, no reply yet.

**Comment by SDXC** [comment]
For now it's only these specific titles. If the API from MangaRock will block more of them, we will consider changing back to the DOM.
