### ISSUE TITLE
Can we have "Change 'saveto'" apply to multiple rows in the faves list?

### ISSUE THREAD

**Issue by shimizurei** [fmd-project-team/FMD#250]
The context menu option "change saveto" can only be used line-by-line. It's very tedious. Since changing the saveto location in the settings doesn't apply to the favorites list, you have to use the right-click menu. It's kind of annoying. Would you please consider fixing this?

**Comment by Slasar41** [comment]
Duplicate of https://github.com/fmd-project-team/FMD/issues/10

**Comment by Tmp341** [comment]
Duplicate of #10 like @Slasar41 said.
