### ISSUE TITLE
Chapter list missing all [Kyuroku]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#252]
please fix that
![Capture4](https://user-images.githubusercontent.com/45929526/59415622-078e2600-8dee-11e9-8ed0-2682c27d0643.PNG)
![Capture5](https://user-images.githubusercontent.com/45929526/59415632-0bba4380-8dee-11e9-96d3-2ab928335978.PNG)

**Comment by MIRVOUS** [comment]
I tried other manga but the results were the same

**Comment by AbidZakaria** [comment]
wait pull by @SDXC

**Comment by AbidZakaria** [comment]
@MIRVOUS cari link doujin indo yang lain aja bukan doujindesu 
soalnya doujindesu sistemnya sedikit ada malware di situsnya :V

**Comment by MIRVOUS** [comment]
@AbidZakaria oke nanti saya cari kalau senggan. soalnya ini juga sembari ngewifi

**Comment by MIRVOUS** [comment]
senggang

**Comment by SDXC** [comment]
Has been fixed thanks to AbidZakaria.
