### ISSUE TITLE
Downloading chapters doesn't work [NinjaScans]

### ISSUE THREAD

**Issue by jokosablenk** [fmd-project-team/FMD#255]
I tried to download one of the chapter of martial peak from ninjascans but failed.

https://ibb.co/R02CqTx

**Comment by AbidZakaria** [comment]
can you give me a problematic manga link

**Comment by jokosablenk** [comment]
Thank you for fast response. i tried to download chapter 78 of martial peak, but failed

https://ninjascans.com/manhua/martial-peak/chapter-78/

terima kasih

**Comment by AbidZakaria** [comment]
wait pull by @SDXC

**Comment by SDXC** [comment]
Merged.
