### ISSUE TITLE
Download doesn't work [MerakiScans]

### ISSUE THREAD

**Issue by jokosablenk** [fmd-project-team/FMD#265]
Tried to download new chapter but failed.

![failed](https://i.imgur.com/aF4u1Px.jpg)

**Comment by Tmp341** [comment]
Just disable ``TCloudflareBypass`` under ``Advanced -> Meraki Scans``

**Comment by AbidZakaria** [comment]
@jokosablenk wait pull by @SDXC

**Comment by SDXC** [comment]
Fixed thanks to AbidZakaria.
