### ISSUE TITLE
Can't get info [Mangadex]

### ISSUE THREAD

**Issue by Sakurahime08** [fmd-project-team/FMD#267]
Hi, N/A is shown when viewing manga with cloudflare bypass enabled. I still do the manual pasting of cookies. What should be the normal settings for this? Thank you!

**Comment by WildCrow** [comment]
Someone is bot spamming the Mangadex forums, not sure if it's related.

**Comment by bryamamigo** [comment]
I had the same problem, I could not even download anything from Mangadex. 
Go to Options -> Websites -> Advanced search for Mangadex ->  DisableCloudflareBypass 
Set it like this 
![image](https://user-images.githubusercontent.com/37577648/59558819-1da40e00-8fc9-11e9-9074-a5fe8e3505da.png)
That Solved my problem.

**Comment by Tmp341** [comment]
I've disabled all, it started working after that.

**Comment by SDXC** [comment]
That was a special case and MD is back to normal. I'll close this issue.
