### ISSUE TITLE
Summary is missing in manga info tab [WestManga]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#268]
can you make Westmanga full info like other
so in the software is nothing synopsis info but in the Website is there

![Capture6](https://user-images.githubusercontent.com/45929526/59560770-54b60600-9041-11e9-8d28-7262cbd13aee.PNG)
![Capture7](https://user-images.githubusercontent.com/45929526/59560771-554e9c80-9041-11e9-9995-2e77ce614234.PNG)

**Comment by SDXC** [comment]
@AbidZakaria Can you fix this? I have region lock and can't access the website. Should be a simple fix.

**Comment by AbidZakaria** [comment]
Ok, I'll fix it

**Comment by AbidZakaria** [comment]
@MIRVOUS wait pull by @SDXC

**Comment by SDXC** [comment]
@MIRVOUS Does it work now with the fix from AbidZakaria?

**Comment by MIRVOUS** [comment]
wait I just got online.
and I don't know why but my fmd settings are gone.
like just downloaded .

**Comment by MIRVOUS** [comment]
now is fix thanks
![Capture8](https://user-images.githubusercontent.com/45929526/59579875-272c9380-90f9-11e9-8167-e6d2f22be6d2.PNG)
i will close the issue
