### ISSUE TITLE
Add support for website [KakaoPage]

### ISSUE THREAD

**Issue by gfhghfghfh** [fmd-project-team/FMD#274]
https://page.kakao.com/

**Comment by AbidZakaria** [comment]
is this free or paid manga
I can't read Korean on the site

**Comment by gfhghfghfh** [comment]
Paid

**Comment by gfhghfghfh** [comment]
but we can wait ,and get chapter for free

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
