### ISSUE TITLE
FMD creates Folders which are too long for windows to copy

### ISSUE THREAD

**Issue by Aaron2550** [fmd-project-team/FMD#278]
[I think the titles says it all, maybe add a popup that warns the user when a title is too long](https://files.catbox.moe/57tnml.jpg)

**Comment by SDXC** [comment]
This has been reported including a feature request on how to handle that:
https://github.com/fmd-project-team/FMD/issues/155

I'll close this issue. You can subscribe to the other issue if you want to be reminded if something is going on regarding this issue.
