### ISSUE TITLE
Check all checkboxes at once

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#28]
![fmd4](https://user-images.githubusercontent.com/45929526/55611653-51381000-57b0-11e9-977a-a601a538a87e.PNG)

**Comment by SDXC** [comment]
Implemented. It also takes your current filter into consideration. See gif to check how it works:

![(Un)SelectAll-Feature](https://user-images.githubusercontent.com/5290260/55684136-41ebca80-5948-11e9-8583-a0c07a8392bb.gif)

**Comment by Tmp341** [comment]
Is it possible to only check under 1 title? For example, we chose ``English``, will it only check English sites?

**Comment by SDXC** [comment]
@Tmp341 now it does ;)

![(Un)SelectAll-Feature-2](https://user-images.githubusercontent.com/5290260/55684608-2d5e0100-594d-11e9-9850-7fd13d4e8322.gif)

**Comment by SDXC** [comment]
Free Manga Downloader 0.9.162.0 has been released:
https://github.com/fmd-project-team/FMD/releases/tag/0.9.162.0

Issue will be closed.
