### ISSUE TITLE
How to access manga websites blocked by ISP?

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#282]
Many manga site with some H or borderline H is blocked in my country and most Hentai site is blocked too.
Is there any way to bypass that without using any software like VPN?

**Comment by Slasar41** [comment]
Use [Simple DNSCrypt](https://simplednscrypt.org) instead.

**Comment by knight109** [comment]
im gonna honest with you chief, i dont know how to use it.

**Comment by Slasar41** [comment]
Like the name of the program, it's simple.
Just install it, open it, in Main Menu tab there's `DNSCrypt Service` change it to enable, then on `Network Cards` select your network adapter.

**Comment by knight109** [comment]
Okay thanks.

And do you have recommendation on good H site ?

**Comment by Slasar41** [comment]
I only visit nHentai

**Comment by Tmp341** [comment]
- You can use proxy servers on FMD.
- You can use special softwares like Ultrasurf.
- You can use VPN softwares.

Other than these, you can change your dns settings. But nowadays, you can't bypass isp blocks with changing dns.

**Comment by knight109** [comment]
i already use DNSCrypt Service, it work fine now.

another question i have is that, when i updating H site, it takes way too long to completed, since well, the list is far to long if compare to manga site. does this problem already fixed?

**Comment by knight109** [comment]
![image](https://user-images.githubusercontent.com/30251842/59766555-0ddf3f00-92d3-11e9-90c1-46b7728a46cb.png)
Why i cant get any new updates or open any of them?
I also cant download.

I still use DNSCrypt Service and can open most blocked website.

**Comment by Slasar41** [comment]
I can access your link just fine.
![image](https://user-images.githubusercontent.com/28888646/59768687-ff8f2400-92ce-11e9-9e3e-677a5c417359.png)
Can you access that link from your browser?

**Comment by knight109** [comment]
![image](https://user-images.githubusercontent.com/30251842/59770389-88f82380-92da-11e9-8587-dc00acf66f67.png)

Wierd, i can access any other blocked website, only nhentai that i currently know that cant be accessed

**Comment by Slasar41** [comment]
Maybe NHentai already blocked by your ISP on IP address level.
So the other solutions is use proxy servers on FMD or use VPN.

**Comment by Slasar41** [comment]
Put it here if you want to use proxy servers for NHentai only.
![image](https://user-images.githubusercontent.com/28888646/59771220-7fb78880-92d3-11e9-980c-53f297983007.png)

**Comment by Tmp341** [comment]
Nhentai might be blocking that servers maybe.

**Comment by Slasar41** [comment]
@Tmp341 Maybe.
@knight109 If you want, try disabling `Automatic Mode` then just choose `cloudflare (DoH)` then click `apply settings`
![image](https://user-images.githubusercontent.com/28888646/59773220-76c8b600-92d7-11e9-8c07-efc7205a3c72.png)

**Comment by knight109** [comment]
![image](https://user-images.githubusercontent.com/30251842/59777589-8a7c1880-92e7-11e9-846a-bc026269b385.png)

Done it. Still no luck.
I dont know what to put on proxy settings.

**Comment by Slasar41** [comment]
Then it's really blocked on IP Address level.
Google `free proxy list`

**Comment by knight109** [comment]
Does this correct?
![image](https://user-images.githubusercontent.com/30251842/59785235-e39f7880-92f6-11e9-96e0-681924b66ccf.png)

Every link i click become
![image](https://user-images.githubusercontent.com/30251842/59785286-fe71ed00-92f6-11e9-98cd-de9438c84f1a.png)

i use the proxy on mozzila
![image](https://user-images.githubusercontent.com/30251842/59785332-16497100-92f7-11e9-8c9f-e7efb9951392.png)

but nothing
![image](https://user-images.githubusercontent.com/30251842/59785356-26615080-92f7-11e9-8b79-048318dc9e9c.png)
i got pass the captcha but all i got is that

**Comment by Slasar41** [comment]
Try selecting `Use this proxy server for all protocols` on Firefox

**Comment by knight109** [comment]
Still cant download it. Every link i open still become One more time, another IP address make the link become another words, dont really remember it.

Already selecting Use this proxy server for all protocols but still got "File not found"

**Comment by Josexv1** [comment]
There can be a few misconceptions here.

You need to select the correct SOCKS type for the Proxy. In FMD you selected HTTP and in Firefox SOCKS5. Check.

While browsing Proxies look what type is and [test them](https://checkerproxy.net/) first, because not all of them are alive, Free proxies are short lived since they're used to promote premium services.

The easiest way to solve this problem is to use a VPN, Free or Paid.

**Comment by Slasar41** [comment]
@knight109 Already uncheck `DisableCloudflareBypass` on FMD?
Try another proxy servers.
I think it's best to use VPN when accessing NH for you.

**Comment by knight109** [comment]
Yeah, i probably gonna try something for a moment and then if i still cant access it, either gonna use VPN or change to the other site.
Thanks guys

**Comment by knight109** [comment]
Also can i ask what good free VPN or what and where i can find cracked VPN app?
All i can find either free trial or weird site that doesnt have real download button.

**Comment by Slasar41** [comment]
I'm using [SoftEther VPN Client + VPN Gate Client Plugin](https://www.vpngate.net/en/download.aspx)

**Comment by knight109** [comment]
Well i can open NHentai now, but i kinda like using DNSCrypt Service, so i probably use other site even though they doesnt have as much as NHentai offered.

**Comment by SDXC** [comment]
Looks like this has been answered then.
Thanks @Slasar41 for helping.
