### ISSUE TITLE
Chapter download doesn't work [HitomiLa]

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#287]
I can open hitomi.la and read directly from there. 

And as you can see, it fine in here
![image](https://user-images.githubusercontent.com/30251842/59816855-42451080-9350-11e9-968e-666d43a58cb5.png)
But all my download stayed like this
![image](https://user-images.githubusercontent.com/30251842/59816893-5db01b80-9350-11e9-99f6-c790b8ef5f98.png)
And then failed

I copied the link from that one then open it from my browser and yes, working fine for me.

**Comment by Josexv1** [comment]
Did you check if the folder is created and if FMD has the correct permissions to create files in that directory? That's the issue in most cases.

**Comment by knight109** [comment]
Yes, all manga i download from there already make folder in that directory, just nothing in there. Its a hidden folder but still, when i make it normal, i still cant download.

**Comment by Josexv1** [comment]
I checked in my project, and indeed it's broken.

**Comment by knight109** [comment]
So it indeed broken right?
Welp all to do now is waiting then.

Thanks guys

**Comment by AbidZakaria** [comment]
@Tmp341 lua problem or site problem?

**Comment by Slasar41** [comment]
@knight109 Is the image load just fine on your browser that you want to download?
See https://github.com/fmd-project-team/FMD/issues/13

**Comment by knight109** [comment]
yeah, just like i said.
work fine on browser and i can preview the manga on FMD i just can download it.

**Comment by Tmp341** [comment]
I think site code changed somewhere @AbidZakaria

**Comment by knight109** [comment]
I got same problem with Tsumino. Almost exactly the same, but i was just fine when downloading it and then all of a sudden i cant download it anymore.

Also i cant see how many file i need to download unlike the problem i got on Hitomi.la
![image](https://user-images.githubusercontent.com/30251842/59844495-9de1bf00-938d-11e9-8ba0-1f9307818bbf.png)

**Comment by SDXC** [comment]
Has been fixed. If there still are some titles that can't be downloaded, please provide a link.

**Comment by knight109** [comment]
I dont know why, but i cant get the new lua even though i update the modules a few times.
Well, i just download 2 file that changed from that link above and it worked.

**Comment by SDXC** [comment]
Do you even use our forked version or are you sill on riderkicks FMD 0.9.158.0?

**Comment by knight109** [comment]
i the the forked version, but since i move from FMD 0.9.158.0 i copied some file from there.
Probably this affect it.

**Comment by Tmp341** [comment]
@knight109 Use this method to backup your existing files and do fresh install:

https://github.com/fmd-project-team/FMD/wiki#fresh-install

**Comment by SDXC** [comment]
When migrating to our fork I think it's best not to copy the module.json because of the old module links in there. Let FMD create a new one.

**Comment by knight109** [comment]
ok thanks guys
