### ISSUE TITLE
Chapter download doesn't work [MangaDoom]

### ISSUE THREAD

**Issue by spamtaztik** [fmd-project-team/FMD#288]
Favorite checks are fine, new chapters are queued, the running task shows the number of pages (0/28 or whatever), but all tasks from MangaDoom always fails and no pages are downloaded. The tasks from MangaDoom SEEM like they're working properly (there are traffic and all), but the traffic is very small, less than 10Kbps. After a while they just failed. 

I tried entering cookies and user agent (like the workaround for MangaDex and Kissmanga) but it doesn't solve the problem. Any idea why?

By the way, similar issue with ReadMangaToday (favorite checks are fine, new chapters queued, but running tasks show 0/1 then fails).

**Comment by Tmp341** [comment]
ReadMangaToday is already reported.

**Comment by SDXC** [comment]
See here how you can bring ReadMangaToday to download:
https://github.com/fmd-project-team/FMD/issues/286#issuecomment-504018220

**Comment by spamtaztik** [comment]
Huh. It worked. Awesome! So mangadoom and readmangatoday are part of funmanga, eh? Okey dokey.

Thanks much @SDXC! 

CLOSED
