### ISSUE TITLE
"Download all lists from server at once" can't find all lists (404 not found)

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#29]
![fmd5](https://user-images.githubusercontent.com/45929526/55613899-fa353980-57b5-11e9-8c75-8f355490f3ae.PNG)

**Comment by MIRVOUS** [comment]
i'm trying to "download all lists from server at once"

**Comment by AbidZakaria** [comment]
Your FMD program not update or base.ini not Linked to fmd-project-team link

**Comment by SDXC** [comment]
The problem is, that the manga list files are hosted in a sourceforge repo that isn't maintained by us.
All these sites that are listed in the error message don't exist in that repo:
https://sourceforge.net/projects/newfmd/files/data/

We will probably create our own repo for that, but that will come later.

**Comment by MIRVOUS** [comment]
OK. I checked the link

**Comment by MIRVOUS** [comment]
and there is no same link in my photo

**Comment by MIRVOUS** [comment]
can you tell me how to add the manga list in a sourceforge repo?

**Comment by SDXC** [comment]
As far as I know, you (and me neither) can't add new files to that repository. That's one reason why we will create our own (github) repository, but we need a bit of time to plan this, as we want to let more users to contribute somehow.

**Comment by MIRVOUS** [comment]
ok thanks for information and Good luck

**Comment by Tmp341** [comment]
> 
> 
> can you tell me how to add the manga list in a sourceforge repo?

You had to be in the previous FMD team (riderkick's). Since you're not, that repository in SF is not up to date.

**Comment by MIRVOUS** [comment]
ok. i see
