### ISSUE TITLE
Readmanga still not downloading after the work around

### ISSUE THREAD

**Issue by ratbunuts** [fmd-project-team/FMD#291]
Sorry about this but I did follow your work around of the issue. My main problem is the useragent always comes back whenever I deleted/clear it and then apply. So its still not downloading for me.

**Comment by Tmp341** [comment]
Your useragent should be gotten by cf_bypass.

**Comment by ratbunuts** [comment]
Sorry about that. Although I already followed what you did but it still not downloading for me.
