### ISSUE TITLE
Chapter download doesn't work [MangaLib]

### ISSUE THREAD

**Issue by Tosterr1** [fmd-project-team/FMD#292]
Doesn't work download from MangaLib, FMD download only empty folder.
![image](https://user-images.githubusercontent.com/42684479/59962763-40b34e00-94f2-11e9-9722-719fae49de3b.png)
![image](https://user-images.githubusercontent.com/42684479/59962766-490b8900-94f2-11e9-8927-d47d59c8a2a5.png)
![image](https://user-images.githubusercontent.com/42684479/59962772-50cb2d80-94f2-11e9-8576-6afbfa3a5007.png)

**Comment by SDXC** [comment]
The chapter download part should be fixed now.

The manga list update part still has to be done.
