### ISSUE TITLE
Website not working [MangaArab]

### ISSUE THREAD

**Issue by ChocolateOtaku** [fmd-project-team/FMD#293]
Cannot get/update manga list
Favorites also not working anymore

**Comment by SDXC** [comment]
It looks the website is offline to me.
Can anybody confirm that?

**Comment by Tmp341** [comment]
> 185.141.63.104
Pinging 185.141.63.104 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.

Ip adress gives error, host seems offline. It is a 90 days website anyway 👍 
> Creation Date: 2019-03-25T15:31:07.00Z

**Comment by SDXC** [comment]
I will wait until the weekend. If the website is still not reachable until then, it will be removed from FMD.

**Comment by SDXC** [comment]
Well, didn't want to wait that long. Website removed.
