### ISSUE TITLE
Is there anyone that still needs to update their Kissmanga cookies?

### ISSUE THREAD

**Issue by spamtaztik** [fmd-project-team/FMD#294]
Just a quick question like in the title. I know cf_bypass has done wonders, especially with MangaDex's cf protection (thank you Devs!), but for some reason I still have to update my Kissmanga cookie once a day or two. Is it just me, or is there anyone else that faces the same problem here?

The only adv settings I changed are the cookie and useragent. The DisableCloudflareBypass checkbox is off.

**Comment by Josexv1** [comment]
cf_bypass should automatically bypass cloudflare each time the software is open, check if it's active in the Kissmanga's config.

_Btw, i know this isn't a correct answer but just move your manga library from them, there are other aggregators without cf that have pretty much the same library and even more._

**Comment by SDXC** [comment]
KissManga resets the cf cookies in short timespans.
cf_bypass still has some issues on detecting when to renew the cookies.
I hopefully will be able to fix this soon.

The easiest way right now to make sure you don't have to manually update the cookies is to just restart FMD before calling KissManga links again.

**Comment by spamtaztik** [comment]
So it's still a no go eh? <sigh> Alrighty, thanks @SDXC .

@Josexv1 Yeah I've been thinking of moving my mangas to another site. They're mostly old mangas so maybe that's why I never really got around to doing it (or maybe I'm just lazy). I guess it's time to do it.
