### ISSUE TITLE
How to move from FMD 32bit (Riderkick version) to 64bit (SDXC version)?

### ISSUE THREAD

**Issue by devprojectid** [fmd-project-team/FMD#3]
i want to move all downloaded manga, config, etc from my old FMD to this version, how to do it ?

**Comment by SDXC** [comment]
Hi @devprojectid 

First, make a backup of the complete installation folder of your old FMD (zip it and move the zip to a safe location)

For migrating to the new FMD and also to x64 you have to do the following steps:

* Delete the files in the base folder (from 7za.exe to updater.exe, but **don't** delete the subfolders)
* Open the new FMD package (downloaded 7z archive) and paste all the files and folders into your FMD install folder. Overwrite the files if a prompt pops up.

For example the file **duktape32.dll** should now be replaced by **duktape64.dll**.

After that, you should be able to start FMD as x64.

**Comment by Tmp341** [comment]
- ``config\config.ini`` -> Your personal settings (where to save etc)
- ``config\luamodules.json`` -> I think this is a checksum file for luas.
- ``config\modules.json`` -> Your personal entries for sites (User Agent etc)
- ``data\`` -> Manga sites' manga databases. If you update them, keep them.
- ``works\downloadedchapters.db`` -> As the name says, downloaded manga chapters. 
- ``works\downloads.db`` -> Download list.
- ``works\favorites.db`` -> Favorites.

These are my personal files i keep. I don't think these files keep architecture based info (like 32bit or 64bit). Your never delete should be the first ``config.ini`` and ``favorites.db`` for safety. If you delete first one, you will lose your personal settings like chosen websites, save where to. Last one is keeping your favorite mangas. If you delete it, you have to favorite your mangas again.

**Comment by molitar** [comment]
awesome sounds great.. A move to 64 bit.. great.

**Comment by anfgomezmo** [comment]
@Tmp341 Can you add it in the wiki?? and close this thread, please

**Comment by SDXC** [comment]
We will make a wiki page for that, but the issue stays open until we get feedback or if we don't get any feedback in the next 2-3 days.

**Comment by Tmp341** [comment]
> @Tmp341 Can you add it in the wiki?? and close this thread, please

Did it work for you?

**Comment by devprojectid** [comment]
> * `config\config.ini` -> Your personal settings (where to save etc)
> * `config\modules.json` -> Your personal entries for sites (User Agent etc)
> * `data\` -> Manga sites' manga databases. If you update them, keep them.
> * `works\downloadedchapters.db` -> As the name says, downloaded manga chapters.
> * `works\downloads.db` -> Download list.
> * `works\favorites.db` -> Favorites.
> 
> These are my personal files i keep. I don't think these files keep architecture based info (like 32bit or 64bit). Your never delete should be the first `config.ini` and `favorites.db` for safety. If you delete first one, you will lose your personal settings like chosen websites, save where to. Last one is keeping your favorite mangas. If you delete it, you have to favorite your mangas again.

it works for me, thanks

**Comment by gfhghfghfh** [comment]
> * `config\config.ini` -> Your personal settings (where to save etc)
> * `config\modules.json` -> Your personal entries for sites (User Agent etc)
> * `data\` -> Manga sites' manga databases. If you update them, keep them.
> * `works\downloadedchapters.db` -> As the name says, downloaded manga chapters.
> * `works\downloads.db` -> Download list.
> * `works\favorites.db` -> Favorites.
> 
> These are my personal files i keep. I don't think these files keep architecture based info (like 32bit or 64bit). Your never delete should be the first `config.ini` and `favorites.db` for safety. If you delete first one, you will lose your personal settings like chosen websites, save where to. Last one is keeping your favorite mangas. If you delete it, you have to favorite your mangas again.

 @Tmp341 

Can l ask for config\luamodules.json  and config\base.ini
Do i need to keep them?

**Comment by Tmp341** [comment]
> Can l ask for config\luamodules.json and config\base.ini
> Do i need to keep them?

- ``Base.ini`` file is default in every FMD release package, and it contains infos for FMD (update etc).
- ``Luamodules.json`` file contains Lua modules' update url, what changed about them (changelog) etc. It will be created again. But if you wanna keep lua modules (for example, you've modified one), you should keep it, since this file will tell FMD that your modules are gone, needed to be downloaded again. but Since normal users don't change Lua modules, you don't have to keep it.

**Comment by gfhghfghfh** [comment]
I appreciate your message.
