### ISSUE TITLE
Button to read local files in associated application

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#30]
![fmd6](https://user-images.githubusercontent.com/45929526/55624866-683b2a00-57d1-11e9-95d0-d535dac65b40.PNG)

**Comment by MIRVOUS** [comment]
and maybe for ".pdf" viewer

**Comment by SDXC** [comment]
I probably won't implement it, as FMD is primarily just a downloader and not a local file/collection manager.

For now I won't close the issue yet. I'll get a good night's sleep and re-evaluate this before making a definite decision.

**Comment by MIRVOUS** [comment]
ok thank for confirm

**Comment by SDXC** [comment]
I decided to not implement this feature. Sorry.
