### ISSUE TITLE
Stitch long strip images together

### ISSUE THREAD

**Issue by molitar** [fmd-project-team/FMD#302]
When downloading from mangapark sometimes it will only down the single image at a time and other times it will download all images.
  
Warning: Adult site
https://mangapark.net/manga/our-complications/i1864975/c1

If you go to the URL above and in the pull down set to Load Images: 1 Image you will see how the image is so broken it's unreadable.  So I would like it to either download as Load Images: all images if not possible to set a specific setting for it but best would be Load Images: 3 images as this makes it not too long for full compatibility with manga readers. Some do not like the really long strips after all.

**Comment by SDXC** [comment]
That's actually not really a problem. The images are hosted like that. What you want is a feature to stitch these images together.

Honestly, if I ever will implement this, it will be really low on the priority list.
Is your manga reader not able to show images in a longstrip format? Do you even use a manga reader?

**Comment by molitar** [comment]
No the problem is the downloader downloads typically with a default 1 image only.  That makes it just about impossible to read is the problem. If it did all images it would be no problem but with 1 image it's just about unreadable.

**Comment by SDXC** [comment]
That's what I meant. The website provides the images split into these small chunks for optimal image loading while reading. If you configure the reader settings to load more images, in the background it will still use these chunks, but it aligns them so it looks as if it was one image, which it isn't.

**Comment by molitar** [comment]
Ok so a crap manga site that destroys the original image.. the sizes are not even typical page or manga size.. So another site to avoid it seems.

**Comment by SDXC** [comment]
Well, regardless of the website itself, this function isn't that dumb if it's meant for online reading only. I can't really hold it against them.
