### ISSUE TITLE
Getting manga list not working correctly [ReadMangaRu, MintMangaRu]

### ISSUE THREAD

**Issue by LordARTOG** [fmd-project-team/FMD#307]
Please update database for ReadMnagaRu and MintMangaRu. Now it's only have 70 titles but they has mush bigger title list.

**Comment by LordARTOG** [comment]
+there is a issue with MintMangaRu with 18+ manga. Some of manga hav

**Comment by AbidZakaria** [comment]
give me example link

**Comment by LordARTOG** [comment]
> give me example link

http://mintmanga.com/goblin_slayer__side_story_year_one/vol5/26
Like this one. It's a 18+ warning on MintMangaRU

**Comment by SDXC** [comment]
I will close this ticket, as you opened a new issue here:
https://github.com/fmd-project-team/FMD/issues/572
