### ISSUE TITLE
Add, fix, change and remove some Indonesian sites

### ISSUE THREAD

**Issue by riedhows** [fmd-project-team/FMD#31]
hello some indonesia site error

List error site
Mangaid.me - can't fetch new chapter
komikcast.com - change template and title show N/A
neumanga.tv - change template and title show N/A
pecintakomik.com - change domain to pecintakomik.net
komikotaku.net - change domain to kyuroku.com
Kiryuu.co - can't fetch new chapter

and please add this site
bacamanga.web.id
komikindo.web.id

delete site
mangakid.net
mangaindo.net

thank you

**Comment by SDXC** [comment]
@riedhows I saw you also posted this in the old FMD repo. Before you made this issue, did you try this fork with v0.9.161.0?

**Comment by AbidZakaria** [comment]
Mangaid.me moved manga to bacamanga.web.id
I try to create for lua file for that website

**Comment by AbidZakaria** [comment]
@SDXC I will check the error manga source

**Comment by AbidZakaria** [comment]
Mangaid.me - moved to BacaManga
komikcast.com - work fine
neumanga.tv - small fix with info title
pecintakomik.com -  work fine
komikotaku.net - deteled
kyuroku.com - site added
Kiryuu.co - work fine
bacamanga.web.id - site added
komikindo.web.id - using komikindo.co
mangakid.net - why delete?
mangaindo.net - why delete?

**Comment by MIRVOUS** [comment]
Kiryuu.co - work fine
bacamanga.web.id - site added

> Mangaid.me - moved to BacaManga and site delete
> komikcast.com - work fine
> neumanga.tv - small fix with info title
> pecintakomik.com - work fine
> komikotaku.net - deteled
> kyuroku.com - site added
> Kiryuu.co - work fine
> bacamanga.web.id - site added
> komikindo.web.id - using komikindo.co same sorce manga
> mangakid.net - why delete?
> mangaindo.net - why delete?

how do i check it out

**Comment by admiralmikan** [comment]
Anyway, can you check westmanga too? It only showing #NA on titles

![2019-04-05 22_54_57-Free Manga Downloader](https://user-images.githubusercontent.com/17843605/55640490-e90c1d00-57f5-11e9-83f7-7b650c5d6ab2.jpg)

**Comment by AbidZakaria** [comment]
> Kiryuu.co - work fine
> bacamanga.web.id - site added
> 
> > Mangaid.me - moved to BacaManga and site delete
> > komikcast.com - work fine
> > neumanga.tv - small fix with info title
> > pecintakomik.com - work fine
> > komikotaku.net - deteled
> > kyuroku.com - site added
> > Kiryuu.co - work fine
> > bacamanga.web.id - site added
> > komikindo.web.id - using komikindo.co same sorce manga
> > mangakid.net - why delete?
> > mangaindo.net - why delete?
> 
> how do i check it out

not yet assigned by @SDXC  :V

**Comment by MIRVOUS** [comment]
ok.
can you add this site
https://www.komikzone.com/
maybe the list is not many but. that is good site in my opinion

**Comment by AbidZakaria** [comment]
> Anyway, can you check westmanga too? It only showing #NA on titles
> 
> ![2019-04-05 22_54_57-Free Manga Downloader](https://user-images.githubusercontent.com/17843605/55640490-e90c1d00-57f5-11e9-83f7-7b650c5d6ab2.jpg)

that sites was change template

**Comment by admiralmikan** [comment]
> 
> that sites was change template

so it needs updated lua?

**Comment by AbidZakaria** [comment]
> > that sites was change template
> 
> so it needs updated lua?

![image](https://user-images.githubusercontent.com/19544118/55642123-ce3ba780-57f9-11e9-8019-90861ca1cb58.png)
small fixing

**Comment by Tmp341** [comment]
I can approve those changes, but since i don't know anything about ``coding lua`` etc, i've marked @SDXC to review them.

**Comment by AbidZakaria** [comment]
> ok.
> can you add this site
> https://www.komikzone.com/
> maybe the list is not many but. that is good site in my opinion

you must create new issue for request new sites

**Comment by AbidZakaria** [comment]
@admiralmikan waiting merge from @SDXC or @Tmp341

**Comment by SDXC** [comment]
@all I will review and approve the changes in a bit.

@Tmp341 Except for Localization please don't push/approve any commits/requests. I explicitly want to be the last instance before something gets approved. But thanks for the preparation so far.

@AbidZakaria Also thanks for your contribution.

**Comment by SDXC** [comment]
Current status of the site requests, etc.

- [ ] mangaid.me - remove
- [ ] komikcast.com - ok
- [ ] neumanga.tv - fix
- [ ] pecintakomik.com - ok
- [ ] komikotaku.net - remove
- [ ] kyuroku.com - add
- [ ] Kiryuu.co - ok
- [ ] bacamanga.web.id - add
- [ ] komikindo.web.id - same source as komikindo.co
- [ ] mangakid.net - why delete?
- [ ] mangaindo.net - why delete?
- [ ] komikzone.com - add

@riedhows please verify all the sites (which are checked in the list) and give us feedback.

**Comment by SDXC** [comment]
> 
> 
> ok.
> can you add this site
> https://www.komikzone.com/
> maybe the list is not many but. that is good site in my opinion

@MIRVOUS like AbidZakaria said, please open a new issue for that.

**Comment by Tmp341** [comment]
> @Tmp341 Except for Localization please don't push/approve any commits/requests. I explicitly want to be the last instance before something gets approved. But thanks for the preparation so far.

I haven't approved (and won't approve) those, since i don't know anything about coding. 😃

**Comment by SDXC** [comment]
@Tmp341 yeah, it was just a preventive info 😄

**Comment by riedhows** [comment]
> Mangaid.me - moved to BacaManga and site delete
> komikcast.com - work fine
> neumanga.tv - small fix with info title
> pecintakomik.com - work fine
> komikotaku.net - deteled
> kyuroku.com - site added
> Kiryuu.co - work fine
> bacamanga.web.id - site added
> komikindo.web.id - using komikindo.co same sorce manga
> mangakid.net - why delete?
> mangaindo.net - why delete?

mangakid.net and mangaindo.net it hasn't been updated for a long time and almost all the images are damaged

for komikindo.web.id and komikindo.co it's different

**Comment by riedhows** [comment]
another site - mangakita.net can''t fetch chapter from list

**Comment by riedhows** [comment]
> @riedhows I saw you also posted this in the old FMD repo. Before you made this issue, did you try this fork with v0.9.161.0?

yes, for some problems in the old repo has been resolved in the latest repo

thank you

**Comment by SDXC** [comment]
@riedhows I think we let mangakid.net and mangaindo.net stay until the websites really go offline. It doesn't really hurt and there is always that single soul out there who wants to fetch something from such sites ;)

komikindo.web.id will get it's own entry (like MangaPark and MangaParkOrg).

mangakita.net will be fixed.

**Comment by AbidZakaria** [comment]
@SDXC i will be fixed mangakita.net

**Comment by AbidZakaria** [comment]
> Anyway, can you check westmanga too? It only showing #NA on titles
> 
> ![2019-04-05 22_54_57-Free Manga Downloader](https://user-images.githubusercontent.com/17843605/55640490-e90c1d00-57f5-11e9-83f7-7b650c5d6ab2.jpg)

![image](https://user-images.githubusercontent.com/19544118/55664803-856a0a00-585e-11e9-85bd-b1a2325ef0ae.png)

westmanga work again

**Comment by riedhows** [comment]
> @riedhows I think we let mangakid.net and mangaindo.net stay until the websites really go offline. It doesn't really hurt and there is always that single soul out there who wants to fetch something from such sites ;)
> 
> komikindo.web.id will get it's own entry (like MangaPark and MangaParkOrg).
> 
> mangakita.net will be fixed.

ryoukai capt. :D

**Comment by riedhows** [comment]
> > Anyway, can you check westmanga too? It only showing #NA on titles
> > ![2019-04-05 22_54_57-Free Manga Downloader](https://user-images.githubusercontent.com/17843605/55640490-e90c1d00-57f5-11e9-83f7-7b650c5d6ab2.jpg)
> 
> ![image](https://user-images.githubusercontent.com/19544118/55664803-856a0a00-585e-11e9-85bd-b1a2325ef0ae.png)
> 
> westmanga work again

same with me , all indonesian site works

**Comment by SDXC** [comment]
Fixed MangaKita.

**Comment by Tmp341** [comment]
Is there any one still not fixed?

**Comment by SDXC** [comment]
komikindo.web.id has to be added. I'm on it right now.

**Comment by SDXC** [comment]
komikindo.web.id has been added and works.

Issue will be closed now.
