### ISSUE TITLE
  Download doesn't work [ZManga]

### ISSUE THREAD

**Issue by lordzidiousback** [fmd-project-team/FMD#310]
The site show and update de manga list but not download this is the log when i treat to download from zmanga 

![1](https://user-images.githubusercontent.com/51537246/60316877-7fa23300-993a-11e9-8b80-2cd4449d1f5b.png)

**Comment by AbidZakaria** [comment]
can you try in your browser?
for that chapter, work or not?

**Comment by lordzidiousback** [comment]
i always first probe in webbrowser probe the opction of cf  and revew the issues is not work i open and issue in firefox open and work

**Comment by lordzidiousback** [comment]
https://github.com/manga-download/hakuneko/commit/86da11b0978c1fbc89379571d02634fd3b710d0e

**Comment by SDXC** [comment]
Has been fixed. Some other websites were also fixed with this commit.
