### ISSUE TITLE
cf_bypass.exe - Entry point not found

### ISSUE THREAD

**Issue by Souravi785** [fmd-project-team/FMD#311]
I tried few websites including kissmanga, holymanga, mangadex, etc. it shows cf_bypass.exe - Entry Point Not Found. In addition "The procedure entry point ucrtbase.abort could not be located in the dynamic link library api-ms-win-crt-runtime-l1-1-0.dll. 

Any fix?

P.S - Kissmanga is empty when I tried to double click a manga. Is this cloudfare problem?

**Comment by SDXC** [comment]
Do you also still use Windows 7?
https://github.com/fmd-project-team/FMD/issues/200#issuecomment-495444237

**Comment by Souravi785** [comment]
Yes, I still use Windows 7.
