### ISSUE TITLE
Add support for website [Multiple Japanese]

### ISSUE THREAD

**Issue by Ever4engel** [fmd-project-team/FMD#313]
https://kuragebunch.com/
https://shonenjumpplus.com/
http://mangalifewin.takeshobo.co.jp/gamma/
http://webcomicgamma.takeshobo.co.jp/
http://gammaplus.takeshobo.co.jp/index.html]
https://comic-meteor.jp/
https://manga-park.com/
https://urasunday.com/
https://comic.pixiv.net/
https://www.ganganonline.com/
https://comic-ryu.jp/
https://comic-days.com/
https://manga.line.me/
https://seiga.nicovideo.jp/manga/
https://comic-walker.com/
https://mangacross.jp/
https://comicborder.com/
https://pocket.shonenmagazine.com/
https://www.comic-clear.jp/
https://www.mangaz.com/
http://ganma.jp/
http://webaction.jp/webcomic/
https://www.sukima.me/book/search/?free=1
https://piccoma.com/web/
https://mangaplus.shueisha.co.jp/

**Comment by SDXC** [comment]
@Ever4engel Task for you: Mark all websites that need a login/premium account or that have other restrictions.

**Comment by Ever4engel** [comment]
Yup i'll do that 
i'll edit later this post

**Comment by AbdulMateen2000** [comment]
Can you also add 
https://booklive.jp/

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
