### ISSUE TITLE
Website not found in lua scripts [ManhwaHentai]

### ISSUE THREAD

**Issue by Nimesh-Bhana** [fmd-project-team/FMD#314]
I can not seem to find ManhwaHentai and other sites in lua folder am I missing something.

**Comment by jokosablenk** [comment]
manhwahentai is down and has been removed from fmd

**Comment by SDXC** [comment]
jokosablenk already answered this. The other websites with the same name but different TLD are all fake and won't be added.

**Comment by ChocolateOtaku** [comment]
@Nimesh-Bhana  You may try HakuNeko, it still seems to support ManhwaHentai, but some may not have chapters

**Comment by SDXC** [comment]
I re-added the ManhwaHentai website with the new url. Manga list update won't work right now because of the new template, but using the manga url and chapter download works.

**Comment by Nimesh-Bhana** [comment]
thanks for the responces and re adding it
