### ISSUE TITLE
Website changed domain [KazeManga]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#316]
From "https://kazemanga.xyz" to "https://kazemanga.web.id"
![Capture](https://user-images.githubusercontent.com/45929526/60396735-60401b80-9b6f-11e9-98e3-e060563221b7.PNG)
![Capture1](https://user-images.githubusercontent.com/45929526/60396736-60401b80-9b6f-11e9-9cf4-a27273c090ae.PNG)

**Comment by SDXC** [comment]
Fixed
