### ISSUE TITLE
Missing manga info [Multiple Indonesian]

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#322]
KomikIndoWebId: https://www.komikindo.web.id
![image](https://user-images.githubusercontent.com/28888646/60429970-6b09b780-9c26-11e9-82e1-7fd42c5df39d.png)
Missing: Cover, Summary

KomikManga: https://komikmanga.com
![image](https://user-images.githubusercontent.com/28888646/60430272-187ccb00-9c27-11e9-8505-2dcb9d25fc23.png)
Missing: Genre

KomikStation: https://www.komikstation.com
![image](https://user-images.githubusercontent.com/28888646/60430019-896fb300-9c26-11e9-9287-63ebb1f0b40c.png)
Missing: Cover

Kyuroku: https://kyuroku.com
![image](https://user-images.githubusercontent.com/28888646/60430377-60035700-9c27-11e9-9089-2fc16baa3bd4.png)
Missing: Genre

MangaKita: http://www.mangakita.net
![image](https://user-images.githubusercontent.com/28888646/60430587-dd2ecc00-9c27-11e9-9c73-d51d3d3922d3.png)
Missing: Summary

MangaKu: http://mangaku.in
![image](https://user-images.githubusercontent.com/28888646/60430671-149d7880-9c28-11e9-800a-b3d8af6b4e1b.png)
Missing: Author, Artist, Status, Summary
The chapter numbers are inverted.

MangaKid: http://mgku.me
![image](https://user-images.githubusercontent.com/28888646/60430123-b8862480-9c26-11e9-8404-d6e64186bc66.png)
Missing: Cover

OtakuIndo: https://otakuindo.co
![image](https://user-images.githubusercontent.com/28888646/60430989-dce30080-9c28-11e9-8b81-6df40b5ef55e.png)
Missing: Author, Status

**Comment by AbidZakaria** [comment]
@Slasar41 Proses Rebuild menggnakan metode OOP

**Comment by Slasar41** [comment]
@AbidZakaria Jadi?

**Comment by AbidZakaria** [comment]
intinya nanti kaya module madara.lua
kamu tinggal masukin linknya saja
nanti otomatis semua manga info akan tampil
kalau yang sekarang kan sendiri" meskipun satu module
kedepannya nanti tak buatkan Objek agar semua bisa terintegrasi
semua template manga indo itu sama semua

**Comment by Slasar41** [comment]
iya, semua web indo aku bukain tata letaknya pada mirip" 😅
sip, semangat ngerjainnya
gak perlu buru" sih, kan fitur unduhnya masih berfungsi, cuma biar lebih rapi dan bisa disaring di FMD aja :3

**Comment by AbidZakaria** [comment]
sulit pengucapan
dan kasian yang udah bookmark manga di website MangaKid jadi ngubah semua

**Comment by Slasar41** [comment]
hanya kelihatan jadi rancu saja sih
kalau cari "mangakid" di google kan sudah tidak ada
orang yg ingin unduh dari mgku.me pertama kali di FMD juga jadi bingung karena tidak ada database Mgku
oke tidak perlu diubah :3

**Comment by AbidZakaria** [comment]
liat nanti aja :V

**Comment by SDXC** [comment]
@Slasar41 @AbidZakaria Please write in English when talking on the GitHub issues. Otherwise use Discord.

**Comment by Slasar41** [comment]
@SDXC Alright, sorry.

**Comment by SDXC** [comment]
@AbidZakaria Are all these sites fixed with your pull request?

**Comment by Slasar41** [comment]
I want to test it.

**Comment by SDXC** [comment]
@Slasar41 If all pages are fixed, you can close the issue.

**Comment by Slasar41** [comment]
@AbidZakaria @SDXC Problems:
KazeManga - https://kazemanga.web.id/barakamon/
Has some strings on the summary

KomikIndoWebId - https://www.komikindo.web.id/manga/1-nen-a-gumi-no-monster/
Missing: Summary

KomikManga - https://komikmanga.com/manga/1nen-agumi-no-monster
Missing: Genre

Komiku - https://komiku.co/manga/1-nen-a-gumi-no-monster/
Missing: Chapter list

Mangacan - http://www.mangacanblog.com/baca-komik-29_to_jk-bahasa-indonesia-online-terbaru.html
All the manga's title has `|   |can` on it

MangaIndo - https://mangaindo.web.id/absolute-duo/
All the manga's title became `indo`

MangaKid - https://mgku.me/manga/absolute-duo/
All the manga's title became `Mgku.me`

MangaKita - https://www.mangakita.net/manga/absolute-duo/
Missing: Summary, Chapter list

MangaKu - https://mangaku.in/manga-absolute-duo-bahasa-indonesia/
Missing: Author, Artist, Status, Summary
The chapter numbers are inverted.

OtakuIndo - https://otakuindo.co/baca-manga/1-nen-a-gumi-no-monster/
Missing: Author, Status, Chapter list

**Comment by ChocolateOtaku** [comment]
How did this pull request find its way inside without being tested?
Furthermore, even with my low level C# skills i could spot the code smells immediately.

The conditions below will stop propagation as soon as there is any match and i doubt the websites are kind enough to follow this priority order and are only allowing one exclusive match of these conditions.

For example `"//h1"` is a top candidate to hit something that is not supposed to be the title on various websites...

```lua
function getTitle(x)
	local title = ''
	if title == '' then title = x.xpathstring('//div[@class="infox"]/h1') end
	if title == '' then title = x.xpathstring('//h1[@itemprop="headline"]') end
	if title == '' then title = x.xpathstring('//h1') end
	if title == '' then title = x.xpathstring('//div[@class="info1"]/*') end
	if title == '' then title = x.xpathstring('//div[@class="mangainfo"]/h1') end
	if title == '' then title = x.xpathstring('//*[@class="title"]/h2') end
	title = title:gsub('Bahasa Indonesia$', ''):gsub(' Indonesia|Baca"', ''):gsub('Bahasa Indonesia', ''):gsub('Komik', '')
	title = title:gsub('Manga', ''):gsub('Indonesia', ''):gsub('Baca', '')
	return title
end
```

**Comment by Slasar41** [comment]
The module should be reverted for the time being.

**Comment by SDXC** [comment]
has been reverted

**Comment by SDXC** [comment]
@Slasar41 Does the reverted version pop up as a module update for you?

**Comment by Slasar41** [comment]
Yes, got a module update.

**Comment by SDXC** [comment]
okay, thanks.

**Comment by AbidZakaria** [comment]
> How did this pull request find its way inside without being tested?
> Furthermore, even with my low level C# skills i could spot the code smells immediately.
> 
> The conditions below will stop propagation as soon as there is any match and i doubt the websites are kind enough to follow this priority order and are only allowing one exclusive match of these conditions.
> 
> For example `"//h1"` is a top candidate to hit something that is not supposed to be the title on various websites...
> 
> ```lua
> function getTitle(x)
> 	local title = ''
> 	if title == '' then title = x.xpathstring('//div[@class="infox"]/h1') end
> 	if title == '' then title = x.xpathstring('//h1[@itemprop="headline"]') end
> 	if title == '' then title = x.xpathstring('//h1') end
> 	if title == '' then title = x.xpathstring('//div[@class="info1"]/*') end
> 	if title == '' then title = x.xpathstring('//div[@class="mangainfo"]/h1') end
> 	if title == '' then title = x.xpathstring('//*[@class="title"]/h2') end
> 	title = title:gsub('Bahasa Indonesia$', ''):gsub(' Indonesia|Baca"', ''):gsub('Bahasa Indonesia', ''):gsub('Komik', '')
> 	title = title:gsub('Manga', ''):gsub('Indonesia', ''):gsub('Baca', '')
> 	return title
> end
> ```

oh,
`//h1` should be the top candidate

**Comment by ChocolateOtaku** [comment]
No that is not what i meant by **top candidate**. I was referring to **the best example** to see why the whole propagation scheme is wrong.
The `getTitle(x)` (or any of the other functions) will run all the conditions for each website and take the first condition that matches. But in reality each website only has a single condition that shall be tested, so there is always a chance that a wrong condition will match.

Website A - This will work with `getTitle`
```html
<div><h1>Manga title</h1></div>
```

Website B - This will not work with `getTitle`, because multiple conditions are matching and the first one is choosen, which is wrong for this website
```html
<div><h1>Not a manga title<h1><div>
<div class="info"<h1>Manga title<h1><div>
```

Sure you may change the conditions to make them more throw another hundreds of if-else inside and hope that only one of each condition will match any website, but that is still a bad solution. I think a better way is provide the condition depends on website. There may be different ways to do it, one example is to use the same scheme as it is already done for [dirurls](https://github.com/fmd-project-team/FMD/blob/eb68238ed9dfe328f2beffb045d851613095129c/lua/modules/MangaShiro.lua#L201). It is possible to assign a single condition for the title, for genres, for chapters, ...

**Comment by AbidZakaria** [comment]
```lua
function getTitle(x)
	local title = ''
	
	if title == '' then title = x.xpathstring('//div[@class="infox"]/h1') end
	if title == '' then title = x.xpathstring('//h1[@itemprop="headline"]') end	
	if title == '' then title = x.xpathstring('//div[@class="info1"]/*') end
	if title == '' then title = x.xpathstring('//div[@class="mangainfo"]/h1') end	
	if title == '' then title = x.xpathstring('//h1') end
	if title == '' then title = x.xpathstring('//h2') end
	title = title:gsub('Bahasa Indonesia$', ''):gsub(' Indonesia|Baca"', ''):gsub('Bahasa Indonesia', ''):gsub('Komik', '')
	title = title:gsub('Manga', ''):gsub('Indonesia', ''):gsub('Baca', ''):gsub(' bahasa Indonesia', '')
	return title
end
```

First, getTitle will check if there is a title in if-else first
If there is still no, then check whether the other one is second
and if it has been found
then no need to check again

and for double h1
in the mangashiro template there is only 1 h1
so everything is fine if use getTitle

**Comment by Slasar41** [comment]
@AbidZakaria If you already done fixing it, give the module to me so I can test it.

**Comment by ChocolateOtaku** [comment]
Sorry to be blunt, but the current implementation is just wrong. It doesn't matter how often you reorder the conditions or how detailed your conditions are, there is always a chance it will fail.

Your last implementation will simply not work for the following sample HTML, because it will return **Not a manga title** instead of the expected **Manga title**.

```html
<div class="info"<h1>Not a manga title<h1><div>
<div><h1>Manga title<h1><div>
```

You even explained why this will fail, because it stops propagation as soon as a title is found, so why still clinging to this unstable implementation...

**Comment by SDXC** [comment]
This should be okay now.
