### ISSUE TITLE
Add support for website [Gntai]

### ISSUE THREAD

**Issue by lordzidiousback** [fmd-project-team/FMD#323]
please add support for

http://www.gntai.xyz

**Comment by AbidZakaria** [comment]
Note:
Mangalist : http://www.gntai.xyz/page/92?m=1
Gntai 
Cat : Spanish

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
