### ISSUE TITLE
TSQLite3ConnectionH : database disk image is malformed

### ISSUE THREAD

**Issue by fales13** [fmd-project-team/FMD#325]
whats todo????
thanks
![image](https://user-images.githubusercontent.com/37041682/60678307-4c1d5680-9eae-11e9-9168-77a77fdc2db0.png)

Program exception!
Application       : Free Manga Downloader
Version           : 0.9.165.0
Product Version   : Win64
Host Machine      : Windows 10 64-bit
FPC Version       : 3.0.4
LCL Version       : 1.8.4.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2019/06/10 22:42:04
Path              : D:\FMD_SHIP\fmd.exe
Process ID        : 3204
MainThread ID     : 9528
Thread ID         : 9528
Time              : 04/07/2019 22:49:07.946
Sender Class      : TDownloadedChaptersDB
Exception Class   : ESQLDatabaseError
Message           : TSQLite3ConnectionH : database disk image is malformed
  $000000010046B6AF
  $00000001004696C1
  $0000000100469CC0
  $000000010046A80A
  $000000010046E116
  $000000010046DF18
  $00000001004AC4E1
  $00000001004ACA5E
  $00000001004AC751
  $00000001004A3684
  $00000001000102B0
  $000000010027B2B6
  $00000001000102B0
  $0000000100070DB7
  $0000000100077101
  $0000000100020717
  $000000010001E940

**Comment by Tmp341** [comment]
1. Have you changed anything, force closed FMD, did something after your last succesful fmd execution?
2. Also, send your fmd package.

**Comment by fales13** [comment]
1. i ever force close FMD (taskmanager), because of freeze process and memory leaks
2. https://fales.co/FMD_SHIP.rar (42.02 MB) (the full package) , https://fales.co/FMD_SHIP - Copy.rar (22.41 MB) (whitout data)

**Comment by fales13** [comment]
1. i ever force close FMD (taskmanager), because of freeze process and memory leaks
2. 

[fmd.zip](https://github.com/fmd-project-team/FMD/files/3360938/fmd.zip)

**Comment by Tmp341** [comment]
Your database file might have been corrupted, that's why i asked if something different happened.

Also, i wanted your whole folder, not just ``exe`` file.

**Comment by fales13** [comment]
database corruption is my first guess, i tried using random sql editor with no avail

sorry, here my whole FMD package https://fales.co/FMD_SHIP.rar (52 or so MB)

if i press "continue", nothing happened, only if i press "terminate" FMD will forced to be closed

thanks for your reply

**Comment by AbidZakaria** [comment]
i test your FMD in my laptop
is everything fine

![image](https://user-images.githubusercontent.com/19544118/60722032-ee464880-9f59-11e9-99ec-1ae8185de290.png)

**Comment by Tmp341** [comment]
No problem here too:

![ssss](https://user-images.githubusercontent.com/1683388/60730911-dd440a00-9f4e-11e9-8d6f-782c9e85eee8.jpg)

**Comment by fales13** [comment]
thanks for your replies

may be there is problem in my windows or my memory
you could close this issue

**Comment by Tmp341** [comment]
Change your FMD from C to D drive or D to C and try again.
