### ISSUE TITLE
Add support for website [OnePiece-Tube]

### ISSUE THREAD

**Issue by skupfer** [fmd-project-team/FMD#327]
I would like to ask whether it is possible to add support for onepiece-tube (german site: http://onepiece-tube.com/kapitel-mangaliste). They usually have more chapters available and alot of sites fork from them anyways but without corrected errors which often occur later on after reports.

Tried to add support by myself but wasn't able to accomplish this so far.

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
