### ISSUE TITLE
Can't download chapters [MangaYosh and DoujinYosh]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#329]
I think it's because "MangaYosh" and "DoujinYosh" has changed the template.
because the case is same as before #73

**Comment by AbidZakaria** [comment]
wait pull

**Comment by SDXC** [comment]
Merged

**Comment by MIRVOUS** [comment]
Hello there. i try DoujinYosh and MangaYosh but Failed/can't download again. Can you fix it again

**Comment by AbidZakaria** [comment]
@MIRVOUS create new issue
i'll be checked later
