### ISSUE TITLE
Download Error [Zmanga.org]

### ISSUE THREAD

**Issue by inkanime** [fmd-project-team/FMD#330]
cannot download anything from zmanga.org

**Comment by djgerman10** [comment]
it's walking perfectly (zmanga)
![x](https://user-images.githubusercontent.com/48584512/61947842-a88b0780-af7c-11e9-84fa-ef9a3b9323a9.png)

![xx](https://user-images.githubusercontent.com/48584512/61947868-b476c980-af7c-11e9-8b60-6920e5af3e23.png)

**Comment by SDXC** [comment]
They removed some of their series so the manga list contained some titles that weren't valid anymore. Website database is updated and contains only the valid titles now.
