### ISSUE TITLE
Chapter list missing [MangaShiro]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#331]
![Capture](https://user-images.githubusercontent.com/45929526/60759377-a35a2d00-a04e-11e9-8c94-4b7daeaf35fe.PNG)
![Capture2](https://user-images.githubusercontent.com/45929526/60759378-a35a2d00-a04e-11e9-8878-b69df5b901e8.PNG)

**Comment by MIRVOUS** [comment]
I tried the others and results is same

**Comment by SDXC** [comment]
Merged

**Comment by MIRVOUS** [comment]
stay nothing list chapter
![Capture5](https://user-images.githubusercontent.com/45929526/60869553-657d2480-a259-11e9-9e65-6e8b28435d62.PNG)

**Comment by SDXC** [comment]
This should be fixed now.
