### ISSUE TITLE
Chapter list missing [Kiryuu]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#332]
![Capture3](https://user-images.githubusercontent.com/45929526/60759536-e9b08b80-a050-11e9-8582-639a17fd2599.PNG)
![Capture4](https://user-images.githubusercontent.com/45929526/60759537-e9b08b80-a050-11e9-8c76-df831551f25f.PNG)

**Comment by SDXC** [comment]
Merged

**Comment by MIRVOUS** [comment]
stay nothing list
![Capture6](https://user-images.githubusercontent.com/45929526/60870080-577bd380-a25a-11e9-82c7-f0dbb082d461.PNG)

**Comment by SDXC** [comment]
Should also be fixed now.
