### ISSUE TITLE
Failed Chapter Download [MangaDex]

### ISSUE THREAD

**Issue by nille02** [fmd-project-team/FMD#334]
There is a Issue with chapter 71 (From TOOR Scans) from Mana: https://mangadex.org/manga/10045. Chapterlink: https://mangadex.org/chapter/657402/1

All other Files are working like a charm, but just this one fails. My guess is a Filename issue due to the >< in the filename ```Argh~ Now I don't know what to do anymore ><```.

**Comment by Tmp341** [comment]
Choose some another character for ``Options->Save To->Replace all unicode character with->`` choose something like ``_`` (i have this).

**Comment by nille02** [comment]
Unfortunately hat didn't help. In The Process the Jumps between 0/0 and 1/1 before he Goes to Failed. Is there a way to get more verbose information whats going on? 

```=== Log Session Started at 07.07.2019 21:05:51 by Free Manga Downloader ===
21:05:51:646 INFO: "Free Manga Downloader" started with [PID:4136] [HANDLE:18446744073709551615]
21:05:51:646 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.165.0
               Product Version   : Win64
               Host Machine      : Windows 10 64-bit
               FPC Version       : 3.0.4
               LCL Version       : 1.8.4.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2019/06/10 22:42:04
               Path              : F:\Media\Software\Manga Loader\fmd.exe
               Process ID        : 4136
               MainThread ID     : 8872
21:06:04:671 WARNING: TTaskThread, checkforfinish failed=1/1 [Mangadex]"Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" > "/chapter/657402"
W
21:06:04:672 WARNING: TTaskThread, download failed. "Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" "Vol. 014 Ch. 071 - Argh~ Now I don't know what to do anymore  [TOOR Scans]" "/chapter/657402"
21:06:06:676 WARNING: TTaskThread, checkforfinish failed=1/1 [Mangadex]"Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" > "/chapter/657402"
W
21:06:06:676 WARNING: TTaskThread, download failed. "Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" "Vol. 014 Ch. 071 - Argh~ Now I don't know what to do anymore  [TOOR Scans]" "/chapter/657402"
21:06:08:679 WARNING: TTaskThread, checkforfinish failed=1/1 [Mangadex]"Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" > "/chapter/657402"
W
21:06:08:679 WARNING: TTaskThread, download failed. "Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" "Vol. 014 Ch. 071 - Argh~ Now I don't know what to do anymore  [TOOR Scans]" "/chapter/657402"
21:06:10:685 WARNING: TTaskThread, checkforfinish failed=1/1 [Mangadex]"Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" > "/chapter/657402"
W
21:06:10:686 WARNING: TTaskThread, download failed. "Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" "Vol. 014 Ch. 071 - Argh~ Now I don't know what to do anymore  [TOOR Scans]" "/chapter/657402"
21:06:12:691 WARNING: TTaskThread, checkforfinish failed=1/1 [Mangadex]"Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" > "/chapter/657402"
W
21:06:12:691 WARNING: TTaskThread, download failed. "Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" "Vol. 014 Ch. 071 - Argh~ Now I don't know what to do anymore  [TOOR Scans]" "/chapter/657402"
21:06:14:693 WARNING: TTaskThread, checkforfinish failed=1/1 [Mangadex]"Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" > "/chapter/657402"
W
21:06:14:693 WARNING: TTaskThread, download failed. "Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Rachirareta Ken" "Vol. 014 Ch. 071 - Argh~ Now I don't know what to do anymore  [TOOR Scans]" "/chapter/657402"
```

**Comment by Tmp341** [comment]
Yup, it is not working for me too.

**Comment by SDXC** [comment]
the title + chapter name + download path may be too long (more than 255 characters)

**Comment by nille02** [comment]
There are other chapters with longer names in that manga that cause no problem. Like ```Vol. 013 Ch. 069.5 - The conversation between a charismatic mother and a clumsy daughter [TOOR Scans]```

**Comment by Tmp341** [comment]
@nille02 Can you post your ``Save To`` settings screen?

**Comment by nille02** [comment]
![grafik](https://user-images.githubusercontent.com/4272018/60805576-c84ebd00-a180-11e9-8516-058b83e1697b.png)

![grafik](https://user-images.githubusercontent.com/4272018/60805593-d270bb80-a180-11e9-85cb-6c1c2060ef76.png)

![grafik](https://user-images.githubusercontent.com/4272018/60805643-f7fdc500-a180-11e9-8c40-dcc511609afb.png)

**Comment by Slasar41** [comment]
It's works on other site like KissManga even though not enabling `Enable Replace all unicode character with` but the >< characters isn't on folder name.
https://kissmanga.com/Manga/Ore-ga-Ojou-sama-Gakkou-ni-Shomin-Sample-Toshite-Rachirareta-Ken

**Comment by nille02** [comment]
Then its something different with this chapter from mangadex that trigger a bug.

**Comment by SDXC** [comment]
Can reproduce this behavior even when using numbering instead of chaptername. I will have to look into it as soon as my holidays start on friday.

**Comment by ayase-tan** [comment]
this similar situation happened to me when downloading chapter 165 from this series https://mangarock.com/manga/mrs-serie-283326

**Comment by SDXC** [comment]
Should work now.

**Comment by nille02** [comment]
and it does
