### ISSUE TITLE
Only one page is being downloaded when using [KissManga]

### ISSUE THREAD

**Issue by newmanism17** [fmd-project-team/FMD#336]
Downloading from KissManga sometimes results in only one page being downloaded per chapter

[fmd.log](https://github.com/fmd-project-team/FMD/files/3366676/fmd.log)

My assumption is that it has to do with cloudflare, but I know nothing about any of this stuff.

**Comment by Tmp341** [comment]
``ERROR: KissManga, image list empty.`` @SDXC

**Comment by ayanamichie** [comment]
That is not a problem, check the wiki the Kissmanga workaround.
![image](https://user-images.githubusercontent.com/48865118/60871828-f1fff680-a209-11e9-8a29-9c1198946be2.png)
one of those changed, you need to get it again.

**Comment by molitar** [comment]
No I don't think it is a problem with a specific site.  I had several sites do this what is strange most of them were all downloads on the same day.  I have not seen this behavior though on Kissmanga but other sites.

**Comment by Tmp341** [comment]
Check #1109
