### ISSUE TITLE
add new sites

### ISSUE THREAD

**Issue by Demevil** [fmd-project-team/FMD#340]
https://kyuroku.com/
https://komiku.co
https://bacamanga.co
https://mangazuki.me/
https://mangazuki.club
http://ww1.heavenmanga.vip/
https://www.mangadropout.com/
http://bacamanhwa.me/
https://mangairo.com/
https://manganelo.com
https://www.simply-hentai.com/home
https://www.8muses.com/comics
http://xlecx.com/
https://freeadultcomix.com/
https://lacomics.org/
https://myhentaigallery.com/
https://www.erofus.com/
https://svscomics.com/
https://www.porncomixonline.net/
https://multporn.net/
https://bato.to
https://bacamanga.co
http://sukahentai.com/
http://isekaiscan.com/
https://zeroscans.com/
https://mangabat.com/web

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.

**Comment by legolaslx** [comment]
Plz add https://manhwahentai.site , thanks

**Comment by Tmp341** [comment]
> 
> 
> Plz add https://manhwahentai.site , thanks

Alright, added your request too.

**Comment by Demevil** [comment]
hello where can I find data for the latest site?
I haven't received any website updates

**Comment by Tmp341** [comment]
@Demevil You can download from [here](https://github.com/fmd-project-team/FMD-WebsiteDatabases)

**Comment by Demevil** [comment]
TY

**Comment by legolaslx** [comment]
Plz add https://www.mangaromance.eu/. Can you give me a link to the Paypal.me please?

**Comment by SDXC** [comment]
Site added to the list.
We won't accept any donations because this is a project that doesn't need any funds.

**Comment by SDXC** [comment]
Just to inform you: 8muses is already partially supported, it's only getting manga info and downloading the images though. You can't select the website in the options and you can't get a manga list. This is intentional and won't be changed.
