### ISSUE TITLE
Module update delete all lua

### ISSUE THREAD

**Issue by zwxr** [fmd-project-team/FMD#341]
Hello
Sometimes when I open fmd or fmd on idle mode, module updates always showing and it keeps deleting the current lua instead of updating it. can you fix it?
Thanks

![Screenshot_1](https://user-images.githubusercontent.com/8922267/60852514-326b6e80-a222-11e9-9d1f-4ae9676f60df.jpg)

**Comment by Tmp341** [comment]
It is about your connection. When your connection is lost (even for a second) while fmd checks lua's, fmd does that.

**Comment by zwxr** [comment]
But, this doesn't happen on the riderkick version.

**Comment by Tmp341** [comment]
I remember that happened to me on that version too. I lost connection and fmd asked me this.

It is about connection, not FMD's module system. Make sure your internet is stable. Also, for example, if you try to connect a vpn and try to update modules, this happens. I mean, i get this error when i try to connect a vpn and open fmd at the same time.

**Comment by Fortiori** [comment]
I'm hoping this can be fixed by checking if there is a connection first. I use FMD on a laptop when travelling and it spends a lot of time without internet access (but with FMD open so I can see what I have that's new).
