### ISSUE TITLE
Fix typo "Weebtoons" to "Webtoons"

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#344]
In 'Filter' genre, it Weebtoons not Webtoons.

Yeah, i know about custom genre, but changing that tag for future update wont be much problem right.

And it also kind of funny.

Weeb: A weeb is a derisive term for a non-Japanese person who is so obsessed with Japanese culture that they wish they were actually Japanese.

Toon : Noun. toon (plural toons) (informal) A cartoon, especially an animated television show. (informal, video games) A player's avatar or visible character in a massively multiplayer online role-playing game. (informal, by extension) Only used in loony toon or looney toon, alternative forms of loony tune, which see.

**Comment by Tmp341** [comment]
Is it not finding ``Webtoons`` regardless?

**Comment by SDXC** [comment]
Fixed all translations. Next release will bring the fix.

**Comment by SDXC** [comment]
FMD v0.9.166.0 has been released!
https://github.com/fmd-project-team/FMD/releases/tag/0.9.166.0
