### ISSUE TITLE
Can't download [KissManga]

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#346]
I can go to the website, but when i open it from FMD i only got this 
![image](https://user-images.githubusercontent.com/30251842/61070572-a20b7480-a441-11e9-8fdc-360b7dadcb19.png)

**Comment by Tmp341** [comment]
Have you tried ``[Kissmanga Workaround](https://github.com/fmd-project-team/FMD/wiki#troubleshooting-guides)`` ?

**Comment by knight109** [comment]
![image](https://user-images.githubusercontent.com/30251842/61105094-6c9b7100-a4ab-11e9-8043-92c5c1d6011a.png)


I think the site is under maintenance, probably that is why.
Gonna do it later after it done.

**Comment by Tmp341** [comment]
That error shows when their website bans your IP, because of too many requests (like FMD or another downloader).

**Comment by Slasar41** [comment]
> That error shows when their website bans your IP, because of too many requests (like FMD or another downloader). Just delete cookies and try again.
> 
> I personally dropped using that site, not even checking on browser either. There are many other sites i can use.

No such thing as too many request causing that message.
It's because he's use an Adblock to open the website.
The solution is delete all cookies from KissManga and then use `KissAnime Anti-Adblock Blocker` script.

**Comment by knight109** [comment]
> > That error shows when their website bans your IP, because of too many requests (like FMD or another downloader). Just delete cookies and try again.
> > I personally dropped using that site, not even checking on browser either. There are many other sites i can use.
> 
> No such thing as too many request causing that message.
> It's because he's use an Adblock to open the website.
> The solution is delete all cookies from KissManga and then use `KissAnime Anti-Adblock Blocker` script.

Turn off my adblock and clear my cache. i can go there now.

But i just realize that Initialization vector i got from website and the one from tutorial and the original one that FMD used is the same.
Even different manga have the same Initialization vector.

**Comment by Slasar41** [comment]
Yes, different manga have the same Key and Initialization Vector.
So you say the Key and Initialization Vector you got from website already the same as in FMD?

**Comment by knight109** [comment]
> Yes, different manga have the same Key and Initialization Vector.
> So you say the Key and Initialization Vector you got from website already the same as in FMD?

Well, more like every Key and Initialization Vector i got is the same.
I thought it because im not login, but when i do it still the same
![image](https://user-images.githubusercontent.com/30251842/61124745-55c04300-a4da-11e9-8cec-abd5b774294d.png)
![image](https://user-images.githubusercontent.com/30251842/61124769-6375c880-a4da-11e9-8b6d-b90620ffbe46.png)

**Comment by Tmp341** [comment]
> No such thing as too many request causing that message.

It happened to me even though i didn't have an adblock (disabled at that time).

**Comment by Slasar41** [comment]
> Well, more like every Key and Initialization Vector i got is the same.
> I thought it because im not login, but when i do it still the same
> ![image](https://user-images.githubusercontent.com/30251842/61124745-55c04300-a4da-11e9-8cec-abd5b774294d.png)
> ![image](https://user-images.githubusercontent.com/30251842/61124769-6375c880-a4da-11e9-8b6d-b90620ffbe46.png)

Yeah, it's normal like that.
Is it match within FMD?

**Comment by knight109** [comment]
> Yeah, it's normal like that.
> Is it match within FMD?

Yup. but not exactly the same.
The key on FMD is: mshsdf832nsdbash20asdmmshsdf832nsdbash20asdm
which is mshsdf832nsdbash20asdm paste twice.
Both not working tho.

Does this just on my end or other people also get this?

**Comment by Slasar41** [comment]
That's wrong.
It's should be like this:
![image](https://user-images.githubusercontent.com/28888646/61130551-1a754280-a4e1-11e9-8a25-2a22fc4f36d9.png)

**Comment by knight109** [comment]
The key change but only once, but then it stay the same no matter what manga i open, probably it change daily(?)

**Comment by knight109** [comment]
Nevermind... i foudn the real problem
![image](https://user-images.githubusercontent.com/30251842/61168129-902dec80-a57b-11e9-811a-6786f91dc1d4.png)
I set those to true and there was some code on the cookies.

Delete the cookies and make it false fix this problem.
I dont even remember setting those in Kissmanga.
Sorry for the problem.

**Comment by Tmp341** [comment]
The ones on your screenshot are set by cf_bypass file. It is an automatic process unless you check that ``DisableCloudflareBypass`` setting.

**Comment by SDXC** [comment]
I'll rewrite the behavior so cf_bypass won't disable itself automatically by default.

Does the KissManga problem itself still occur for you?

**Comment by knight109** [comment]
Nope, all good now
