### ISSUE TITLE
Drop Box not working

### ISSUE THREAD

**Issue by zartzaku** [fmd-project-team/FMD#347]
When I drag the link to the drop box it show circle with slash inside, which mean the link cannot be drop into drop box.

**Comment by Slasar41** [comment]
Works fine for me.
https://i.imgur.com/1k5YbMO.gifv

**Comment by SDXC** [comment]
@zartzaku Where do you drag your link from?

**Comment by zartzaku** [comment]
Not work When using Firefox 68.0, but when I am using chrome it work.
maybe because my firefox is have many addon.
is there any firefox addon that can add "download with fmd" when using right click?

**Comment by SDXC** [comment]
I don't know of any addons that interrupt the drag and drop behavior of Firefox. But I know that it normally works. At least Chrome works for you and so I will close this issue.
