### ISSUE TITLE
Do not disable cf_bypass by default

### ISSUE THREAD

**Issue by ayanamichie** [fmd-project-team/FMD#350]
![image](https://user-images.githubusercontent.com/48865118/61140511-f6464100-a4a1-11e9-94e9-9d0784963ac8.png)

Normally when i open after windows start FMD is setting that to true, when it's false it works fine.
when i close and reopen its false, problem only when i start windows.

**Comment by SDXC** [comment]
@ayanamichie Always state which website you're trying to use. you snipped away the one important information I need to analyze what's happening.

**Comment by ayanamichie** [comment]
Sorry, Kissmanga

**Comment by Thrieze** [comment]
I sorta have the same issue, it gets caught on just kissmanga then fails eventually, I do have the bypass working on other sites.

**Comment by ayanamichie** [comment]
![image](https://user-images.githubusercontent.com/48865118/61394039-b06dec00-a898-11e9-8f23-680ad43d337b.png)
this keeping happening, it's just not only when i start up windows it's seems, after sometime it auto cheek itself to True.
@SDXC

**Comment by molitar** [comment]
Yeah that setting itself to True so Cloudflare does not work is a real pain.  How about on every start it auto disables all that are set as True so it can try again?

**Comment by SDXC** [comment]
I'll rewrite that behavior so it doesn't automatically disable at default.

**Comment by SDXC** [comment]
FMD v0.9.166.0 has been released!
https://github.com/fmd-project-team/FMD/releases/tag/0.9.166.0

cf_bypass doesn't automatically disable itself anymore by default.
