### ISSUE TITLE
Sort the Downloads tab when using Drop Box

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#353]
If I use the drop box feature, the manga still listed at the bottom even though I already check `Sort Downloads tab when adding new tasks`
https://i.imgur.com/1k5YbMO.gifv

Also, it's defaulting to View tab on Options tab when open/reopening FMD. Could you change the default to General tab?

**Comment by SDXC** [comment]
Fixed. Comes with the next release.

**Comment by SDXC** [comment]
FMD v0.9.166.0 has been released!
https://github.com/fmd-project-team/FMD/releases/tag/0.9.166.0
