### ISSUE TITLE
Chapter check for favorites doesn't find new chapters

### ISSUE THREAD

**Issue by noering** [fmd-project-team/FMD#354]
Hello,
Favorites cannot chek new chapter at all, bato.to, mangarock, manganello etc.

**Comment by noering** [comment]
I don't know whether this is just me or someone else too :(

**Comment by bloodsign** [comment]
Can you describe the problem in more detail?
You can also post the log here which can be found on [Options] > [Misc] > [Log]

**Comment by noering** [comment]
After FMD started, the favorites check the list one by one, but cannot recognize it from the save list whether there is a recent chapter or not. Although there are many updated new chapters that have been online
![Capture](https://user-images.githubusercontent.com/3715548/61169065-e9008380-a581-11e9-95a8-2f7b19c95f85.PNG)

**Comment by noering** [comment]
From the log, I found bato.to, manganello and mangarock do not have * .lua files. But I don't know whether this is the source of the problem
![bato](https://user-images.githubusercontent.com/3715548/61169253-45b16d80-a585-11e9-8787-54aa8e75d7f6.PNG)
![manganello](https://user-images.githubusercontent.com/3715548/61169258-4cd87b80-a585-11e9-92a8-ad08635e6d00.PNG)
![mangarock](https://user-images.githubusercontent.com/3715548/61169259-519d2f80-a585-11e9-8a1c-d274fd885c4c.PNG)
![end](https://user-images.githubusercontent.com/3715548/61169264-5530b680-a585-11e9-9932-68995c2ca257.PNG)

**Comment by bloodsign** [comment]
If i remember correctly, green circle means you have the latest chapters. 

I checked one of the series on your watchlist on mangarock (Assassin's Pride) and the number of chapters matches what's on your list (20), Same goes for (Almadianos Eiyuuden) which has (14) chapters. 
Which series are giving you problems?

**Comment by noering** [comment]
Yes you right, about the green circle.

Here are some from mangarock (bato.to seems fine, sorry - my mistake)
The wolf won't sleep (4) it should be 5
https://mangarock.com/manga/mrs-serie-200039783
![01](https://user-images.githubusercontent.com/3715548/61169591-a478e600-a589-11e9-8b1e-573046cd6a1c.PNG)

The necromancer maid (3)) it should be 4
https://mangarock.com/manga/mrs-serie-200048374
![02](https://user-images.githubusercontent.com/3715548/61169629-c3777800-a589-11e9-88e0-6d502f99a66f.PNG)

Or perhaps it just not yet updated some how? server side problem etc?

**Comment by bloodsign** [comment]
Hmm, it might be on your end, because it correctly shows in my FDM.
Have you tried checking manga info if it shows in the chapter list right now? 
Sometimes, it takes awhile to for FDM to retrieve newly posted chapters.

**Comment by bloodsign** [comment]
![FDM-issue](https://user-images.githubusercontent.com/12083007/61169782-d5f6af00-a593-11e9-8c72-faf6feca8bff.png)

**Comment by noering** [comment]
'Hmm, it might be on your end, because it correctly shows in my FDM.'  - Yes, that's possible :(
Ok I'll try chek it with mangan info.

'Sometimes, it takes awhile to for FDM to retrieve newly posted chapters.' Yes that makes sense, I will try to wait a while later, hopefully everything back to normal :)

**Comment by Tmp341** [comment]
Try [fresh install](https://github.com/fmd-project-team/FMD/wiki#useful-informations)

**Comment by noering** [comment]
Ok thanx

**Comment by SDXC** [comment]
@noering Did the fresh install fix the problem for you?

**Comment by noering** [comment]
No, but after fresh install and I wait about  more than a day, everything back to normal again. It looks like the problem came from my internet connection / or their server.

**Comment by noering** [comment]
I mean not from FDM

**Comment by Tmp341** [comment]
If you have any problem regarding this, reopen this issue.
