### ISSUE TITLE
Genres not returning all matches [HentaiNexus]

### ISSUE THREAD

**Issue by Vantageright** [fmd-project-team/FMD#356]
Filtering by custom genre on Hentai Nexus doesn't work well - it returns fewer results than actually have the tag or will not return any at all. Tested with the nun, pregnant and squirting tags which returned 0, 2 and 5 when each had at minimum 8 works.
I can search for works with the tag(s) by name, and if I click it then it updates and the work can be found through the custom search but not before. <- Tested with 2 nun tag works.

Using latest version, 0.9.165.0 with updated manga list.

**Comment by Vantageright** [comment]
Correction - genres in general don't work for nexus. The hentai tag has 155 pages of works on the site, searching for hentai with the filter box ticked returns 101 works total.

**Comment by SDXC** [comment]
Should be fixed now. Just re-download the database from the server. If you still have any problems, just re-open this issue.
