### ISSUE TITLE
Chapter download doesn't work [ReadMangaToday]

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#359]
Already do the Bypass
![image](https://user-images.githubusercontent.com/30251842/61577022-58431e00-ab14-11e9-8263-21bfcda53a47.png)

But still cant download.

**Comment by SDXC** [comment]
It works fine for me. Which title are you trying to download?

**Comment by lordzidiousback** [comment]
demarcate the cf bypass do the bypass url save inmeditle restart FMD and check

**Comment by knight109** [comment]
It fixed now. I just make DisableCloudflareBypass to false and it worked. 
The last time i need to make it enable and have the BypassURL filled.
