### ISSUE TITLE
Can't download [MangaRock]

### ISSUE THREAD

**Issue by sadeghp88** [fmd-project-team/FMD#362]
![111](https://user-images.githubusercontent.com/28827241/61589518-3606da00-abc0-11e9-920a-19d7ad7f69fd.png)

the same error for 
https://mangarock.com/manga/mrs-serie-100262466
https://mangarock.com/manga/mrs-serie-254590
https://mangarock.com/manga/mrs-serie-100118472
https://mangarock.com/manga/mrs-serie-100205100
https://mangarock.com/manga/mrs-serie-200085062

**Comment by knight109** [comment]
not a developer, but im fine with downloading those.

**Comment by Tmp341** [comment]
There is a region (actually country) lock for some mangas, mangarock api doesn't let you download it. 

For example, US: https://api.mangarockhd.com/query/web401/license?msid=71&country=United%20States

**Comment by sadeghp88** [comment]
only some chapters of these mangas doesn't downloaded and show this error!
![111](https://user-images.githubusercontent.com/28827241/61591626-08308e00-abde-11e9-8097-63cf17e023ad.png)

**Comment by Tmp341** [comment]
Which chapters specifically?

**Comment by Tmp341** [comment]
18 days passed and no answer given, so closing this for now. If you want to share mor info etc, feel free to reopen it.
