### ISSUE TITLE
Chapter download doesn't work [TumangaOnline]

### ISSUE THREAD

**Issue by lordzidiousback** [fmd-project-team/FMD#366]
again whe cant download from tmofan i do everyting posible to treat to work but dont maybe is de page have cloudflare again

**Comment by SDXC** [comment]
It works fine for me. Which title are you trying to download?

**Comment by lordzidiousback** [comment]
no today is workin ahi dont now what happen whit download yesterday not working today is wortking maybe the site

**Comment by lordzidiousback** [comment]
you can close the issue now is work fine
