### ISSUE TITLE
no image in the manga information [Kombatch]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#370]
Thank you before, for adding the website.
and at the time I tried it there was no picture in the manga information even though on the website there was.

**Comment by MIRVOUS** [comment]
![Capture1](https://user-images.githubusercontent.com/45929526/61700920-7bb1d700-ad67-11e9-8866-8c5dc9644f30.PNG)
![Capture2](https://user-images.githubusercontent.com/45929526/61700925-7c4a6d80-ad67-11e9-9518-f3407787ea97.PNG)

**Comment by Slasar41** [comment]
The cover from the website is .webp format and FMD only support the conversion part.

**Comment by MIRVOUS** [comment]
sorry, what is conversion part

**Comment by Slasar41** [comment]
In "Save to" there's an option to convert WebP to others format, that's it.
All the images from KoMBatch is in .webp format.
FMD doesn't support showing .webp cover yet.

**Comment by MIRVOUS** [comment]
okay, thanks. i will wait to FMD support that
