### ISSUE TITLE
Chapter download not working because of re:captcha [KissManga]

### ISSUE THREAD

**Issue by ayanamichie** [fmd-project-team/FMD#374]
seems that kissmanga have recaptcha timeout about 10~15 seconds, there any way to fix/bypass  this?

**Comment by SDXC** [comment]
Recaptcha can only be bypassed by manually doing the cloudflare bypass (Browser F12, putting the needed values into FMD, etc.)

**Comment by ayanamichie** [comment]
yeah even then that a timeout, i think something between 1~2 minutes.

**Comment by SDXC** [comment]
Still a problem or working again?

**Comment by ayanamichie** [comment]
not sure, problaby not, i have not download anything from kissmanga theses days. no chapter releases XD
just did access their site and not asking recaptcha so its fine me thinks.
