### ISSUE TITLE
Website doesn't work [TuMangaOnline]

### ISSUE THREAD

**Issue by akir42019** [fmd-project-team/FMD#375]
Today I stop recognizing the links.
Stopped working before the update from Release: 0.9.165.0 to Release: 0.9.165.0

**Comment by horacio881** [comment]
same problem, downloads do not work and check new chapters either. I'm using the version 0.9.166.1

**Comment by lordzidiousback** [comment]
same error

**Comment by AbidZakaria** [comment]
@SDXC cf_bypass can't get cookie and user agent TuMangaOnline

work with manual get cookie and useragent

**Comment by djgerman10** [comment]
your manga is not online with the new update.

![1](https://user-images.githubusercontent.com/48584512/61946986-64970300-af7a-11e9-9b00-55e0a1a3a628.png)

![2](https://user-images.githubusercontent.com/48584512/61947000-6c56a780-af7a-11e9-9d58-4e55d1d8e27f.png)

![3](https://user-images.githubusercontent.com/48584512/61947016-737db580-af7a-11e9-8e3d-cf4bfa84b8c5.png)

**Comment by SDXC** [comment]
TMOFans configured Cloudflare with http instead of https, so cf_bypass couldn't resolve the challenge. I fixed the url in the lua script and it should work now. You have to clear/disable the cookies/user agent in your advanced settings if you used the manual workaround.

**Comment by djgerman10** [comment]
![z](https://user-images.githubusercontent.com/48584512/61948573-88f4de80-af7e-11e9-9db6-cb6fc5c90137.png)

![zz](https://user-images.githubusercontent.com/48584512/61948588-96aa6400-af7e-11e9-8162-6ab36d353262.png)

![zzz](https://user-images.githubusercontent.com/48584512/61948599-9dd17200-af7e-11e9-9289-864dbb1542ad.png)

![zzzz](https://user-images.githubusercontent.com/48584512/61948623-afb31500-af7e-11e9-9b57-353f3b9eaede.png)


It doesn't go.

with manual proxy and neither walked.
deactivate the bypass and neither walked.

**Comment by SDXC** [comment]
@djgerman10 what are your advanced website settings of tumanga? cf_bypass must be enabled for tumanga otherwise it won't work.

**Comment by angeltonio** [comment]
Still not working...I activated all, and nothing...

**Comment by angeltonio** [comment]
@SDXC where can i do this.. "You have to clear/disable the cookies/user agent in your advanced settings if you used the manual workaround"

**Comment by SDXC** [comment]
"Clear" means it has to look like this before you try it again:

![grafik](https://user-images.githubusercontent.com/5290260/61976581-6dc0b800-afec-11e9-9e56-8f6efa72070a.png)

**Comment by angeltonio** [comment]
Thanks a lot...work now!!!!...

**Comment by djgerman10** [comment]
He is back, thank you very much.
I don't know why when I had updated it today when the new module just came out it didn't go.

sorry for my English. greetings from Argentina

**Comment by angeltonio** [comment]
it's not working again...something happens??
