### ISSUE TITLE
Problems with de info of chapters TuMangaOnline

### ISSUE THREAD

**Issue by angeltonio** [fmd-project-team/FMD#377]
For a few days he has not loaded the information of the manga of the page of tumangonline, like boruto, and others ..

**Comment by Tmp341** [comment]
See [#375](https://github.com/fmd-project-team/FMD/issues/375#issuecomment-515335121)

**Comment by angeltonio** [comment]
It's not working...

**Comment by SDXC** [comment]
https://github.com/fmd-project-team/FMD/issues/375#issuecomment-515575862
