### ISSUE TITLE
BacaManga - not working

### ISSUE THREAD

**Issue by ChocolateOtaku** [fmd-project-team/FMD#38]
The "Update Manga" command is not working, list is still empty after update...

**Comment by MIRVOUS** [comment]
i think it is still work

![fmd 8](https://user-images.githubusercontent.com/45929526/55660844-8a18c900-5832-11e9-9b77-88453990e90a.PNG)

**Comment by MIRVOUS** [comment]
![fmd9](https://user-images.githubusercontent.com/45929526/55661077-ed572b00-5833-11e9-9fe6-640e461f5261.PNG)

**Comment by MIRVOUS** [comment]
![fmd10](https://user-images.githubusercontent.com/45929526/55661112-1d9ec980-5834-11e9-8331-c2fe6bccca7a.PNG)

**Comment by ChocolateOtaku** [comment]
Maybe region locked?

![image](https://user-images.githubusercontent.com/38581381/55661197-abfe5580-580a-11e9-8293-33dcaf382bfd.png)

**Comment by Tmp341** [comment]
I guess there are some region locks for some certain sites, because i can't reach them too.

**Comment by ChocolateOtaku** [comment]
I can also reach the website, but not the manga list:
https://bacamanga.web.id/manga

**Comment by Tmp341** [comment]
Let me check that again from FMD.

**Comment by AbidZakaria** [comment]
![Screenshot_20190406-143028](https://user-images.githubusercontent.com/19544118/55666397-ac353a00-5878-11e9-9d31-01f137a3fc7d.png)

It's work

**Comment by Tmp341** [comment]
> 
> 
> ![Screenshot_20190406-143028](https://user-images.githubusercontent.com/19544118/55666397-ac353a00-5878-11e9-9d31-01f137a3fc7d.png)
> 
> It's work

Website works, and i can reach it on browser. but i can't download mangalist on FMD.

**Comment by SDXC** [comment]
The manga list and the image filelinks are region locked. I can navigate through the mangas and open chapters, but the images won't load.

Can someone who isn't locked out make a final test if FMD works with that website?
If it works, then this issue should be closed, as it is not an FMD thing anymore.

**Comment by riedhows** [comment]
bacamanga work fine
![Untitled](https://user-images.githubusercontent.com/35851136/55668637-db5aa400-5896-11e9-97bd-f7c75c215cc9.png)

**Comment by SDXC** [comment]
Thanks for testing this.
@ChocolateOtaku I'll close this ticket. You can re-open this issue if there's a need for that.
