### ISSUE TITLE
Can't download chapters [TuMangaOnline]

### ISSUE THREAD

**Issue by alexl25** [fmd-project-team/FMD#381]
Hello,
The list of the mangas is correctly downloaded, but the chapters didn't appear.

![chapters](https://user-images.githubusercontent.com/53397794/62005754-26dfd900-b138-11e9-8a20-09f45ca165cd.png)

Also I checked and in Advance settings is everything disabled, as is explained in #375 
![disabled](https://user-images.githubusercontent.com/53397794/62005767-5bec2b80-b138-11e9-9c45-f191155637b5.png)

Also I tried to redownload the modules and download FMD again.
There are a workarount to fix it? 

Big thanks!

**Comment by SDXC** [comment]
It works for me. Is it still a problem for you?

**Comment by alexl25** [comment]
Yes, still happening. Try to redownload the fmd, and still happening.

**Comment by SDXC** [comment]
Do you use a VPN or Proxy?

**Comment by alexl25** [comment]
No

**Comment by SDXC** [comment]
Can you open the website?

**Comment by alexl25** [comment]
Yes

![tmofans](https://user-images.githubusercontent.com/53397794/62151214-18dcb480-b300-11e9-81fb-a0f576e683e9.png)

**Comment by SDXC** [comment]
Please zip your FMD folder (without the downloads) and upload it somewhere so I can check if it's your settings something else.

**Comment by SDXC** [comment]
Did you have to resolve a captcha when opening Tumanga? Do you have to solve a captcha when you clear the cookies in your browser?

FMD can't bypass captchas, so you'd have to do the manual workaround by putting the user agent and cookies in the advanced website settings by yourself.

**Comment by syleniaa** [comment]
Hi, i downloaded the last release of FDM (fmd_0.9.166.1) and TuMangaOnline does not appear?? 
![Image 2](https://user-images.githubusercontent.com/16405194/62299042-cacbcc00-b439-11e9-8441-b4e5575309da.png)
![Image 3](https://user-images.githubusercontent.com/16405194/62299043-cacbcc00-b439-11e9-8dca-c6330d753692.png)

**Comment by SDXC** [comment]
@syleniaa The lua modules aren't present. You have to let FMD download them, otherwise it will never be added to the list. Go to the Modules tab and check for updates.

**Comment by SDXC** [comment]
@alexl25 Do you have a proxy configured in FMD?

**Comment by syleniaa** [comment]
> 
> 
> @syleniaa The lua modules aren't present. You have to let FMD download them, otherwise it will never be added to the list. Go to the Modules tab and check for updates.

thnks, i forgot to configure my proxy , and now it show me all the availables modules

**Comment by syleniaa** [comment]
tumangaonline it's now in the list but now it happening the same thing that happened to alexl25. The chapters of any manga doesn't show

**Comment by syleniaa** [comment]
> 
> 
> Did you have to resolve a captcha when opening Tumanga? Do you have to solve a captcha when you clear the cookies in your browser?
> 
> FMD can't bypass captchas, so you'd have to do the manual workaround by putting the user agent and cookies in the advanced website settings by yourself.

i cleared the cookies of my browser and opened TuMangaOnline, i did not have to solve the captcha, the website opened normally. for my intenet connection i use a proxy and i configured it in fdm but always worked ok, until this tuesday , that TuManga stoped working and i updated the app, but any other site works ok

**Comment by SDXC** [comment]
Does Tumanga work with the older version 0.9.165.0?
Do you need the proxy or can you test it without proxy?

**Comment by syleniaa** [comment]
i don't have that version , the last one that i used was 0.9.158.0
 from https://github.com/riderkick/FMD , then when Tumanga stoped working someone gave the link of this fork in the related issue. yeah i need proxy because we had to use at work for internet connection

**Comment by SDXC** [comment]
I guess you have the proxy configured in FMD, not on the system, right?

Do other websites work (probably test MangaDex)?

**Comment by syleniaa** [comment]
i have it configured in FDM. MangaDex works alright, i tested it right now.

**Comment by SDXC** [comment]
Okay, then the problem is probably that cf_bypass which bypasses Cloudflare doesn't work with proxies. The dev of the scraping script behind cf_bypass has implemented a proxy parameter, so I will try to implement it with the next version. For now either don't use a proxy (which is not possible it seems) or do the manual workaround. You can find 3 examples in the wiki.

**Comment by syleniaa** [comment]
i will search it , thnks

**Comment by syleniaa** [comment]
it worked! i configured the cookies and user agent for tumanga an dno wit show me the manga and chapters , now i will try downloading something. thnks

**Comment by syleniaa** [comment]
sorry, i don't know but it only worked for some mangas, others shows nothing and i searched them in the web and it have chapters

**Comment by SDXC** [comment]
please provide some examples so i can check if it's a general problem or only for you.

**Comment by syleniaa** [comment]
look i select some random mangas, one of them shows the info and chapters and the other shows nothing but behind you can see in the browser that the manga does have chapters. i don't now why but it is completely random, i just started selecting and ones work and others don't. but i saw that the ones that doesn't work shows me the cloudfare bypass page again and the ones that works doesn't show it

**Comment by SDXC** [comment]
tumanga seems to have a pretty aggressive CF setting or it doesn't like your proxy....

**Comment by syleniaa** [comment]
what it's getting me crazy it's that tumanga worked great untild 3 days ago and i don't get why is havin gproblems now

**Comment by djgerman10** [comment]
not going [TuMangaOnline]



![1](https://user-images.githubusercontent.com/48584512/62789863-3ba95e80-baa0-11e9-8468-75cdad57d11f.png)

![2](https://user-images.githubusercontent.com/48584512/62790136-d86bfc00-baa0-11e9-9b89-1588695e88a1.png)

**Comment by ZeroCool940711** [comment]
Hi guys, im having troubles with TuMangaOnline too, it was working before the last update, right after the update I tried downloading from TuMangaOnline and its not working anymore, all other sites work correctly including TMOHentai which is made by the same people as TuMangaOnline (aka TmoFans). I dont get any captcha when I access the website on the browser and I've tried clearing my cookies and also with multiple browsers. I think it might be a problem with redirects, before the url was `http://tumangaonline.com` and now it is `https://tmofans.com`, when you try to access `tumangaonline.com` it redirects you to `tmofans.com`, also could be a problem with HTTPS, before it was just using HTTP and now it is using HTTPS.
![image](https://user-images.githubusercontent.com/5977640/62816819-9ca55680-bae1-11e9-9939-206e66a93d36.png)

**Comment by SDXC** [comment]
@ZeroCool940711 do you use a proxy?

**Comment by ZeroCool940711** [comment]
@SDXC I don't use a proxy, and as I said before it was working correctly before the latest update.

**Comment by SDXC** [comment]
From which version did you update? It looks to me you made an upgrade from riderkick's version. The url of Tumanga had already been changed as of 0.9.158.0.

Can you please test the following versions:
0.9.156.0 from riderkick
0.9.158.0 from riderkick
0.9.165.0
0.9.166.1 (latest)

Please note which version worked and which had problems. Also please use the same manga to test it.

**Comment by syleniaa** [comment]
The last one I used was  0.9.158 from Roderick, it was working fine until one day and the I downloaded the release 0.9.166.1 from fdm-project-team and it gave me the same error. I will try other versions Enviado desde mi Honor 8X-------- Mensaje original --------Asunto: Re: [fmd-project-team/FMD] Can't download chapters [TuMangaOnline] (#381)De: SDXC Para: fmd-project-team/FMD CC: syleniaa ,Mention From which version did you update? It looks to me you made an upgrade from riderkick's version. The url of Tumanga had already been changed as of 0.9.158.0.
Can you please test the following versions:
0.9.156.0 from riderkick
0.9.158.0 from riderkick
0.9.165.0
0.9.166.1 (latest)
Please note which version worked and which had problems. Also please use the same manga to test it.
