### ISSUE TITLE
Download doesn't work [UnionMangas]

### ISSUE THREAD

**Issue by formigao** [fmd-project-team/FMD#382]
please update for the new domain

**Comment by SDXC** [comment]
has been fixed.

**Comment by formigao** [comment]
> has been fixed.

just updated here domain is fixed but still cant load manga info.

the issue must be more complex.

**Comment by Slasar41** [comment]
I can load manga info and download the manga just fine.
![image](https://user-images.githubusercontent.com/28888646/62024381-f747d400-b1fe-11e9-98d4-9d6cc75ee6a2.png)
![image](https://user-images.githubusercontent.com/28888646/62024425-1e060a80-b1ff-11e9-95ca-1260c1d52676.png)
Make sure the advanced settings for the website is empty like this
![image](https://user-images.githubusercontent.com/28888646/62024474-4c83e580-b1ff-11e9-92df-51b961b3ed91.png)

**Comment by formigao** [comment]
only thing i had up was tcloudflarebypass

disabled it and now its working
