### ISSUE TITLE
Remove delay between chapter downloads [MangaHere]

### ISSUE THREAD

**Issue by Anvesh2013** [fmd-project-team/FMD#389]
![Screenshot (39)](https://user-images.githubusercontent.com/10322605/62259888-83d7d980-b42d-11e9-89e9-03a308003d04.png)

The download speed plot and the status, clearly show, when we are moving to a new chapter, the speed drops to 0 completely, and I guess new info is scraped and then the speed goes up. This happens to every chapter. Isn't there anyway, the delay could be minimized or even eliminated?

If it is scraping, why not do it concurrently with the previous chapter download. Or is it actually doing that in the background but the download speed is not reflecting it?

**Comment by Slasar41** [comment]
The code in MangaHere.lua implemented delay 3 seconds each chapter. If there's no delay, the download can be corrupted. Long time ago I also use MangaHere.

**Comment by SDXC** [comment]
Like @Slasar41 just mentioned, it is an intended setting for MangaHere and won't be changed for now.
