### ISSUE TITLE
Crash when updating manga list [ReadComicOnline]

### ISSUE THREAD

**Issue by Arrow-x** [fmd-project-team/FMD#398]
failed to execute 267
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.166.1
Product Version   : Win64
Host Machine      : Windows 7 64-bit
FPC Version       : 3.0.4
LCL Version       : 1.8.4.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2019/07/26 03:39:08
Path              : E:\• Net\Software\fmd_0.9.166.1_Win64\fmd.exe
Process ID        : 103856
MainThread ID     : 105000
Thread ID         : 102096
Time              : 03-08-2019 15:43:46.938
Sender Class      : TUpdateListThread
Exception Class   : EProcess
Message           : Failed to execute  : 267

  Website : ReadComicOnline
  CS      : CS_DIRECTORY_COUNT

  $0000000100144634
  $000000010046359B
  $000000010046592B
  $0000000100282D98
  $00000001000542ED
  $0000000100003B96
  $0000000100015067
  $000000007728652D
  $00000000773BC521

**Comment by SDXC** [comment]
1.) At which point did that error occur? Before update, while updating or after updating at the end?

2.) Please fix your installation path so it doesn't have any UTF-8 characters in it and try again:
> E:\• Net\Software\fmd_0.9.166.1_Win64\fmd.exe
