### ISSUE TITLE
Error ar line 1, Pos -9217184:Unexpected EOF encountered

### ISSUE THREAD

**Issue by PanzerIVF** [fmd-project-team/FMD#41]
I was trying to open FMD and I go this error

![fmd_2019-04-06_12-25-44](https://user-images.githubusercontent.com/22032292/55667079-f1aa3500-5881-11e9-92cb-43f09146f010.png)

Can someone help me what the problem?? And what solution that I need to do?

**Comment by AbidZakaria** [comment]
Try fresh install
Please read
https://github.com/fmd-project-team/FMD/wiki#fresh-install

**Comment by PanzerIVF** [comment]
Thanks!
