### ISSUE TITLE
View history of downloaded manga

### ISSUE THREAD

**Issue by komaedalove** [fmd-project-team/FMD#412]
I would like to view all the manga I downloaded through this app. I can see some URLs in /works/downloadedchapters.db but it's very hard to read.
![Screenshot - 2019-08-09 , 04_28_55](https://user-images.githubusercontent.com/52548608/62749842-43481380-ba5e-11e9-8d14-8220e8ad3579.png)

**Comment by Tmp341** [comment]
I suggest you use an app, like [DB Browser for SQLite](https://sqlitebrowser.org/), there is a portable build, so you don't need to install.

**Comment by SDXC** [comment]
Like Tmp341 suggested, use a tool to get a table view of the file.
FMD only tracks the urls and names of the titles/chapters that you have downloaded, but it doesn't track when you downloaded these, etc.

A history feature will not be implemented. You can use the downloads tab (using downloads.db) as a history of your downloaded content if you don't delete the entries of course.
