### ISSUE TITLE
Website redirects to Komiku [OtakuIndo]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#416]
https://komiku.co/
when I opened the otakuindo website and was diverted to Komiku

**Comment by SDXC** [comment]
I can't test it because of Region Lock.
@AbidZakaria Can you verify this? If OtakuIndo redirects to Komiku, we'll remove OtakuIndo from FMD.

**Comment by MIRVOUS** [comment]
if you are going to get rid of OtakuIndo. Can you fix the Komiku website. because there is an error like this :
![Capture](https://user-images.githubusercontent.com/45929526/62912613-23dd1d80-bdb3-11e9-984c-cdbf6a211a91.PNG)
![Capture2](https://user-images.githubusercontent.com/45929526/62912614-23dd1d80-bdb3-11e9-8ee4-6fdc7db8359d.PNG)

**Comment by SDXC** [comment]
merged. thanks @AbidZakaria
