### ISSUE TITLE
Some titles are only available through second domain [Mangazuki]

### ISSUE THREAD

**Issue by traitorAIZEN** [fmd-project-team/FMD#417]
Something's wrong here.

Example: I downloaded "Lust Awakening" (https://www.mangazuki.online/manga/lust-awakening/) successfully but when i tried downloading "Close as Neighbors" (https://www.mangazuki.online/manga/neighbors-close/)(FMD url), it just creates empty folders. 

I pasted the url from the fmd to the browser but it becomes (https://www.mangazuki.site/manga/close-as-neighbors/). It redirects to ".site", and when i tried pasting this url in fmd i get a "URL not supported!" error.

What's more, while i was in the "Lust Awakening" page (https://www.mangazuki.online/manga/lust-awakening/), when i searched for "Close as Neighbors" it redirects me to that ".site" right? But when i tried searching "Lust Awakening" from that page (https://www.mangazuki.site/manga/close-as-neighbors/), i get a "No manga found". Like wtf? Are these two really the same site? Maybe that's why fmd can't fetch the images.

Or if i'm doing something wrong, please correct me.

**Comment by SDXC** [comment]
The thing is, that some titles are only available through .site and other only through .online

FMD currently supports only one domain because nobody knew about that until now. I will add the other domain as well (as MangaZukiSite), so both can be used.

**Comment by SDXC** [comment]
Site added.
