### ISSUE TITLE
Website and URL changed [HeavenManga]

### ISSUE THREAD

**Issue by KucingCyber** [fmd-project-team/FMD#42]
i have a problem here,
it seems heaven manga move their site from [heavenmanga.ca](url) to [heavenmanga.vip](url)
can you fix this?
thank you in advance & sorry for my bad English,

**Comment by AbidZakaria** [comment]
Ok, i Will fix it

**Comment by KucingCyber** [comment]
Thank you very much

**Comment by SDXC** [comment]
Merged the fix from @AbidZakaria 

@KucingCyber Please start FMD, update the lua files (dialog should prompt) and try again with HeavenManga. Give us feedback.

**Comment by KucingCyber** [comment]
It's functioned properly now, thank you very much
