### ISSUE TITLE
Favorites counter don't update correctly

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#423]
not realy show the number of Manga's Enabled or desabled :
![Capture3](https://user-images.githubusercontent.com/45929526/62916742-e339d000-bdc3-11e9-9e45-b812e2ac244a.PNG)

**Comment by MIRVOUS** [comment]
in that picture i have 7 dasabled manga's but in in the number is zero/Disabled(0)

**Comment by Slasar41** [comment]
I think that's a bug.
The number should show how many title got disabled.

**Comment by SDXC** [comment]
Currently the numbers are only updated when adding/removing an entry or on FMD startup.
Disabling/Enabling doesn't change the count.

**Comment by SDXC** [comment]
fixed. Wait for release.

**Comment by SDXC** [comment]
Free Manga Downloader (0.9.167.0) has been released.
