### ISSUE TITLE
Latest chapter sometimes not listed [MangaRock]

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#434]
I just realize something.
I visited Mangarock to search a manga and then i saw Kurosagi and Enami-kun wa Ikiru no ga tsurai have a new chapter, so i update my Favorites list but i got no update for them. I also check manually but still the same, no update.
And then i try random manga in the site that newly updated, and when i check in FFMD they're all doesnt get new chapter.

Does this intentional or something?

**Comment by SDXC** [comment]
MangaRock has an API for manga/chapter info. FMD uses this API. It's possible that the API is takes a few minutes/hours until it's being updated. Until then FMD can't see the new chapters. Currently the latest chapters for your mentioned titles are listed now.

**Comment by knight109** [comment]
Okay thanks
