### ISSUE TITLE
Error when trying to update FMD [0.9.160.0 -> 0.9.161.0]

### ISSUE THREAD

**Issue by Owyn** [fmd-project-team/FMD#44]
![изображение](https://user-images.githubusercontent.com/1309656/55673197-34cdcd80-58ad-11e9-8e30-df9b1f7082bf.png)

**Comment by AbidZakaria** [comment]
Using manual update

**Comment by Tmp341** [comment]
There was a problem with the updater, you cant update from ``0.9.160.0`` to ``0.9.161.0``. Download it manually.

**Comment by SDXC** [comment]
@Owyn Were you able to do the manual update to 0.9.161.0 or even better to 0.9.162.0?
