### ISSUE TITLE
Download doesn't work [WebToons]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#440]
i tried to download a manga in webtoon. but the download is fail. this result:
![Capture](https://user-images.githubusercontent.com/45929526/63334129-ec4b1400-c364-11e9-9b98-f961037ca6f7.PNG)
i tried on browser and it work.
![Capture4](https://user-images.githubusercontent.com/45929526/63334265-4350e900-c365-11e9-881c-a190fc4660b2.PNG)

**Comment by Tmp341** [comment]
> 07:49:32:837 INFO: Running cf_bypass for website: [WebToons]
08:32:47:561 WARNING: TTaskThread, checkforfinish failed=1/1 [WebToons]"Ghost Path" > "/id/horror/guidao/prolog/viewer?title_no=874&episode_no=1"
W
08:32:47:561 WARNING: TTaskThread, download failed. "Ghost Path" "Prolog" "/id/horror/guidao/prolog/viewer?title_no=874&episode_no=1"
08:32:51:066 WARNING: TTaskThread, checkforfinish failed=1/1 [WebToons]"Ghost Path" > "/id/horror/guidao/prolog/viewer?title_no=874&episode_no=1"
W
08:32:51:066 WARNING: TTaskThread, download failed. "Ghost Path" "Prolog" "/id/horror/guidao/prolog/viewer?title_no=874&episode_no=1"
08:32:54:571 WARNING: TTaskThread, checkforfinish failed=1/1 [WebToons]"Ghost Path" > "/id/horror/guidao/prolog/viewer?title_no=874&episode_no=1"
W
08:32:54:571 WARNING: TTaskThread, download failed. "Ghost Path" "Prolog" "/id/horror/guidao/prolog/viewer?title_no=874&episode_no=1"
08:32:57:576 WARNING: TTaskThread, checkforfinish failed=1/1 [WebToons]"Ghost Path" > "/id/horror/guidao/prolog/viewer?title_no=874&episode_no=1"
W
08:32:57:576 WARNING: TTaskThread, download failed. "Ghost Path" "Prolog" "/id/horror/guidao/prolog/viewer?title_no=874&episode_no=1"
