### ISSUE TITLE
Can't download chapters [TuMangaOnline]

### ISSUE THREAD

**Issue by elvis5656** [fmd-project-team/FMD#442]
Cant download new chapters
![Capturaffff](https://user-images.githubusercontent.com/53345396/63474641-82ec0380-c43f-11e9-863a-0e9a3a11316b.PNG)

**Comment by akir42019** [comment]
I can't download pages in new chapters

Bokutachi ga Yarimashita cap 30 pag 7
https://lectormanga.com/viewer/5d576e055bcd3/paginated/7

fake https://statics.tmofans.com/uploads/5d576e055bcd3/d11a64d5.jpg
correct https://statics.tmofans.com/uploads/5d576e055bcd3/d11a64da.jpg

**Comment by akir42019** [comment]
01:38:30:935 WARNING: TTaskThread, download failed. "Bokutachi ga Yarimashita" "Capítulo 030.00  Yangu-san [Ravens Scans]" "/goto/419232"
01:38:35:277 WARNING: TTaskThread, checkforfinish failed=2/20 [Tumangaonline]"Bokutachi ga Yarimashita" > "/goto/419232"
https://statics.tmofans.com/uploads/5d576e055bcd3/d11a64d5.jpg

**Comment by SDXC** [comment]
Go through that issue: https://github.com/fmd-project-team/FMD/issues/381

Until next version of FMD you have to do the manual Cloudflare workaround or check your settings/connections.

**Comment by elvis5656** [comment]
I can do the manual Cloudflare workaround
![Capturahhdh](https://user-images.githubusercontent.com/53345396/63523518-e61d7a80-c4bf-11e9-8697-62ddd9f62c88.PNG)

**Comment by rs3mk** [comment]
It is not a problem of cf.

Pages are downloaded but not all, from 30 it is downloaded 25/29

![23-26](https://user-images.githubusercontent.com/19628943/63524564-d7d05e00-c4c1-11e9-9192-dd676a0dfa65.png)

**Comment by elvis5656** [comment]
Yes @rs3mk, same problem
