### ISSUE TITLE
Can't download specific manga [MangaHere]

### ISSUE THREAD

**Issue by Geese1** [fmd-project-team/FMD#443]
Been trying to download 6 chapters from MangaHere that I haven't found anywhere else on the web, and every time I keep getting an error message after the downloads (supposedly) complete.

I understand, reading the support pages here, that there's a delay in downloading from the site that's built into the program, but my problem is even after they downloads supposedly finish I get the red bar saying there was a problem and to retry, and when I check my folder during the download process it doesn't seem like anything is actually downloading.

Is there an issue with this, or am I doing something wrong?

**Comment by Slasar41** [comment]
What manga?

**Comment by Geese1** [comment]
The last 6 chapters (Volume 7) of Hiiragi Shougakkou Renai Kurabu. I'd like to finish reading it, but the last volume is being really difficult to find. There is a torrent out there, but it's apparently been dead for some time, and I haven't found these chapters on any other reader site so far.

**Comment by Slasar41** [comment]
Same I can't download it too.
I tried to find on different websites but nothing past Vol. 6...

**Comment by Geese1** [comment]
Thanks for checking. I've spent the past half hour or so going to various websites on the supported websites page here, looking to see if anyone else had the chapters, but I didn't have any luck either.

I've had the torrent running for a little over 9 weeks at this point, but as others have said, still no movement. I'll keep it going though, as I once had a torrent take something like a year or two to finally start seeding, so I'll keep hoping this one starts moving as well.

Ideally though, I could just download the chapters from MangaHere. ;)

**Comment by Slasar41** [comment]
How do you read it on the website?
I stuck on this:
![image](https://user-images.githubusercontent.com/28888646/63529600-1d774000-c52f-11e9-9ec4-4047e1c20b9f.png)
Even though I already click this before clicking the chapter:
![image](https://user-images.githubusercontent.com/28888646/63529644-308a1000-c52f-11e9-875d-f6737325461a.png)

**Comment by Geese1** [comment]
Don't know; that's as far as I get. Wasn't sure if you needed to have an account or something, although I think I tried a different series and was able to see it without any issue?

**Comment by SDXC** [comment]
As this is not an FMD issue, I'll close it. If you want to discuss this any further, you can continue on the Discord server.
