### ISSUE TITLE
Problem when downloading mangas with too long names

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#445]
download without chapter number.

when downloading always puts the same name, does not put chapter number.
replace the same cap always.

[http://es.ninemanga.com/manga/Life+as+a+Reincarnated+Sage+in+Another+World+%7EGaining+a+Second+Profession+and+Becoming+the+Strongest+in+the+World%7E.html](http://es.ninemanga.com/manga/Life+as+a+Reincarnated+Sage+in+Another+World+%7EGaining+a+Second+Profession+and+Becoming+the+Strongest+in+the+World%7E.html)

![1](https://user-images.githubusercontent.com/48584512/63575592-cf7b3000-c560-11e9-9506-f3b96239b2ca.png)

![2](https://user-images.githubusercontent.com/48584512/63575607-d73ad480-c560-11e9-83ef-5e7289ac8044.png)

**Comment by SDXC** [comment]
Same problem: https://github.com/fmd-project-team/FMD/issues/155
