### ISSUE TITLE
New manga are not marked [HentaiHere]

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#446]
Every new manga that i get after uploaded get mark/color, for me is purple.\
But only on HentaiHere that color doesnt appear at all.

I dont know if FDM doesnt update the manga list or what, but all i know, it probably do it, since i can download from HentaiHere, i just dont get the new manga mark.

**Comment by Tmp341** [comment]
Have you backed up ``HentaiHere.db``, deleted it and updated it via ``Update mangalist`` feature?

**Comment by SDXC** [comment]
Mangas with status "Completed" have a different color higher priority over new entries. Only "Ongoing" titles are marked as new.

**Comment by knight109** [comment]
I think Mangas with status "Completed" have same priority with new mangas. It give me Purple color rather than Light-Green for usual "Completed" list when this happen.

After i delete the data and update it, i can search by "Search only new manga" from filter.
All completed manga that is new is on purple and all new manga that is "Ongoing" is on red.

I think the problem fix.
Gonna post it again if i got another problem. Thanks a lot guys.
