### ISSUE TITLE
Can't get manga info [Toonkor]

### ISSUE THREAD

**Issue by mastercheat001** [fmd-project-team/FMD#447]
[https://i.imgur.com/rYuQhsM.png](url)

**Comment by SDXC** [comment]
This is a problem on your side. It works perfectly fine on my end. Please check your advanced website settings and reset all values in there. Also make sure you use the latest version of FMD.

**Comment by mastercheat001** [comment]
Well the site did change from .guru to .id. So it doesnt work now.

**Comment by SDXC** [comment]
This should be fixed with the pull request of Slasar41.
I'll close this issue. If you still have issues, feel free to re-open it.
