### ISSUE TITLE
Add support for website [MangaHost]

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#448]
add site portugues MangaHosted
[https://mangahosted.com/](https://mangahosted.com/)

_Please add this site, there are very few Portuguese pages._

**Comment by SDXC** [comment]
If I have time on the weekend, I'll probably add this website.

**Comment by djgerman10** [comment]
Great, I will look forward to it.

Thank you very much for your great work SDXC

**Comment by SDXC** [comment]
Website has been added. Manga list is currently running and will be uploaded a bit later today.
