### ISSUE TITLE
Updated Spanish Localization

### ISSUE THREAD

**Issue by Mariolr93** [fmd-project-team/FMD#451]
Hi!
Here I leave a revised and updated version of the Spanish Localization.
I don't know who updated the translation before, but I noticed some spell errors and some missing lines.
And I was who translated FMD to spanish first.

Hope you can include it in the next update.

[fmd.es.zip](https://github.com/fmd-project-team/FMD/files/3540467/fmd.es.zip)

**Comment by Tmp341** [comment]
Please add it via code editing : Fork it first or just click edit [this](https://github.com/fmd-project-team/FMD/blob/master/languages/fmd.es.po) file.
