### ISSUE TITLE
Descriptions font changed by non-standard characters

### ISSUE THREAD

**Issue by Vantageright** [fmd-project-team/FMD#452]
A mangas description after characters like 『 』found in [this manga](https://mangadex.org/title/28920/arafoo-kenja-no-isekai-seikatsu-nikki) will change the entire descriptions font.

**Comment by Slasar41** [comment]
Looks fine for me.
![image](https://user-images.githubusercontent.com/28888646/63714729-9ac2ed80-c86c-11e9-9cb1-56d693d96416.png)

**Comment by Vantageright** [comment]
What I see. 
![image](https://user-images.githubusercontent.com/28931479/63714959-b6150500-c83a-11e9-96ca-0073100e7aed.png)

**Comment by Slasar41** [comment]
Maybe because I use Japan locale.

**Comment by Tmp341** [comment]
No problem at all here, im using Turkish locale.

Same with English locale.
![ssss](https://user-images.githubusercontent.com/1683388/63719758-56c4ee00-c856-11e9-9c19-c5d52fb9117d.jpg)

**Comment by SDXC** [comment]
@Vantageright Do you have any special formatting settings in FMD or on the OS level?

**Comment by Vantageright** [comment]
No and none that I'm aware of. I've got no need or want for them.

**Comment by SDXC** [comment]
Which OS are you using?

**Comment by Vantageright** [comment]
W7 pro x64
