### ISSUE TITLE
Mangadex only one simultaneous download at a time?

### ISSUE THREAD

**Issue by limno97** [fmd-project-team/FMD#457]
heya, not sure if its just me. But on my fmd, mangadex only has one download at a time. whereas others like mangarock can download multiple manga at a time. is there a way to fix this?

Also is there like a community for this? like a discord or subreddit. did just find out theres a newer fmd lol

**Comment by rs3mk** [comment]
You can change that, but mangadex can block your ip.

**Comment by limno97** [comment]
i see, better then huh. thanks for the info.

**Comment by Tmp341** [comment]
It is a feature added for not getting banned on Mangadex.

**Comment by SDXC** [comment]
@limno97 In case you didn't find it until now: https://discord.gg/cXKKgw3

**Comment by limno97** [comment]
Oh sick, thanks
