### ISSUE TITLE
Favorite check doesn't work anymore [ReadComicsOnline]

### ISSUE THREAD

**Issue by Clydefrosch22** [fmd-project-team/FMD#46]
Already tried switching repositories and updating, still red bar and showing current chapter as 0.
Reading online works fine.

**Comment by AbidZakaria** [comment]
Please send a screenshot for your problem

**Comment by Clydefrosch22** [comment]
https://imgur.com/BdMFXcH

**Comment by Clydefrosch22** [comment]
I guess I chose the title kind of badly, sorry.
Note that it's not just the favorite check that doesn't work, but manga info tab won't load any info, image or chapter list. Basically, readcomicsonline is broken atm.

**Comment by AbidZakaria** [comment]
ReadComicsOnline adding Cloudflare in website
youmust read this wiki https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation
for your problem

**Comment by AbidZakaria** [comment]
![image](https://user-images.githubusercontent.com/19544118/55678945-a6992c00-592c-11e9-974e-34dde24c3250.png)

![image](https://user-images.githubusercontent.com/19544118/55678936-76ea2400-592c-11e9-9267-08306ed03f2d.png)

![image](https://user-images.githubusercontent.com/19544118/55678931-5a4dec00-592c-11e9-87ae-0845aa5127c4.png)

same issue with https://github.com/fmd-project-team/FMD/issues/2 and https://github.com/fmd-project-team/FMD/issues/47

**Comment by Clydefrosch22** [comment]
I actually did try and follow that workaround before, but without success.
It's still doing the same :/

These are the cookie strings i got.
I will try a few more times, but am i right to assume that even if i got this to work, I'd have to do this again every time? Since cookies aren't very persistent and such?

bbbi=18b6b0c6-a660-4bba-80e1-4f9d515b7601; 
__cfduid=d117c59da441c49491d79e7119560925f1552503394; 
BB_plg=bn|Tn|An|In|pm; 
cf_clearance=6bc8934dd94a3aafb6b04e916e9df49e0bdcee70-1554620954-1800-150; 
_ga=GA1.2.2013503191.1554621560; 
_gid=GA1.2.2044705179.1554621560; 
_gat=1

useragent Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/55.0

**Comment by Tmp341** [comment]
You can access website via browser right?

I think your log might give us some info.

**Comment by AbidZakaria** [comment]
> I actually did try and follow that workaround before, but without success.
> It's still doing the same :/
> 
> These are the cookie strings i got.
> I will try a few more times, but am i right to assume that even if i got this to work, I'd have to do this again every time? Since cookies aren't very persistent and such?
> 
> bbbi=18b6b0c6-a660-4bba-80e1-4f9d515b7601;
> __cfduid=d117c59da441c49491d79e7119560925f1552503394;
> BB_plg=bn|Tn|An|In|pm;
> cf_clearance=6bc8934dd94a3aafb6b04e916e9df49e0bdcee70-1554620954-1800-150;
> _ga=GA1.2.2013503191.1554621560;
> _gid=GA1.2.2044705179.1554621560;
> _gat=1
> 
> useragent Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/55.0

try this https://github.com/fmd-project-team/FMD/issues/61

**Comment by Clydefrosch22** [comment]
Ok, so it seems to be working after all, I guess I was just too slow in copying the strings and putting them in the correct format, so they were already invalid when i tried downloading something.

**Comment by SDXC** [comment]
Thanks for the feedback. I'll close this issue then.

**Comment by Clydefrosch22** [comment]
Ok, tried again today, multiple times, workaround doesn't seem to be working anymore for the site.
