### ISSUE TITLE
Failed to download [MangaShiro]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#460]
when i try to download
 ch. 40 - 44 from manga "Akaaka to Shita Chi no Monogatari" cannot be downloaded.
![fmd1](https://user-images.githubusercontent.com/45929526/64120391-45379500-cdc6-11e9-9ede-db77eb0b39b0.png)

**Comment by AbidZakaria** [comment]
try it in your browser, can it?
some manga can't because the picture isn't on the site

**Comment by Tmp341** [comment]
Those chapters aren't showing on the site iether, got ``We cannot complete this request, remote data could not be fetched`` error.

**Comment by Tmp341** [comment]
Closing this for now, if you have problem even those files are fixed, reopen this issue.

**Comment by MIRVOUS** [comment]
in the browser is completely show the image.
![fmd5](https://user-images.githubusercontent.com/45929526/64326012-629d7680-cff3-11e9-8059-01dc5125ce4f.PNG)

**Comment by Slasar41** [comment]
The issue on Hakuneko has been fixed. https://github.com/manga-download/hakuneko/issues/399
Need fixes for FMD too.

**Comment by Tmp341** [comment]
There is some kinda region lock then.
