### ISSUE TITLE
Folder icon Manga

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#461]
**This should not put here.**
[deviantart.com/djgerman10](https://www.deviantart.com/djgerman10)
But I wanted to share some folder icon with you, maybe you're just like me crazy for having everything tidy. or maybe not. But aesthetically it looks good.

I will continue making more icons.

_Icon requests just comment below._

Greetings to manga lovers.

![xd](https://user-images.githubusercontent.com/48584512/64142272-ba649380-cde1-11e9-9517-2dbd3dd37285.png)

**Comment by Slasar41** [comment]
You should use Discord to share something like this.
