### ISSUE TITLE
Can't download chapters [DoujinYosh, MangaYosh]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#464]
the problem is same like #329
![fmd3](https://user-images.githubusercontent.com/45929526/64325665-c5424280-cff2-11e9-99b2-d048a2f5e867.PNG)
![fmd4](https://user-images.githubusercontent.com/45929526/64325668-c5dad900-cff2-11e9-8e51-b95f7d1d638b.PNG)

**Comment by SDXC** [comment]
Merged.
