### ISSUE TITLE
"Curtain's Up, I'm Off" doesn't list any chapters [MangaDex]

### ISSUE THREAD

**Issue by azraei97** [fmd-project-team/FMD#465]
This link https://mangadex.org/title/39553 other manga works fine
![Untitled](https://user-images.githubusercontent.com/40983245/64336980-d69a4780-d010-11e9-80c4-97781d86637b.png)

Other was please bring support download Web Comic from WuxiaWorld

**Comment by SDXC** [comment]
The chapters are from MangaPlus which aren't hosted on MangaDex and are intentionally ignored.

**Comment by azraei97** [comment]
I able to download the chapter using mobile apps Tachiyomi (MangaPlus extension) normally but when I try same link mangaplus.shueisha.co.jp in FDM it say URL not support.

Please bring support MangaPlus and WuxiaWorld. Thank you

**Comment by SDXC** [comment]
MangaPlus won't be added anytime soon for FMD. Problem lies with the decryption of the images which in case of FMD has to be reverse engineered as far as I can tell. FMD doesn't use a browser engine to get the content of a website so the javascript parts have to be extracted or ported/reverse engineered for FMD to use.

**Comment by azraei97** [comment]
So about the WuxiaWorld?

**Comment by SDXC** [comment]
As far as I can see, WuxiaWorld only has text based novels.
We don't support text based content, only image scraping and it's not planned to be added.

**Comment by azraei97** [comment]
WuxiaWorld have comic (https://wuxiaworld.site/tag/webcomics) that actually more chapter then other site. That's why I'm requesting it. Please don't close section before check properly .

**Comment by SDXC** [comment]
Please always provide a link to websites you request!
I only checked wuxiaworld.com because you didn't provide a link.

**Comment by azraei97** [comment]
Sorry. My mistake for not providing link. I didn't know that there are difference site wuxiaworld.
Ow great. Thanks for accept my web request.

**Comment by azraei97** [comment]
#983 #982 should be close now because already complete
