### ISSUE TITLE
Mangadoom have double manga list

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#466]
Well, as the title said, it have double manga list, probably for every manga.
The only different is the manga link have different capitalization.

here are some picture 
![Screenshot_3](https://user-images.githubusercontent.com/30251842/64337977-18c48880-d013-11e9-8d40-8edf1ea6d28a.png)
![Screenshot_4](https://user-images.githubusercontent.com/30251842/64337988-20842d00-d013-11e9-9721-65afacaf9212.png)

**Comment by Tmp341** [comment]
That happens when a website url changed and you've updated manga database for that site. 

Delete ``Website.db`` under ``Data`` folder and redownload it. FMD only writes new links, doesn't delete existing not used ones from databases.

**Comment by knight109** [comment]
ohh thanks

**Comment by Tmp341** [comment]
Closing this for now.
