### ISSUE TITLE
Cannot get manga info. Please check your internet connection and try again [SenseScans]

### ISSUE THREAD

**Issue by JLChamberlain** [fmd-project-team/FMD#468]
Any time I try and look at a series from SenseScans in FMD I am always prompted with this message. Does FMD have an issue with SenseScans at the moment because I definitely have an internet connection. Happens on all titles under SenseScans.

**Comment by SDXC** [comment]
This should be fixed now. I'll close the issue. Feel free to re-open it, if you still have problems.
