### ISSUE TITLE
Website doesn't work again [LHTranslation]

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [fmd-project-team/FMD#47]
The site has not changed urls, but the chapter list does not appear, the favorites does not work and directly pasting a URL gives a N/A error.

**Comment by SDXC** [comment]
Did you already repeated these steps?:
https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation

**Comment by Tmp341** [comment]
I can check manga list, it even started downloading.

**Comment by l-l-l-l-l-l** [comment]
I have just tried the workaround. I have done everything, checked, rechecked and still nothing. I don't get the warning pop-up shown there, it's just blank.

**Comment by Tmp341** [comment]
Send fmd's log entry please.

**Comment by l-l-l-l-l-l** [comment]
[fmd.log](https://github.com/fmd-project-team/FMD/files/3051600/fmd.log)

**Comment by l-l-l-l-l-l** [comment]
[fmd.log](https://github.com/fmd-project-team/FMD/files/3051610/fmd.log)
Correct one this time.

**Comment by Tmp341** [comment]
Whoops, my bad. Please try sending it after you try to download from LHT.

**Comment by l-l-l-l-l-l** [comment]
How do I do to make a download task if I cannot access the chapter list?

**Comment by SDXC** [comment]
Something strange I found in your log:

16:10:16:953 ERROR: ...\Jorge\Desktop\5E\fmd_0.9.69.0_Win64\lua\modules\dm5.lua:7: unexpected symbol near '<'
16:10:17:110 ERROR: ...e\Desktop\5E\fmd_0.9.69.0_Win64\lua\modules\jsunpack.lua:7: unexpected symbol near '<'
16:10:17:134 ERROR: ...e\Desktop\5E\fmd_0.9.69.0_Win64\lua\modules\lzstring.lua:7: unexpected symbol near '<'

at least jsunpack is script that is used for some websites. If the script has an error, this functionality will not be available. Please rename your "lua" folder, delete the log file, start FMD and let it redownload the scripts. Afterwards please post the new log again.

**Comment by Tmp341** [comment]
You can just copy a lht link and past in FMD.

**Comment by l-l-l-l-l-l** [comment]
Copying a link results in a N/A error.
I tried modifying the download.db to add a new download. The first thing I found was that the archive was a bit misshapen, with a couple of duplicates and a couple of half-deleted entries. After tidying it, I added the download and tried again, first as is, then deleting the lua directory and redownloading it. These are the resulting logs:
[fmd-log-dl.log](https://github.com/fmd-project-team/FMD/files/3051708/fmd-log-dl.log)
[fmd-log-redl-lua.log](https://github.com/fmd-project-team/FMD/files/3051709/fmd-log-redl-lua.log)

**Comment by l-l-l-l-l-l** [comment]
Wait, that somehow erased the sites from my list, as well as the workarounds.

**Comment by l-l-l-l-l-l** [comment]
New log with the workaround set again:
[fmd.log](https://github.com/fmd-project-team/FMD/files/3051716/fmd.log)

**Comment by Tmp341** [comment]
You can open LHT on browser right? 

New fmd is out (v0.9.162.0), download it and do a fresh install:

https://github.com/fmd-project-team/FMD/wiki#fresh-install

**Comment by Tmp341** [comment]
Im trying something, please wait a little.

**Comment by l-l-l-l-l-l** [comment]
Did a clean installation and now it does work.
The log, just in case:
[fmd.log](https://github.com/fmd-project-team/FMD/files/3052221/fmd.log)

**Comment by Tmp341** [comment]
You can delete that line, it was for debugging.
