### ISSUE TITLE
Kissmanga does not work

### ISSUE THREAD

**Issue by Souravi785** [fmd-project-team/FMD#470]
When I click a manga it's empty. I tried several ones but the same result. The Cloudfare bypass is enabled as well. What can I do?

**Comment by Tmp341** [comment]
Just tested and got mangalist on random manga.

**Comment by Souravi785** [comment]
Doesn't work.

**Comment by Souravi785** [comment]
Where can I find the database file?

**Comment by Tmp341** [comment]
Oh shoot, forgot to link it, here:
[KissManga.7z](https://github.com/fmd-project-team/FMD-WebsiteDatabases/raw/master/packages/KissManga.7z)

**Comment by Souravi785** [comment]
Still doesn't work.

**Comment by Slasar41** [comment]
Check in Options -> Websites -> Advanced -> KissManga, `DisableCloudflareBypass` option should be set to `False`. If it `True` then uncheck it.

**Comment by Tmp341** [comment]
> 
> 
> Check in Options -> Websites -> Advanced -> KissManga, `DisableCloudflareBypass` option should be set to `False`. If it `True` then uncheck it.

Do this, and if you set manual cookies before, delete them too.

**Comment by Souravi785** [comment]
> Check in Options -> Websites -> Advanced -> KissManga, `DisableCloudflareBypass` option should be set to `False`. If it `True` then uncheck it.

Thanks it worked.
