### ISSUE TITLE
Can't update manga list [NinjaScans]

### ISSUE THREAD

**Issue by jokosablenk** [fmd-project-team/FMD#478]
there is a new series https://ninjascans.com/manhua/dimensional-mercenary/
and i can't add it to the current manga list.

**Comment by Tmp341** [comment]
Only that series?

**Comment by jokosablenk** [comment]
yes, because it is a new series. seem like they changed something to the site

**Comment by Tmp341** [comment]
But if that's right, then you couldn't be able to download other mangas too. 

Have you deleted your local ``NinjaScans`` database file inside ``Data`` folder and updated NinjaScans manually?
