### ISSUE TITLE
Missing pages downloading chapters from [TuMangaOnline]

### ISSUE THREAD

**Issue by Mariolr93** [fmd-project-team/FMD#479]
Everything else is working fine with TMO, but when downloading chapters there is missing pages from any manga in TMO.

![Captura](https://user-images.githubusercontent.com/19262204/64506184-d65dae80-d293-11e9-896a-4f9879b249ca.JPG)

**Comment by Tmp341** [comment]
It seems they've added a recaptcha, which you can't pass it normally. Then you should disable auto cf_bypass and put cookies manually.

**Comment by TheDoom95** [comment]
How do I disable cf_bypass and add cookies to Tumangaonline?

**Comment by Tmp341** [comment]
![disabled](https://user-images.githubusercontent.com/53397794/62005767-5bec2b80-b138-11e9-9c45-f191155637b5.png)

Another users screenshot. Do [this](https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation) workaround, similar steps but different cookies, then go to advanced tab of Tumangaonline's showing on the picture above, then mark ``"DisableCloudflareBypass"``.

**Comment by TheDoom95** [comment]
![ds](https://user-images.githubusercontent.com/32015214/64924268-ecfb8c80-d7e2-11e9-9cf1-07f3d3b293c4.PNG)
Sorry, look, apparently when I look at cookies I get 5 different ones. Do I put the five using "=" and the ";" I also don't know where to put them: HTTP or CloudflareBypass

**Comment by Tmp341** [comment]
Below ``HTTP`` inside ``Cookies``.

**Comment by Mariolr93** [comment]
Tried everything you said and nothing. Not working for me.

**Comment by SDXC** [comment]
Is this still a thing with the latest version 0.9.167.0?

**Comment by acristobo** [comment]
I have the same problem
The problem persists in version 0.9.167.0.

**Comment by acristobo** [comment]
The problem also persists in version 1 0.9.167.1

**Comment by SDXC** [comment]
It seems that some image links are only being loaded/generated when showing the chapter content in the browser (JavaScript I think, didn't look to deep into it). The image behind the static links will be saved in the browser cache so the users can still read it safely, but if you open the image in a separate tab and refresh it, the link isn't valid anymore and you'll get an error 404.

FMD doesn't use browser components and running JavaScript is only possible with much pain and kind of restricted. So don't expect a fast fix for now.

**Comment by acristobo** [comment]
if that's the case,
Wouldn't it be nice to disable "TuMangaOnline" (until resolved)? ...
because all the "manga" are failing.
