### ISSUE TITLE
Download speed going to 0bps [MangaRock]

### ISSUE THREAD

**Issue by ZodiaBruh** [fmd-project-team/FMD#48]
I downloaded one manga from MangaRock and it went fine. 
But now trying to download others and the download speed is going to 0bps every 2 seconds or so, making it nearly impossible to download. 

I tried reducing the connection timeout to 5s and elevating the number of retries to 50 as I saw someone suggesting, but didn't work.

Any ideas anyone? Thanks in advance

**Comment by Von07** [comment]
Lower the "Number of Downloaded task' and "Number of Downloaded Files"

**Comment by ZodiaBruh** [comment]
Sadly both are at 1 already.

**Comment by Tmp341** [comment]
It is working for me.

**Comment by SDXC** [comment]
I'll close this issue for now. If you still have problems you can re-open the issue anytime.
