### ISSUE TITLE
Download doesn't work [Tumangaonline, MangaDoor]

### ISSUE THREAD

**Issue by PhantoManresa** [fmd-project-team/FMD#481]
Hi, I am new to this fork of FMD. I can't download or access to any manga from tumangaonline and mangadoor. I can access them from the browser, so I have Internet connection. I read some issues regarding tumangaonline, but I don't quite understand the cf_bypass stuff. Any help is appreciated.
Thanks in advance

**Comment by Tmp341** [comment]
Tumangaonline is a little problematic. You have to manually set cookies.

**Comment by PhantoManresa** [comment]
Hi, how do I set the cookies manually? There is a tutorial somewhere? Thanks again

**Comment by Tmp341** [comment]
[Check wiki](https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation). Same steps, different cookies.

**Comment by PhantoManresa** [comment]
Hi @Tmp341, I tried what you suggested but I still have the same issue. That works for you on those sites? I have one doubt with the example, though. Now there is a Cloudflare Bypass section in the advanced section that did not exist in the tutorial. I have to put the cookies and the agent in the Cloudflare Bypass section or the Http section like in the example? I tried both, but none of them worked for me. Actually, FMD overwrites the cookies and the agent values of the Cloudflare Bypass section.
Please, try to do this and let me know if I am making something wrong, but I followed the tutorial very carefully.

**Comment by Tmp341** [comment]
You should make them look like these:

![1](https://user-images.githubusercontent.com/1683388/64666847-651f2680-d460-11e9-93c8-5bc44734e105.jpg)
![2](https://user-images.githubusercontent.com/1683388/64666850-68b2ad80-d460-11e9-8a51-ea36edb8baf5.jpg)

**Comment by PhantoManresa** [comment]
That's exactly how I have it, with the difference that I have more cookies. I don't know if that can be an issue. The config you have worked for you?
![config1](https://user-images.githubusercontent.com/42277800/64668387-684bef80-d42b-11e9-93c3-ff923fe0ca5e.png)
![config2](https://user-images.githubusercontent.com/42277800/64668390-6aae4980-d42b-11e9-862a-c80dd9f97860.png)

**Comment by Tmp341** [comment]
What is that cookie starts with ``49``?

Also, try to delete ``_ga`` and ``_gid`` lines.

**Comment by PhantoManresa** [comment]
> What is that cookie starts with 49?

No idea.
> Also, try to delete _ga and _gid lines.

I did that and still no result.

**Comment by SDXC** [comment]
Are you using a proxy in FMD?

**Comment by lordzidiousback** [comment]
@SDXC https://github.com/fmd-project-team/FMD/pull/547 repair fixed TMO as well

**Comment by PhantoManresa** [comment]
> @SDXC #547 repair fixed TMO as well

Hi, this issue was closed because of this, but I still can't download from neither. I should wait for an update for this changes to work?

Thanks for your hard work

**Comment by Slasar41** [comment]
https://github.com/fmd-project-team/FMD/pull/547 fixes doesn't have anything to do with this issue.

**Comment by Slasar41** [comment]
@PhantoManresa Try removing any settings in Options -> Websites -> Advanced for both Tumangaonline and MangaDoor.
![image](https://user-images.githubusercontent.com/28888646/66682541-9d07cc80-ec9f-11e9-9315-77d605473a8a.png)
I can download from both website just fine.
![image](https://user-images.githubusercontent.com/28888646/66682743-12739d00-eca0-11e9-9ec4-e90b38923d21.png)
If you use a proxy in FMD, then maybe that's the problem.

**Comment by PhantoManresa** [comment]
I am not using any proxy and my options are by default. I just downloaded the current version of FMD to make me sure of it.
This is what happens when I try to find a manga in MangaDoor:
![mangadoor](https://user-images.githubusercontent.com/42277800/66684306-c39a1900-ec47-11e9-8925-a15ef662bb33.png)

This is for Tumangaonline:
![tumangaonline](https://user-images.githubusercontent.com/42277800/66684311-c85ecd00-ec47-11e9-8d6a-458712152e16.png)

There is a cf_bypass_error.log file created with the following text when I try to access to Tumangaonline. This does not happen for MangaDoor. It says the following:

Error: cf_bypass has encountered a problem with the website [Tumangaonline]
Traceback (most recent call last):
  File "cf_bypass.py", line 29, in <module>
  File "cfscrape\__init__.py", line 336, in get_tokens
  File "site-packages\requests\sessions.py", line 546, in get
  File "cfscrape\__init__.py", line 124, in request
  File "cfscrape\__init__.py", line 147, in handle_captcha_challenge
cfscrape.CloudflareCaptchaError: Cloudflare captcha challenge presented for tmofans.com (cfscrape cannot solve captchas)

**Comment by Tmp341** [comment]
> cfscrape.CloudflareCaptchaError: Cloudflare captcha challenge presented for tmofans.com (cfscrape cannot solve captchas)

This line tells you what is going on. Tumangaonline has captcha and cf_bypass can't pass it by itself.

**Comment by PhantoManresa** [comment]
Yes, I can see that, but why is it working for @Slasar41 ? And what about MangaDoor? There is no captcha error with MangaDoor.

**Comment by Tmp341** [comment]
Well, i don't know. He needs to explain if he does anything different.

**Comment by Slasar41** [comment]
I don't have any setting for these websites.
See: https://streamable.com/bp1w6

**Comment by Tmp341** [comment]
> 
> 
> I don't have any setting for these websites.
> See: https://streamable.com/bp1w6

Looks like your settings are default.

**Comment by Slasar41** [comment]
Maybe the same case as https://github.com/fmd-project-team/FMD/issues/542#issuecomment-541416684?

**Comment by Tmp341** [comment]
Maybe.
