### ISSUE TITLE
Download doesn't work [MangaDoom]

### ISSUE THREAD

**Issue by spamtaztik** [fmd-project-team/FMD#486]
I can't download anything from Mangadoom again. Even opening manga info is a no-go. I already tried the solution in https://github.com/fmd-project-team/FMD/issues/286, but it's still not working (it USED TO work). 

I emptied all the options in advanced options, only filled out the "bypassURL" field with https://www.funmanga.com/uploads/chapters/16091/98/1.jpg. Still no go.

Any other workaround I should try?
Thanks much.

**Comment by SDXC** [comment]
The BypassURL-Workaround doesn't seem to be needed anymore.
I tried downloading "Godspeed" Chapter 9 and it worked, but it is brutally slow in doing that, but it's the website itself that took too long in loading the images. Nothing we can do.

If you have specific problems with a manga, please provide the title and chapter you're trying to download.

**Comment by spamtaztik** [comment]
Yeah, I was about to write here about the bypassURL not needed anymore but you beat me to it. It seems they no longer load the images from funmanga or something. Thanks for checking it for us! Cheers!

CLOSED
