### ISSUE TITLE
Can't get manga info [MangaDex]

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#489]
I can access the website with browser but i cant access it in FMD.
It just give me N/A in FMD

**Comment by SDXC** [comment]
You're probably blocked on the API side.
Can you view the following page?:
https://mangadex.org/api/manga/20679/

**Comment by knight109** [comment]
nope, all just some text and some non sense.

**Comment by SDXC** [comment]
If you see the text (which is a JSON output from the API) then you aren't blocked.

Try a fresh install to test if it works.

**Comment by knight109** [comment]
I download the new ones, but i still cant access mangedex. But it change for N/A to give a title, genre, and other but no picture or chapter.

**Comment by knight109** [comment]
Fresh install doesnt work.

And when i check, i got this when i directly choose from mangadex list
![Screenshot_5](https://user-images.githubusercontent.com/30251842/64916608-261c0880-d7b3-11e9-9b56-18c0855097f7.png)
(look at the link)

And then when i choose from my favorite list
![Screenshot_7](https://user-images.githubusercontent.com/30251842/64916612-3cc25f80-d7b3-11e9-8e01-4a8dffcf1274.png)

**Comment by spamtaztik** [comment]
Huh. All my MD favs' links are mangadex.org/title/blahblahblah instead of mangadex.org/manga/blahblah. Even the mangas in MD's "updates" section also have /title/ as their URLs. 

Have you updated your LUAs lately?

**Comment by SDXC** [comment]
It actually doesn't matter because the lua script builds the API url only from the ID and the base url. In the browser both notations work as /manga/ is the old and /title/ the current format. I have both types (long and short as well) in my favorites and it works fine.

Does the manga info load fully (cover, chapter list, etc.) when using /manga/ in your favs?
Also, maybe you should upload your favorites.db so we can check if the entries themselves are the problem.

**Comment by knight109** [comment]
> Does the manga info load fully (cover, chapter list, etc.) when using /manga/ in your favs?
Nope, if i use /manga/ i got N/A and if i use /title/ i got title, author, genre, etc, but i doesn't get chapter list and cover.

> Also, maybe you should upload your favorites.db so we can check if the entries themselves are the problem.
here it is
[favorites.zip](https://github.com/fmd-project-team/FMD/files/3614059/favorites.zip)

**Comment by SDXC** [comment]
Hmm... doesn't look like a problem with the favorites. They worked fine for me.

Did you also check the advanced website settings of MangaDex? Are there possibly some settings set that could be the cause?

**Comment by knight109** [comment]
![image](https://user-images.githubusercontent.com/30251842/64935188-567ea800-d882-11e9-8fde-5bf7d5706c89.png)

Just that, and i tried to on/off the DisableCloudflareBypass but it just the same.

**Comment by SDXC** [comment]
Could you try to uncheck the "Enable" checkbox on top of the settings and re-test?

**Comment by knight109** [comment]
> Could you try to uncheck the "Enable" checkbox on top of the settings and re-test?
> Don't forget to apply.

Done it. Still the same.

> And if it still doesn't work, please upload the MangaDex.lua file.

Done it by deleting and updating. Still the same.

**Comment by SDXC** [comment]
I meant uploading the lua file here, so I can check if you have the correct version.

But maybe it's better to just pack the whole install folder and upload it (you probably need to upload it to another hoster like mediafire).

**Comment by knight109** [comment]
i'll upload the link after i finish redownload my manga list. it almost 1 gb file since i try most of the manga list so i need to deleted most of them

**Comment by knight109** [comment]
https://drive.google.com/file/d/1mCI_0xlBGeHJ87BYqaaljKeUGhaLtH1p/view?usp=sharing

**Comment by SDXC** [comment]
Okay, I think I get the gist of your problem. There are 2 things I found:
First is this:
![proxy](https://user-images.githubusercontent.com/5290260/64996064-303a2600-d8dd-11e9-9cfc-9229ff5d6c8d.png)

If you don't use any proxy, disable this setting. If you do use a proxy, that may be the actual problem. I found in the cf_bypass.log following error:

```
Error: cf_bypass has encountered a problem with the website [MangaDex]
Traceback (most recent call last):
  File "cf_bypass.py", line 29, in <module>
  File "cfscrape\__init__.py", line 336, in get_tokens
  File "site-packages\requests\sessions.py", line 546, in get
  File "cfscrape\__init__.py", line 124, in request
  File "cfscrape\__init__.py", line 147, in handle_captcha_challenge
cfscrape.CloudflareCaptchaError: Cloudflare captcha challenge presented for mangadex.org (cfscrape cannot solve captchas)
```

Which indicates that you had too many connections to the API of MangaDex. When using a proxy that may not be particularily your fault though as others also may be using the same proxy.

If you still get the error above, then you may wait for some time before retrying or do the manual Cloudflare workaround for MangaDex.

**Comment by knight109** [comment]
Yeah it still not working.

**Comment by Tmp341** [comment]
> 
> 
> Yeah it still not working.
> 
> Where is the tutorial to do Cloudflare workaround?
> I dont remember how to do it.

Same steps, different cookies:
https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation

**Comment by knight109** [comment]
Thanks

**Comment by meico0** [comment]
i have the same issue with mangadex, i can still get the manga cover image and the description but no manga list
i can open the api file and open it on browser just fine
also same thing with LHtrans, but unlike mangadex, LH show nothing at all
![image](https://user-images.githubusercontent.com/35516048/65209449-5bca3580-dac2-11e9-9ec6-28423b90e321.png)
