### ISSUE TITLE
Renaming settings for chapters not working correctly [NinjaScans]

### ISSUE THREAD

**Issue by ElectroShade** [fmd-project-team/FMD#497]
In my Save To Options I have auto generate chapter folder checked with the chapter name set as "%NUMBERING% - %CHAPTER%"

This normally works but recently I noticed any chapter downloaded from NinjaScans actually saves the files as "%NUMBERING% - %CHAPTER%" rather then the actual number - chapter title. If multiple new chapters exist, it'll overwrite the existing one each time since they'll all just save as "%NUMBERING% - %CHAPTER%" rather them honoring the variables. I've noticed in the chapter list none of the manga have the chapter titles either which may or may not be related.

**Comment by SDXC** [comment]
The Madara template of NinjaScans is malformed. I fixed it and the chapter names should be available again. With this the renaming should work as well.

**Comment by ElectroShade** [comment]
Appears to be working now after the update. Thanks!
