### ISSUE TITLE
Website changed url [HeavenManga]

### ISSUE THREAD

**Issue by spamtaztik** [fmd-project-team/FMD#500]
Starting today, heavenmanga is no longer reachable at heavenmanga.org (from fav list). There are, however, websites at ww2.heavenmanga.org and heavenmanga.fun. The .fun one seems to be more up to date though (e.g.: "all heavenly days" on .fun is up to ch 88 but on the other one is still 84).

Just thought I'd let you know.
Thanks much!

EDIT: none of the titles in manga list in "manga info" page can be opened. I tried updating manga list from heavenmanga's server but it seemed to fail (the "updating list" progress bar just stay quiet then disappeared). I also downloaded manga list from fmd's server but none of the titles can be opened too.

**Comment by AbidZakaria** [comment]
@Tmp341 heavenmanga.fun add in site request

**Comment by Tmp341** [comment]
> 
> 
> @Tmp341 heavenmanga.fun add in site request

Is that completely another site or domain change only?

**Comment by SDXC** [comment]
merged
