### ISSUE TITLE
Forbidden characters in save-to path when changing multiple entries

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#507]
The path now has the character "?" that Windows doesn't accept it, same like in the title.
Causing can't open the folder and error downloading because the path isn't connected to the actual folder.
Now I must remove these character in the path one by one.
![image](https://user-images.githubusercontent.com/28888646/65275592-31bf5480-db50-11e9-89ba-60238f17ebe9.png)

**Comment by Slasar41** [comment]
Alright.

**Comment by SDXC** [comment]
Free Manga Downloader (0.9.167.1) has been released.
