### ISSUE TITLE
Download doesn't work for all titles [Manhwa18]

### ISSUE THREAD

**Issue by molitar** [fmd-project-team/FMD#509]
So I went to download on manhwa18 the manhwa 'Producer Trainee' and it will not download at all. I then attempted to download a different manwha and it downloaded just fine. 

Producer Trainee (fails download)
/Blush-DC. (downloads fine)

![failed download](https://user-images.githubusercontent.com/16074561/65376823-bbffd980-dc72-11e9-9491-0be809968b40.jpg)

I can see the chapters just fine and clicking read online takes me to the main page for the chapters just fine.  Both URLS look same for the reading of the manhwa so really makes no sense. I tried to enable logging but noticed the logging does now show anything but the LUA updates and CFBypass running and does not log anything to do with downloads to see what might be the problem.

**Comment by TeepoLurking** [comment]
I'd like to add that most series download fine, but Manga title detection is broken.

Hakuneko downloader has same issue and both software require renaming manually, but still I'm happy to at least have partial functionality. Better than nothing, as this website has a lot of unique content.

**Comment by ronny1982** [comment]
For HakuNeko related issues create a ticket in the [repository](https://github.com/manga-download/hakuneko/issues).

In HakuNeko copy/paste is not fully supported for this website.
Synchronize the manga list instead, this is even more convenient then copy/paste.

**Comment by Slasar41** [comment]
Should be fixed with a module update.
