### ISSUE TITLE
Is the Demographic tag available through API? [MangaDex]

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#51]
Is the genre from demographic info in the website already implemented in MangaDex API?
https://github.com/riderkick/FMD/issues/1615
![image](https://user-images.githubusercontent.com/28888646/55682415-41a9fa00-595d-11e9-9ca6-3df4f9c056c4.png)

**Comment by SDXC** [comment]
It's still not in the API, but MangaDex has a pending task to re-implement the API. Until then, they probably won't make many more changes to the current API.
