### ISSUE TITLE
Add support for website [Manytoon]

### ISSUE THREAD

**Issue by TeepoLurking** [fmd-project-team/FMD#512]
https://manytoon.com/

Website looks very similar to https://manhwahentai.me and even contains some links to that site.
Quite possibly doesn't require big code changes to get it working.

**Comment by jokosablenk** [comment]
it's been added. check this too https://github.com/fmd-project-team/FMD/issues/429

**Comment by Tmp341** [comment]
Please check your version.

**Comment by jokosablenk** [comment]
who's version?

**Comment by Tmp341** [comment]
> 
> 
> who's version?

Yours. If you're using [this](https://github.com/fmd-project-team/FMD/releases/tag/0.9.167.1) version, then you should be able to download from there.

**Comment by jokosablenk** [comment]
i'm using that version

**Comment by Tmp341** [comment]
Then it should be working, ``https://manytoon.com`` changed it's url to ``https://manytoon.me``.
