### ISSUE TITLE
Problem with 0.9.167.1 because cf_bypass is missing

### ISSUE THREAD

**Issue by arbiter9605** [fmd-project-team/FMD#515]
Ever since the .1 update been getting error like this when doing update, sometimes it says "Message           : Failed to execute  : 225" others its 2.
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.167.1
Product Version   : Win64
Host Machine      : Windows 10 64-bit
FPC Version       : 3.0.4
LCL Version       : 1.8.4.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2019/09/21 15:54:42
Path              : C:\Users\arbiter\Desktop\Batoto_v3.1\fmd_0.9.161.0_Win64\fmd.exe
Process ID        : 22496
MainThread ID     : 10256
Thread ID         : 21936
Time              : 24/09/2019 01:55:00.021
Sender Class      : TFavoriteThread
Exception Class   : EProcess
Message           : Failed to execute  : 2
  $00000001001443B4
  $00000001004634D2
  $00000001004658FB
  $0000000100465C79
  $000000010027E98B
  $00000001000542ED
  $0000000100003B96
  $0000000100015067
  $00007FF815D17BD4
  $00007FF81740CEE1

edit: even downgrading to 0.9.167.0 still get it so maybe a lua is giving me issue but didn't start til did update .1

**Comment by Slasar41** [comment]
See https://github.com/fmd-project-team/FMD/issues/514#issuecomment-534235780

**Comment by SDXC** [comment]
It seems Windows Defender (or the Antivirus you're using) doesn't like cf_bypass.exe which ships with FMD. Because of some changes to support HTTP proxies in cf_bypass, the Antivirus reacts by removing the file.

You can either go back to 166.1 until I find/implement a better solution for cf_bypass or you can set exceptions in the antivirus so it doesn't block/remove the file.

**Comment by SDXC** [comment]
I'll close this issue as duplicate. Please use the following issue, if you still have problems or if you want to add some input:
https://github.com/fmd-project-team/FMD/issues/514
