### ISSUE TITLE
Small visual fixes (control alignment, exiting behavior)

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#52]
When exiting FMD while the window is set to maximize mode, it will change back to the last position & size window for a second and then disappear.

Also, can this section to be align by default?
![image](https://user-images.githubusercontent.com/28888646/55684550-3fa06500-5976-11e9-9d6c-4732ead67b1b.png)

**Comment by SDXC** [comment]
The alignment thingy should be fixed fast.

The exiting behavior may be a little bit more complex, depending on what's executed in the exit sourcecode. If it's too much work to change that behavior, I won't change it.

**Comment by SDXC** [comment]
Free Manga Downloader 0.9.162.0 has been released:
https://github.com/fmd-project-team/FMD/releases/tag/0.9.162.0

Issue will be closed.
