### ISSUE TITLE
"An error occured during program execution"

### ISSUE THREAD

**Issue by japzone1** [fmd-project-team/FMD#520]
The below error appears when I launch FMD since around September 23rd. If I choose `Ignore this exception for next time` and continue the program launches, but checking for new chapters seems not to work, as even though no errors are displayed during the process, none of my manga show new chapters since September 22nd. Also I can't load the Manga Info for any manga, no matter what source I try.

![error](https://i.imgur.com/SIAzXsO.png)
![manga info](https://i.imgur.com/P4IrIKQ.png)
```
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.167.1
Product Version   : Win64
Host Machine      : Windows 10 64-bit
FPC Version       : 3.0.4
LCL Version       : 1.8.4.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2019/09/21 15:54:42
Path              : C:\Users\medie_000\Downloads\fmd_0.9.21.8_Win64\fmd.exe
Process ID        : 91220
MainThread ID     : 94080
Thread ID         : 86120
Time              : 26/09/2019 23:48:54.131
Sender Class      : TFavoriteThread
Exception Class   : EProcess
Message           : Failed to execute  : 2
  $00000001001443B4
  $00000001004634D2
  $00000001004658FB
  $0000000100465C79
  $000000010027E98B
  $00000001000542ED
  $0000000100003B96
  $0000000100015067
  $00007FFF5A162784
  $00007FFF5B5B0C31
```

**Comment by temp1366** [comment]
same here
![image](https://user-images.githubusercontent.com/29550019/65752319-6c5d5a00-e119-11e9-9388-c5cf6c964ee4.png)

**Comment by SDXC** [comment]
Please check here:
https://github.com/fmd-project-team/FMD/issues/514

**Comment by japzone1** [comment]
> 
> 
> Please check here:
> #514

Ah, indeed Windows Defender quarantined `cf_bypass.exe` on exactly September 23rd. I managed to restore it and add an exception to WD for the file.
