### ISSUE TITLE
cf_bypass Virus Alert

### ISSUE THREAD

**Issue by alatnet** [fmd-project-team/FMD#522]
Windows Defender keeps popping up with a virus alert about cf_bypass.exe.
Says it has Trojan:Win32/Zpevdo.B and Trojan:Win32/Ludicrouz.V.

**Comment by Tmp341** [comment]
Duplicate of #514. Read that issue for more info.

**Comment by Tmp341** [comment]
Duplicate of #514.

**Comment by alatnet** [comment]
Ah, ok. didnt see that thread.

**Comment by Tmp341** [comment]
> 
> 
> Ah, ok. didnt see that thread.

No problem. Having one issue is both useful for us and users.
