### ISSUE TITLE
Can't download certain manga [MangaDex]

### ISSUE THREAD

**Issue by Sakurahime08** [fmd-project-team/FMD#526]
Hi! as the title says, for some reason, I am not able to download chapters from this title:
https://mangadex.org/title/33691/survive-as-the-hero-s-wife

Everything else from mangadex seem to be working though. so I don't know what the issue might be. Hope you can help! Thanks!

![image](https://user-images.githubusercontent.com/35158146/65830251-64034b80-e2e0-11e9-802d-5a177e355813.png)

![image](https://user-images.githubusercontent.com/35158146/65830269-8bf2af00-e2e0-11e9-992e-2e33f98c9753.png)

**Comment by Slasar41** [comment]
Same, the manga isn't available in the website on my end.
![image](https://user-images.githubusercontent.com/28888646/65835688-85315f80-e313-11e9-8028-0c8352458587.png)

**Comment by Sakurahime08** [comment]
the website is working for me. I think you need to log in for it to show up. Maybe we need account access for mangadex in the app?

**Comment by Tmp341** [comment]
Sometimes Mangadex blocks access users without an account.

**Comment by Slasar41** [comment]
Im already logged in though.
Is there restriction per user account?
![image](https://user-images.githubusercontent.com/28888646/66217628-dc5b7980-e6f1-11e9-99d1-d5472039331b.png)

**Comment by Tmp341** [comment]
> 
> 
> Im already logged in though.
> Is there restriction per user account?

Not that i've heard any. Maybe a code changed or something.

**Comment by Slasar41** [comment]
I have some information about why this title can't be downloaded
![image](https://user-images.githubusercontent.com/28888646/66429545-6da85400-ea42-11e9-8907-f28100032368.png)
I think FMD should implemented user account for MangaDex

**Comment by Tmp341** [comment]
> 
> 
> I have some information about why this title can't be downloaded
> ![image](https://user-images.githubusercontent.com/28888646/66429545-6da85400-ea42-11e9-8907-f28100032368.png)
> I think FMD should implemented user account for MangaDex

Well, i was doing it as :  

1. Login to Mangadex on browser
2. Get logged in cookies
3. Use them

**Comment by Slasar41** [comment]
> Well, i was doing it as :
> 
> 1. Login to Mangadex on browser
> 2. Get logged in cookies
> 3. Use them
> 
> But i think a Mangadex account (or account add feature for all necessary sites) adding feature wouldn't hurt.

Yups, as workaround you can download the manga with cookies info.

**Comment by SDXC** [comment]
I'll close this ticket.
