### ISSUE TITLE
Integration with Myanimelist

### ISSUE THREAD

**Issue by formigao** [fmd-project-team/FMD#528]
is it possible make FMD work with myanimelist?
if it could add or update new chapters and manga titles it would me amazing.

**Comment by SDXC** [comment]
What exactly do you want to do with that website in FMD?
As far as I can see you can't download anything from that website.........

**Comment by formigao** [comment]
yes. something like https://taiga.moe  but for the mangas we are reading!

**Comment by SDXC** [comment]
Mmmhh.... Sorry, but I won't add support for any tracking/info websites.
