### ISSUE TITLE
Chapter numbering doesn't work [Boredom Society]

### ISSUE THREAD

**Issue by JokoeSukri** [fmd-project-team/FMD#53]
Chapter numbering doesn't appear, only String format

![Screenshot_14](https://user-images.githubusercontent.com/32964994/55685000-74b7b200-598c-11e9-8bba-c88c67fb6dc1.jpg)

Because of This issue, I need to Numbering the folder manually

**Comment by Tmp341** [comment]
Website seperated chapter numbers it seems.

**Comment by SDXC** [comment]
Fixed it.
