### ISSUE TITLE
Website changed again [LeviatanScans]

### ISSUE THREAD

**Issue by alzamer2** [fmd-project-team/FMD#530]
i cant download from site LeviatanScans, i think they changed some thing
i can add chapter in queue though, but i cant download

and is there any ref i can use to learn how to edit lua files? i want to be active member in community

and thanks for good job ^^

**Comment by lordzidiousback** [comment]
de problem is the fmd in site see and check de chapter and add to cue but not download

**Comment by alzamer2** [comment]
yep

Sent from Mail for Windows 10

**Comment by jokosablenk** [comment]
same problem here. can't download anything from leviatan
