### ISSUE TITLE
Opening FMD when isn't connected to internet causing high CPU usage

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#531]
I have low end spec.
The high CPU usage happens because FMD checking update for the modules and itself. When I stop it manually, the CPU usage will back to normal.
Also happen when loading manga info without internet connection.
Maybe add a timeout connection.
![image](https://user-images.githubusercontent.com/28888646/66129104-73083780-e619-11e9-9f1f-1c4c33f7e978.png)

**Comment by allydevper** [comment]
same here, but is working
![Captura](https://user-images.githubusercontent.com/28413681/66220882-7c35ea80-e693-11e9-9d58-b60e9f359264.JPG)

**Comment by forvy** [comment]
I guess this one explain my error several months ago? https://github.com/riderkick/FMD/issues/1500

**Comment by Slasar41** [comment]
Looks like this issue has been fixed with the latest update.
Now it'll timeout properly when there's no internet connection.
