### ISSUE TITLE
Cannot download all chapters [Manga-Tr]

### ISSUE THREAD

**Issue by aelbuz** [fmd-project-team/FMD#54]
Hi! I opened this issue 2 weeks ago on project's old page, I want to open here too. 
Old link: https://github.com/riderkick/FMD/issues/1710

I tried to download chapters from manga-tr.com but the site uses Ajax for changing chapter list page.

In example: https://manga-tr.com/manga-kaguya-sama-wa-kokurasetai-tensai-tachi-no-renai-zunousen.html

Manga page contains 3 pages for listing all chapters and they're updating without refreshing or changing the manga page link. So when I try to get the chapters, I only get the first page's chapters from 94 to 142 like this:

![54948711-60b48f00-4f4e-11e9-8f91-d73345f3f7a0](https://user-images.githubusercontent.com/21218001/55687195-e256e480-5972-11e9-91e4-e9a9282de175.PNG)

Thanks to @SDXC for caring about this problem on old project and thanks to everyone who efforts on this project, good luck.

**Comment by Tmp341** [comment]
I'm getting ``Url not supported`` message.

**Comment by SDXC** [comment]
@aelbuz The MangaTR fix should come as a lua update on your next FMD start. Please test it intensively and let us know if everything's okay or not.

**Comment by SDXC** [comment]
I'll close this issue. If anything's not working you can re-open or create a new issue.

**Comment by aelbuz** [comment]
I tried several manga pages and looks like it's working well. Sorry for confirming late.

Thank you so much.
