### ISSUE TITLE
Website not downloading [toonily.com]

### ISSUE THREAD

**Issue by mastercheat001** [fmd-project-team/FMD#542]
Website doesnt load anymore.

**Comment by Slasar41** [comment]
Which title?
I can download random title just fine.
![image](https://user-images.githubusercontent.com/28888646/66341999-95c88200-e972-11e9-8d56-169e591077a8.png)

**Comment by Tmp341** [comment]
> 
> 
> Which title?
> I can download random title just fine.
> ![image](https://user-images.githubusercontent.com/28888646/66341999-95c88200-e972-11e9-8d56-169e591077a8.png)

Are you using default (empty) settings or you used manual cookies?

**Comment by Slasar41** [comment]
> Are you using default (empty) settings or you used manual cookies?

I don't change any settings for Toonily.
Is it not working for you too?

**Comment by Tmp341** [comment]
> 
> 
> > Are you using default (empty) settings or you used manual cookies?
> 
> I don't change any settings for Toonily.
> Is it not working for you too?

I haven't tested myself.

**Comment by Tmp341** [comment]
@mastercheat001 Delete your database inside ``Data`` folder and download it from server again. Then Go to ``Options -> Websites -> Advanced -> HeavenManga``. Make sure the `DisableCloudflareBypass` option is set to `False`.

**Comment by mastercheat001** [comment]
> @mastercheat001
> 
> * Delete your `Toonily.db` inside `Data` folder and download it from server again. I've updated it.
> * Then Go to `Options -> Websites -> Advanced -> Toonily`. Make sure the `DisableCloudflareBypass` option is set to `False`.

I did all you instructed but still failed on all sites. Downloaded a fresh copy and still not working. I think it has something to do with CloudFlare. :(

**Comment by Tmp341** [comment]
But mine bypassed it by itself. Check your fmd package.

**Comment by AbidZakaria** [comment]
> Website doesnt load anymore.

![image](https://user-images.githubusercontent.com/19544118/66466876-a3365700-eaad-11e9-95ce-e104566f235d.png)

I can download random title just fine.

**Comment by mastercheat001** [comment]
> But mine bypassed it by itself. Check your fmd package.

where to? website load in normal browers but cant in FMD :(

**Comment by Tmp341** [comment]
Backup your FMD folder in a zip file etc, then download latest FMD and overwrite existing files. Normal package doesn't contain any personal databases, so you can overwrite on it. Then try again.

**Comment by mastercheat001** [comment]
> Backup your FMD folder in a zip file etc, then download latest FMD and overwrite existing files. Normal package doesn't contain any personal databases, so you can overwrite on it. Then try again.

I did as intructed but didnt work. I dont know anymore lol.

**Comment by Tmp341** [comment]
Do you have a log or anything

**Comment by mastercheat001** [comment]
> Do you have a log or anything?

I think i found the problem. It is cloudflare that kinda block my IPS. I can download it fine at work but cant at home. If i use VPN software like hotspot i can access it. Technically any site that uses CF blocks my download from FMD. I still can access the site normally though. Any workaround?

**Comment by Tmp341** [comment]
> 
> 
> > Do you have a log or anything?
> 
> I think i found the problem. It is cloudflare that kinda block my IPS. I can download it fine at work but cant at home. If i use VPN software like hotspot i can access it. Technically any site that uses CF blocks my download from FMD. I still can access the site normally though. Any workaround?

Why CF blocks your ISP? You should contact with your ISP and try to find what is going on.

**Comment by mastercheat001** [comment]
> > > Do you have a log or anything?
> > 
> > 
> > I think i found the problem. It is cloudflare that kinda block my IPS. I can download it fine at work but cant at home. If i use VPN software like hotspot i can access it. Technically any site that uses CF blocks my download from FMD. I still can access the site normally though. Any workaround?
> 
> Why CF blocks your ISP? You should contact with your ISP and try to find what is going on.

CF technically doesnt block my IPS cuz i still can access it in my browser. Only when i use FMD it happens. Every website that uses CF has this problem for me. :(

**Comment by Tmp341** [comment]
> CF technically doesnt block my IPS cuz i still can access it in my browser. Only when i use FMD it happens. Every website that uses CF has this problem for me. :(

Well, check your proxy settings, also remove any setting under `Toonily Advanced Settings`.

**Comment by mastercheat001** [comment]
There is no strange setting. I even tried to download a brand new version of 32 and 64 bit but nothing works.

**Comment by Tmp341** [comment]
Just tested on my end, no problem here (2 seperate windows on same page here):
![ssss](https://user-images.githubusercontent.com/1683388/66806554-82985200-ef30-11e9-98de-c5b956be58cf.jpg)

**Comment by mastercheat001** [comment]
> Just tested on my end, no problem here (2 seperate windows on same page here):
> 
> ![ssss](https://user-images.githubusercontent.com/1683388/66806554-82985200-ef30-11e9-98de-c5b956be58cf.jpg)

I can still use FMD to download from websites using cloudflare with VPN (HotSpot, Tunnel Bear) But my naked IP cant do that :(

**Comment by Tmp341** [comment]
Sorry, like i said, I can't point what is your problem here.

**Comment by mastercheat001** [comment]
> Sorry, like i said, I can't point what is your problem here.

I think it is because cf bypass doesnt work for me. If i use VPN cloudflare doesnt appear to protect my visit to those websites. No VPN CF will appears and yea. I can say CF bypass doest work.

**Comment by Tmp341** [comment]
`8a91914ecbdec184b27366a9e2cc5369 cf_bypass.exe`

Check this md5 code, if you have it (comes with latest fmd), then try to use a previous release ones (just extract cf_bypass.exe from it over existing one).

**Comment by Tmp341** [comment]
> Actually I also have an ISP here that couldn't download manga from website that has Cloudflare (like KissManga), so whenever I'm using that ISP, I must enabled VPN too.

Then CF specifically blocking some ISPs.
