### ISSUE TITLE
Chapter download only gets placeholders [NineMangaES, Tumangaonline]

### ISSUE THREAD

**Issue by JavikusRod** [fmd-project-team/FMD#543]
Since 2-10-2019 
![001](https://user-images.githubusercontent.com/16100843/66337692-a5fa4600-e90d-11e9-9303-74773751bece.jpg)

wear add

**Comment by Slasar41** [comment]
Which website?

**Comment by JavikusRod** [comment]
Spanish sites NinemamgaEs and Tu mangaonline

**Comment by Slasar41** [comment]
I'm try to download from these sites and both download the images just fine.
![image](https://user-images.githubusercontent.com/28888646/66373101-0488f800-e9d2-11e9-8a1f-10ee3e775bd9.png)
Could you specific which titles that have the problem?

**Comment by JavikusRod** [comment]
I try with some randooms titles and all do it .I try with a new fmd client
and i told you if something changes

**Comment by JavikusRod** [comment]
NinemangaEs is the module with problems
al the pages i downloaded from there had problems adds in every page

**Comment by Slasar41** [comment]
> NinemangaEs is the module with problems
> al the pages i downloaded from there had problems adds in every page

Could you give me the title example that has problem?

**Comment by JavikusRod** [comment]
Ippon again! Vol. 02 Ch. 015 Promesa. i choose this and download the adds
instead.
but i can choose anyone and still occur the same. NineMangaES

**Comment by JavikusRod** [comment]
![wear](https://user-images.githubusercontent.com/16100843/66402821-80277c80-e9b3-11e9-801e-b2a43c07f600.png)
same chapter same adds??

**Comment by Slasar41** [comment]
Just tried download Ippon again Ch. 15 and it's download the images just fine
![image](https://user-images.githubusercontent.com/28888646/66403100-31f49680-ea10-11e9-9229-5969ad374785.png)
Try go to Options -> Websites -> Advanced -> NineMangaES. Make sure the DisableCloudflareBypass option is set to False.

**Comment by JavikusRod** [comment]
DisableCloudflareBypass is that the problem ty

**Comment by JavikusRod** [comment]
i need to disabled for all sites??

**Comment by Slasar41** [comment]
No, that option need to be `False` for Cloudflare Bypass to works.
If that option is `True`, then CloudFlare Bypass isn't working.

**Comment by JavikusRod** [comment]
Nice works and suport guys!!

**Comment by JavikusRod** [comment]
I the problem shows again, with the web site NineManga. Donwloads the same picture in all comics

**Comment by Slasar41** [comment]
Someone already reported it, see: https://github.com/fmd-project-team/FMD/issues/594

**Comment by JavikusRod** [comment]
Thanks, you are so fast with the issues!!! What a team
