### ISSUE TITLE
repair 11toon

### ISSUE THREAD

**Issue by Dgraid12** [fmd-project-team/FMD#545]
### Thank you and sorry for the inconvenience!

**Comment by Tmp341** [comment]
It is working with `Cloudflarebypass` enabled.

**Comment by Dgraid12** [comment]
@Tmp341  thanks for the help, it's already working for me .. I don't know what happened .. `Cloudflarebypass` was disabled

**Comment by Tmp341** [comment]
Ok, closing this issue for now. If you have problem again, try my tip next time. If that doesn't work too, you can reopen this issue.
