### ISSUE TITLE
Unable download chapters of a manga from Mangadex

### ISSUE THREAD

**Issue by anonm39** [fmd-project-team/FMD#546]
Survive As The Hero's Wife
https://mangadex.org/title/33691/survive-as-the-hero-s-wife
https://mangadex.org/title/33691

Works fine for the rest of the Manga on Mangadex. Just "Survive As The Hero's Wife" is the one I have problem download any chapters from Mangadex. Tried older builds, both 32/64 bit build, still can't get them to download chapter of this manga. Tried different folder/directory/disks, still nope. I could download the manga from different source like Mangakakalot though (Yet to have latest chapter).
![fmd_U9fpFOWcWR](https://user-images.githubusercontent.com/56298953/66388497-dc60bf80-e9f8-11e9-8e62-eddb08e2c4f2.png)
![fmd_lgU9DBlvR4](https://user-images.githubusercontent.com/56298953/66388506-e08cdd00-e9f8-11e9-9dbe-6c3d06c77ca8.png)
![fmd_JJfx1Y6pDi](https://user-images.githubusercontent.com/56298953/66388517-e387cd80-e9f8-11e9-92ca-ac61cde9f69a.png)
3rd screenshot are what I get on other older builds

**Comment by Slasar41** [comment]
Same as https://github.com/fmd-project-team/FMD/issues/526

**Comment by Tmp341** [comment]
Please follow #526.
