### ISSUE TITLE
Discord Server invite expired

### ISSUE THREAD

**Issue by molitar** [fmd-project-team/FMD#55]
Unable to join Discord server as the invite is expired.

**Comment by Tmp341** [comment]
https://discord.gg/F8datrf

**Comment by SDXC** [comment]
I created a permanent invitation link. Didn't know I had to explicitly set that.
https://discord.gg/cXKKgw3

**Comment by Tmp341** [comment]
Then you can remove my inv. 😃

**Comment by SDXC** [comment]
As this invite works and is infinite now, I'll close this issue.
