### ISSUE TITLE
Manga on MangaNelo keeps re-downloading 

### ISSUE THREAD

**Issue by molitar** [fmd-project-team/FMD#551]
Ok I have the manga...

Sekkaku Cheat wo Moratte Isekai ni Teni shita n dakara, Suki na you ni Ikitemitai

From MangaNelo but it keeps re-downloading the first 11 chapters repeatedly.

**Comment by Tmp341** [comment]
How? Fmd checks new chapters and finds first 11 chapters again?

**Comment by molitar** [comment]
Yes that is exactly what is happening.

**Comment by Tmp341** [comment]
On which drive is your fmd located? C drive? Maybe fmd can't write on `downloadedchapters.db` file.

**Comment by molitar** [comment]
It's only that one single manga that has this problem. So the file is accessible.  It re-downloaded all 11 chapters again yesterday.  It is only this subscription that is having problems all the others are working fine so the database must be able to be accessed.

**Comment by molitar** [comment]
Ok I figured out the problem but it did not show in favorites. I decided to look at the database and the entry was in the favorites database twice.  May need to key the table to disallow dupes from same site.

**Comment by Tmp341** [comment]
Well, it will be 1-2 times usable feature. You just need to delete database and reupdate it. 

We update databases from time to time. You can download it and manually update it on your end.

**Comment by spamtaztik** [comment]
@Tmp341 I think he meant the manga is listed twice in his bookmarks/favorites, not the series database.

**Comment by Tmp341** [comment]
@spamtaztik No, i meant, should remove favorite and update database (manually or downloading database). Then readd that manga. If you have a favorite manga and if associated website changed it's code, you can't use that favorite anymore.

**Comment by molitar** [comment]
@spamtaztik No I use SQLite and found it was entered twice for the same site.  So I had two for the same site. A simple key on the table to make the manga title and site would make sure it has to be unique preventing two entries from happening.  I manually deleted it from the favorites database the dupe.

**Comment by SDXC** [comment]
@molitar Are you sure that the entries were EXACTLY the same? The row 'websitelink' is a primary key so I'm pretty sure that at least one character was different (for example an additional '/').

Nonetheless I'll close this issue, as you fixed it for yourself.
