### ISSUE TITLE
Chibi Manga download error

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [fmd-project-team/FMD#565]
I've just added a new marker for Chibi Manga to my favorites, but every time I triy to downlad a chapter, it fails. I have enabled, cleared and disabled Cloudfare Bypass just in case it was that, but it still failed every time  (after the last one, I re-enabled it).

Another thing I noticed is that, for some reason, the chapters for that site appear out of order: they are in order per volume, but volumes are in reverse order, with newest first.

**Comment by Slasar41** [comment]
Next Madara module update will fixed image download, but I don't think can fix the chapters order because on the website it's appear that way.

**Comment by l-l-l-l-l-l** [comment]
Fixed (what can be fixed, at least). Thanks.
