### ISSUE TITLE
Chapter download doesn't work [KoMBatch]; Add support for website [MangaSusu]

### ISSUE THREAD

**Issue by wow2134** [fmd-project-team/FMD#566]
failed to download the latest chapter from [kombatch](https://kombatch.com/).
like, I can download chapter 9, but failed to download chapter 35.
and when I try to download it manually the file names are not sequential.
like this
![Capture 01](https://user-images.githubusercontent.com/35753907/66753180-6e673d00-eebd-11e9-9acf-97a5d68fe180.JPG)
and another request is please add [mangadropout](https://mangadropout.net/) in your project.
actually it had been requested by another user
![Capture 02](https://user-images.githubusercontent.com/35753907/66754845-15010d00-eec1-11e9-8c9f-f25568f1ce78.JPG)
or you can also add [mangasusu](https://www.mangasusu.me/) into your project.
these websites like mangazuki, they translate adult manhwa into Indonesian language,
so I hope you guys can make it

sorry for my bad english (90% [Gtl](https://translate.google.com/))

thank you

**Comment by Slasar41** [comment]
I couldn't find "Isekai ni Tensei Shitara..." on KoMBatch.

**Comment by wow2134** [comment]
ah.. sorry, I entered the wrong folder name when downloading manually.
the correct is _Hiraheishi wa Kako wo Yumemiru_

**Comment by Slasar41** [comment]
Should be fixed.
