### ISSUE TITLE
Add support for website [WebtoonsDiscover]

### ISSUE THREAD

**Issue by ElectroShade** [fmd-project-team/FMD#57]
Could Webtoons Discover be added as a new site to FMD?  https://www.webtoons.com/en/challenge

Its a sub-site of Webtoons (http://www.webtoons.com/en) which is already supported. It contains self-published comics that may eventually get picked up to be published on the main Webtoons site. 

Since all the comic pages are formatted similarly to the main Webtoons site you can currently manually put in a discover URL into FMD and it will pick up all the chapters and series summary but it doesn't pick up the title of the series (sets them all as N/A).

So there is a workaround for now to download them but it would be nice if it was officially and fully supported by FMD so they could be searched through and downloaded without having to manually change the favorite name. Thanks if this is possible!

**Comment by SDXC** [comment]
Just some note for myself:
Webtoons is currently a Pascal module. It would be the best to migrate the module to Lua first and add the new website afterwards.

**Comment by SDXC** [comment]
@ElectroShade Webtoons Discover (also called Challenge) will be a part of the normal WebToons script without distinction between different sites. Would that be okay for you?

Additional languages are added as well.

**Comment by SDXC** [comment]
Getting the manga list for challenge mangas could get really ugly. Over 300 pages just to get the titles. We can implement it, but you will probably updating your manga list for an eternity...

**Comment by SDXC** [comment]
I'll add Discover as an option (default disabled).
Because Discover also doesn't have a subdomain, we can't make a separate Website Module for it.

**Comment by SDXC** [comment]
Multilanguage support for WebToons and WebToons Challenge (Discover) added. Lua script will be published soon.

**Comment by SDXC** [comment]
Another info:
Updating manga list for Webtoons Challenge will only go through the latest 1000 pages (for EN there exist about 2650 pages). Everything after that won't be checked/added anymore, you have to manually look for these titles on the website and add them to FMD afterwards.

We will probably add a complete list of entries to our upcoming mangalist archives though.

**Comment by SDXC** [comment]
Script has been released. the script should override the Pascal module implementation in 0.9.162.0.
Pascal module will be removed with 0.9.163.0.

Issue will be closed. Please re-open this issue, if you have problems.

**Comment by ElectroShade** [comment]
@SDXC  Thanks for adding support for this.  I was able to test that the multi-language support worked fine, the Webtoon Challenge checkbox doesn't appear to work though. When I update the manga list it doesn't appear to ever attempt it. Looking at the lua file, could it maybe be because its returning prior to hitting that once it finishes the main Webtoon list? im not all that familiar with lua but if I move the new method to the top or move the return no_error to below it then i think it starts attempting it. 

My only other comment/suggestion is that it would be nice if there was some way to filter the manga list to either show or hide WebToons Challenge manga. 

Also you mentioned manually adding titles to FMD. Is there a simple way to do that currently? Could a "Add to Manga List" button be added so that we could just paste a link into FMD and click it to add that title to the manga list db? if thats not already possible should I log an issue for adding something like that?

**Comment by SDXC** [comment]
@ElectroShade Fetching the Challenge titles (going through 1000 pages of 20 titles per page) takes very long before it starts getting the manga info and updating the list. Does it stop or is it still in the state of looking for new titles?

I could add a suffix [Challenge] after the title if you want.

By adding I meant for your favorites, which is possible through manually paste the urls in the Manga Info tab or by adding the urls by using the Dropbox feature of FMD.

**Comment by ElectroShade** [comment]
@SDXC  It stops. I deleted one of my main Webtoon titles and then updated the list and it found that deleted title and then re-added it. So im guessing its just never even attempting to look for the challenge ones. 

Adding the [Challenge] suffix might work. That would let it be filtered to. Though to filter them out is there a way to to do an exclusion search in the FMD title filter? 

Yeah I can add Favorites manually which is useful. I was more just curious if it would be possible to add to the manga list manually at all. I feel like that might be a nice feature for scenarios where the full list is too large like for Webtoon Challenge. Not sure how challenging that would be to implement though. Just an idea.
