### ISSUE TITLE
Add download manga info as txt 

### ISSUE THREAD

**Issue by Riztard** [fmd-project-team/FMD#571]
download manga info into a folder as txt like artist genre synopsis 
download this each time task started and overwrite if there is any current txt

**Comment by Slasar41** [comment]
Looks like this issue already got it covered, not as txt files though: https://github.com/fmd-project-team/FMD/issues/277

**Comment by Slasar41** [comment]
I think it's the same issue as https://github.com/fmd-project-team/FMD/issues/277 but not saved as txt files though.

**Comment by SDXC** [comment]
The data is actually cached (except chapter list), but the lua scripts currently don't handle that and override the values with empty string when using offline or when problems with the website occurs. Will be handled in later lua script updates, but not actively handled with other mechanisms.
