### ISSUE TITLE
FMD doesn't remove folder after download as zip

### ISSUE THREAD

**Issue by tuanden0** [fmd-project-team/FMD#577]
Hi, I migrated my FMD Riderkick version to this new FMD. Everything is OK but when I download manga as zip, it created a new folder then zip all image. But after zip, they don't move the zipped file to download folder and delete the empty folder such as Riderkick version.

Eg: My download file path: E:\Download
After I download some chapter, they create new folder: E:\Download\some_manga\00x.png, when download complete, they zip file to E:\Download\some_manga\some_manga.zip.

But on Riderkick version, the zipped file move to E:\Download and the E:\Download\some_manga\ was remove.

**Comment by SDXC** [comment]
Did you compare your save-settings between both versions? You probably have some default settings on our version that need to be changed.

**Comment by tuanden0** [comment]
Here's my setting:

[general]
DownloadFilterSelect=0
MangaListSelect=MangaFox,MangaHere,MangaReader
LiveSearch=0
OneInstanceOnly=1
MinimizeOnStart=0
MinimizeToTray=0
DeleteCompletedTasksOnClose=1
SortDownloadsWhenAddingNewDownloadTasks=0
LetFMDDo=0
ExternalProgramPath=
ExternalProgramParams="%PATH%%CHAPTER%"
ChapterListHideDownloaded=0
AddAsStopped=0
HighlightNewManga=1
HighlightDownloadedChapters=1

[droptarget]
Show=0
Mode=0
Opacity=255
Width=64
Heigth=64
Top=-1
Left=-1

[languages]
Selected=en

[view]
ShowDownloadsToolbar=1
ShowDownloadsToolbarLeft=0
ShowFavoritesTabOnNewManga=0
ShowDownloadsTabOnNewTasks=1
ShowDownloadsToolbarDeleteAll=1
LoadMangaCover=1
ShowBalloonHint=0

[connections]
NumberOfTasks=8
NumberOfThreadsPerTask=8
Retry=5
ConnectionTimeout=30
NumberOfAutoRetryFailedTask=1
AlwaysRetruFailedChaptersOnStart=1
OptionEnableCloudflareBypass=1
OptionAutomaticallyDisableCloudflareBypass=0
UseProxy=0
ProxyType=HTTP
Host=
Pass=
Port=
User=

[saveto]
SaveTo=E:\Download\z
ChangeUnicodeCharacter=0
ChangeUnicodeCharacterStr=_
GenerateMangaFolder=0
MangaCustomRename=%MANGA%
Compress=1
PDFQuality=100
RemoveMangaNameFromChapter=0
GenerateChapterFolder=0
ChapterCustomRename=%CHAPTER%
ConvertDigitVolume=1
ConvertDigitChapter=1
DigitVolumeLength=1
DigitChapterLength=1
FilenameCustomRename=%FILENAME%
PNGSaveAsJPEG=0
ConvertWebP=1
PNGCompressionLevel=0
JPEGQuality=80

[update]
AutoCheckLatestVersion=1
AutoCheckFavStartup=1
AutoOpenFavStartup=0
AutoCheckFavInterval=0
AutoCheckFavIntervalMinutes=60
NewMangaTime=1
AutoCheckFavAutoDownload=0
AutoCheckFavAutoRemoveCompletedManga=0
UpdateListNoMangaInfo=0
UpdateListRemoveDuplicateLocalData=0

[modulesupdater]
ShowUpdateWarning=1
AutoRestart=1

[dialogs]
ShowQuitDialog=0
ShowDeleteDldTaskDialog=0
ShowDownloadMangalistDialog=0

[BasicListColors]
BackgroundColor=clWindow
BorderColor=clBtnFace
DisabledColor=clBtnShadow
DropMarkColor=clHighlight
DropTargetColor=clHighlight
DropTargetBorderColor=clHotLight
FocusedSelectionColor=clHighlight
FocusedSelectionBorderColor=clHotLight
GridLineColor=clBtnFace
HeaderHotColor=clBtnShadow
HotColor=clWindowText
SelectionRectangleBlendColor=clHighlight
SelectionRectangleBorderColor=clHotLight
TreeLineColor=clBtnShadow
UnfocusedSelectionColor=clBtnFace
UnfocusedSelectionBorderColor=clBtnShadow
NormalTextColor=clWindowText
FocusedSelectionTextColor=clWindowText
UnfocusedSelectionTextColor=clWindowText
OddColor=clBtnFace
EvenColor=clWindow
SortedColumnColor=$00F8E6D6

[MangaListColors]
NewMangaColor=$00FDC594
CompletedMangaColor=$00B8FFB8

[FavoriteListColors]
BrokenFavoriteColor=$008080FF
CheckingColor=$0080EBFE
NewChapterFoundColor=$00FDC594
CompletedSeriesColor=$00B8FFB8
EmptyChapters=$00CCDDFF

[ChapterListColor]
DownloadedColor=$00B8FFB8

[logger]
Enabled=0
LogFileName=E:\Soft\FMD\fmd.log

[form]
DownloadsSplitter=152
MangaInfoSplitter=145
pcMainPageIndex=0
SelectManga=0
MainFormMaximized=0
MainFormLeft=708
MainFormTop=214
MainFormWidth=558
MainFormHeight=515

[vtDownload]
SortColumn=-1
SortDirection=0
Column0Width=176
Column0Position=0
Column1Width=105
Column1Position=1
Column2Width=55
Column2Position=2
Column3Width=50
Column3Position=3
Column4Width=65
Column4Position=4
Column5Width=150
Column5Position=5
Column6Width=80
Column6Position=6

[vtFavorites]
SortColumn=-1
SortDirection=0
Column0Width=50
Column0Position=0
Column1Width=150
Column1Position=1
Column2Width=100
Column2Position=2
Column3Width=65
Column3Position=3
Column4Width=200
Column4Position=4

[vtLuaModulesRepos]
SortColumn=-1
SortDirection=0
Column0Width=150
Column0Position=0
Column1Width=110
Column1Position=1
Column2Width=250
Column2Position=2

[vtAccountList]
SortColumn=-1
SortDirection=0
Column0Width=25
Column0Position=0
Column1Width=50
Column1Position=1
Column2Width=50
Column2Position=2
Column3Width=50
Column3Position=3
