### ISSUE TITLE
Website doesn't work anymore [Fallen Angel Scans]

### ISSUE THREAD

**Issue by JokoeSukri** [fmd-project-team/FMD#58]
I found This Problem After Update FMD 0.9.162.0
![Screenshot_22](https://user-images.githubusercontent.com/32964994/55690888-3cd35d80-59d2-11e9-9a4f-370d1856842f.jpg)

**Comment by Tmp341** [comment]
Let me test it for myself.

**Comment by AbidZakaria** [comment]
problem with cloudflare

after adding cokkie and Useragent
![image](https://user-images.githubusercontent.com/19544118/55705119-3c55b980-5a08-11e9-8e28-e7c343535782.png)

**Comment by AbidZakaria** [comment]
> I found This Problem After Update FMD 0.9.162.0
> ![Screenshot_22](https://user-images.githubusercontent.com/32964994/55690888-3cd35d80-59d2-11e9-9a4f-370d1856842f.jpg)

try this https://github.com/fmd-project-team/FMD/issues/61

**Comment by Tmp341** [comment]
Ok, now i think Firefox doesn't show all necessary cookie infos. ı've made it work like this:

- Installed Opera.
- Opened FallenAngels, opened a manga.
- **Ctrl + Shift + I** for Developer tools -> Network tab -> Ctrl + R or F5 
- Tap on something, like first thing on the list.
- Be sure you're on ``Headers`` tab. Then scroll down until you see **cache-control:** and **cookie:**
- Copy the whole cookie, paste it in FMD cookie, like this : 

`__cfduid=xxxxxxxxxxxxxxxxxxxxx;`
`cf_clearance=xxxxxxxxxxxxxx;` 
`_ga=xxxxxxxxxxxxxxxx;`
`_gid=xxxxxxxxxxxxxxxxx; `
`XSRF-TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; `
`laravel_session=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

**Comment by Tmp341** [comment]
For firefox: 

- Opened FallenAngels, opened a manga.
- **F12** for Developer tools -> Network tab -> F5 
- Tap on something, like first thing on the list.
- Be sure you're on ``Cookies`` tab. Then scroll down, ``Request Cookies`` (or similar in English or in your language``
- Copy and paste entries in FMD cookie, like this : 

`__cfduid=xxxxxxxxxxxxxxxxxxxxx;`
`cf_clearance=xxxxxxxxxxxxxx;` 
`XSRF-TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; `
`laravel_session=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

Remove the double ``==`` at the end of ``laravel_session``.

**Comment by JokoeSukri** [comment]
Yes, I always check every webside I have visited if it has cloudfare, 
I use cookies on advanced modules, but still no avail, 
After struggle it out, It seems, I got problem with my service provider in my country, 
Because, it works again after I use with Proxy
![Screenshot_23](https://user-images.githubusercontent.com/32964994/55714147-0bd44680-5a2d-11e9-8abb-c057e2841ac8.jpg)
![Screenshot_24](https://user-images.githubusercontent.com/32964994/55714162-10006400-5a2d-11e9-813b-2548fef3436e.jpg)

**Comment by JokoeSukri** [comment]
Yep, The problem solved. Thank you
