### ISSUE TITLE
Website not working [Tumangaonline]

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#588]
![12asad](https://user-images.githubusercontent.com/48584512/67741658-a5c70500-f9f8-11e9-9e9c-288c28af629a.png)

They should put the option to fill CAPTCHA as HakuNeko has.
I think it is the only solution for tumangaonline
![223](https://user-images.githubusercontent.com/48584512/67741847-1a01a880-f9f9-11e9-802c-245041425b7a.png)

**Comment by Slasar41** [comment]
First, try go to Options -> Websites -> Advanced -> Tumangaonline. The `DisableCloudflareBypass` option is set to `False` or `True`?

**Comment by djgerman10** [comment]
It is by default.

Do I have to put some cookies or something?

![346](https://user-images.githubusercontent.com/48584512/67827282-4dead580-faae-11e9-83a7-7d96eb357c5c.jpg)

**Comment by Slasar41** [comment]
I think some ISP somehow will activate captcha function in cloudflare.
Try to use an VPN.

**Comment by SDXC** [comment]
If cf_cloudflare doesn't work, use the manual workaround. In case of Captchas, you have to do that anyway.

Also we can't add the same functionality like HakuNeko as we don't have an accessible and cleanly working webbrowser component for pascal including JavaScript support.

**Comment by djgerman10** [comment]
Is there any way to pass the captcha manually? with cookies or something?

-If you explain to me how to do it, I would be very grateful

**Comment by Tmp341** [comment]
Captcha is only for humans, you can't bypass it manually with another app. You should open that website, bypass it, then get manual cookies.

**Comment by djgerman10** [comment]
![qwe](https://user-images.githubusercontent.com/48584512/68105991-f938c780-febe-11e9-980a-ec5de26f92f9.png)
What cookies do I have to copy?

**Comment by SDXC** [comment]
you need the cf_clearance and __cfduid cookies.
You can use this example (works the same way):
https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-JapScan

**Comment by djgerman10** [comment]
![zx](https://user-images.githubusercontent.com/48584512/68146909-bb1bc200-ff17-11e9-9240-59713739852d.png)
thank you very much walked me walked perfect

**Comment by SDXC** [comment]
Don't forget that you have to renew your cookies regularly. If you have to resolve a captcha in your browser, you will need to renew your cookies in FMD as well.

**Comment by syleniaa** [comment]
it was working fine until friday, i don't understand why is having problem now. in the browser the website doesn't ask me any captcha, but now even with the work around it doesn't show me the chapters. i copy __cfduid, cf_clearance and tumangaonline_session, do i need any other??

**Comment by djgerman10** [comment]
yes yes the page doesn't go anymore

**Comment by SDXC** [comment]
The main topic of this issue has been answered.
I will close it.

For the current problem with getting the chapter list, please keep track in this issue:
https://github.com/fmd-project-team/FMD/issues/609
