### ISSUE TITLE
[MangaDex] Issue with checking for new chapters, view manga info and dragging new title to Favorites tab

### ISSUE THREAD

**Issue by gooreat** [fmd-project-team/FMD#59]
Not sure if it's just me, but some reason none of the aforementioned features are working after updating FMD to the latest version (0.9.162.0). 

Thanks!

**Comment by Tmp341** [comment]
Can you give use more info?

- Can you reach mangadex via browser?
- Is your fmd downloading normally?

**Comment by SDXC** [comment]
I'm pretty sure that MangaDex was in mitigation mode.

**Comment by gooreat** [comment]
> Can you give use more info?
> 
>     * Can you reach mangadex via browser?
Yep. Had no trouble accessing it.

>     * Is your fmd downloading normally?
I'm sure it's working normally, since I can download/check new chapters from other sites (besides the problematic ones). Again, this is on the latest version, 0.9.162.0. 

>     * What is not working?
As I've mentioned it on the thread title. I can't:
* Check for new chapters via Favorites tab (always get the default 'red' mark color)
* View manga info (always shows blank result, N/A etc)
* Load new manga title into the Favorites, which can be done by dragging the clickable manga title (doesn't work on most sites, only supported ones, iirc. But it always works on MD before).

**Comment by AbidZakaria** [comment]
mangadex adding cloudfire in website
please read this wiki https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation

same issue https://github.com/fmd-project-team/FMD/issues/2

![image](https://user-images.githubusercontent.com/19544118/55704555-9786ac80-5a06-11e9-8770-0e97f15994bd.png)

![image](https://user-images.githubusercontent.com/19544118/55704622-ca30a500-5a06-11e9-81d9-a6374120c57a.png)

**Comment by AbidZakaria** [comment]
> > Can you give use more info?
> > ```
> > * Can you reach mangadex via browser?
> > ```
> 
> Yep. Had no trouble accessing it.
> 
> > ```
> > * Is your fmd downloading normally?
> > ```
> 
> I'm sure it's working normally, since I can download/check new chapters from other sites (besides the problematic ones). Again, this is on the latest version, 0.9.162.0.
> 
> > ```
> > * What is not working?
> > ```
> 
> As I've mentioned it on the thread title. I can't:
> 
> * Check for new chapters via Favorites tab (always get the default 'red' mark color)
> * View manga info (always shows blank result, N/A etc)
> * Load new manga title into the Favorites, which can be done by dragging the clickable manga title (doesn't work on most sites, only supported ones, iirc. But it always works on MD before).
> 
> EDIT:
> @SDXC Hopefully that's the case. I've also noticed Cloudflare kicking in when I tried to access it just now. Will try again later and see if there any changes.

try thi https://github.com/fmd-project-team/FMD/issues/61

**Comment by SDXC** [comment]
MangaDex is getting bigger and bigger and that is something most aggregator sites don't like because many of their own userbase migrate to MD. So I'm not surprised, that MD is getting targeted by many DDoS attacks.

Good thing: Mitigation works pretty well if you get an active session. It's like nothing is going on. FMD is only a bit unflexible right now when it comes to Cloudflare. It's also my personal opinion, but when mitigation is active it would be better when users don't use FMD until everything is back to normal. That's what I do as well. I just have to catch up reading a bit later.

**Comment by Tmp341** [comment]
@gooreat Try the workaround I've explained in #58 

I've explained for 2 browsers, Firefox and Opera. Try using similar workaround for Mangadex, withour and/or with your user (account) info.

**Comment by gooreat** [comment]
Well. well. would you look at that, MD is working again. Just when I'm about to try the above workaround lol
@SDXC I see. Guess I'll just wait for awhile if it does happen again

@AbidZakaria @Tmp341 Bookmarked the workaround. Thanks :D

Closing this since it has been resolved.
