### ISSUE TITLE
Make a youtube tutorial for writing new modules in FMD 

### ISSUE THREAD

**Issue by ahmadi3d** [fmd-project-team/FMD#593]
I read some of the module written in lua, and i kinda understood them but still i was also baffled, is it possible to make a 15 minute tutorial video on how to write a new module ?  
I really like to contribute if i can.
Thanks.

**Comment by Tmp341** [comment]
Doing video will take time, which our developer doesn't have much. So, you can do what you can, create a PR then wait for it to be fixed/approved.

**Comment by SDXC** [comment]
I'm sorry but i don't have time for making videos. Another reason is, that I don't even have a documentation which I could use as a reference for a video, so we don't have a stable base to make a useful video out of.
