### ISSUE TITLE
Chapter download only gets first page for all pages [NineMangaES]

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#594]
### do not download ninemangaES correctly

**-** Download the manga but all pages have the same image.
![22222222](https://user-images.githubusercontent.com/48584512/68070370-084b3880-fd4c-11e9-96b4-e04a7f3fc2dc.png)
![222222111111](https://user-images.githubusercontent.com/48584512/68070372-0d0fec80-fd4c-11e9-9d83-ada5e7a3f1ae.png)

**-** warning also appears in the web address
![3333](https://user-images.githubusercontent.com/48584512/68070396-709a1a00-fd4c-11e9-901e-a34cca16e539.png)

_to complete that your [manga online] is not working now stop walking [ninemangaES]_
![13607039](https://user-images.githubusercontent.com/48584512/68070454-4137dd00-fd4d-11e9-85e3-89ff3efeba55.jpg)

**Comment by JavikusRod** [comment]
In the settings this is the cookies the programs get me : 
__cfduid=d90c59af900dadbac7db8e618c37019b91573043451;cf_clearance=
and the user agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36

**Comment by djgerman10** [comment]
no it's not the captcha problem it's a problem that downloads only one page of the chapter

**Comment by KvotheDeimos** [comment]
Apparently NineMangaES visualizes each chapter on a separate website.
Dr. Stone example: https://www.gardenmanage.com/statuses/860721.html.

I am sure the problem is part of this.

**Comment by djgerman10** [comment]
I don't think that's the problem is a script error, because it only downloads the first image of the chapters [ESNinemanga](http://es.ninemanga.com/)

**Comment by SDXC** [comment]
NineManga ported to lua and fixed all. You should be able to download again after the lua modules have been updated.

**Comment by djgerman10** [comment]
thank you very much genius

_Should I put, an option to donate on PayPal in FMD_
