### ISSUE TITLE
havent been able to download from hitomila since the last update....

### ISSUE THREAD

**Issue by necropower** [fmd-project-team/FMD#599]
havent been able to download from hitomila since the last update....
and i cant even add new files to be download now...

**Comment by AbidZakaria** [comment]
try fresh install
https://github.com/fmd-project-team/FMD/wiki#fresh-install

**Comment by allydevper** [comment]
Me too. and i try download all project and nothing.
![Captura](https://user-images.githubusercontent.com/28413681/68221960-40ef4a00-ffb8-11e9-9e00-833689145b7e.JPG)

and the error in the log show.

```
Error: cf_bypass has encountered a problem with the website [HitomiLa]
Traceback (most recent call last):
  File "cf_bypass.py", line 29, in <module>
  File "cfscrape\__init__.py", line 351, in get_tokens
ValueError: Unable to find Cloudflare cookies. Does the site actually have Cloudflare IUAM ("I'm Under Attack Mode") enabled?
```

**Comment by Slasar41** [comment]
I can see the manga info with the new link but can't download it.
Need module and database update.
![image](https://user-images.githubusercontent.com/28888646/68222855-467f7b00-001e-11ea-9f6e-4bd3fbd5df25.png)

**Comment by necropower** [comment]
> 
> 
> try fresh install
> https://github.com/fmd-project-team/FMD/wiki#fresh-install

I did, still with the same problem

**Comment by necropower** [comment]
> 
> 
> Me too. and i try download all project and nothing.
> ![Captura](https://user-images.githubusercontent.com/28413681/68221960-40ef4a00-ffb8-11e9-9e00-833689145b7e.JPG)
> 
> and the error in the log show.
> 
> ```
> Error: cf_bypass has encountered a problem with the website [HitomiLa]
> Traceback (most recent call last):
>   File "cf_bypass.py", line 29, in <module>
>   File "cfscrape\__init__.py", line 351, in get_tokens
> ValueError: Unable to find Cloudflare cookies. Does the site actually have Cloudflare IUAM ("I'm Under Attack Mode") enabled?
> ```

got the same problem

Error: cf_bypass has encountered a problem with the website [HitomiLa]
Traceback (most recent call last):
  File "cf_bypass.py", line 29, in <module>
  File "cfscrape\__init__.py", line 351, in get_tokens
ValueError: Unable to find Cloudflare cookies. Does the site actually have Cloudflare IUAM ("I'm Under Attack Mode") enabled?

**Comment by AbidZakaria** [comment]
> > Me too. and i try download all project and nothing.
> > ![Captura](https://user-images.githubusercontent.com/28413681/68221960-40ef4a00-ffb8-11e9-9e00-833689145b7e.JPG)
> > and the error in the log show.
> > ```
> > Error: cf_bypass has encountered a problem with the website [HitomiLa]
> > Traceback (most recent call last):
> >   File "cf_bypass.py", line 29, in <module>
> >   File "cfscrape\__init__.py", line 351, in get_tokens
> > ValueError: Unable to find Cloudflare cookies. Does the site actually have Cloudflare IUAM ("I'm Under Attack Mode") enabled?
> > ```
> 
> got the same problem
> 
> Error: cf_bypass has encountered a problem with the website [HitomiLa]
> Traceback (most recent call last):
> File "cf_bypass.py", line 29, in
> File "cfscrape__init__.py", line 351, in get_tokens
> ValueError: Unable to find Cloudflare cookies. Does the site actually have Cloudflare IUAM ("I'm Under Attack Mode") enabled?

for you try get manual cookie
please read this link https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-JapScan

**Comment by Slasar41** [comment]
> for you try get manual cookie
> please read this link https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-JapScan

No, he need to put the new link from the browser to FMD because the link in database can't be used again.
But the module need to be changed first to fix the download problem.

**Comment by Tmp341** [comment]
> But the module need to be changed first to fix the download problem.

So:

1. Something in the **[Hitomi.la](https://github.com/fmd-project-team/FMD/blob/master/lua/modules/HitomiLa.lua)** module is broken. A fix is needed.
2. Then, someone with an access to site needs to update it's database.

**Comment by Hypertyrannical** [comment]
It seems that the database download retrieves old links that redirect to the new links, but the module does not have any way of waiting for the redirection to the new link, so it comes back with nothing.

I've been looking around in other modules trying to figure out if anyone has done something like this but haven't found anything concrete.

**Comment by dazedcat19** [comment]
Added option "download webp". It's true by default.

@Tmp341 it needs a new database

**Comment by Tmp341** [comment]
@dazedcat19 Is this supposed to happen? : 

![ssss](https://user-images.githubusercontent.com/1683388/74216595-f6b3ee00-4cb5-11ea-90dd-c472feb3659c.jpg)

**Comment by dazedcat19** [comment]
Who wrote the update list script? Where he even get that list `https://ltn.hitomi.la/index-all.nozomi` that file indexed all the gallery number only.

**Comment by Slasar41** [comment]
He's kmvi, former developer.

**Comment by dazedcat19** [comment]
There's traditional way but may take forever to load. I pushed a change to load this gallery link.
This website has a very long list. It's not practical to have the database. They may add hundreds of record per day. It's faster to open the website with a browser instead. Then use drag-n-drop to download.

**Comment by Slasar41** [comment]
Maybe throw an error that this website doesn't have a manga list like hakuneko one, could FMD do that?
https://github.com/manga-download/hakuneko/blob/800fdc26c09160b2b9c12a52d37caa6366cd8d3f/src/web/mjs/connectors/Hitomi.mjs

**Comment by dazedcat19** [comment]
There's already an error when trying to download non-existent databases. In theory all website should have a database. We just unable to maintain it.

**Comment by Tmp341** [comment]
FMD showed that Hitomi has 500k+ titles. :D That's why i stopped updating it.
