### ISSUE TITLE
[April Fools Issue] With MangaDex

### ISSUE THREAD

**Issue by JokoeSukri** [fmd-project-team/FMD#6]
**FAQ**

- Why I cant download at mangadex?? 

- I use tutorial wiki to bypass Cloud Flare why still cant downloading

- Why Mangadex change into MangaCat

**Answer :** This is 1st april

Some of Devs change the script to fools some people, Even you try Bypass with CF cookie, you can't download at mangadex for now. And the script still changing, depending on the depth of the Joke

![999](https://user-images.githubusercontent.com/32964994/55296462-ccb65c00-5454-11e9-8d14-ba370d5ba934.jpg)
![9999](https://user-images.githubusercontent.com/32964994/55296463-cd4ef280-5454-11e9-909a-1b687b87a038.jpg)

**Comment by JokoeSukri** [comment]
and I'll wait for SDXC answer

**Comment by SDXC** [comment]
Just a side note: on days such as april fools day we all probably shouldn't try to do anything, rather wait a day or two and try again. It's much safer for your favorites and in some cases no issues are needed as they fix itself.
