### ISSUE TITLE
Website changed domain [LeoManga]

### ISSUE THREAD

**Issue by thorio2002** [fmd-project-team/FMD#60]
Leo manga changed its domain from ".com" to ".xyz" and can no longer be downloaded.

**Comment by rs3mk** [comment]
It's not leomanga, it's another scraping site

**Comment by SDXC** [comment]
Just to make sure: leomanga.com is offline and leomanga.xyz is a new aggregator website that just took on the name or it's the same guys but with a new domain AND website?

**Comment by rs3mk** [comment]
It's another site, leomanga.com is dead. On their facebook they do not mention a new page: https://www.facebook.com/leomanga.online

**Comment by SDXC** [comment]
Okay, will be added as a new website then.

**Comment by SDXC** [comment]
Note to myself: Old LeoManga is a Pascal module. Has to be removed. New LeoManga module will be in Lua.

**Comment by SDXC** [comment]
Does anyone have a favorites.db with entries of the old LeoManga website? I want to check, if I can take over the links or if I have to create new LeoManga as "LeoMangaXYZ" instead of "LeoManga".

**Comment by AbidZakaria** [comment]
leomanga done created lua file

**Comment by SDXC** [comment]
Thanks to @AbidZakaria the website has now been changed to the new url and is now a lua script.

Issue will be closed. If you have problems with the new website you can re-open this issue.
