### ISSUE TITLE
Unable to download from mangakakalot

### ISSUE THREAD

**Issue by dreamboatcap** [fmd-project-team/FMD#604]
I am unable to download from mangakakalot. Anyone having the same issue or is it just me?

**Comment by Slasar41** [comment]
See: https://github.com/fmd-project-team/FMD/issues/591

**Comment by Tmp341** [comment]
Some titles redirect to Manganelo. You can move those titles to Manganelo or wait for Mangakakalot to stop redirecting those titles. See #591 just like @Slasar41 said.
