### ISSUE TITLE
those of you who have problems with cloudflare please try this

### ISSUE THREAD

**Issue by AbidZakaria** [fmd-project-team/FMD#61]
look for your website that wants to be filled,
check and fill in the form as it was drawn
![image](https://user-images.githubusercontent.com/19544118/55705474-1250c700-5a09-11e9-8646-25a2cb1f85b9.png)

and at the bottom as drawn
![image](https://user-images.githubusercontent.com/19544118/55705542-357b7680-5a09-11e9-9406-6af85b577cf6.png)

fill as I wrote
==================
MangaDex

cookie
-------------------------------
__cfduid=d174ecaf764df6f09d203191e4977255f1554706575; cf_clearance=bb32aeee88819325c7f267747bb4f3c3db6ea357-1554706623-86400-150

useragent
-------------------------------
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.127
===================

FallenAngelScan

cookie
------------------------------------
__cfduid=d11ad75aab7a35a1a98969305b25819bd1554707394; XSRF-TOKEN=eyJpdiI6InZMNUdGZ3JGZHpDNnB0cTluVldXeHc9PSIsInZhbHVlIjoiaElaQUZpNnZjNkJiRkxJZmxOUHo1b0IzcDhRRHI4K3Nsb0ZrZHRJVFdnTGpkOXBZM2hwSmxvMVNONTR5QzlBQ1duMXkrRlRQVDRwVUxkN1M3Wm5vVFE9PSIsIm1hYyI6ImNkN2NjNDQ5MjdmNWM1YjI4YzBhNWRiMWVjY2M0MzJjNmVkZjRlMjQ1YmJhZGY2Yjg2OTJlODA3OGY5NDQ4NzAifQ%3D%3D; laravel_session=eyJpdiI6IlJKampVRHlHUlFtT2cwMEpadnBMenc9PSIsInZhbHVlIjoiTnBXMFwveXcza05jYzNCUWEwTktUREdZemNHMXRNV2swOEUxVFRCWnJ0M2tlQU0yeHZcL2lrSTBCVllUOEJXVnZ2UzFZcnpiQ0lWVWtsN0ZEcnA1bVdPZz09IiwibWFjIjoiZmY2YTg2OGQ3YzY5ZTlhMjA2OGY5YWM2OGEyMmIyY2IyYmQ3MTFlNjRjZWQzYTdjN2QzMjBkNDlhOGE2NzdlMyJ9; _ga=GA1.2.977887877.1554707406; _gid=GA1.2.133363285.1554707406; cf_clearance=a1756b402c22a36c05b060a747bf895a8d7b5c88-1554709652-1800-150

useragent
--------------------------------------
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.127
=======================================

ReadComicOnline

cookie
-----------------------------------------
_ga=GA1.2.1807997439.1554612119; BB_plg=pm; bbbi=55611ea1-c3ec-4409-8c6d-bcd8c8b48837; __unam=6f7af7d-169f61a89ed-55e3b402-2; cf_clearance=4af812cfd4ceaea8a1d818513c9c3b826aac2891-1554709261-1800-150

useragent
---------------------------------------
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.127

**Comment by Tmp341** [comment]
I still can't get mangalist.

**Comment by AbidZakaria** [comment]
what manga?

**Comment by Tmp341** [comment]
All of them. I get manga name, manga info, but not the list or cover.

**Comment by AbidZakaria** [comment]
for fallenmanga 
try this

cookie
__cfduid=d11ad75aab7a35a1a98969305b25819bd1554707394; XSRF-TOKEN=eyJpdiI6InZMNUdGZ3JGZHpDNnB0cTluVldXeHc9PSIsInZhbHVlIjoiaElaQUZpNnZjNkJiRkxJZmxOUHo1b0IzcDhRRHI4K3Nsb0ZrZHRJVFdnTGpkOXBZM2hwSmxvMVNONTR5QzlBQ1duMXkrRlRQVDRwVUxkN1M3Wm5vVFE9PSIsIm1hYyI6ImNkN2NjNDQ5MjdmNWM1YjI4YzBhNWRiMWVjY2M0MzJjNmVkZjRlMjQ1YmJhZGY2Yjg2OTJlODA3OGY5NDQ4NzAifQ%3D%3D; laravel_session=eyJpdiI6IlJKampVRHlHUlFtT2cwMEpadnBMenc9PSIsInZhbHVlIjoiTnBXMFwveXcza05jYzNCUWEwTktUREdZemNHMXRNV2swOEUxVFRCWnJ0M2tlQU0yeHZcL2lrSTBCVllUOEJXVnZ2UzFZcnpiQ0lWVWtsN0ZEcnA1bVdPZz09IiwibWFjIjoiZmY2YTg2OGQ3YzY5ZTlhMjA2OGY5YWM2OGEyMmIyY2IyYmQ3MTFlNjRjZWQzYTdjN2QzMjBkNDlhOGE2NzdlMyJ9; _ga=GA1.2.977887877.1554707406; _gid=GA1.2.133363285.1554707406; cf_clearance=a1756b402c22a36c05b060a747bf895a8d7b5c88-1554709652-1800-150

**Comment by AbidZakaria** [comment]
there is something hidden in fallen manga

**Comment by AbidZakaria** [comment]
@Tmp341 it's work?

**Comment by Slasar41** [comment]
> for fallenangle
> try this
> 
> cookie
> __cfduid=d11ad75aab7a35a1a98969305b25819bd1554707394; XSRF-TOKEN=eyJpdiI6InZMNUdGZ3JGZHpDNnB0cTluVldXeHc9PSIsInZhbHVlIjoiaElaQUZpNnZjNkJiRkxJZmxOUHo1b0IzcDhRRHI4K3Nsb0ZrZHRJVFdnTGpkOXBZM2hwSmxvMVNONTR5QzlBQ1duMXkrRlRQVDRwVUxkN1M3Wm5vVFE9PSIsIm1hYyI6ImNkN2NjNDQ5MjdmNWM1YjI4YzBhNWRiMWVjY2M0MzJjNmVkZjRlMjQ1YmJhZGY2Yjg2OTJlODA3OGY5NDQ4NzAifQ%3D%3D; laravel_session=eyJpdiI6IlJKampVRHlHUlFtT2cwMEpadnBMenc9PSIsInZhbHVlIjoiTnBXMFwveXcza05jYzNCUWEwTktUREdZemNHMXRNV2swOEUxVFRCWnJ0M2tlQU0yeHZcL2lrSTBCVllUOEJXVnZ2UzFZcnpiQ0lWVWtsN0ZEcnA1bVdPZz09IiwibWFjIjoiZmY2YTg2OGQ3YzY5ZTlhMjA2OGY5YWM2OGEyMmIyY2IyYmQ3MTFlNjRjZWQzYTdjN2QzMjBkNDlhOGE2NzdlMyJ9; _ga=GA1.2.977887877.1554707406; _gid=GA1.2.133363285.1554707406; cf_clearance=a1756b402c22a36c05b060a747bf895a8d7b5c88-1554709652-1800-150

Different IP got different cookies.
I try yours and not working, but when I got it myself it's working.
![image](https://user-images.githubusercontent.com/28888646/55707760-9194c980-5a0e-11e9-87b0-817e285765ac.png)

**Comment by AbidZakaria** [comment]
ok
just trying and
thank you for trying

and delete this issue
