### ISSUE TITLE
Can't get chapter list [Readcomiconline]

### ISSUE THREAD

**Issue by EpicLunchBox** [fmd-project-team/FMD#617]
The title and other info shows up when I click on the comic I want to download, but not the chapter or cover image. 

![image](https://user-images.githubusercontent.com/29029681/68551209-0cbcc480-03d0-11ea-8ef7-c83491496cd3.png)

At first, I thought it would be a problem with cf_bypass, so I tried to download a random manga from KissManga and it worked, the chapter and the cover appeared.

![image](https://user-images.githubusercontent.com/29029681/68551222-468dcb00-03d0-11ea-8626-84c81663cfdf.png)

Probably its just my computer but I hope u can help me with this issue.

**Comment by Tmp341** [comment]
So, you've tried CF workaround?

**Comment by Slasar41** [comment]
I can access it.
![image](https://user-images.githubusercontent.com/28888646/68613639-c95a7700-04f1-11ea-8de9-70e53f834043.png)
Go to Options -> Websites -> Advanced -> ReadComicOnline. Make sure the `DisableCloudflareBypass` option is set to `False`.
![image](https://user-images.githubusercontent.com/28888646/68613758-11799980-04f2-11ea-8084-9482a24a3118.png)

**Comment by EpicLunchBox** [comment]
> So, you've tried CF workaround?

Yeah, at least I tried with Kissmanga, no luck with Readcomic.

**Comment by EpicLunchBox** [comment]
> I can access it.
> ![image](https://user-images.githubusercontent.com/28888646/68613639-c95a7700-04f1-11ea-8de9-70e53f834043.png)
> Go to Options -> Websites -> Advanced -> ReadComicOnline. Make sure the `DisableCloudflareBypass` option is set to `False`.
> ![image](https://user-images.githubusercontent.com/28888646/68613758-11799980-04f2-11ea-8084-9482a24a3118.png)

I just checked and it’s set to false. Sadly still not working for me.

**Comment by ivanm48** [comment]
I have the same problem as you with one extra.

Not only does it never load but the entire program freezes, I can't switch to another site or close the program.

I have to forcefully close it in task manager.

**Comment by SDXC** [comment]
is this still a problem with 0.9.167.2?
i tested the same title you tried (The Flash (2016)) and it worked.

if you're using a VPN/Proxy that could also be an issue.

**Comment by EpicLunchBox** [comment]
> is this still a problem with 0.9.167.2?
> i tested the same title you tried (The Flash (2016)) and it worked.
> 
> if you're using a VPN/Proxy that could also be an issue.

I just update to 0.9.167.2 and the problem stills. Ironically I just figured out that if I use a VPN it works perfectly. So I asume it was a problem with my IP all this time.

Sorry for the inconvenience and thanks for the support. :-)
