### ISSUE TITLE
Just a question, not really an issue

### ISSUE THREAD

**Issue by spamtaztik** [fmd-project-team/FMD#618]
Can someone recommend me a good android app that can be used to read long-strip manhuas please? I'm currently using x-plore for my file manager/image viewer but texts & images come up very blurry on 7MB+ long strip files, and the app simply chokes on long strips that's 10MB or more. It can open big files just fine as long as it's not long strip.

So, anyone?
Thanks.

**Comment by Slasar41** [comment]
Try http://www.mangabirdapp.com
It can also display manga that stored locally and has continuous vertical scrolling.

**Comment by spamtaztik** [comment]
Awesome. Thanks much!
