### ISSUE TITLE
Add support for website [MangaPlus]

### ISSUE THREAD

**Issue by rs3mk** [fmd-project-team/FMD#62]
supports multi-languages: https://mangaplus.shueisha.co.jp/updates

thanks

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.

**Comment by Sakurahime08** [comment]
Hope you can add this sooner since Mangastream has shut down already and to be able to download latest chapters. Thank you!

**Comment by alzamer2** [comment]
hi i'm i dont know any thing about pascal
but i was able to wrote python scrit that let you download from manga plus, you can use it as ref
[mangaplus.zip](https://github.com/fmd-project-team/FMD/files/4242680/mangaplus.zip)

ps:this is simple script i use so i dont guaranty that it will work out in all manga as i only tested itt out on some title only (which i read)

**Comment by gin9980** [comment]
Theres a script out that can rip from Mangaplus. Is it possible to add this in soon?
