### ISSUE TITLE
Kissmanga no longer works due to Captions.. Can you implement caption capability?

### ISSUE THREAD

**Issue by molitar** [fmd-project-team/FMD#620]
Seems that we need a way to manually enter in captions now.  This is not the first site I see doing this now.  Is it possible to add the capability for us to complete captions in FMD itself?

**Comment by SDXC** [comment]
Not with FMD.

And in case of KissManga it is probably only temporary. When the load on the website gets too much, Captchas kick in. After the load normalizes the Captchas will probably be disabled.

It is also possible that you had too much hits on KissManga or at least while they were having much traffic. In such cases Cloudflare decides which you will get.

Just now I tested KissManga and I got the normal Cloudflare page.

**Comment by molitar** [comment]
Well not sure I log into the browser on Kissmanga just fine and done the cloudflare caption and it works just fine then.  But I still unable to even retrieve even the manga info from FMD.  That is why I was asking what does the Cloudflare bypass identify itself as?  What browser I can then try to login with that browser and see if works then.

Right now Kissmanga is still down for me.

**Comment by IgnatiusC** [comment]
Been having the same problem since last night, Kissmanga on Tachiyomi is broken too. Hopefully it's fixable.

**Comment by Slasar41** [comment]
I don't have a problem with KissManga.
![image](https://user-images.githubusercontent.com/28888646/68703299-ead46500-05bc-11ea-9c97-d46fe871104d.png)
Try this guide: https://github.com/fmd-project-team/FMD/wiki#troubleshooting-guides
Sometimes I do that if KissManga has a problem.

**Comment by molitar** [comment]
Yep I had to go back to the old method of using the keys manually.  Can you tell me what browser that the Cloudbypass identifies itself as?  I might be able to open in that browser then do the caption and have FMD work properly then.
 
I did this on one other site that added caption but on that one I just opened it in any browser did the caption and FMD worked.  But seems that Kissmanga is not looking at IP address but browser header as I had to do the caption in both Firefox and Chromium to get in. So it appears that it's caption is looking at browser header also.

**Comment by Slasar41** [comment]
I don't think you can manually set the Cookies without also having the UserAgent with the same IP address.
I have tested it, if I change the browser (Chrome/Edge) with the same IP address then the cookies will changed, if I just change the IP address (Disconnect and reconnect the modem) without changing the browser then the cookies will also changed.

**Comment by molitar** [comment]
This site has become more of a pain than anything.. removed it from my checked list and moved to Mangadex.  Think it's about time to retire Kissmanga completely even now that it's not asking for captions after not accessing it for a week now it still will not retrieve any chapters.  You spend more time trying to fix this site.  

Since this is a nice free application I think these sites that just keep doing this are not even worth wasting time on and just dropping support for them would actually be best so we can work on new sites that are good and new features.

**Comment by Tmp341** [comment]
Rather than removing support, it will be left alone. After some time, it might be updated again (if development won't be dropped). If a website isn't working, go to another. It is stupid to waste time on their *precious* website.

**Comment by SDXC** [comment]
as cf_bypass has been fixed i'll close this issue.
