### ISSUE TITLE
Update manga list for download

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#621]
Can you guys update the downloadable manga list from server (especially English website and H-sites, since some arent available to download and some have too many list to update)?
I tried to update manually for manga list that isnt available but the list is too long and weirdly fail when i left the PC.

**Comment by Tmp341** [comment]
We update them from time to time. [This](https://github.com/fmd-project-team/FMD-WebsiteDatabases/tree/master/packages) repository contains them.

**Comment by knight109** [comment]
Can you update E-hentai and Ex-hentai?

**Comment by Tmp341** [comment]
Those are broken websites. Until @SDXC or someone else fix them, i can't update those.

**Comment by knight109** [comment]
ohh ok.
i'll wait
