### ISSUE TITLE
Updating list fails, it sets pages as manga [HentaiFox]

### ISSUE THREAD

**Issue by Vantageright** [fmd-project-team/FMD#623]
Updating the list from the site rather than the server returns 11 results, 2-9, 3167-8 and Previous.[What I mean.](https://imgur.com/a/SYKNFaX)

**Comment by Tmp341** [comment]
Your problem is fixed?

**Comment by Slasar41** [comment]
Could you test it?
[HentaiFox.zip](https://github.com/fmd-project-team/FMD/files/3865646/HentaiFox.zip)

**Comment by Slasar41** [comment]
Should be fixed with module update.
