### ISSUE TITLE
ChibiManga is not on the Advanced list

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [fmd-project-team/FMD#625]
Chibmanga has recently implemented a +18 warning pop-up for some series and that prevents the downloader from accessing the chapter list either for checking updates or for downloading. I've tried to add the cookie for the consent (wpmanga-adault=1) in order to bypass it, but Chibi Manga is not among the list of sites in the Advanced list, so I can't.

**Comment by Slasar41** [comment]
Mine have it.
![image](https://user-images.githubusercontent.com/28888646/68786192-ef0e8a00-0671-11ea-801f-78c60f84d107.png)
Maybe the module isn't loaded properly on yours? Check FMD log file.
And give me example of the title that has the warning.

**Comment by l-l-l-l-l-l** [comment]
I'm going to try reinstalling it to check if maybe there was an issue with the last update that I've missed for two weeks.

**Comment by l-l-l-l-l-l** [comment]
OK, I think I found the issue. For some reason there were several modules that kept updating incorrectly and ended up corrupted, being one of them the one needed for this (Madara). I'm currently replacing the corrupted modules with the correct ones from the source.

**Comment by l-l-l-l-l-l** [comment]
That was it. Thanks.
