### ISSUE TITLE
Problems with chapter updates [MangaDex]

### ISSUE THREAD

**Issue by nille02** [fmd-project-team/FMD#636]
Since today i have a small issue with mangadex. The Manga Updates are not really working. Most of them got a error and if i repeat the update often enough get the correct chapter list.

I dont know if it happen due to a heavy load on mangadex, but even with a 5 second delay and 5 second interval delay

**Comment by SDXC** [comment]
This is an issue of MangaDex. You probably shouldn't do anything with MD for today and probably tomorrow. They are fixing some DB issues but it seems it doesn't work well currently.

**Comment by nille02** [comment]
ok, then i wait a bit. Thank you.
