### ISSUE TITLE
Problems with getting certain manga list and info [MangazukiOnline]

### ISSUE THREAD

**Issue by jillybeans** [fmd-project-team/FMD#637]
on https://www.mangazuki.online/manga/read-her-summon/
it redirects me to https://whatstatus.co/manga/manga/mon/ which I cant download from but I can read it just fine but I would prefer to download it on fmd
but https://www.mangazuki.online/manga/hahris-lumpy-star/ does not direct me to it, but the original mangazuki page which downloads on fmd just fine

so was just wondering is there a workaround or a solution for it, sorry if this is the wrong place for this problem or if it was already brought up.

**Comment by SDXC** [comment]
As a quickshot solution i added the whatstatus.co domain as a separate website module "MangaZukiWhatStatus". Just move the favorites that redirected you to the new website module. if there are other different redirect urls let me know. I'll rethink the strategy if that happens.
