### ISSUE TITLE
Incomplete download [LHScans]

### ISSUE THREAD

**Issue by Dgraid12** [fmd-project-team/FMD#647]
good .. I come to ask for help and see if anyone knows why the lhscans chapters are not downloaded .. were there any changes to the page? additional .. just download the last page of each chapter

![imagen](https://user-images.githubusercontent.com/53473707/69839585-7e996880-122e-11ea-910d-e7c27e5be89e.png)

![imagen](https://user-images.githubusercontent.com/53473707/69839598-8a852a80-122e-11ea-8ae5-d161e1213828.png)

![imagen](https://user-images.githubusercontent.com/53473707/69839602-940e9280-122e-11ea-8e87-bf28613e3480.png)

**Comment by Slasar41** [comment]
Should be fixed with a module update.
