### ISSUE TITLE
Export links in the download list as a text file

### ISSUE THREAD

**Issue by ImFeyn** [fmd-project-team/FMD#65]
I am sorry if this has been asked in the old git but I have not been able to find it so just a quick question, is it possible to export the links in my download list as a clean textfile? 
The only links I have been able to find are in the files in the works folder but with some symbols and missing dots instead of a clean address eg: Ь/%nhentai/g/######.

**Comment by Tmp341** [comment]
You can open and extract links via db browsers, like DB Browser for SQLite.

**Comment by SDXC** [comment]
It's not a built-in feature yet, but I plan to do that, and for the favorites as well.
