### ISSUE TITLE
Website doesn't work [Toonkor]

### ISSUE THREAD

**Issue by Ethanaelle** [fmd-project-team/FMD#66]
Hi ! Thank you for taking over this project ! 
Toonkor doesn't work anymore, its changed its domain from ".co" to ".pink".

**Comment by AbidZakaria** [comment]
Please sent screenshot

**Comment by Ethanaelle** [comment]
![image](https://user-images.githubusercontent.com/48924418/55738433-68ccfe00-5a27-11e9-969d-ad0511c79b85.png)
 Thank you ~!

**Comment by SDXC** [comment]
Script should be fixed now. Please try again and let us know if it works for you.

**Comment by Ethanaelle** [comment]
It's working ! Thank you !

**Comment by Ethanaelle** [comment]
It's working ! Thank you !!

**Comment by SDXC** [comment]
Thank @AbidZakaria for that. ^^
