### ISSUE TITLE
Fail to download chapters of some titles [MangaKakalot]

### ISSUE THREAD

**Issue by PhantoManresa** [fmd-project-team/FMD#662]
Hi, I am trying to download from MangaKakalot, but some mangas download without problem while others are giving me failed downloads. Funny thing is, some of the mangas I can't download now I could download them a couples of days ago. The chapters are loaded successfully in the Manga Info tab. One of the manga I am having issues right now is Kengan Omeg.
Thanks for your every day effort.

**Comment by Slasar41** [comment]
That manga title is redirected to MangaNelo website.
See: https://github.com/fmd-project-team/FMD/issues/591#issuecomment-548904374

**Comment by PhantoManresa** [comment]
Oh, you are right. If I go thorough MangaNelo it downloads correctly. I don't know why I could through MangaKakalot before.
Thank you very much.
