### ISSUE TITLE
[FMD] All sorts of problems

### ISSUE THREAD

**Issue by Souravi785** [fmd-project-team/FMD#668]
Sorry, but fmd is in a whole lot of mess and I don't know the reason. It's been fine last week but this week kissmanga doesn't work, mangakalot doesn't work, mangasee sometime works and sometime don't, trying to exit when fmd is loading a manga causes it to freeze, etc. Any advice?

**Comment by Tmp341** [comment]
I think the real cause is Cloudflare. Kissmanga uses for example, and cf_bypass included can't handle those. Also, SDXC is busy irl, AbidZakaria left project, i don't know anything about coding etc etc.

**Comment by SDXC** [comment]
in case of cf_bypass i am currently waiting for a fix as well. but it seems one of the FMD users is up to fixing the python script. i will add it and release a new version of FMD as soon as it works.

**Comment by Souravi785** [comment]
I hope FMD starts working soon :D

**Comment by traitorAIZEN** [comment]
just transfer all your mangakakalot bookmarks to manganelo

**Comment by forvy** [comment]
@traitorAIZEN  and manganelo has some web not working too now :) 

Funny enough. On browser I can open it:
![image](https://user-images.githubusercontent.com/17746819/71511972-df1bd400-28c6-11ea-962b-50ac5bc93a49.png)


and yet on FMD shows N/A :
![image](https://user-images.githubusercontent.com/17746819/71511958-cd3a3100-28c6-11ea-9b74-908512132cae.png)

**Comment by Tmp341** [comment]
> 
> 
> @traitorAIZEN and manganelo has some web not working too now :)
> 
> Funny enough. On browser I can open it:
> ![image](https://user-images.githubusercontent.com/17746819/71511972-df1bd400-28c6-11ea-962b-50ac5bc93a49.png)
> 
> and yet on FMD shows N/A :
> ![image](https://user-images.githubusercontent.com/17746819/71511958-cd3a3100-28c6-11ea-9b74-908512132cae.png)

I just pasted Haikyuu link and it loaded chapter list.

**Comment by traitorAIZEN** [comment]
@forvy works fine for me even with the cf_bypass disabled.
be sure that you have updated your module.
if that doesn't work, you can also try changing your DNS. This fixed my issue with MN.
