### ISSUE TITLE
Make update on Mangadex faster

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#669]
![Untitled](https://user-images.githubusercontent.com/30251842/70314429-68a12e80-1852-11ea-9d80-febc3f5c7fb6.png)

Mangarock only need about 66 but Mangadex takes that much and its really slow.
Can you guys make it faster?

Or if it just happen for me please help me to fix it.
Thanks

**Comment by Tmp341** [comment]
If you go any faster, Mangadex's Cloudflare will ban your IP, so you can't download.

**Comment by knight109** [comment]
ohhh okay.
