### ISSUE TITLE
Add website support [MangaToon]

### ISSUE THREAD

**Issue by rs3mk** [fmd-project-team/FMD#67]
Site of manhuas: https://mangatoon.mobi [multi language]

**Comment by SDXC** [comment]
MangaToon has been added (found in English for now). Manga list will check for English, but on the Manga Info tab you also can add other languages.

I will look into the multi-language thing from the other issue.

**Comment by rs3mk** [comment]
Yes, works!!.

For multi-languages, it can be done as ninemanga (NinemangaIT, NinemangaPT, NinemangaES, etc)

**Comment by SDXC** [comment]
I'll probably do that.

**Comment by SDXC** [comment]
Multilanguage support is now implemented as well, thanks to @AbidZakaria
