### ISSUE TITLE
Site changed [mintmanga]

### ISSUE THREAD

**Issue by dezill** [fmd-project-team/FMD#672]
https://mintmanga.com/
to
https://mintmanga.live/

**Comment by excalibur1010** [comment]
nothing change 
it's http://mintmanga.live/ on MintMangaRU

**Comment by Tmp341** [comment]
Yeah. It is already ``https://mintmanga.live/`` on FMD.

**Comment by dezill** [comment]
Hmm, ok, it turned out that I'm using old version of FMD which is not updating, now I downloaded the latest version, but for unknown reason I can't choose that and some other websites, it shows only one russian, can you help?
![image001](https://user-images.githubusercontent.com/17165601/70561621-9cf75080-1bac-11ea-98c0-0dc978f4d904.png)

**Comment by excalibur1010** [comment]
it's fine on me
![image](https://user-images.githubusercontent.com/58497792/70568269-223d2e00-1bca-11ea-8052-4b5118746358.png)

try fresh install
https://github.com/fmd-project-team/FMD/wiki#fresh-install

**Comment by dezill** [comment]
By "fresh install" you mean delete previous version, download new version and install it? I did it and showed you result in previous comment (image) while in old version(0.9.158) it looks like in your image, all websites are available. 
As I said before, my previous version(0.9.158) haven't been updated for long time, don't know why. So I also followed the link that you gave me(https://github.com/fmd-project-team/FMD/wiki#fresh-install) tried to copy files listed there from old folder into the new folder and had same result, as in "fresh install".
and also read there "Don't backup config/base.ini, because you need the base.ini from this fork to get updates, etc.!", so I replaced that file in my old folder with new file from freshly downloaded archive and when I started the program it asked me to update, I clicked "OK", but after update is finished, it showed me an error(attached image) and after terminating and restarting program it remains on previous version and asks for update again. But in the folder I found updatepackage(second attached image), so I unpacked it and replaced files with same name, and after launching FMD I saw that it is updated(0.9.167) but again, I can't see all websites in that list, as in upper image.
Or I understood and did wrong the "fresh install"? Tomorrow, if I will have access to different computer I will try to install it there and look if it will work, but why isn't it working on my current laptop? 

![image002](https://user-images.githubusercontent.com/17165601/70571611-03d23500-1bc0-11ea-9d07-6c4fa4ec6234.png)

![image003](https://user-images.githubusercontent.com/17165601/70572256-47796e80-1bc1-11ea-9c5d-4af1cf467fc7.png)

**Comment by excalibur1010** [comment]
maybe problem with your folder name 
![image](https://user-images.githubusercontent.com/58497792/70641449-35a2d480-1c70-11ea-82bd-17a850c13957.png)

**Comment by dezill** [comment]
OK, I unpacked it to just "C:\fmd_0.9.167.2_Win64" and after downloading all modules it showed all websites(but if I copy that working folder to russian named folder it crushes again), ok will not move it from C:\. Thanks for helping.
But why older version (0.9.158 which maybe was downloaded from here: https://github.com/riderkick/FMD and because of that it wasn't updating) worked fine? maybe when you updated it and moved here(https://github.com/fmd-project-team/FMD) something changed that prevented from using with russian language?
And as I said, I checked on another computer, situation was same.

Also I noticed that update(new chapters of favorites) checking time in this latest version is slower than in older version (0.9.158), 2.9-5 seconds vs 0.7-2.5 seconds for each title.

**Comment by Tmp341** [comment]
> 
> 
> OK, I unpacked it to just "C:\fmd_0.9.167.2_Win64" and after downloading all modules it showed all websites(but if I copy that working folder to russian named folder it crushes again), ok will not move it from C:. Thanks for helping.
> But why older version (0.9.158 which maybe was downloaded from here: https://github.com/riderkick/FMD and because of that it wasn't updating) worked fine? maybe when you updated it and moved here(https://github.com/fmd-project-team/FMD) something changed that prevented from using with russian language?
> And as I said, I checked on another computer, situation was same.
> 
> Also I noticed that update(new chapters of favorites) checking time in this latest version is slower than in older version (0.9.158), 2.9-5 seconds vs 0.7-2.5 seconds for each title.

It was always like that afaik. I remember some issues fixed by changing folder names with special characters.

**Comment by dezill** [comment]
I'm using FMD for almost 4 years with 2 laptops and a computer, all had russian named folders and never had this problem

**Comment by SDXC** [comment]
@dezill Some of the russian website modules moved to lua scripts so they are easier to fix in the future. FMD has its problems with many characters outside the scope of ANSI, especially if they occur in the application path. FMD can't detect the lua scripts if russian/cyrillic characters are in the application path and that's why you didn't see the websites anymore.

Regarding the downloading speed:
![grafik](https://user-images.githubusercontent.com/5290260/70932274-a1eb5280-2039-11ea-95f6-d1784d3cfc87.png)

**Comment by SDXC** [comment]
For now i'll close this issue. If you still have problems you can always re-open this issue.
