### ISSUE TITLE
Zero Scans Site Changed[Fixed], New Bug : Problem With Numbering Chapter

### ISSUE THREAD

**Issue by JokoeSukri** [fmd-project-team/FMD#674]
**Zero Scans  Site Changed**
Ex Previous : https://zeroscans.com/manga/hero-i-quit-a-long-time-ago/
Change Into : https://zeroscans.com/comics/636122-hero-i-quit-a-long-time-ago

**Regarding The Question**
I Soon Upgrading My OS, From Win7 to Win10,
Did my previous fmd List (such as save, history, bookmark, On hold download) lost as well when I upgrading my os?? 

What the best solution to prevented this??

**Comment by azraei97** [comment]
Yup Zero Scans has Site Changed. I also waiting for FDM update this website.

"Regarding The Question
I Soon Upgrading My OS, From Win7 to Win10,
Did my previous fmd List (such as save, history, bookmark, On hold download) lost as well when I upgrading my os??

What the best solution to prevented this??"

Best solution is **copy all** your "Free Manga Downloader" folder. Make sure don't miss anything from that folder to difference drive/usb or anything

later after you format, you will just need to restore or copy the folder back to where you want it to be. Then just run fmd.exe like normally and you will see all you such as save, history, bookmark, On hold download restore like nothing happen before

**Comment by JokoeSukri** [comment]
azraei97, Got it. OK thanks

**Comment by Slasar41** [comment]
Should be fixed with a module update.

**Comment by JokoeSukri** [comment]
Yes It was fixed 12 hours ago, thanks

**Comment by JokoeSukri** [comment]
Wait, Dont close this thread yet, I found another problem here

**Comment by JokoeSukri** [comment]
I Encountered this after I download Few chapters, There is problem with numbering such as :
**1. Chapter number is missing, Only left the Chapter's name**
![Screenshot_23](https://user-images.githubusercontent.com/32964994/70696732-9a5d3e00-1d07-11ea-940d-92f880c9e669.jpg)
![Screenshot_24](https://user-images.githubusercontent.com/32964994/70696733-9a5d3e00-1d07-11ea-90cc-1baf1d92ab82.jpg)

**2. The numbering is wrong when encountering with fraction number**
![Screenshot_25](https://user-images.githubusercontent.com/32964994/70696949-0475e300-1d08-11ea-9330-a2d707d068c1.jpg)
![Screenshot_26](https://user-images.githubusercontent.com/32964994/70696950-0475e300-1d08-11ea-83f1-92229b827759.jpg)

**3. The Number starting at 1, not same as numbering label**
![Screenshot_27](https://user-images.githubusercontent.com/32964994/70697090-4010ad00-1d08-11ea-9cbe-c5ed5f0553c7.jpg)
![Screenshot_28](https://user-images.githubusercontent.com/32964994/70697092-40a94380-1d08-11ea-8beb-ea38d582894e.jpg)

**Comment by Slasar41** [comment]
Ah, currently it only grab the chapter name as is, this manga displaying the number just fine: https://zeroscans.com/comics/636122-hero-i-quit-a-long-time-ago. It become problem for chapter name that doesn't have numbering on it.
@SDXC how to solve this, should we add that number to chapter name?
But it'll show double numbering for chapter name that has already have number on it.

**Comment by SDXC** [comment]
@Slasar41 It's probably better to get the numbering and use the chapter name as title. it would be a bit redundant but still better than not having the numbering.

**Comment by Slasar41** [comment]
@JokoeSukri Like this?
![image](https://user-images.githubusercontent.com/28888646/70722262-8b878300-1d29-11ea-8758-7febb197cf6a.png)
![image](https://user-images.githubusercontent.com/28888646/70722289-96daae80-1d29-11ea-8b7f-8801a050c419.png)
The bad is it got double numbering for chapter name that already have number on it:
![image](https://user-images.githubusercontent.com/28888646/70722778-752df700-1d2a-11ea-9693-d9e923834043.png)

**Comment by JokoeSukri** [comment]
@Slasar41 Yes like that. Rather that bland number, Could you added dot and separator like this 
[Ch]+[dot]+[space]+[separator]+[space]+[Manga's Title]
Ex : Ch. 027 - Example

**Comment by Slasar41** [comment]
Is this good?
![image](https://user-images.githubusercontent.com/28888646/70735683-48390e80-1d41-11ea-823e-cd461420ccc4.png)

**Comment by JokoeSukri** [comment]
Yes, Acceptable, Although I prefer shortener "Ch." rather "Chapter"
Because the title more readable in DomDomSoft Mangareader
