### ISSUE TITLE
Problem downloading 2 manga from manganelo.com

### ISSUE THREAD

**Issue by Rhisk** [fmd-project-team/FMD#676]
When I try to download the following comics the download always fails.
https://manganelo.com/manga/mq918999
https://manganelo.com/manga/apotheosis

Note: The MangaKakalot module must be active.

**Comment by Slasar41** [comment]
Which chapter?
I can download the latest chapter from both titles.
![image](https://user-images.githubusercontent.com/28888646/70650154-224c3500-1c81-11ea-90cd-393c55765b1d.png)

**Comment by Rhisk** [comment]
Not work for me.
![Sin título](https://user-images.githubusercontent.com/18038511/70806905-58291080-1d8a-11ea-9942-83744fec9544.png)

**Comment by Slasar41** [comment]
Ah, that title got redirect to MangaNelo, I thougt you have an issue with MangaNelo.
See: https://github.com/fmd-project-team/FMD/issues/591#issuecomment-548904374

**Comment by Rhisk** [comment]
Problem solved.
I load the module for Manganelo and change the donwload link in favorites. Now work fine.
