### ISSUE TITLE
Program Exception Error messages.

### ISSUE THREAD

**Issue by stronghand7** [fmd-project-team/FMD#679]
I got this error when trying to "Check for new chapter" on favorite tab.
Although I could just press "ignore this message" button, thought that i should share with you the error log, as follows:

Program exception!
Application       : Free Manga Downloader
Version           : 0.9.167.2
Product Version   : Win64
Host Machine      : Windows 10 64-bit
FPC Version       : 3.0.4
LCL Version       : 1.8.4.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2019/12/07 22:39:08
Path              : D:\Manga\Free Manga Downloader\fmd.exe
Process ID        : 16064
MainThread ID     : 12032
Thread ID         : 10004
Time              : 11/12/2019 23:43:53.614
Ignored Exception : EInOutError
Sender Class      : TFavoriteThread
Exception Class   : EInOutError
Message           : File not open

**Comment by Tmp341** [comment]
Seems like your favorites file is corrupted. Try to move it somewhere else and open FMD again.

**Comment by stronghand7** [comment]
> Seems like your favorites file is corrupted. Try to move it somewhere else and open FMD again.

hi Tmp,
I tried but somehow i couldnt import list from the previous favorites list.. My favorite list is about >1k items so it's quite a work to put them back in place manually...
Shouldn't I use import list features which located on favorite tab? my fresh copy of the program didnt receive anything...
please kindly advise..

![asdq](https://user-images.githubusercontent.com/36535193/70846375-52672400-1e8b-11ea-8295-bd52f8b0fa93.PNG)

**Comment by Tmp341** [comment]
> hi Tmp,
> I tried but somehow i couldnt import list from the previous favorites list.. My favorite list is about >1k items so it's quite a work to put them back in place manually...
> Shouldn't I use import list features which located on favorite tab? my fresh copy of the program didnt receive anything... it said completed but the list still empty.
> please kindly advise..

So, moving file fixed your error. I don't know anything about ``Import`` feature coding, one of the coders might be able to help you.

**Comment by SDXC** [comment]
@stronghand7 Please upload your favorites.db (zipped). I will look if it can be used/repaired.

**Comment by stronghand7** [comment]
[favorites.zip](https://github.com/fmd-project-team/FMD/files/3979448/favorites.zip)

**Comment by stronghand7** [comment]
@SDXC sorry just read your message. I have uploaded the files as above.

**Comment by SDXC** [comment]
@stronghand7 Just placing the favorites.db in my FMD folder worked okay and checking some of the favorites as well. does the error occur on all favorites or only at a specific title? If it's a specific title, can you let me know which one?
