### ISSUE TITLE
Help for Lua script [MangaToon] #just_one_bug

### ISSUE THREAD

**Issue by AbidZakaria** [fmd-project-team/FMD#68]
[Mangatoon Chapter not sorted.zip](https://github.com/fmd-project-team/FMD/files/3057819/Mangatoon.Chapter.not.sorted.zip)

update 2019/04/09

**Comment by AbidZakaria** [comment]
please see my chat on the discord @SDXC

**Comment by AbidZakaria** [comment]
Lua mangatoon has been fixed all
But one bug : chapter list not sorted

**Comment by SDXC** [comment]
Inverting was actually not needed. Removing it solved it.
