### ISSUE TITLE
MyReadingManga chapters not showing up

### ISSUE THREAD

**Issue by komaedalove** [fmd-project-team/FMD#680]
the title I have issues with:
https://myreadingmanga.info/konkichi-zettai-bl-ni-naru-sekai-vs-zettai-bl-ni-naritakunai-otoko-eng/

There are 20 chapters but only one "blank" chapters appears, no title or anything, and can't be downloaded.

**Comment by Slasar41** [comment]
It's show up for me and downloaded just fine.
![image](https://user-images.githubusercontent.com/28888646/70649728-4e1aeb00-1c80-11ea-85d0-b0e0c6961757.png)
Try go to Options -> Websites -> Advanced -> MyReadingManga, make sure the `DisableCloudflareBypass` option is set to `False`.

**Comment by komaedalove** [comment]
that didn't work

**Comment by Slasar41** [comment]
Your problem is like this, right?
![image](https://user-images.githubusercontent.com/28888646/70803274-46755680-1de6-11ea-9c7b-13a79baf608f.png)
Make sure the `Enable Cloudflare Bypass` option in `Options -> Connections` is enabled.
If it already enabled, try to use cloudflare workaround like this: https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-JapScan

**Comment by komaedalove** [comment]
![Screenshot - 2019-12-14 , 00_44_33](https://user-images.githubusercontent.com/52548608/70838998-08d6f480-1e0b-11ea-95a5-14a46a0361d1.png)
![Screenshot - 2019-12-14 , 00_44_45](https://user-images.githubusercontent.com/52548608/70839000-08d6f480-1e0b-11ea-8c1f-b176e8794843.png)

Thank you. Here are my settings... is the script broken? The workaround is really annoying.

**Comment by Tmp341** [comment]
> 
> 
> ![Screenshot - 2019-12-14 , 00_44_33](https://user-images.githubusercontent.com/52548608/70838998-08d6f480-1e0b-11ea-95a5-14a46a0361d1.png)
> ![Screenshot - 2019-12-14 , 00_44_45](https://user-images.githubusercontent.com/52548608/70839000-08d6f480-1e0b-11ea-8c1f-b176e8794843.png)
> 
> Thank you. Here are my settings... is the script broken? The workaround is really annoying.

Annoying yeah, but we can't bypass automatically a "bot checking" precaution (like Cloudflare).

**Comment by komaedalove** [comment]
I see, that's too bad. Thank you for your help!
