### ISSUE TITLE
tutorial [lua]

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#689]
is there any tutorial to make the modules [lua]

_-I also want to contribute a grain of sand_

**Comment by SDXC** [comment]
i like the sentiment of wanting to help but as of now we're not able to do anything like that. covering the basics would be too much and if you already know lua, html and xpath you won't really need a tutorial for FMD specifically. A cheat sheet covering the most important aspects of FMDs functions, etc. would be more helpful actually.

we try to give a bit of guidance or help you with specific problems on Discord though.
maybe i'll create at least a cheet sheet some time around. i'm already noting down many things but it's not on a level to publish yet. if the cheet sheet will ever be published, i'll let you all know by the changelog or the releases page. i'm closing this issue for now.
