### ISSUE TITLE
Kissmanga won't work

### ISSUE THREAD

**Issue by Enkhilada** [fmd-project-team/FMD#695]
I am currently using this new fork but I cannot download from kissmanga yet. I am using the tampermonkey script but still nothing. The manga list appears in FMD, it takes a long time to load but when I start a download it just fails.

**Comment by Slasar41** [comment]
I can download KissManga just fine.
Try this guide: https://github.com/fmd-project-team/FMD/wiki#troubleshooting-guides

**Comment by Tmp341** [comment]
I've just downloaded from Kissmanga yesterday. Haven't tried today, but i don't think it got broken in 24 hours.

**Comment by Enkhilada** [comment]
> I can download KissManga just fine.
> Try this guide: https://github.com/fmd-project-team/FMD/wiki#troubleshooting-guides

That worked thanks!
