### ISSUE TITLE
Can't get chapter pages (Kissmanga.com)

### ISSUE THREAD

**Issue by Drsoe08** [fmd-project-team/FMD#696]
Whenever I try to download from Kissmanga this thing happens
![FMD ISSUE](https://user-images.githubusercontent.com/59337129/71558088-28685100-2a8a-11ea-91f7-568c56eb019e.png)
![FMD issue 2](https://user-images.githubusercontent.com/59337129/71558090-328a4f80-2a8a-11ea-9441-f9960b64041c.png)

**Comment by Tmp341** [comment]
https://github.com/fmd-project-team/FMD/wiki#troubleshooting-guides

Kissmanga changed it's ``key``, you can get it via workaround mentioned in the Wiki.

**Comment by Tmp341** [comment]
Closing this for now, if the problem still exists, reopen issue.
