### ISSUE TITLE
Can't get manga info [Zero Scans]

### ISSUE THREAD

**Issue by JokoeSukri** [fmd-project-team/FMD#7]
I cant get pages on Zero scans in this version 160
![Screenshot_23](https://user-images.githubusercontent.com/32964994/55309675-79b2c800-5499-11e9-88ca-c0dce885c843.jpg)

I still have old FMD as well ver.154 and works as far as I go
![Screenshot_24](https://user-images.githubusercontent.com/32964994/55309726-9949f080-5499-11e9-9c70-63405451a9e3.jpg)

I hope you can fix this

**Comment by Tmp341** [comment]
It seems ``Madara.lua`` contains Zeroscans' codes.

**Comment by SDXC** [comment]
@JokoeSukri Just to make sure, can you upload your `Madara.lua` file so I can compare them? I will probably look into it today evening (GMT+1h).

**Comment by JokoeSukri** [comment]
Github don't support lua, so I compress them

FMD 0.9.160.0 : [Madara.lua (v.160).zip](https://github.com/fmd-project-team/FMD/files/3028995/Madara.lua.v.160.zip)

[FMD 0.9.154.0 : Madara.lua (ver.154).zip](https://github.com/fmd-project-team/FMD/files/3029000/Madara.lua.ver.154.zip)

**Comment by SDXC** [comment]
Problems seems to be one of the thirdparty libraries or the IDE version itself. I'm currently investigating where it went wrong.

Problem is, that it's not documented, which libraries were used in the old builds.

**Comment by SDXC** [comment]
@JokoeSukri Please try the new version attached before I release it. It should be okay now.

[fmd_0.9.160.1.zip](https://github.com/fmd-project-team/FMD/files/3031427/fmd_0.9.160.1.zip)

-> It was actually Synapse, which was too old. It's now the latest version.

**Comment by JokoeSukri** [comment]
I just woke up, sorry for late reply
![Screenshot_18](https://user-images.githubusercontent.com/32964994/55371860-b5519e80-553a-11e9-8e56-c4e0ec86940c.jpg)
![Screenshot_14](https://user-images.githubusercontent.com/32964994/55371877-c26e8d80-553a-11e9-9c5b-845a051603ec.jpg)

It works like a charm between x64 and x32

**Comment by SDXC** [comment]
Official release is out now. The updater in the version 0.9.160.0 and the hotfix 0.9.160.1 doesn't work. You have to update manually. Updater should work for the future releases though.
