### ISSUE TITLE
Can't get chapter list for some H-mangas [MangaPark]

### ISSUE THREAD

**Issue by SalarG** [fmd-project-team/FMD#70]
Hi there.
I had no problem with MangaPark this morning and I was using Latest version of FMD (0.9.161). this afternoon I updated FMD to (0.9.162) and after that MangaPark is not fetching any chapter list. It's like the time when we have issues with MangaPark before you fixed chapter download (Issue #9).

**Comment by Tmp341** [comment]
Have you tried doing similar written in this workaround?

https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation

**Comment by SalarG** [comment]
> 
> 
> Have you tried doing similar written in this workaround?
> 
> https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation

I tried to use a similar method, but it's not solving the problem and I found out that not all mangas are affected but a few ones did. I can still see most of the manga's chapter list, but when FMD tries to load chapter list for some of them, I get an empty list.

**Comment by SalarG** [comment]
> 
> 
> @SalarG Could you please give us some examples that didn't work?

https://mangapark.me/manga/okirakugaki-higurashi-bokurano
https://mangapark.me/manga/gaki-ni-modotte-yarinaoshi
https://mangapark.me/manga/otaku-no-ore-o-baka-ni-shita-kusogaki-o-kankin-shikaeshi-sekkan

**Comment by SDXC** [comment]
I had to add a cookie to view hentai and now it works. If anything still doesn't work, please re-open this issue.
