### ISSUE TITLE
Mangadex will be down for aprox. 72 hours

### ISSUE THREAD

**Issue by muto4013** [fmd-project-team/FMD#700]
Just in case some people will discover mangadex-problems in the next few hours/days:
from mangadex forum (1.1.20)
[quote] Here are a few quick announcements:

    We are going to be down for a short time within the next 24 hours or so because our host is no longer able to support us and we need to move to a new hosting service. While we are offline, we will also be carrying out some essential server maintenance. While we are down, you can join our Discord to stay up to date with the latest news and chat with the community. [/quote]

**Comment by muto4013** [comment]
Update: downtime is estimated for 72 Hours

**Comment by formigao** [comment]
AFTER this 72 i had a problem. can't update all my other mangas because fmd stays infinitely searching 50+ mangas from a server that is offline.

Solution: make FMD check site stacks before updating mangas or skip manga from that server after X number from that site fail to load. @Tmp341

**Comment by muto4013** [comment]
why so complicated ? Sort your favorites by host and temporarily disable the host entry's, if the site / server is back online just enable again.

**Comment by formigao** [comment]
> why so complicated ? Sort your favorites by host and temporarily disable the host entry's (in favorites), if the site / server is back online just enable again.

because i have many disabled that are on "hold" and i dont and to mix it.

**Comment by Tmp341** [comment]
I have 2 favorites file in hand:

1. Standard, keep reading and active mangas.
2. Passive, on hold, scanlation keeps on getting hiatus etc.

Created 1 batch file for it, when i wanna check passive one, i just start with that batch file, if not, use standard one.

**Comment by GelgoogGuy** [comment]
Mangadex is back up but they've moved to mangadex.cc. Anyone know how we can manually update that inside FMD or in the files?

**Comment by arbiter9605** [comment]
> > Mangadex is back up but they've moved to mangadex.cc. Anyone know how we can manually update that inside FMD or in the files?
They likely will update the lua soon but even so unless you put cookie data inside fmd it won't work for a bit as the site is current in login mode so you gotta log in to view anything.

But if you don't want to wait go in to fmd install directory, go LUA > Modules. Find the file named Mangadex.lua. Open it in text editor, at the bottom you will see the line "m.rooturl='https://mangadex.org' ", you edit the ".org" to ".cc" then save.

**Comment by kazenoade** [comment]
i tried that, but is not work, in favorite and in download

**Comment by Tmp341** [comment]
> 
> 
> i tried that, but is not work, in favorite and in download

You need to change favorites.db, since changed website url also blocks favorited manga access.

**Comment by kazenoade** [comment]
<img width="782" alt="fail" src="https://user-images.githubusercontent.com/59524272/71776287-5afdd680-2fc1-11ea-829e-e8659fdd7817.png">

**Comment by GelgoogGuy** [comment]
@kazenoade I got the same problem after updating my MangaDex lua and downloading a fresh MangaDex database.

**Comment by Tmp341** [comment]
> 1. Our .cc domain is temporary for now. Our .org domain was acquired via our reseller, who has removed us from CF and have stopped supporting us due to legal pressure. .org will be unavailable until the transfer to our new provider completes.

> 2. Due to the length of time it takes to move the domain, older chapters aren't available just yet. It will probably be the beginning of next week before they're available but we're hoping the move will complete before the weekend is over. You can, however, upload new chapters, comment on old chapters, etc., etc

It seems they might switch back to .org domain again in the future. 

[Source](https://mangadex.cc/thread/200708)

**Comment by Tmp341** [comment]
Also, i just changed the url under ``Mangadex.lua`` and it worked:

![SSS](https://user-images.githubusercontent.com/1683388/71776408-5249d800-2fa2-11ea-9711-471e3d9c9b20.jpg)

**Comment by GelgoogGuy** [comment]
@Tmp341 did it actually download anything?

**Comment by fales13** [comment]
![image](https://user-images.githubusercontent.com/37041682/71776461-9d74e280-2fc4-11ea-8a9a-2a64c0a8b0c8.png)
mine woks just fine

**Comment by Tmp341** [comment]
> 
> 
> @Tmp341 did it actually download anything?

Updating database for now.

**Comment by muto4013** [comment]
Before anybody went into panic-mode or start to change things unnecessary please read this from MD-forum:

> 1. Our .cc domain is temporary for now. Our .org domain was acquired via our reseller, who has removed us from CF and have stopped supporting us due to legal pressure. .org will be unavailable until the transfer to our new provider completes.
> 
> 2. Due to the length of time it takes to move the domain, older chapters aren't available just yet. It will probably be the beginning of next week before they're available but we're hoping the move will complete before the weekend is over. You can, however, upload new chapters, comment on old chapters, etc., etc.
> [...]
> As we have moved to a new provider, you may experience issues. If you see any errors, please report it on our Discord.
>


 

>  Known problems:
> - As mentioned, chapters uploaded before the host change don't load yet - we know, please don't report them
> - User mention links like @Teasday that were made before the domain switch point to .org (no fixing this one, sorry)
> - Similarly, any other links pointing directly to mangadex.org in places such as title/group descriptions etc. will obviously not work unless edited, but since we're going to go back to .org eventually, probably no reason to fix those

for reference original posts: https://mangadex.cc/thread/200708

**Comment by GelgoogGuy** [comment]
@muto4013 I saw that, I was having problems getting even recently uploaded chapters. I was just going to the main page and seeing what was freshly updated but couldn't grab them. Though I now suspect that FMD didn't do a full download of the database as it's found another 4k things to go through.

**Comment by kazenoade** [comment]
lets wait for now

**Comment by muto4013** [comment]
yep, i noticed this also :) Therefore the reminder that MD has not finished the move.
At the moment several imageservers are not working properly or are offline, so no wonder FMD has some problems.
Maybe another reminder: Before someone changes things as temporal measures BACKUP your database and lua - could help if you need to reverse back

**Comment by GelgoogGuy** [comment]
Years of Oblivion and Skyrim modding means that I tend to backup things before modifying them. But yeah I figure waiting a few more days to a week will straighten this all out.

**Comment by fales13** [comment]
![image](https://user-images.githubusercontent.com/37041682/71778504-47fafe80-2fe1-11ea-8d65-e1bde4b49f24.png)

mine, updated just fine

**Comment by SDXC** [comment]
The MD url has been changed in the lua module. No need for manual steps anymore until the old url is back.

**Comment by knight109** [comment]
How to update it to .cc?
Mine still like this:
![image](https://user-images.githubusercontent.com/30251842/71781615-cbc9e080-300b-11ea-9228-dd956780bdc5.png)
same in favorite

**Comment by Tmp341** [comment]
> 
> 
> How to update it to .cc?
> Mine still like this:
> ![image](https://user-images.githubusercontent.com/30251842/71781615-cbc9e080-300b-11ea-9228-dd956780bdc5.png)
> same in favorite

Check lua modules: 

![sssss](https://user-images.githubusercontent.com/1683388/71782447-fe171600-2fea-11ea-9045-bb77cb752542.jpg)

**Comment by knight109** [comment]
> > How to update it to .cc?
> > Mine still like this:
> > same in favorite
> 
> @knight109 Check lua modules:
> 
> ![sssss](https://user-images.githubusercontent.com/1683388/71782447-fe171600-2fea-11ea-9045-bb77cb752542.jpg)

already did that before asking, but probably it bugged last time.
deleted the lua and re-download make it work.
thanks.
