### ISSUE TITLE
FMD Won't list all manga chapters from a specific website

### ISSUE THREAD

**Issue by aleaallee** [fmd-project-team/FMD#709]
Hi, since I read mangas in spanish, I'm trying to download a manga with FMD from a website I like (tumangaonline.com). The problem is that FMD only lists the last chapter of any manga available on the website instead of every available chapter. It also fails to download any manga chapter from that specific website.

**Comment by Tmp341** [comment]
TMO has cloudfare, also encryption, which changed as soon as encryption decrypted. We can't directly decrypt it via FMD too. So, you either use a javascript supported apps like hakuneko, wait tmo drop acting like this or wait for FMD coders add decrypt support.
