### ISSUE TITLE
[WebToons] failed to list chapters past the last 10 unless a cookie is set

### ISSUE THREAD

**Issue by GDXN** [fmd-project-team/FMD#710]
It only list the last 10 chapters but they are in the web and adding the cookie: "ageGatePass=true" fix it

**Comment by Tmp341** [comment]
Then add that cookie under webtoons' advanced settings?

**Comment by GDXN** [comment]
I have set it but I made the issue to notify of it ans its workaround

**Comment by SDXC** [comment]
we should be able to include the cookie in the website module. will look into it.

**Comment by Slasar41** [comment]
Could you tell which title?
I tested with random titles and it shows all chapters without adding the cookies.

**Comment by GDXN** [comment]
That was with: Magician

**Comment by Slasar41** [comment]
I can see all chapters:
![image](https://user-images.githubusercontent.com/28888646/74634564-af869b00-5196-11ea-9803-f067b7aac150.png)

**Comment by Slasar41** [comment]
Should be fixed.
