### ISSUE TITLE
[Site Domain Changed]Mangadex Domain Changed because of Legal Issues

### ISSUE THREAD

**Issue by JokoeSukri** [fmd-project-team/FMD#712]
> Good news, everyone! As you can see, MangaDex is back.
> 
> A few things to note:
> 
> 1. Our .cc domain is temporary for now. Our .org domain was acquired via our reseller, who has removed us from CF and have stopped supporting us due to legal pressure. .org will be unavailable until the transfer to our new provider completes.

Cite from Mangadex Announcement
Before : https://mangadex.org/
After : https://mangadex.cc/

**Comment by l-l-l-l-l-l** [comment]
The have also changed from Cloudfare to DDoS-Guard, which needs manual input.

**Comment by JokoeSukri** [comment]
Just wait, *sigh*
90% of old manga is unreadable, the image is not loading.
They said at least 7 days to moved to new domain provider, the old one was sued.
And... No further notice when mangadex revert back from .cc to ,org

**Comment by SDXC** [comment]
There was already an issue:
https://github.com/fmd-project-team/FMD/issues/700

We temporarily changed the url in the website module, hoping that most of the MD users actually read the announcements....

In one announcement they said it would be around a week until the old url is back up. But it's possible they removed the estimation from the announcement.

I'll close the issue for now.
