### ISSUE TITLE
Unable to download from MangaDex since the move to the .cc domain

### ISSUE THREAD

**Issue by Geese1** [fmd-project-team/FMD#714]
Just saw that news that MangaDex has moved over to a new, temporary .cc domain. I came here to check and saw the updated .lua information posted by SDXC. I made the change to the file, and while I can now see the chapters in the program, I get an error whenever I try to download them.

I'm wondering if it's a change that needs to be made to the cookies for the MangaDex site info (like we used to have to do when they were on CloudFlare)? I tried to play around with a few settings, but I haven't had any luck.

Any help would be appreciated.

**Comment by Tmp341** [comment]
@Geese1  Check lua modules: 

![sssss](https://user-images.githubusercontent.com/1683388/71782447-fe171600-2fea-11ea-9045-bb77cb752542.jpg)

**Comment by Geese1** [comment]
@Tmp341 

Thanks, I double checked and the module was already updated.

Just tried starting the downloads again, and this time they went through. Also was able to download a new chapter after checking for new releases. Not sure why it worked this time, but I'm wondering if it was something on MangaDex's end, since they were in the process of getting everything set up on the new domain. Since I was back with my original settings (after having fooled around with them while trying to download earlier), I don't think it's anything I did. 

Regardless, it seems to be working now.

**Comment by limno97** [comment]
mm i updated it earlier

**Comment by Tmp341** [comment]
> 
> 
> mm i updated it earlier
> [https://i.imgur.com/8Gzhs8p.png](https://i.imgurp.com/8Gzhs8p.png)
> though am still getting an error with downloading manga
> 
> some seem to work whereas some others dont
> [https://i.imgur.com/CVk05Ov.png](https://i.imgurp.com/CVk05Ov.png)

@limno97, mangadex stated this in the announcement : 

> 2. Due to the length of time it takes to move the domain, older chapters aren't available just yet. It will probably be the beginning of next week before they're available but we're hoping the move will complete before the weekend is over. You can, however, upload new chapters, comment on old chapters, etc., etc.

**Comment by limno97** [comment]
@Tmp341 ah shiet, my bad. thanks a lot!

**Comment by Tmp341** [comment]
@limno97 Just wait and try to use mangadex as it is, until they switch back to the ``.org`` domain.

**Comment by limno97** [comment]
@Tmp341 yup can wait, just wasnt sure if i had done what you said correctly or not. but all is good. know they and you are working hard on providing us with content haha
