### ISSUE TITLE
mangalife

### ISSUE THREAD

**Issue by eikaichijo01** [fmd-project-team/FMD#717]
cannot download from mangalife site or no chapter list

**Comment by Tmp341** [comment]
@eikaichijo01 It is still waiting to be ported to ``lua``.

**Comment by SDXC** [comment]
Ported and fixed.

**Comment by SDXC** [comment]
just a side note: the favorites will be redownloaded once when checking for new chapters.

**Comment by eikaichijo01** [comment]
pls fix i cant download on manga4life again cause
as a sample : web chapter is 50 but in fdm is more chapter
i already trying to re paste the link but still same
here the pic
![2020-04-15_103616](https://user-images.githubusercontent.com/26455590/79296252-17423380-7f05-11ea-98c3-d6b8dd5eebdd.png)
![2020-04-15_103647](https://user-images.githubusercontent.com/26455590/79296266-20330500-7f05-11ea-8104-5e37925b24e9.png)

**Comment by Tmp341** [comment]
> 
> 
> pls fix i cant download on manga4life again cause
> as a sample : web chapter is 50 but in fdm is more chapter
> i already trying to re paste the link but still same
> here the pic as a sample

Use existing issue #891
