### ISSUE TITLE
[QUESTION] What's the correct way to purge a site's manga list and start anew?

### ISSUE THREAD

**Issue by spamtaztik** [fmd-project-team/FMD#718]
Sometimes when I just clicked the "update manga list" button I'd get some (not all) titles with multiple entries in the manga list window. This happens mainly for scanslation group sites that only have < 100 entries, unlike aggregator sites. It seems if there's something that was changed in a particular manga's info from the original download site (I dunno, title, address, description, tags, whatever), FMD would sometimes add a new entry with the same title instead of updating the old one. I dunno if it's just my FMD.

Anyway, how do I completely purge the old manga list and download a new one from the download site? 

If I use the "download manga list from server" link, would the old data be -replaced- (not -updated-) with the new downloaded file, and I can then just use the "update manga list" link to update whatever new titles that are not in the downloaded manga list file?

**Comment by Tmp341** [comment]
1. Close FMD
2. Go to FMD main folder
3. Open ``data`` folder, 
4. Find that site's database, for example ``Mangadex.db``
5. Delete it. 
6. Launch FMD
7. Download it again.

**Comment by molitar** [comment]
I found just redownloading it will eliminate any redundant data like duplicates. I had sites that showed.

name (71)
name (72)
name (73)
name (74)

so basically it just kept creating a new entry increasing the count. This type of problem I just used download from server.. and problem was fixed. So don't always have to manually delete the database sometimes just downloading again resolves it.

**Comment by spamtaztik** [comment]
Got it. Thanks you two.

Closed.
