### ISSUE TITLE
issue with certain mangas not downloading from [Mangalife] after site change

### ISSUE THREAD

**Issue by jillybeans** [fmd-project-team/FMD#720]
the site works fine and most of the mangas on the new site download normally but certain mangas don't download at all, even though there is no problem on the site itself with said mangas

https://manga4life.com/manga/Tower-Of-God
https://manga4life.com/manga/Wind-Breaker

**Comment by SDXC** [comment]
ah, looks like the chapters are logically split by season. didn't know ML had a system like that. i will take a look into it.

**Comment by SDXC** [comment]
should be fixed now.
