### ISSUE TITLE
[Question] Did anyone's FMD download from Mangadex v.e.r.y... sloo....wwwlyy?

### ISSUE THREAD

**Issue by spamtaztik** [fmd-project-team/FMD#721]
For some reason after MD change to the new .cc site, I'm stuck with download speed of around 100KBps (most of the time it's below 50). I tried increasing my bandwidth up to 20Mbps, still the same (slow) speed. At the same time, I can download from nelo full speed. 

Did anyone else also experience this, or are there some settings that I need to change? Before the site change MD's download speed was normal.

**Comment by SDXC** [comment]
on my machine (Switzerland, no Proxy, no VPN) I have 3.5 Mbps on MD.
Maybe it's a regional problem with one of the image servers.

**Comment by spamtaztik** [comment]
Hmm... Well dangit. It's really frustrating because sometimes it would go as low as below 10K <sigh> for a minute or two before going back up. Most of my favs are from MD, so it's doubly frustrating.

Oh well, I'll just leave the PC running overnight while I sleep then. 
Thanks for checking @SDXC.
