### ISSUE TITLE
mangadex: DDoS-Guard issues  [no fmd issue]

### ISSUE THREAD

**Issue by muto4013** [fmd-project-team/FMD#722]
i just got some DDoS-Guard ip-bans at Mangadex since this morning, here a temp workaround:
slow FMD down, under options/websites/advanced/mangadex set all limits to 1,
renew your IP,
Get cookies from browser and insert into cookies field,
Check your user agent entry, DDoS-Guard seems to dislike some agent-entry's, especial apple or linux had resolved in another ip-ban.
CloudflareBypass should be disabled.
Be aware that the cookies last only few hours, sometimes you need to renew the cookie entry and if you got banned renew your ip before using a new cookie.

Reminder: if you don't know how to get the cookies please visit the wiki, (japscan or lhscan gives a hint)

**Comment by WildCrow** [comment]
Confirmed the DdoS-Guard ban, and yes the cookie workaround worked with my Firefox cookie but had problems with Chrome.

**Comment by Tmp341** [comment]
It was CF ban before, now after their server change it is Ddos-guard. They probably flagged autoset user agents.

**Comment by SDXC** [comment]
I will create a howto for the wiki. The issue will be closed when the howto is done.
