### ISSUE TITLE
issue with [Mangalife], after the last fix, it started working fine again but now all chapters dont work anymore

### ISSUE THREAD

**Issue by jillybeans** [fmd-project-team/FMD#724]
an issue with [Mangalife], after the last fix, it started working fine again but now all chapters don't work anymore, it might just be my end not sure, but it was working fine for a while, but today every chapter I try to download no longer works anymore, at least the latest chapters of these ones, the site still works, just not on FMD

https://manga4life.com/manga/Gokushufudou-The-Way-Of-The-House-Husband
https://manga4life.com/manga/Be-Blues---Ao-Ni-Nare
https://manga4life.com/manga/Sen-no-Sukiru-o-Motsu-Otoko

**Comment by jillybeans** [comment]
it started working again but im not sure if its because i stopped downloading for a bit or because it fixed it self

**Comment by SDXC** [comment]
i experienced it myself. not sure what it was but it also works for me again.

just a side note: restarting the download tasks didn't work. I had to re-add the chapters to download.
