### ISSUE TITLE
Site changed domain & Update manga lists not work [DoujinYosh]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#728]
From "https://doujinyosh.xyz"
To "https://doujinyosh.fun"

**Comment by Slasar41** [comment]
Should be fixed.

**Comment by MIRVOUS** [comment]
Still can't update manga lists

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/72345291-eab02d00-3705-11ea-9a2a-b98a4774d98d.png)

**Comment by MIRVOUS** [comment]
now can. maybe the internet was slow at that time.
