### ISSUE TITLE
Other download link for FMD 0.9.167.2

### ISSUE THREAD

**Issue by fyamyy** [fmd-project-team/FMD#729]
Hi, I've been trying to download the latest zip release from https://github.com/fmd-project-team/FMD/releases/tag/0.9.167.2 but it keeps failing. The speed is slow and then ended up with a failure for any of the zip releases, win32 or win64, and yet the download for the source code can be completed with ease. 

I don't think I can install it with the source code since I'm not that tech-savvy, is there some reasons why I can't download it? Does anyone have another link where I can download the zip for win32? 

Thanks in advance

**Comment by Tmp341** [comment]
Do you have a firewall or something?

**Comment by fyamyy** [comment]
> Do you have a firewall or something?

Nope, and I can download it now finally. I guess there was some problem with the server before
