### ISSUE TITLE
Can't download chapters [MangaYosh]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#73]
![fmd13](https://user-images.githubusercontent.com/45929526/55783815-7f339200-5ad9-11e9-9f54-9a93bb85f916.PNG)
![fmd14](https://user-images.githubusercontent.com/45929526/55783836-865aa000-5ad9-11e9-829a-0e56be119ed7.PNG)
![fmd15](https://user-images.githubusercontent.com/45929526/55783837-86f33680-5ad9-11e9-8045-3d60e89d710a.PNG)

**Comment by MIRVOUS** [comment]
it is only produces an empty folder

**Comment by AbidZakaria** [comment]
give me a manga link that has nuances

**Comment by SDXC** [comment]
Should be fixed now. I tested some manga titles and they all worked. I'll close this issue. If something's still off, please re-open this issue.
