### ISSUE TITLE
Domain change [Mangadex]

### ISSUE THREAD

**Issue by Dgraid12** [fmd-project-team/FMD#730]
I think it would be nice to change the domain from "mangadex" back to ".org"

**Comment by JokoeSukri** [comment]
mangadex ".to" ".cc" became secondary backup domain and redirect into primary ".org"
Rather to replace .cc into .org, I hope FMD admin just add .org and leave .cc intact

**Comment by JokoeSukri** [comment]
If you waiting SDXC, pretty sure he's online 8-12 hours from now.
If you want fix it immediately, its pretty easy while DIY
**<<your directory>>\fmd_0.9.167.2_Win64\lua\modules\mangadex.lua**
![Screenshot_200](https://user-images.githubusercontent.com/32964994/72320341-d7d93080-36e4-11ea-97b3-aaa42efbcd96.jpg)
**Voila....**
.
![Screenshot_26](https://user-images.githubusercontent.com/32964994/72320515-33a3b980-36e5-11ea-9b73-6d11e9196551.jpg)
![Screenshot_27](https://user-images.githubusercontent.com/32964994/72320532-3b635e00-36e5-11ea-9489-d0dc902ba0d5.jpg)
