### ISSUE TITLE
Annoying Display

### ISSUE THREAD

**Issue by lamphong0806** [fmd-project-team/FMD#734]
![Screenshot (127)](https://user-images.githubusercontent.com/59887040/72384123-5e2a5c80-374f-11ea-990d-04dd0deb1ca7.png)
This is my default display after i install it
Does anyone know how how to fix it ?
Thanks

**Comment by Slasar41** [comment]
Try this: https://github.com/fmd-project-team/FMD/issues/167#issuecomment-492319798

**Comment by dazedcat19** [comment]
AFAIK, the current VTV v4 doesn't have a dpi-awareness.

Try this build with VTV v5.
https://drive.google.com/file/d/1-AMy2udlNV7VIj3tANfk4WpmkasYkVnE/view?usp=drivesdk
https://drive.google.com/file/d/1-DtUsdCqPJYZlR8XN7TrfKhHXq2LBE7C/view?usp=drivesdk

You may also need to use this dlls tho. Download everything to your fmd instalation. 
https://github.com/fmd-project-team/FMD/tree/master/dist

**Comment by dazedcat19** [comment]
This issue fixed in release 1.0
