### ISSUE TITLE
Cannot Update MangaDex Manga List

### ISSUE THREAD

**Issue by BuroP** [fmd-project-team/FMD#736]
It has been a couple of weeks that I can't update the manga list for MangaDex, so I can't download the newer manga. is there a way around this?

**Comment by Tmp341** [comment]
I think i've updated my list and uploaded it on server. Try downloading it, i will update it again.

Mangadex changed ddos protection firm, so you might have been flagged falsely.

**Comment by BuroP** [comment]
thank you for the update!

**Comment by Tmp341** [comment]
> 
> 
> thank you for the update!

I've updated server database yesterday. You can download it again if you want.
