### ISSUE TITLE
KissManga not working

### ISSUE THREAD

**Issue by alzamer2** [fmd-project-team/FMD#737]
hi
thanks foe new update
new cloudflare is working fine and i was able to view and dowanload manga that needed it.
but KissManga not downloading, when i gone to the page of manga they asked me if i'm human
And only after i copied the cookies and user agent of kissmana i was able to download

**Comment by SDXC** [comment]
FMD can't solve captchas, including the "Are you a human?" page.
Normally this is just a temporary state which can happen if KissManga gets too many hits either in general (many users, DDoS, etc.) or from your network (too many hits in a short amount of time from same address).
