### ISSUE TITLE
KissManga don't download chapters

### ISSUE THREAD

**Issue by GDXN** [fmd-project-team/FMD#739]
FMD fails to download chapters. I tried copying the cokkies and usestring from browser but it din't work to fix it.

**Comment by Slasar41** [comment]
Can load the manga info but failed to download?
Try this guide: https://github.com/fmd-project-team/FMD/wiki#troubleshooting-guides

**Comment by Tmp341** [comment]
Just tried, and it started downloading. 

Kissmanga uses Cloudflare, and you need to pass a captcha and then use the workaround mentioned by Slasar41.

**Comment by GDXN** [comment]
thanks, it was the key that changed.
