### ISSUE TITLE
Add a site

### ISSUE THREAD

**Issue by Ahmad252525** [fmd-project-team/FMD#744]
Hello, can you support this site in your application?  They are a big Arab team that translates manga.

🗳| https://3asq.org/

**Comment by Tmp341** [comment]
It is already supported. Maybe they've changed coding. Are you using latest [0.9.168.1](https://github.com/fmd-project-team/FMD/releases/tag/0.9.168.1)?

**Comment by Tmp341** [comment]
I've updated database, download it from ``server``.

**Comment by Ahmad252525** [comment]
Where can I download the latest version?  The existing version is 0.9.158.1

**Comment by Ahmad252525** [comment]
Yes I am using  latest  0.9.168.1 and have not found it

**Comment by Ahmad252525** [comment]
I did not find it in any list either modules or advanced
