### ISSUE TITLE
Komikcast error

### ISSUE THREAD

**Issue by Rifcky21** [fmd-project-team/FMD#745]
Cannot get manga info, update list manga, and download manga from website komikcast

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/73051562-80da1500-3eb5-11ea-92d2-c8587df8a284.png)
![image](https://user-images.githubusercontent.com/28888646/73051425-496b6880-3eb5-11ea-8587-efbb81b73f43.png)

**Comment by Tmp341** [comment]
Mine updates database now. I don't see any problem either.
