### ISSUE TITLE
Website changed URL [TheCatScans]

### ISSUE THREAD

**Issue by arbiter9605** [fmd-project-team/FMD#75]
Since now you are updating, its rather simple and minor addition too foolsslide module. Catscans moved to a new reader link where old link was reader.catscans and new one is reader2.catscans. So could add a line to that lua so their site works. I had it manually added for fmd 131 since it wasn't being updated. This way downloading from their reader works as well.

"AddWebsiteModule('TheCatScans2', 'https://reader2.thecatscans.com', cat)"

**Comment by SDXC** [comment]
Did they change the url only? Then I'd rather change
`AddWebsiteModule('TheCatScans', 'https://reader.thecatscans.com', cat)`
to
`AddWebsiteModule('TheCatScans', 'https://reader2.thecatscans.com', cat)`
instead of making it TheCatScans2.

**Comment by SDXC** [comment]
Script has been updated. I'll close this issue now. If anything's wrong, just re-open this issue.
