### ISSUE TITLE
Unable to download from Readcomiconline despite using cookies and useragent

### ISSUE THREAD

**Issue by newmanism17** [fmd-project-team/FMD#752]
I can't download from Readcomiconline despite using cookies and useragent from the website

I have a version of fmd that's fully updated so I don't think the version is any issue.

I tried with a fresh installation also, but it goes "0/1 to 1/1" for every chapter
At the very least it's consistent I guess
I checked which websites were working on the Github, and apparently Readcomiconline shows up as working

Back when Cf_bypass was still a thing I did everything the same way and it worked then, so I'm really confused about what's happening and I don't know enough about this stuff

If y'all need any logs from my instance of fmd, just let me know

**Comment by Slasar41** [comment]
I can download just fine without using the cookies workaround.
![image](https://user-images.githubusercontent.com/28888646/73336496-8c0db600-42a4-11ea-86c3-d5edd57eb8e3.png)
Try using a VPN
