### ISSUE TITLE
Lost all my favorites after FMD crash.

### ISSUE THREAD

**Issue by formigao** [fmd-project-team/FMD#753]
is there a way to backup it ?  where the favorites are saved ?

**Comment by Slasar41** [comment]
Check `works` folder if there's any files

**Comment by formigao** [comment]
> Check works folder if there are any files

they are here. but FMD cant read it. shows 0 favorites =/

**Comment by formigao** [comment]
i've uploaded my works folder.
https://mega.nz/#!ooYVlCZC!NS0AU4JJ2a9mWCzGpbN0Z-kUoAwMu763QVy2IeeFtdA

can someone desbug it ?

**Comment by Slasar41** [comment]
Looks like the favorites file got corrupted, I can't open it with DB Browser program.
Wait for other people to confirm it.

**Comment by SDXC** [comment]
yeah, that one is gone. normally you can open sqlite files in notepad and you will see most of your entries. FMD probably crashed while it was writing to the file.

**Comment by formigao** [comment]
lost everything them ? =/

**Comment by SDXC** [comment]
Yes and no...

Of course you lost the favorites as-is in that database file, but for restoring most of it (manually though) you can at least use the entries from "downloadedchapters.db" to help you with that.

I extracted the website links and put them in a text file for you.
It's not the most reliable way to find your favorites again, but it can help you.

[export-downloaded-chapters.txt](https://github.com/fmd-project-team/FMD/files/4130227/export-downloaded-chapters.txt)

**Comment by formigao** [comment]
ty. is there a way to do periodically backups ?
if not i strongly ask for it.

after losing a list with 150+ favorites... i would really love it the favorite file had some duplicates saved to avoid it happenning again.
