### ISSUE TITLE
Not work knightnofansub

### ISSUE THREAD

**Issue by rs3mk** [fmd-project-team/FMD#754]
Hi.

There was a change in your access to comics.

Old:
`https://knightnofansub.site/biblioteca/survival-story-of-a-sword-king-in-a-fantasy-world/`

New:
`https://knightnofansub.site/bl/survival-story-of-a-sword-king-in-a-fantasy-world/`

Regards

**Comment by Slasar41** [comment]
The old link still works for me in FMD.
Just need to update the manga list so it'll get the new link.

**Comment by Tmp341** [comment]
Just delete and readd ``fansub.db`` file.

**Comment by knightnoscanlation** [comment]
![image](https://user-images.githubusercontent.com/60488087/73557923-247c7580-4420-11ea-96a4-ca4339325e89.png)

**Comment by rs3mk** [comment]
If there are many favorites, it works to edit the file.
https://github.com/riderkick/FMD/issues/1283#issuecomment-398511717

change domain to: knightnoscanlation.com

**Comment by Tmp341** [comment]
3d7af93 changed the url. But couldn't update database.

**Comment by Slasar41** [comment]
@Tmp341 you can update the database now.

**Comment by Tmp341** [comment]
Updated database.

If your problem continues, reopen this issue.
