### ISSUE TITLE
Auto backup settings everyday 

### ISSUE THREAD

**Issue by dazedcat19** [fmd-project-team/FMD#755]
To make it simple it just auto backup all config and databases file everyday. Maybe a limit to 7 backup and the older backup file will be deleted. It has no auto import. User has to import it manually in case of corrupted files.
I'm thinking just to use one of the existing periodic timer or add a new static periodic timer. Idle timer would be preferable.
The backup file will utilize 7z that already included in fmd distribution.

**Comment by Slasar41** [comment]
Maybe also add a new tab as I suggested in this issue?
https://github.com/fmd-project-team/FMD/issues/280#issue-457094712

**Comment by dazedcat19** [comment]
I will just add the basic. The other free to add more functionality. Import, export, gui settings etc. Just don't mess with the basic. To import a setting you need to terminate all threads, close and lock the database, maybe lock some ui too, since some list read/write directly to the database, etc.

**Comment by Slasar41** [comment]
Okay.
While you're on it, could you fix my issue regarding the database files? https://github.com/fmd-project-team/FMD/issues/177
Maybe increase the time interval to 5 or 10 minutes so I'll less notice the freeze.
