### ISSUE TITLE
Not Issue but request if there development of a MangaReader for FMD?

### ISSUE THREAD

**Issue by StormJumper** [fmd-project-team/FMD#759]
Will there be a future development where there is a MangaReader that read the download manga and opens it in a self contained Reader for FMD? I don't like how you have to go to the folder and use the O/S default viewer to open the manga to read it.

**Comment by Tmp341** [comment]
Well, FMD supports external readers. I use XnView on PC myself. Go ``Options\General\External Program\`` and set one you like.
