### ISSUE TITLE
Re-arrange the OK and Cancel button

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#76]
Could you re-arrange the OK and Cancel button to the same place for better consistency?
![image](https://user-images.githubusercontent.com/28888646/55823002-00ffdb80-5b2b-11e9-9ba6-028dd21978f4.png)

**Comment by SDXC** [comment]
Implemented. Wait for Release.

**Comment by SDXC** [comment]
Version 0.9.163.0 has been released.
