### ISSUE TITLE
[Question] About MangaDex's Advanced setting

### ISSUE THREAD

**Issue by gooreat** [fmd-project-team/FMD#761]
Not really and issue (I think), but do I need to enable the MangaDex's Advanced setting (the one under Options > Websites tab) on the latest FMD version (1.0.0.0)?

Just noticed the setting was disabled after the latest release and usually it was enabled by default to reduce the risk of getting IP banned from that site, IIRC.

Thanks.

**Comment by Tmp341** [comment]
Mangadex has limited settings by default (1 task at a time and 2 connection limit). You can reduce connection limit etc under there, or increase by taking the risk. Also, it was for cloudflare before (it is some another ddos proctection company) cookies.

**Comment by gooreat** [comment]
By default you mean the settings is already in the program code and there's no need to enable the site's advanced setting anymore?  

sorry for the questions, just want to make sure lol

**Comment by Tmp341** [comment]
> ...already in the program code...

Sort of. ``Mangadex.lua`` sets : 

    m.maxtasklimit=1
    m.maxconnectionlimit=2

**Comment by gooreat** [comment]
Oh. If that's the case, I guess it's safe to just leave the setting disabled then?

**Comment by dazedcat19** [comment]
If you want to be really safe maybe enable the setting and set the maxconnection to 1. Maybe even edit the module file mangadex.lua and add `sleep(random(1000,3000))` before every `http.get` or `http.post`. This of course will significantly reduce the download speed.

**Comment by Tmp341** [comment]
> Oh. If that's the case, I guess it's safe to just leave the setting disabled then?

Nothing is safe, since websites use ddos protectors, which track automated requests (like fmd). If you do things fast, you hit a wall (cloudflare etc). But, you can use lowest numbers (``1`` in this case) to be safe as long as possible.
