### ISSUE TITLE
Issues with downloading from MangahubIO

### ISSUE THREAD

**Issue by rahvindel** [fmd-project-team/FMD#762]
issues are queued up but are sitting at downloading with nothing going on. I have made sure the .lua for them is the newest one but no joy.

**Comment by Tmp341** [comment]
fec5f33 should have fixed it. Update your modules.

**Comment by rahvindel** [comment]
My modules are updated and am still getting the same thing. 
![module](https://user-images.githubusercontent.com/15792235/73600208-9503bf00-4512-11ea-966c-bb263dcae990.PNG)

![download](https://user-images.githubusercontent.com/15792235/73600222-b5337e00-4512-11ea-80ae-90445cc0a53f.PNG)

![version](https://user-images.githubusercontent.com/15792235/73600234-cd0b0200-4512-11ea-9650-0b07d0b71515.PNG)
