### ISSUE TITLE
TODO: change the website module unique id

### ISSUE THREAD

**Issue by dazedcat19** [fmd-project-team/FMD#764]
Currently website id is using its unique name. There's a problem when a website changing its name, the name in fmd become irrelevant.
I'm planning to add a unique id for each module. Maybe using UUID/GUID. This of course will break the most of the databases, since they used the website name as identifier. This will be easier to deal with empty databases.
I don't know how to deal with the existing databases. There's already existing conversion codes in existing source, and I'm planning to clean them off.
Maybe providing a conversion tool and let the update break, what do you think?

This is of course will not be implement soon.

**Comment by SDXC** [comment]
I think for the favorites it'd be better to implement a simple conversion function and put that in a separate unit (e.g. uMigration.pas). Also make this function part of the database import utility of FMD.

In case of the website database files I suggest we still use the website name as filename.

**Comment by alzamer2** [comment]
you can create new DB with new table
and make fmd check which DB exist
if he did not find new DB and find old DB===> convert
if he did find both DB (old and new) ======> ignore old and use new (dont delete old DB)
if he did not find any DB (old and new) ====> create new DB

**Comment by dazedcat19** [comment]
I already explained that before. Tho I already removed most of the db conversion(they're more than 2 years old). There's used to be a db check and fmd will convert them on runtime. But the codes became clustered, there's a few times there's db structure change in the past. The point is it's hard to maintain different version of database. The codes will just become messy. It's not so simple as `if not FindFields("field0") then`. There's a lot of thing to do. there's data type conversion and other stuff. Maybe multiple conversion in one go. which make it unstable. there's a few case where it break databases in the past. with so much clustered codes it become so hard to debug. If you ever been to programming. It can take hours just to find a simple bug. that's why I reluctant to change any db structure since then.

**Comment by dazedcat19** [comment]
#501 
I have a new proposal. It's better to stop current version of fmd which is v1.x. The new proposed fmd version is 2.x with new database structure and different filename. Also all of the local config files will be changed. maybe moved to json. since the ini files doesn't support multiline or unicode. it's easier to use json. the database filename on the server also must be renamed to the unique id.
This changes of course will be not compatible with current version of fmd. User have to migrate it manually with provided import tool. So the conversion will be executed only once.

proposed unique id is UUID without bracket without hypen. example: `6859f76f3d424b96b03706c622ec24c5`
