### ISSUE TITLE
Sorting favorites doesn't works properly

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#765]
When I'm sorting it on `Enabled` or `Disabled` options, it'll sorted as if like in `All` option.

**Comment by Tmp341** [comment]
What do you mean?

**Comment by Slasar41** [comment]
Sorry I can't explain it properly.
Here's the recording for what happened: https://i.imgur.com/YAU9Qk4.gifv

**Comment by Tmp341** [comment]
Checked and reproduced it.
