### ISSUE TITLE
Favorite Tab Now Blank after updating to 1.1.0.0

### ISSUE THREAD

**Issue by JLChamberlain** [fmd-project-team/FMD#768]
Just updated to the newest release and now my favorite tab is completely blank! "Check for new chapter" still runs and acts as it should but all info (id number, manga title, website, etc.) is missing.

[Proof](https://i.imgur.com/MpDvoqR.gif)

**Comment by dazedcat19** [comment]
It's fine here 
![Untitled](https://user-images.githubusercontent.com/59296763/73698762-fdbe8780-471c-11ea-8328-4270879c4fab.jpg)

**Comment by Tmp341** [comment]
No problem over here too. Check your favorites with a db browser.
