### ISSUE TITLE
Unable to download [PsychoPlay]

### ISSUE THREAD

**Issue by Geese1** [fmd-project-team/FMD#77]
Been trying to download from the scanlator website, Psycho Play, but the downloads keep failing. I can see the files available to download, but the downloads just don't go through.

I'm assuming it has something to do with Cloudflare, but I'm not sure how to get around the problem. 

Any help would be appreciated.

**Comment by SDXC** [comment]
Check this wiki page:
https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-PsychoPlay

**Comment by Geese1** [comment]
Thanks, was able to figure it out. I just used the __cfduid and cf_clearance values, along with the user agent, and got it to work. I kept thinking there should be more cookies to input, like on the MangaDex fix, but I only needed those two.

**Comment by SDXC** [comment]
in most cases only the mentioned cookie settings are needed. Just to be sure we advise sometimes to use all cookie settings.

I'll close this issue then. Thanks for the feedback.
