### ISSUE TITLE
Mangadex no speed

### ISSUE THREAD

**Issue by Souravi785** [fmd-project-team/FMD#770]
When I download something from mangadex the speed is extremely slow. If it's kissmanga or batoto the speed works fine but with only mangadex, the speed drops to 1/10 of my normal speed for some reason. Is there any solution to this?

**Comment by Tmp341** [comment]
It is for your own safety (and also not causing heavy weight on mangadex server too). If you download too fast, ddos protector bans your IP.

``lua/modules/MangaDex.lua`` contains 2 settings hardcoded:

```lua
m.maxtasklimit=1
m.maxconnectionlimit=2
```
You can try changing those, but prepare for ip bans etc. They've changed from Cloudflare to Ddos-Guard.net, which i don't know what it is capable of.

**Comment by Souravi785** [comment]
But still average 70-100kbps is too slow. What's the maximum value you recommend and how can I change it?

**Comment by Tmp341** [comment]
Higher than those speeds will mark you as target and ban your IP. but if you make them ``0``, you will get max speeds. I've warned you.

**Comment by SDXC** [comment]
@Souravi785 How long does it take when checking for new chapters? It may be, that your mangadex session id cookie is invalid and you have to renew it.

**Comment by Souravi785** [comment]
@SDXC Checking for chapters is normal just like any other sites.
