### ISSUE TITLE
Actively throttle FMD by IP address. [Manhuagui]

### ISSUE THREAD

**Issue by mirlov** [fmd-project-team/FMD#775]
I've noticed since last week that every time I try to download comic from manhuagui, my download will stop half way if there is more than 1 concurrent download task. Once the download have been throttled, 'Update Manga List' will stop functioning for this site as well, even 'viewing manga info' will not work. However, if I change my ip address, normal function will resume.

Can anyone verify my observation? And if there is any way to circumvent this?

**Comment by Slasar41** [comment]
What's the number on your connection options?

**Comment by mirlov** [comment]
![image](https://user-images.githubusercontent.com/8164095/74082159-2aaec980-4a92-11ea-8aa5-8399ee3271b0.png)

**Comment by Tmp341** [comment]
I thought it was Cloudflare issue, but couldn't find a trace about it. But i think website uses slow speed server, thus banning high speed computer requests, like ddos protection.

**Comment by mirlov** [comment]
Nope, no extra setting under Advanced Tab.

If it is the DDOS protection kicking in, does it mean I have to request to be slower than the default setting?

![image](https://user-images.githubusercontent.com/8164095/74084244-4329de80-4aa8-11ea-8962-fcd806e10912.png)

**Comment by Tmp341** [comment]
> If it is the DDOS protection kicking in, does it mean I have to request to be slower than the default setting?

Not sure exactly, but try setting these to ``1``
```lua
MaxTaskLimit=1
MaxThreadPerTaskLimit=1
MaxConnectionLimit=1
UpdateListNumberOfThread=1```

**Comment by mirlov** [comment]
Your settings works! Thanks bro!

Looks like your suspiction on the DDOS protection is on point. Download & 'update manga list' is working now.

Just want to ask you if you have any idea why after using the 'update manga list', I am still not getting some of the newly uploaded manga in FMD to show up? Although on the website, it is available for reading.

**Comment by Tmp341** [comment]
> 
> 
> Your settings works! Thanks bro!
> 
> Looks like your suspicion on the DDOS protection is on point. Download & 'update manga list' is working now.
> 
> Just want to ask you if you have any idea why after using the 'update manga list', I am still not getting some of the newly uploaded manga in FMD to show up? Although on the website, it is available for reading.

Delete or rename ``ManhuaGui.db`` inside ``data`` folder. Then try again.

**Comment by dazedcat19** [comment]
@Tmp341  If it's a server issue, maybe change the default connection settings for this website.

**Comment by dazedcat19** [comment]
@Tmp341  If it's a server issue, maybe change the default connection settings for this website.

**Comment by Tmp341** [comment]
> @Tmp341 If it's a server issue, maybe change the default connection settings for this website.

When i used the settings i've mentioned above, it works. But when i remove them, it just stucks at some point and i can't open via browser. Seems like server keeps low settings, and who passes that will get an IP ban.
