### ISSUE TITLE
Auto Update Manga Modules

### ISSUE THREAD

**Issue by HyruleanKnight37** [fmd-project-team/FMD#778]
I'd like the option to have fmd install new manga modules as well as delete outdated ones automatically, without needing my confirmation. Thank you. You guys are doing a great job.

**Comment by Tmp341** [comment]
![ssss](https://user-images.githubusercontent.com/1683388/74090163-7f196f80-4ab9-11ea-892d-2aec44448fc5.jpg)

Choosing these settings should do those.
