### ISSUE TITLE
Column settings reset after restart

### ISSUE THREAD

**Issue by Tmp341** [fmd-project-team/FMD#782]
First part is the one i've set before, second is the one i've wanted to set, 3rd is what happens when i close FMD:

![sssss](https://user-images.githubusercontent.com/1683388/74214650-43e09180-4caf-11ea-9f1d-60f0c0d78862.jpg)

Why these settings use same position numbers``2`` ? 

```ini
[vtDownload]
SortColumn=1
SortDirection=0
Column0Width=350
Column0Position=0
Column1Width=163
Column1Position=3
Column2Width=94
Column2Position=4
Column3Width=76
Column3Position=5
Column4Width=126
Column4Position=1
Column5Width=372
Column5Position=2
Column6Width=128
Column6Position=2

[vtFavorites]
SortColumn=1
SortDirection=0
Column0Width=43
Column0Position=0
Column1Width=692
Column1Position=1
Column2Width=110
Column2Position=2
Column3Width=143
Column3Position=2
Column4Width=793
Column4Position=3
```

**Comment by dazedcat19** [comment]
what is your dpi setting?

**Comment by dazedcat19** [comment]
I don't get what do you mean. Is it the column's size or the order?
You should post the content of `vtfavorites` before and after.
First is when not running. Second is after you run fmd and close it. And what do you expect. Please elaborate.
Do you even use the same version? Your fmd title is different.

**Comment by Tmp341** [comment]
I've just checked and ``config.ini`` and ``config.ini-run`` are same, even after i've changed columns' places:

![SSSSS](https://user-images.githubusercontent.com/1683388/74237975-cedc7e80-4ce5-11ea-93fd-eda9d8d42e51.jpg)

**Comment by dazedcat19** [comment]
I can't reproduce your issue. Config file only saved after you click apply or when closing fmd. ".run" file simply the temporary file and will be renamed to the actual config.

**Comment by Tmp341** [comment]
Which column keeps that ``current chapter`` setting for me? I want to manually set that.

**Comment by Tmp341** [comment]
Ok, found out what is going on.

So, when i close my FMD, it rewrites my settings:

```ìni
[vtFavorites]
SortColumn=1
SortDirection=0
Column0Width=43
Column0Position=0
Column1Width=692
Column1Position=1
Column2Width=110
Column2Position=3
Column3Width=143
Column3Position=2
Column4Width=793
Column4Position=2
```

**Comment by Tmp341** [comment]
Ok, i've switched to ``100%`` scale, set my order, switched back to ``125%`` and it still keeps it.

**Comment by dazedcat19** [comment]
If you look at the source VT columns width and position are automatically saved with "for loop". So I don't see why it can't save to your desired position.

**Comment by Tmp341** [comment]
> 
> 
> If you look at the source VT columns width and position are automatically saved with "for loop". So I don't see why it can't save to your desired position.

I don't see why it wants my scale lower, to set what i want. Well, now it set what i want.
