### ISSUE TITLE
Can't download 1 particular series in Mangadex

### ISSUE THREAD

**Issue by AnonX007** [fmd-project-team/FMD#783]
https://mangadex.org/title/35013/why-are-you-doing-this-duke

Here's the log.

[fmd.log](https://github.com/fmd-project-team/FMD/files/4185619/fmd.log)

**Comment by Slasar41** [comment]
Same issue as https://github.com/fmd-project-team/FMD/issues/526
You can workaround this by getting the cookies manually.
FMD need user login for MangaDex.

**Comment by AnonX007** [comment]
I'm sorry but how exactly do i do that?

**Comment by dazedcat19** [comment]
@there's should be an example in one of Lua files on how to implement an account feature. There's onlogin method accessible from lua.

**Comment by dazedcat19** [comment]
I have no mangadex account. And they seems to closed the account registration at the moment. Maybe you can send me your account in discord so I can test it

**Comment by Tmp341** [comment]
> 
> 
> I'm sorry but how exactly do i do that?

@AnonX007 Firs, you need to log into your account via browser. Then follow these steps https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation

**Comment by Tmp341** [comment]
> Info: In order to prevent spam accounts, most disposable/temporary email domains are banned. Using these may get your account banned by mistake, so it is advised that you do not use these.

@dazedcat19 Disposable and temporary email providers are banned. But other than that, signups are open.

**Comment by dazedcat19** [comment]
The account should be usable by now once you get the account setup and validated. But it need the new release for proper handling from lua.
