### ISSUE TITLE
Holymanga.net site change

### ISSUE THREAD

**Issue by jillybeans** [fmd-project-team/FMD#784]
site is now http://w11.holymanga.net/her-summon 
the old one (http://ww9.holymanga.net/her-summon ) doesnt work on fmd anymore

**Comment by Thrieze** [comment]
I had to manually add the cloudflare strings then it works. For holy and heaven manga.

**Comment by jillybeans** [comment]
site changed once again, and manually adding the Cloudflare string isn't working anymore for me

http://w14.holymanga.net/her-summon/

**Comment by jillybeans** [comment]
don't know how to reopen
