### ISSUE TITLE
FMD Crash after update

### ISSUE THREAD

**Issue by noering** [fmd-project-team/FMD#785]
After auto update FMD crash and cannot start.
Here's the report:

Unhandled exception!
Application       : Free Manga Downloader
Version           : 1.1.1.0
Product Version   : Win64
Host Machine      : Windows 7 64-bit
FPC Version       : 3.3.1
LCL Version       : 2.1.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2020/02/12 15:09:15
Path              : D\.............................\Free Manga Downloader\fmd.exe  --> edited/hide by me.
Process ID        : 3024
MainThread ID     : 5744
Thread ID         : 5744
Time              : 12/02/2020 20:01:26.498
Exception Class   : EAccessViolation
Message           : Access violation
  $0000000100183546
  $0000000100161467
  $000000010015083C
  $0000000100150815
  $000000010001C76F
  $000000010001D2DE
  $000000010002361F
  $0000000100071E3F
  $000000010001E99E
  $000000010001D251
  $000000010002361F
  $000000010002A6D4
  $0000000100003E0C
  $0000000100003E86
  $00000001000186A0
  $0000000100003457
  $000000007717555D

Screenshot:
![Capture](https://user-images.githubusercontent.com/3715548/74337667-4e944700-4dd3-11ea-8dc2-6fbb8680d98b.JPG)

**Comment by GelgoogGuy** [comment]
Getting the same error, tried copying and pasting the zip files in but same deal.
Unhandled exception!
Application       : Free Manga Downloader
Version           : 1.1.1.0
Product Version   : Win64
Host Machine      : Windows 10 64-bit
FPC Version       : 3.3.1
LCL Version       : 2.1.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2020/02/12 15:09:15
Path              : G:\FMD 4\fmd.exe
Process ID        : 25716
MainThread ID     : 27404
Thread ID         : 27404
Time              : 12/02/2020 08:21:25.642
Exception Class   : EAccessViolation
Message           : Access violation
  $0000000100183546
  $0000000100161467
  $000000010015083C
  $0000000100150815
  $000000010001C76F
  $000000010001D2DE
  $000000010002361F
  $0000000100071E3F
  $000000010001E99E
  $000000010001D251
  $000000010002361F
  $000000010002A6D4
  $0000000100003E0C
  $0000000100003E86
  $00000001000186A0
  $0000000100003457
  $00007FFE8E2E7BD4

**Comment by KeithHanzhel** [comment]
Got the same error.... Should have read this before updating... Damn...

Unhandled exception!
Application       : Free Manga Downloader
Version           : 1.1.1.0
Product Version   : Win64
Host Machine      : Windows 8.1 64-bit
FPC Version       : 3.3.1
LCL Version       : 2.1.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2020/02/12 15:09:15
Path              : D:\Utilities\Browser, Chat & Download Manager\FMD\fmd.exe
Process ID        : 1352
MainThread ID     : 6428
Thread ID         : 6428
Time              : 12/02/2020 20:29:52.051
Exception Class   : EAccessViolation
Message           : Access violation
  $0000000100183546
  $0000000100161467
  $000000010015083C
  $0000000100150815
  $000000010001C76F
  $000000010001D2DE
  $000000010002361F
  $0000000100071E3F
  $000000010001E99E
  $000000010001D251
  $000000010002361F
  $000000010002A6D4
  $0000000100003E0C
  $0000000100003E86
  $00000001000186A0
  $0000000100003457
  $00007FFFFAB416AD

**Comment by JLChamberlain** [comment]
I also can't open FMD after update.
![fmd_n1v2DpJVk6](https://user-images.githubusercontent.com/22307144/74345653-525da480-4da6-11ea-9f30-b9afffb49ced.png)

**Comment by amit34521** [comment]
Tried to revert to OLD 1.1.0.0 version manually. None of the favorites or other items are working. cant see the mangadex and other sites in the manga list as well

**Comment by Tmp341** [comment]
Download previous version and use it until @dazedcat19 fixes this.

**Comment by temp1366** [comment]
Same here

**Comment by SBoyer4** [comment]
I may be overlooking it but I cant find teh previous version

**Comment by dazedcat19** [comment]
Strange. There's no problem here with my computer.
Try this.  I compile it with fpc 3.0.6. maybe that was the problem. Rename .zip to .7z
[fmd_1.1.2.0_Win64.zip](https://github.com/fmd-project-team/FMD/files/4195930/fmd_1.1.2.0_Win64.zip)

[fmd_1.1.2.0_Win32.zip](https://github.com/fmd-project-team/FMD/files/4195917/fmd_1.1.2.0_Win32.zip)

**Comment by GelgoogGuy** [comment]
@dazedcat19 that worked for me, thanks dude.

**Comment by feelingwalnut** [comment]
@dazedcat19 recompiled exe fixed it on win10 64bit.
thank you.

**Comment by noering** [comment]
@dazedcat19 
fmd_1.1.2.0_Win64.zip worked for me, Thank you :)

**Comment by dazedcat19** [comment]
So the problem is the compiler. What version of windows are you using?

**Comment by GelgoogGuy** [comment]
@dazedcat19 I'm on Windows 10 x64 1903 build 183623.592. If it makes any difference I'm using a Ryzen 2700x.

**Comment by noering** [comment]
@dazedcat19
Windows 7 Ultimate SP 1

**Comment by dazedcat19** [comment]
Could be something to do with cpu. Since I can't reproduce it and have no actual stack trace I can't report it to fpc bugtracker.

**Comment by rs3mk** [comment]
Works new build.

Windows 10 Enterprise LTSC [Versión 10.0.17763.973]

**Comment by feelingwalnut** [comment]
Ive got a coffee lake intel cpu.

On February 13, 2020 12:34:43 AM EST, dazedcat19 <notifications@github.com> wrote:
>Could be something to do with cpu. Since I can't reproduce it and have
>no actual stack trace I can't report it to fpc bugtracker.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/fmd-project-team/FMD/issues/785#issuecomment-585559555

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
