### ISSUE TITLE
Can't Download [Mangakakalot]

### ISSUE THREAD

**Issue by eikaichijo01** [fmd-project-team/FMD#786]
cannot download or open from mangakakalot.com

**Comment by Tmp341** [comment]
![ssssssss](https://user-images.githubusercontent.com/1683388/74365062-61f8df80-4dde-11ea-9cf9-3c9e4a68d060.jpg)

No problem here.

**Comment by 7h3Cub3** [comment]
Please check you aren't using a VPN, because some sites like mangafox, mangakakalot and others block your download if you are on a well known VPN network.

**Comment by Black-Dalek** [comment]
some titles were moved from mangakakalot to manganelo, search the title on mangakakalot and it will give you the manganelo new link, next, change it on FMD.
