### ISSUE TITLE
Passwords that contain special characters makes the account invalid.

### ISSUE THREAD

**Issue by AnonX007** [fmd-project-team/FMD#788]
I suspected that it was due to using special characters so i changed my old password to a simpler one without using any special characters and it works now.

My previous password in Mangadex is something like this 

> K,d/2BM{\#*zCdVwP9?F8o{;xg4\C96j- 

generated via password manager. (KeePassXC)

**Comment by dazedcat19** [comment]
Please try the update

**Comment by AnonX007** [comment]
Thank you for the update fix it works now.
