### ISSUE TITLE
Holymanga still doesnt work on fmd even with the changed domain name

### ISSUE THREAD

**Issue by jillybeans** [fmd-project-team/FMD#790]
Holymanga still doesnt work on fmd even with the changed domain name

**Comment by jillybeans** [comment]
examples are 
http://w11.holymanga.net/her-summon
http://w11.holymanga.net/solo-leveling

**Comment by Tmp341** [comment]
Please reopen an issue, if it hasn't been fixed.

Duplicate of #784
