### ISSUE TITLE
Add website holymanga [w11.holymanga.net]

### ISSUE THREAD

**Issue by kks945** [fmd-project-team/FMD#793]
The module named heavenmanga dosen't support it cause of wrong url or so i think plz add it.
url-w11.holymanga.net

**Comment by Slasar41** [comment]
@dazedcat19 HeavenManga and HolyManga couldn't get the cloudflare cookies automatically.
It produce an error like this:
![image](https://user-images.githubusercontent.com/28888646/74593136-ca53f500-505a-11ea-8f6e-6b43a85e78ae.png)
If I set the cookies manually, then the manga info will load properly.

**Comment by jillybeans** [comment]
the url was changed again its now 
http://w12.holymanga.net/her-summon/

**Comment by Slasar41** [comment]
Should be fixed.
