### ISSUE TITLE
Zero Chapters for comic under the 'Mature' category. [Manhuagui]

### ISSUE THREAD

**Issue by mirlov** [fmd-project-team/FMD#794]
I've tried to download some of the manga's under the 'Mature' category, but they are always listed with zero chapters.

One of the example: [https://www.manhuagui.com/comic/7826/](url)
and this as well: [http://www.manhuagui.com/comic/26224/](url)

Is there any workaround for this?

**Comment by Slasar41** [comment]
Duplicate of https://github.com/fmd-project-team/FMD/issues/579
Wait for someone able to fix it.

**Comment by mirlov** [comment]
Thank you for fixing this bug.
