### ISSUE TITLE
Add new site [manamoa]

### ISSUE THREAD

**Issue by Dgraid12** [fmd-project-team/FMD#795]
Well, I wanted to ask if this site could be added as raw Korean, I don't know if it works with FMD but I know it has no problem with the cloudflare or as far as I could see

![imagen](https://user-images.githubusercontent.com/53473707/74673310-5d894980-5185-11ea-8496-f4ea007706a3.png)

**Comment by Tmp341** [comment]
Duplicate of #296

**Comment by Tmp341** [comment]
Request was already filled in and pending at #351.
