### ISSUE TITLE
MangaHasu Cloudflare issue

### ISSUE THREAD

**Issue by Thrieze** [fmd-project-team/FMD#796]
Cloudflare does not kick in until you select a chapter of a manga on their website. We had the setting before where you could enter a page for the CF module to check against. The list of manga and chapters shows up fine but downloading doesn't work, Worked once i put in the CF cookie manually.

**Comment by Tmp341** [comment]
When you use manual cookies, it works right?

**Comment by Thrieze** [comment]
Yep, But I have to pick and manga and choose a chapter to get the cloudflare cookie. The main page doesn't have cloudflare it seems.

**Comment by Tmp341** [comment]
We were using external cf bypasser, but developers abandoned that. You need to get cookies manually.
