### ISSUE TITLE
[Cloudflare] Problem with this Sites [TimelessLeaf] [Funmanga]

### ISSUE THREAD

**Issue by Von07** [fmd-project-team/FMD#80]
**Problem:**
![Problem](https://user-images.githubusercontent.com/21298898/55848853-0425b680-5b81-11e9-9405-62d63db5b76b.png)

I tried following this https://github.com/fmd-project-team/FMD/issues/61 & https://github.com/fmd-project-team/FMD/issues/71  but still won't work.. 

Version	:	0.9.162.0

**Comment by AbidZakaria** [comment]
Try https://github.com/fmd-project-team/FMD/issues/71

**Comment by Von07** [comment]
> Try #71

Still won't work

**Comment by Tmp341** [comment]
So, you can open those sites, but can't download even though you've added CF workaround?

**Comment by Tmp341** [comment]
I've done what i've explained in #71 for FunManga, and got the mangalist without a problem.

**Comment by Von07** [comment]
> So, you can open those sites, but can't download even though you've added CF workaround?

Yes



> I've done what i've explained in #71 for FunManga, and got the mangalist without a problem. It is downloading too.
> 
> Edit: TimelessLeaf is working too.

That's weird I can open funmanga and the chapter in websites but in FMD I can update the mangalist of funmanga but opening a manga it says N/A

while the TimelessLeaf some manga says N/A while the other manga can be open and downloaded.. it seems like the location has been change somehow..

**Comment by Von07** [comment]
Edit: WHAT HAVE I DONE!! I'm really sorry for this Issue it seems like I'm the one who cause this myself and I didn't notice that.. 
Problem is that I head to connection tab then I saw that my " Connection Timeouts was [1] " so I change it to [30] then after that it is fix now..

**Comment by SDXC** [comment]
No problem. Thanks for your feedback.
