### ISSUE TITLE
mangatx    (madara)

### ISSUE THREAD

**Issue by baytout00** [fmd-project-team/FMD#801]
https://mangatx.com/

Can you add this website as well?
https://mangalink.cc
Arabic Source
Tanks

**Comment by Tmp341** [comment]
Follow your request via main requests issue #351

**Comment by Slasar41** [comment]
MangaTX has been supported. https://github.com/fmd-project-team/FMD/commit/25a3f673961323287364f7d264dc6987a66ad5ca
