### ISSUE TITLE
Download feature is not working [Komiku]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#802]
this manga : `http://komiku.co/manga/my-wife-is-a-demon-queen/`. ch. 170.
and something is not work properly. see screenshot :
![komiku](https://user-images.githubusercontent.com/45929526/74821849-cebc2e80-5336-11ea-9364-81ed80955a7b.PNG)

**Comment by Slasar41** [comment]
Should be fixed.

**Comment by MIRVOUS** [comment]
can't be download a manga
![komiku](https://user-images.githubusercontent.com/45929526/75090262-a3824b00-5593-11ea-9411-dcaacb08175b.png)

**Comment by Tmp341** [comment]
> 
> 
> can't be download a manga
> ![komiku](https://user-images.githubusercontent.com/45929526/75090262-a3824b00-5593-11ea-9411-dcaacb08175b.png)
> please fix it

Slasar41 removed Clodflare tag, but i've added that on purpose, since you might have hit CF firewall. Have you tried manual CF workaround?

**Comment by Slasar41** [comment]
They changed the structure again.

**Comment by Slasar41** [comment]
Should be fixed.
