### ISSUE TITLE
Download fail from [Hentainexus]

### ISSUE THREAD

**Issue by lamphong0806** [fmd-project-team/FMD#806]
My first time download from Hentainexus usually fail, after that if i resume download it works just fine.
I don't know why but it is very annoying, it seems like it only occur when i have more than one task in progress, download each chapter one by one doesn't have this issue an it only onHentainexus

**Comment by Tmp341** [comment]
![SSSSS](https://user-images.githubusercontent.com/1683388/74906170-3fa82880-53c1-11ea-94ba-694a25d65fdb.png)

Works over here.
