### ISSUE TITLE
Unable to update Manga List due to DDNS protection. [Manhuagui]

### ISSUE THREAD

**Issue by mirlov** [fmd-project-team/FMD#808]
Due to the low setting of Manhuagui's DDNS protection, I've found out that FMD is only able to update new manga list when UpdateListNumberOfThread & UpdateListDirectoryPageNumber is set to 1, which also means FMD will only look at page number 1 for new manga, while ignoring the other 800+ pages. Which leads to the other 800+ pages of manga (Old & New) , starting from page 2 of the website not being scanned and added to the list. 

Is there anyway to lower the request time for each page, so that we won't trigger the DDNS protection?

Or maybe a function for us to be able to choose a range of pages to scan, so that we can spread out the task accordingly.

**Comment by Tmp341** [comment]
Set these to ``1`` :
```lua
Enabled=Ticked (True)
MaxTaskLimit=1
MaxThreadPerTaskLimit=1
MaxConnectionLimit=1
UpdateListNumberOfThread=1
```
