### ISSUE TITLE
Can't download manga list from server with 32bit fmd on 64bit computer

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#81]
![fmd16](https://user-images.githubusercontent.com/45929526/55862394-91c5ce00-5ba2-11e9-8b77-258ac50f2e29.PNG)
![fmd17](https://user-images.githubusercontent.com/45929526/55862451-b02bc980-5ba2-11e9-9caf-f3ce549582cd.PNG)

**Comment by MIRVOUS** [comment]
I tried all the lists and the results were the same

**Comment by MIRVOUS** [comment]
I did it so I could move it to my laptop

**Comment by MIRVOUS** [comment]
sorry wrong type

**Comment by Tmp341** [comment]
- Is your folder contains any Unicode character?
- Are you trying to launch from ``C:\`` drive?

**Comment by MIRVOUS** [comment]
-  I don't know how to check it?

- no i'm from D:\ Drive

- default of windows

**Comment by Tmp341** [comment]
``D:\Program Files\Portable\Fmd`` this is my FMD folder. If i add ``ö``, like ``D:\Program Files\Portable\Fmdö``, it becomes buggy.

**Comment by MIRVOUS** [comment]
yes i can't download anything from the server.
but i can download from "update all lists at once"

**Comment by SDXC** [comment]
Please enable the log in FMD and retry. Post the log here afterwards.

**Comment by MIRVOUS** [comment]
okk. thanks now is work.
that is the log

[fmd.log](https://github.com/fmd-project-team/FMD/files/3062970/fmd.log)

**Comment by Tmp341** [comment]
Since you've closed this, may i assume your problem fixed?

**Comment by MIRVOUS** [comment]
sorry long reply.
yes. the problem is fixed
