### ISSUE TITLE
[WebToons] Add support for WebToons accounts

### ISSUE THREAD

**Issue by Leguron** [fmd-project-team/FMD#810]
I want to be able to add my WebToons account so that I'm able to download more than the last 10 chapters.

**Comment by Slasar41** [comment]
Looks like same issue as https://github.com/fmd-project-team/FMD/issues/710
Which title that only list 10 chapters?

**Comment by Leguron** [comment]
It's "The Gamer"

![The Gamer](https://user-images.githubusercontent.com/21092308/75097545-38913e00-55ac-11ea-97c8-93660be2a3e9.PNG)

**Comment by Slasar41** [comment]
It's listed all the chapters on my side without applying the cookies.
![image](https://user-images.githubusercontent.com/28888646/75104976-ef8bc900-5641-11ea-8991-9f412dd5fbda.png)

I want to try to fix it but I can't test it. Could you test it?
[WebToons.zip](https://github.com/fmd-project-team/FMD/files/4240671/WebToons.zip)
Extract it, put it in lua\modules folder. Remove the workaround.

**Comment by Leguron** [comment]
It works now without the workaround. Thanks.
