### ISSUE TITLE
FMD doesn't save download list when crashed?

### ISSUE THREAD

**Issue by spamtaztik** [fmd-project-team/FMD#811]
These last few days my PC froze a lot because I want to play prototype2 again (sigh, nostalgia), but from that I noticed that FMD doesn't seem to save download list unless I exit the program manually... 

So let's say today I have 50 downloads done, then I deleted some, added some more, making the total at the end of the day 30 downloads. If my PC freeze and has to be reset again, after reset the download list would revert to the 50 I had before the crash. If I want to keep the new download list, I have to exit FMD manually, then restart it. A bug?

**Comment by Tmp341** [comment]
It is not a bug. FMD saves datas in ``.db`` database files. While FMD running, it uses temp files, which writes over existing ones, when it successfully finishes that action. For example, when you update a manga list, it creates 2 extra files, until you stop that or it finishes by itself.
![sssss](https://user-images.githubusercontent.com/1683388/75008385-f4594d00-5488-11ea-89cf-a4cf25696758.jpg)

**Comment by spamtaztik** [comment]
I see that in the WORKS folder there are 3 .db files, and from time to time there would also be a  .db-journal file for each .db files. Are these the temp files? 

When will the .db-journal files be made permanent into the .db files? Because I see earlier, the 3 .db files' "date-modified" is 20 Feb (some 20 hrs ago my time), while the .db-journal file's "date-modified" is about 10 minutes ago.

**Comment by Tmp341** [comment]
Yeah, ``.db-journal`` is the temp file. Like i said, when fmd successfully closed (not a crash etc occured), FMD overwrites temp files over old files, makes them up-to-date.

**Comment by spamtaztik** [comment]
Would it be possible to make FMD overwrite the old .db files after a pre-set amount of time? My PC is almost never turned off and FMD is also almost never closed (unless there's a new FMD version or lua update), so the overwriting of .db files by the temp ones almost never happen. 

It would suck so bad if one day the difference between the .db and temp files become so far (more than several days), then FMD crashed and all changes/updates/new downloads are gone.

**Comment by Tmp341** [comment]
When your pc crashes, just rename temp files with original ones. 

My pc crashed today, and i was updating a list. It left temp files there, so i just renamed ``__MangaNT.db`` to ``MangaNT.db`` and got a half finished list. If you are not sure which file is the good one, just rename the one with high file size (MB).
