### ISSUE TITLE
some glitches after 1.2.0.0 update

### ISSUE THREAD

**Issue by muto4013** [fmd-project-team/FMD#815]
Thanks for the update but it seems something went wrong:

Modules list under option/websites/modules is empty, but modules still exist in folder.
Changelog.txt was not updated, it reads still 1.1.3.0 (in my case, haven't updated).

Haven't checked everything yet, if there is more i will update the post.

**Comment by dazedcat19** [comment]
You need to update to version 1.2.0.0. Many modules dependencies have been moved to other structure. Thus they will fail to start.
Note that the files served on raw.githubusercount.com which we use to download most of our update is cached one. So they may not updated to some area for some times.
