### ISSUE TITLE
Bato.to missing

### ISSUE THREAD

**Issue by Sakurahime08** [fmd-project-team/FMD#817]
Has bato.to been removed? Please bring it back T.T

Thank you!

**Comment by Tmp341** [comment]
[lua.zip](https://github.com/fmd-project-team/FMD/files/4238907/lua.zip)

Put this file inside ``config`` folder, and extract it.

Then close FMD, delete ``modules`` folder, restart FMD.

**Comment by dazedcat19** [comment]
It seems my auth token was busted.

**Comment by Sakurahime08** [comment]
Thank you!

**Comment by Tmp341** [comment]
This problem should have been fixed with the latest update too.
