### ISSUE TITLE
[FMD 1.1.3.0] Lua modules gone after the latest update

### ISSUE THREAD

**Issue by gooreat** [fmd-project-team/FMD#818]
Is this normal with the latest update? Can't see the list anymore on the Modules tab.

**Comment by Tmp341** [comment]
[1.2.0.0](https://github.com/fmd-project-team/FMD/releases/tag/1.2.0.0) is the latest release, and with it, modules changed it's structure.

**Comment by gooreat** [comment]
Oh, actually it's 1.2.0.0. 
I read the latest version wrong in the Changelog tab. Sorry about that. 

So yeah, the modules list is missing. It's working before that (in 1.1.3.0)

**Comment by Slasar41** [comment]
Try: https://github.com/fmd-project-team/FMD/issues/816#issuecomment-589924848

**Comment by gooreat** [comment]
Huh. Not sure why, but suddenly I got prompt for modules update. Didn't get any before that.  
  
Guess that's fix it then lol Thanks.

**Comment by Tmp341** [comment]
I think you got your own ``lua.json`` file. Might be a late file download.

**Comment by dazedcat19** [comment]
It's because the github api rate limit exceeded. the limit is 5000. So, there's at least a thousand user doing using 5 check update already. As a workaround you can use your own token and put it in base.ini
