### ISSUE TITLE
Show rating in manga info tab

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#82]
![fmd18](https://user-images.githubusercontent.com/45929526/55870260-5fbc6800-5bb2-11e9-8962-f4176d698c72.PNG)
![fmd19](https://user-images.githubusercontent.com/45929526/55870261-6054fe80-5bb2-11e9-9f3e-1d1bb1c1670f.PNG)

maybe before or after "status:"

**Comment by SDXC** [comment]
We won't implement this. This would result in multiple other requests (filtering and changing website scripts) which we don't have time for and most users probably don't use anyway.
