### ISSUE TITLE
Chapters order

### ISSUE THREAD

**Issue by Souravi785** [fmd-project-team/FMD#821]
I didn't notice till today but when downloading chapters .5 comes before its original number. For example if I download chapter 1 and 1.5 together of a manga, chapter 1.5 comes before chapter 1 even though chapter 1.5 should be later. Is there any fix?

**Comment by Slasar41** [comment]
Which website and manga?

**Comment by Souravi785** [comment]
Basically, every website I tried, kissmanga, isekaiscans, timelessleaf, and the manga name is above all gods.

**Comment by Tmp341** [comment]
It is window's behaviour afaik.

**Comment by Tmp341** [comment]
Can you show us some screenshots?

**Comment by Thrieze** [comment]
Yea, its a windows naming thing, I think. I ended up doing %NUMBERING% %CHAPTER% for chapter name, so It semi ignores that and just has it numbered by how FMD sees it. So I can ignores names and just load them all into CDisplay in proper order.

![image](https://user-images.githubusercontent.com/26678868/75130756-fc3e0a80-569d-11ea-9f04-455a30915167.png)

**Comment by Souravi785** [comment]
Here's a screenshot

![Chapte order](https://user-images.githubusercontent.com/24958560/75134924-0269d080-570a-11ea-8558-ec93a4542459.PNG)

**Comment by Tmp341** [comment]
I think it is cause by naming files.

**Comment by Slasar41** [comment]
Could you just sort by date created/modified?

**Comment by Tmp341** [comment]
It is CDisplay that (and also some other apps) thinks 89.5 is smaller (before etc) than 89. You need to manually edit those.

**Comment by Souravi785** [comment]
> It is CDisplay that (and also some other apps) thinks 89.5 is smaller (before etc) than 89. You need to manually edit those, or try jus `%Numbering%`, as chapter name contains `x.5` already.

Manually editing so many files is difficult. Are there any other option? Sorting by date is my last resort (by Gouenji).

**Comment by Tmp341** [comment]
> Manually editing so many files is difficult. Are there any other option? Sorting by date is my last resort (by Gouenji....me).
> 
> Ok. Sort by doesn't work either. I tried out various command in FMD, but nothing works. How do I try out the "numbering" thing?

I've just suggested that, don't know whether it will work or not. I use [File Renamer Basic](https://www.sherrodcomputers.com/products_filerenamer.cfm) for batch renaming.

**Comment by Souravi785** [comment]
> > Manually editing so many files is difficult. Are there any other option? Sorting by date is my last resort (by Gouenji....me).
> > Ok. Sort by doesn't work either. I tried out various command in FMD, but nothing works. How do I try out the "numbering" thing?
> 
> I've just suggested that, don't know whether it will work or not. I use [File Renamer Basic](https://www.sherrodcomputers.com/products_filerenamer.cfm) for batch renaming.

I will try using that. Let's see if it works.
