### ISSUE TITLE
[FMD 1.2.3.0] All progress lost after update from FMD 1.2.2.0

### ISSUE THREAD

**Issue by JokoeSukri** [fmd-project-team/FMD#823]
![Screenshot_28](https://user-images.githubusercontent.com/32964994/75117249-25b56100-56b3-11ea-9d64-e2607109769b.jpg)

**Comment by Black-Dalek** [comment]
i have the same issue

**Comment by JokoeSukri** [comment]
![Screenshot_29](https://user-images.githubusercontent.com/32964994/75117435-b3458080-56b4-11ea-9fa6-653cce9b8a25.jpg)
At least I saved few backup and revert back into ver 1.2.2.0

**Comment by Slasar41** [comment]
There's also a backup folder now for those that doesn't have a FMD backup.
So you can download the previous release and extract the backup to it.

**Comment by JokoeSukri** [comment]
Yes, I know, I've tried backup folder before, but still blank. 
I though at first, **works folder** is missing. But that wasn't the case. 
The file .db is still intact. which the problem lies in Ver 1.2.3.0 itself,
Conclusion : Ver 1.2.3.0 Dont link with **works folder**

**Comment by rs3mk** [comment]
Same problem. It does not load the downloads.

**Comment by mirlov** [comment]
same here, lost all download progress. Anyway to get it back?

**Comment by spamtaztik** [comment]
Same problem with mine. 
FMD will still load favorites, but not downloaded manga list. Currently I don't run my FMD because I don't want to risk losing my downloaded mangas. I'll try running from time to time to recheck, or maybe the devs can write something in this thread when FMD's updated? Much obliged.

**Comment by noering** [comment]
Same here, all downloads list is missing

**Comment by Thrieze** [comment]
Thought it was me, was going crazy.

**Comment by gooreat** [comment]
Nooooooo I should've checked this page before updating and now my whole download list is gone. :((

Oh well...

**Comment by Tmp341** [comment]
Extract your ``works\downloads.db`` from ``\backup\fmdbackup_xxxxxxxxxx.7z``

**Comment by Thrieze** [comment]
Tried multiple backups, still blank. downloads.db isnt empty though.

**Comment by noering** [comment]
@gooreat 
Try install FDM prior to this update, your downloads list should back
Just don't update it, wait till it fixed.
@Tmp341 
Like @JokoeSukri said, there's nothing wrong with the backup .db files, it just somehow failed to load / not linked to works folder

**Comment by arbiter9605** [comment]
if you did any updates/downloads while on 1.2.3.0 its not writen to the db file so when you downgrade it doesn't show it as downloaded. though db that tracks you dl'ed gets updated so it won't download same chapters a 2nd time.

**Comment by dazedcat19** [comment]
the database is fine. it just fmd failed to load them. there's changes in lazarus trunk that broke the compability with fpc 3.0.6.
