### ISSUE TITLE
ReadComicsOnline doesn't work

### ISSUE THREAD

**Issue by DSROSE09** [fmd-project-team/FMD#825]
Comic info and chapters still show up but when I try to download, there's nothing just empty folders.

**Comment by Tmp341** [comment]
I'm gonna test it as soon as i can.

**Comment by Tmp341** [comment]
I can download without a problem.

**Comment by DSROSE09** [comment]
> I can download without a problem.

Ok, I'll try again and see if its ok now to download, thanks.

**Comment by DSROSE09** [comment]
> I can download without a problem.

Its working now, thank you.
