### ISSUE TITLE
Scale inside the program is broken on my machine after updating to 1.2.4

### ISSUE THREAD

**Issue by JLChamberlain** [fmd-project-team/FMD#828]
Ever since updating to the newest version (1.2.4) the scaling inside the program has broken on my machine (looks like it used to do before the update to 1.0.0). Version 1.2.3 of the program looked good as usual but after updating it's broken (see picture links). It's almost like the padding inside the columns and rows have been removed and everything looks too close together.

[1.2.3 Screenshots](https://imgur.com/a/YnuvMZK) 
[1.2.4 Screenshots](https://imgur.com/a/ci19PV1)

**Machine:** Matebook X Pro
**Screen Display:** 3000 X 2000 (1500 X 1000 Due to Windows Display Zoom)
**OS Version:** Windows 10 Pro 10.0.18363 Build 18363
**Windows Display:** at 200%

**Comment by dazedcat19** [comment]
Please test and close if ok

**Comment by JLChamberlain** [comment]
> 
> 
> Please test and close if ok

Updating to 1.2.5 seems to rectify the issue, thanks.
