### ISSUE TITLE
Check for new chapter on favorites is not available when selecting only enabled

### ISSUE THREAD

**Issue by typhoe** [fmd-project-team/FMD#835]
Hi,

as the title says, on the "Favorites" tab, if I display only the "Enabled" series, the "Check for new chapter" button is unavailable.

Regards

Tested on version 1.2.5.0

**Comment by Tmp341** [comment]
When i've asked @SDXC about that, he said ``That is intended. You can check for updates only in unfiltered mode because the logic behind it is breaking if you use the filters while checking for new chapters.``

**Comment by typhoe** [comment]
Ok, I find the logic strange but thanks for investigating!
Regards.

**Comment by Tmp341** [comment]
Probably because, since it works, and changing a code might break and will need more attention for it, they leave it like that.
