### ISSUE TITLE
Madara template fails in certain sites

### ISSUE THREAD

**Issue by ahmadi3d** [fmd-project-team/FMD#836]
I noticed that some sites such as https://manhuas.net and Mangazuki.me  fail in download certain chapters
for example : 
https://manhuas.net/manhua/my-three-thousand-years-to-the-sky-manhua/
Fails at chapter 30 and 31 and 32 
I believe that the links with "new" tag cause this, but i'm not sure  
Another example, this time for mangazuki : 
https://mangazuki.me/manga/gaikotsu-kishi-sama-tadaima-isekai-e-odekake-chuu/
https://mangazuki.me/manga/bijo-to-kenja-to-majin-no-ken/
Both seem to fail
Thanks.

**Comment by Slasar41** [comment]
Should be fixed.
For MangaZuki link, it's redirecting to YoManga. This is like MangaKakalot case https://github.com/fmd-project-team/FMD/issues/591#issuecomment-548904374.

**Comment by Tmp341** [comment]
For some mangas/manhuas/manhwas etc, mangazuki redirects to yomanga.

So, you should move those to yomanga etc, if fails on mangazuki.
