### ISSUE TITLE
Items in the download list should have a list showing the selected chapters

### ISSUE THREAD

**Issue by ahmadi3d** [fmd-project-team/FMD#837]
Hello
This is a feature request, i believe that when you right click on a item in the download list, there should be "view selected chapters" which show the selected chapter are going to be downloaded with this certain item
for example the item says : 
Warble [3/3]
But it doesn't allow me to see what were those 3/3 chapters!
Thanks.

**Comment by Tmp341** [comment]
When you hover your mouse over that task, FMD already shows which chapters are there:
```
chapter 1
chapter 2
....
chapter 50
```

Something like this.
