### ISSUE TITLE
Problems downloading [readmanga and mintmanga]

### ISSUE THREAD

**Issue by detailcore** [fmd-project-team/FMD#839]
Guys, please help. Downloading manga doesn’t work for me. I'm very sad. Here are the sites that worked in the old version, now in the new and old versions, the sites do not work.
https://readmanga.me/battle_through_the_heavens
https://mintmanga.live/gun_x_clover
Thank you for your work, you are truly an amazing team!

**Comment by Slasar41** [comment]
Should be fixed.

**Comment by detailcore** [comment]
Thanks so much, it really works
