### ISSUE TITLE
Create search based on manga/manhwa name through all the sites

### ISSUE THREAD

**Issue by ahmadi3d** [fmd-project-team/FMD#841]
This is a feature request.
I believe that the user should be able to search through all the sites based on a manga/manhwa name, instead of searching per site, this has huge benefits for example finding sites with fastest releases or even comparing the quality of a manga between different sites.  
Thank you.

**Comment by Tmp341** [comment]
FMD is mainly download based, it's purpose is making downloads easy, not searching through all sites. But it is up to developers to decide.

**Comment by ahmadi3d** [comment]
> FMD is mainly download based, it's purpose is making downloads easy, not searching through all sites. But it is up to developers to decide.

Maybe, but what if we make this optional ? for example a search setting which has a list of all the selected sites, with a checkbox beside each name, so the user can check which sites he is going to search through.
In any case, i found my self in need of this feature many times, mostly because there is not a single site which can be used as an "all purpose source", so i had to keep changing sites and look for 15 minute to find a good source for a single manga!.

**Comment by Slasar41** [comment]
Like this?
![image](https://user-images.githubusercontent.com/28888646/75613151-df517d80-5b5c-11ea-9191-94b49b427820.png)

**Comment by ahmadi3d** [comment]
Hmm, yes, sorry for wasting your time, i don't know why i didn't see this ...!
