### ISSUE TITLE
Mangasee don't work

### ISSUE THREAD

**Issue by SqueezedByte** [fmd-project-team/FMD#842]
Hi. Mangasee find the title update, find the total page but don't download the image.
Yesterday it was working without issue.
Thanks

**Comment by Slasar41** [comment]
Which titles?
I tested with random manga and it's works fine.
![image](https://user-images.githubusercontent.com/28888646/75708885-3c336c00-5cf4-11ea-9db1-26d360f5b164.png)

**Comment by Shellshock123** [comment]
Mangasee has had its image server nuked

Most manga still works i believe but some don't (most likely new ones i think)

**Comment by SqueezedByte** [comment]
> Which titles?
> I tested with random manga and it's works fine.

As now don't work this
https://mangaseeonline.us/manga/Arifureta-Shokugyou-De-Sekai-Saikyou-Zero
but as Shellshock123 pointed I think is a problem server related.
Some title works , some not.
