### ISSUE TITLE
the chapter list does not appear [LHScans]

### ISSUE THREAD

**Issue by Dgraid12** [fmd-project-team/FMD#843]
sorry .. the problem is that the program does not show the chapters of LHScans

![imagen](https://user-images.githubusercontent.com/53473707/75817904-5a3db280-5d6e-11ea-98ea-8355534a3a5f.png)

**Comment by Tmp341** [comment]
Maybe it is behind Cloudflare. Have you tried manual workaround?

[Wiki](https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation)

**Comment by Slasar41** [comment]
We need to login to view the chapter list.
![image](https://user-images.githubusercontent.com/28888646/75855863-c0394100-5e25-11ea-9188-b5206d2788e7.png)
FMD need to support it.

**Comment by Slasar41** [comment]
Workaround until FMD supported user login:
Login on the browser, grab the Cookies and UserAgent, put it to FMD.
Now FMD will list the chapters.
![image](https://user-images.githubusercontent.com/28888646/75888372-da8f1100-5e5d-11ea-8d72-2c79866fe6f5.png)

**Comment by jillybeans** [comment]
the work around doesnt seem to work anymore i get the same blank no chapters still

**Comment by Slasar41** [comment]
> the work around doesnt seem to work anymore i get the same blank no chapters still

The workaround still working for me.

**Comment by TienVer** [comment]
After yesterday's module update, I can no longer download anything from Lhscans.

I can _see_ the chapters just fine (the __cfduid and PHPSESSID variables are correctly implanted), but nothing gets downloaded (0/x).

**Comment by Slasar41** [comment]
> After yesterday's module update, I can no longer download anything from Lhscans.
> 
> I can _see_ the chapters just fine (the __cfduid, userID, userName and PHPSESSID variables are correctly implanted in the custom cookie settings), but nothing gets downloaded (0/x).

Which title?

**Comment by TienVer** [comment]
> Which title?

All of them. Downloaded just fine yesterday.

**Comment by TienVer** [comment]
Correction - FMD only downloads the recruitment picture they add at the end of each chapter. The ch. contents themselves are AWOL.

**Comment by Slasar41** [comment]
They change it again.
Should be fine now.

**Comment by TienVer** [comment]
Thanks. Works properly now.

**Comment by Dgraid12** [comment]
it already works normally, and the LOGIN is not needed to see the chapters
