### ISSUE TITLE
Can't run more than one task.

### ISSUE THREAD

**Issue by ranztorz** [fmd-project-team/FMD#846]
I had a trouble where i couldn't run more than one task. When i try to run all of the task, only one task runs and the rest is waiting. I already set Number of downloaded task at the same to 3. I try to change to number but the problem still present. Is there anything i could do to solve this problem?

**Comment by Tmp341** [comment]
Is this happening on one site?

**Comment by ranztorz** [comment]
Yes, suprisingly. I've never used anything but Mangadex. After reading your reply,i tried to run multiple task, i used Mangapark as the source and it ran all the task accurately. But it didnt work with Mangadex, is there any explaination to this?

**Comment by Tmp341** [comment]
If i remember correctly, Mangadex tasks limited to ``1`` for not getting banned from it.
