### ISSUE TITLE
Please change cookies to work with : and not just =

### ISSUE THREAD

**Issue by molitar** [fmd-project-team/FMD#847]
Firefox has made it super easy now to get cookies now under storage with a simple right click and copy.  The problem is that FMD does not work with : but only = sign.

__cfduid:"d4ec0a9c5c8abe608fede0949259bbed91583681878"
cf_clearance:"ddb3a1f5d12d710cebcf884930dd3d1cbbcd303f-1583681878-0-150"

Can we get FMD to recognize : so that we don't have to manually edit the string all the time?

**Comment by dazedcat19** [comment]
Those are firefox cookies manager. It just copy the text. They can just change it to any format they desire anytime. Refresh the page, inspect element, network, select root webpage. go to request header, select cookie, copy. or install addons that can easily copy the session cookies.

Cookies defined in RFC 6265. key=value paired with ";" as separator.
