### ISSUE TITLE
Websites don't work anymore [KazeManga, Kiryuu]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#85]
that is i tried "update manga list" and "download manga list from server"
![fmd](https://user-images.githubusercontent.com/45929526/55897213-4b945d00-5bea-11e9-812f-c3564a2da09a.PNG)
![fmd2](https://user-images.githubusercontent.com/45929526/55897214-4b945d00-5bea-11e9-80f4-e71169c39cad.PNG)

**Comment by MIRVOUS** [comment]
and that is the websites in browser

![kazemanga](https://user-images.githubusercontent.com/45929526/55897707-37049480-5beb-11e9-900d-51940019e434.PNG)
![Uploading kiryuu.PNG…]()

**Comment by MIRVOUS** [comment]
![kiryuu](https://user-images.githubusercontent.com/45929526/55897827-81861100-5beb-11e9-9c64-9a4f6c22bffa.PNG)

**Comment by Tmp341** [comment]
Have you tried workaround?

**Comment by MIRVOUS** [comment]
no. 
I don't know how to fix it

**Comment by SDXC** [comment]
No workaround needed. Kiryuu changed a small detail which I fixed right now.

KazeManga has changed to a MangaShiro like template. I'm on it right now.

**Comment by SDXC** [comment]
Fixed and working.

**Comment by MIRVOUS** [comment]
okay.now it work thanks.
