### ISSUE TITLE
Webtoons chapter crawler is broken

### ISSUE THREAD

**Issue by ahmadi3d** [fmd-project-team/FMD#850]
Hello
Try a "Vew Manga Infos" on https://www.webtoons.com/en/action/the-gamer/list?title_no=88  
As you can see due to some changes toward the webtoons end, the program is unable to find all the chapters, and i think it doesn't go to next page to look for more chapters
Thanks.

**Comment by Slasar41** [comment]
It's shows all the chapters on my end.
![image](https://user-images.githubusercontent.com/28888646/76594541-03816700-652c-11ea-913e-33ee3f1ae64a.png)

**Comment by ahmadi3d** [comment]
As you can see mine doesn't, but i noticed the only difference between my and your image is the URL !!, in your image, the manga is inside the Action but **mine** is inside **Fantasy**!  
https://www.webtoons.com/en/action/the-gamer/list?title_no=88
https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88
![image](https://user-images.githubusercontent.com/20884578/76599939-3c651000-651b-11ea-8dc7-778ce27e6e11.png)

**Comment by ahmadi3d** [comment]
So i found the issue!, the issue is the **Server manga list**,  its outdated and people who download this manga list, do not have the latest site changes, and the site seems to have changed some of the genres  
Now i think the best solution is an update of server manga list or maybe handling the redirection of the changed URLs correctly, in either case this is a problem and most people wont notice, and i just saw another person opening a similar issue but unanswered because he couldn't understand what the issue was :  
https://github.com/fmd-project-team/FMD/issues/833  
As this is a high profile site i would really appreciate it if you guys could put a priority on this issue
Thank you !.
![image](https://user-images.githubusercontent.com/20884578/76600735-bfd33100-651c-11ea-813e-9600a5668187.png)

**Comment by Tmp341** [comment]
I will try to update database as soon as i can.

**Comment by Tmp341** [comment]
I've updated server database for Webtoons. Delete yours and redownload it.
