### ISSUE TITLE
Possible to check downloaded chapters against actual files?

### ISSUE THREAD

**Issue by Vantageright** [fmd-project-team/FMD#857]
Im missing a number of manga chapters and dont know why. What makes it more annoying is that to download them I need to select the manga, search for the name to force a refresh of the chapter list and then download any missing chapters. Is there a way to refresh the chapter lists en mass?

EDIT - I had the option to hide downloaded chapters on. Thats shown a different issue in that tracking what has and hasnt been downloaded cant be trusted. Downloaded files are marked as not downloaded and vice versa.

Instead is there a way to force FMD to check the list of files that exist in the save path and check that against what it thinks its downloaded?

**Comment by Slasar41** [comment]
You can download all chapters and FMD will only download the chapters that's not on your storage, skipping the chapters that already on your storage. Is this what you mean?

**Comment by Vantageright** [comment]
Taht would work
