### ISSUE TITLE
Add support for website [WebnovelComics]

### ISSUE THREAD

**Issue by amit34521** [fmd-project-team/FMD#86]
Please add support for webnovel comics. User can login and download premium chapters as well.

**Comment by amit34521** [comment]
Also if the login feature is not possiblefor those who use Google or FB or Twitter as login options, the user can provide cookies to download the content

**Comment by SDXC** [comment]
@amit34521 I'll look into it. Regarding the premium thingy: Do you have a premium account, so you could test it afterwards?

**Comment by amit34521** [comment]
Had one. Premium will be soon stopped. another option is to allow unlocked comic chapters to be downloaded.

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
