### ISSUE TITLE
[Mangadeep] doesn't work

### ISSUE THREAD

**Issue by NhKPaNdA** [fmd-project-team/FMD#863]
Fetching manga info doesn't work fully (maybe because the link is incorrect).
Updating the list doesn't work either.
Getting a link from the site gives even less info than selecting it from the database.

**Comment by NhKPaNdA** [comment]
I felt like messing around and seeing what I could get to work so hopefully what I've done should help you guys.

This is for the GetInfo part that followed the NineManga templet:
```
  mangainfo.Title     = x.XPathString('//div[@class="book-info"]/h1')
  mangainfo.CoverLink = x.XPathString('//div[@class="book-info"]//img/@src')
  mangainfo.Authors   = x.XPathString('string-join(//dd[@class="about-book"]//span[starts-with(.,"Author")]/following-sibling::a)')
  mangainfo.Genres    = x.XPathString('string-join(//ul[@class="inset-menu"]/li/a[not(contains(.,"Manga Reviews"))], ", ")')
  mangainfo.Status    = MangaInfoStatusIfPos(x.XPathString('//dd[@class="about-book"]//span[starts-with(.,"Status")]/following-sibling::a'));
  mangainfo.Summary   = x.XPathString('//dd[@class="short-info"]//span')
  
  s = mangainfo.Title:match('^(.*) Manga$')
  if s ~= nil and s ~= '' then mangainfo.Title = s end
  
  x.XPathHREFAll('//ul[@class="chapter-box"]/li//a', mangainfo.ChapterLinks, mangainfo.ChapterNames)
```

Unfortunately I couldn't get it to update new manga more than a single page given. I'm unsure how this would be done since there isn't a proper all index or pages to go through on the site. It only loads more once you scroll and that seems a bit past what I'd be capable of but here is the xPath for the mangas.

`'//dd[@class="book-list"]/a[not(@class="follow")]'`

**Comment by Slasar41** [comment]
I managed to update the manga list with this code:
`function GetNameAndLink()
  local v, x = nil
  local u = module.RootURL .. DirectoryPagination .. IncStr(url)
  
  --[[Debug]] LuaDebug.WriteLogWithHeader('GetNameAndLink', 'url ->  ' .. u)
  if not http.Get(u) then return net_problem end
  
  x = TXQuery.Create(http.Document)
  if x.XPath('//dd[@class="book-list"]/a[not(@class="follow")]').count == 0 then return no_error end
  for _, v in ipairs(x.XPathI('//dd[@class="book-list"]/a[not(@class="follow")]')) do
    links.Add(x.XPathString('@href', v))
    names.Add(x.XPathString('@title', v))
  end  
  updatelist.CurrentDirectoryPageNumber = updatelist.CurrentDirectoryPageNumber + 1
  
  --[[Debug]] LuaDebug.PrintMangaDirectoryEntries(IncStr(url))
  
  return no_error
end`

Do you know how to exclude the `new` text on the chapter name?
![image](https://user-images.githubusercontent.com/28888646/77258495-900af280-6cad-11ea-928a-adbfeb1bcb06.png)

**Comment by NhKPaNdA** [comment]
Cool. So i changed how it got the chapters from this:
`x.XPathHREFAll('//ul[@class="chapter-box"]/li//a', mangainfo.ChapterLinks, mangainfo.ChapterNames)`
to this:
```
for _, v in ipairs(x.XPathI('//ul[@class="chapter-box"]/li//a')) do
    mangainfo.ChapterNames.Add(x.XPathString('text()[not(parent::span/@class="new_up")]', v))
    mangainfo.ChapterLinks.Add(v.GetAttribute('href'))
  end
```

That got rid of the 'new' next to the chapter

**Comment by NhKPaNdA** [comment]
So I completely forgot to try and see if it would download a chapter. Of course it didn't so i messed around and got this working. Again using ninemanga as a templet:

```
function GetPageNumber()
  local x = nil
  local u = MaybeFillHost(module.RootURL, url)
  
  --[[Debug]] LuaDebug.WriteLogWithHeader('GetPageNumber', 'url ->  ' .. u)
  if not http.Get(u) then return net_problem end
  
  x = TXQuery.Create(http.Document)
  x.XPathStringAll('(//select[@class="sl-page"])[last()]/option/@value', task.PageContainerLinks)
  task.PageNumber = task.PageContainerLinks.Count
  
  --[[Debug]] LuaDebug.PrintChapterPageLinks()
  --[[Debug]] LuaDebug.WriteStatistics('ChapterPages', task.PageContainerLinks.Count .. '  (' .. u .. ')')
  
  return no_error
end

function GetImageURL()
  local u = MaybeFillHost(module.RootURL, task.PageContainerLinks[workid])
  
  if http.Get(u) then
    task.PageLinks[workid] = TXQuery.Create(http.document).XPathString('//img[contains(@class,"manga_pic")]/@src')
    return true
  end
  
  return false
end
```

The method for MangaDeep also works for Manga99 since they are affiliates.

**Comment by Slasar41** [comment]
Nice, thanks for the help!
I don't know about `parent` thing.
Yes, MangaDeep and Manga99 use the same template.

I'll update the lua.

**Comment by Slasar41** [comment]
Should be fixed.
