### ISSUE TITLE
Downloads always fails (ReadComicOnline)

### ISSUE THREAD

**Issue by Drsoe08** [fmd-project-team/FMD#867]
I have already downloaded some chapters/issues but there's a point where it will go like this:
![FMD issue](https://user-images.githubusercontent.com/59337129/77317190-b1b7b880-6d45-11ea-9a8e-39219ef16d24.png)

I've even done a fresh install, but its always likes this, any info in resolving this issue? thank you.

**Comment by Tmp341** [comment]
Might be a problem on website's end?

**Comment by Slasar41** [comment]
Finish downloading without issue on my side.
![image](https://user-images.githubusercontent.com/28888646/77351617-9a41f500-6d70-11ea-801a-54d29cf53a99.png)

**Comment by Drsoe08** [comment]
> Finish downloading without issue on my side.
> ![image](https://user-images.githubusercontent.com/28888646/77351617-9a41f500-6d70-11ea-801a-54d29cf53a99.png)

Ok, I'll try again tonight. thank you for the response

**Comment by Drsoe08** [comment]
> Finish downloading without issue on my side.
> ![image](https://user-images.githubusercontent.com/28888646/77351617-9a41f500-6d70-11ea-801a-54d29cf53a99.png)

Sadly, It doesn't work still.
I've tried again multiple times yesterday and today, I downloads always fails.
