### ISSUE TITLE
mangakakalot Site Change.

### ISSUE THREAD

**Issue by SalarG** [fmd-project-team/FMD#868]
Hi.
A few days ago mangakakalot domain changed from www.mangakakalot.com to www.mangakakalots.com, And FMD cannot connect to old site. Could you plz update the website address in FMD?

Thanks.

**Comment by Slasar41** [comment]
The old one still open and works on my end, I can't access the new one.
![image](https://user-images.githubusercontent.com/28888646/77462015-0a667e80-6e36-11ea-8bef-3a5ab2816e86.png)

**Comment by donotos** [comment]
i think support for mangakalots shoult still be added. i dont know what they are doing with all their clones/mirrors but it's always better to be able to use any of them...

**Comment by Slasar41** [comment]
mangakakalots still display the same thing on my end.

**Comment by SalarG** [comment]
Hi. 
The old one is up and running again, but sometimes goes down. I think it's better if we have both mangakakalot and mangakakalots.

Thanks.

**Comment by Tmp341** [comment]
> 
> 
> mangakakalots still display the same thing on my end.

@Slasar41 Mangakakalots opened up for me, dunno what is going to happen to it, or main domain etc. It looks like a mangakakalot fork.

**Comment by Slasar41** [comment]
Still display the same thing for me even using a VPN.

**Comment by Slasar41** [comment]
MangaKakalots has been added.
