### ISSUE TITLE
Download Fails [RawQQ]

### ISSUE THREAD

**Issue by bloodsign** [fmd-project-team/FMD#87]
FDM can retrieve the chapters from RawQQ.com, however the download stops and fails.
> [1/1] Failed, try resuming this task!

I've tried the cloudflare work around, but i'm not sure it's working.

**Comment by bloodsign** [comment]
I'm trying to download the latest raw chapter of Infection btw, 
https://rawqq.com/manga-infection-raw.html
https://rawqq.com/read-infection-raw-chapter-133.html

**Comment by Tmp341** [comment]
I've just tried with CF workaround. It tries, but nothing gets downloaded. I can see the chapterlist though. It failed in the end.

Rawqq uses flickr?


>06:54:20:104 VALUE: Load lua website module = D:\Program Files\Portable\Fmd\lua\modules\Lhscans.lua
06:54:20:105 VALUE: Loaded modules from Lhscans.lua = Lhscans, RawQQ, RawQV
06:54:47:325 WARNING: TTaskThread, checkforfinish failed=64/64 [RawQQ]"Infection" > "/read-infection-raw-chapter-1.html"
https://farm1.staticflickr.com/869/27828458918_434f2929c8_o.jpg
06:54:47:326 WARNING: TTaskThread, download failed. "Infection" "Infection - Raw Chap 001" "/read-infection-raw-chapter-1.html"

**Comment by bloodsign** [comment]
Looking back at RawQQ, it seems like the images are stored into several servers(1,2,3)
From the latest chapter(chapter 133, page 1), the image uses this URL 
https://baka.cdnimg.club/images/2019/04/05/94a0500c32928af0798ab81dcf7033a91.png
It's possible they changed server and the previous servers no longer hosts the previous chapters. As I can't seem to load chapter 1 even via browser.

**Comment by SDXC** [comment]
It's possible that the mimetype handling of the old image servers is making trouble here. It may be, that FMD doesn't handle forced downloads very well.

**Comment by AbidZakaria** [comment]
I can download from rawQQ and everything fine

**Comment by Tmp341** [comment]
> I can download from rawQQ and everything fine

Region lock maybe? Haven't tried lately.

**Comment by SDXC** [comment]
@AbidZakaria @Tmp341 The problem is, that some image servers used by RawQQ seem to be not working with FMD. A sample chapter that FMD can't handle:
https://rawqq.com/read-infection-raw-chapter-1.html

**Comment by SDXC** [comment]
Found the issue. The referrer wasn't needed anymore for RawQQ. Fixed it.

Issue will be closed. Just re-open it if something still doesn't work.
