### ISSUE TITLE
kissmanga cannot download

### ISSUE THREAD

**Issue by zartzaku** [fmd-project-team/FMD#872]
why kissmanga cannot download or check manga info anymore. just about 6 hour ago I check and download still ok. but now it cannot anymore.

**Comment by Tmp341** [comment]
Maybe it changed keys again?

https://github.com/fmd-project-team/FMD/wiki#troubleshooting-guides

**Comment by revanwolf** [comment]
The Cloudflare page has changed and now it seems to use ReCaptcha.

**Comment by alatnet** [comment]
Yea, it's the ReCaptcha.
You can download a bit if you do it on the site but then when your download(s) start to retry to many times, you have to do it again.

**Comment by zartzaku** [comment]
thanks for all the tips. use them and now its working again.
