### ISSUE TITLE
Add support for website [Coolmic]

### ISSUE THREAD

**Issue by rs3mk** [fmd-project-team/FMD#88]
- [ ] Comics site in English and Japanese, only displayed on mobile: https://coolmic.me

it works from chrome activating mobile mode:

![coolmic](https://user-images.githubusercontent.com/19628943/55908118-372a7300-5b9e-11e9-99fc-2b41e4337682.png)

Thanks

**Comment by AbidZakaria** [comment]
Premium comic

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
