### ISSUE TITLE
Req

### ISSUE THREAD

**Issue by Cyvas** [fmd-project-team/FMD#881]
req
http://mangatsuki.web.id/
-------
Komikstation.com and bacamanga.co error

**Comment by Tmp341** [comment]
You can follow your request via main requests issue #351.

**Comment by Slasar41** [comment]
Added.

KomikStation works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/78061930-2333de80-73b8-11ea-96e6-69124babcac8.png)
