### ISSUE TITLE
[Bug] Some chapters not packed properly

### ISSUE THREAD

**Issue by GDXN** [fmd-project-team/FMD#887]
Sometimes where creating the zip file not all image are stored, I found this on madokami in "Angel Beats! - Heaven's Door" chapter 15 and 26.5, the clue of the root of the problem is that the page that where not packed where in bmp and the rest in jpg.

**Comment by dazedcat19** [comment]
I don't have a madokami account. can you send me your account on discord.

**Comment by dazedcat19** [comment]
Please test and close if okay.

**Comment by GDXN** [comment]
Ups sorry it happens on mangadex.
