### ISSUE TITLE
Readmangatoday [readmng.com]

### ISSUE THREAD

**Issue by dustylancer** [fmd-project-team/FMD#888]
Since 31st March, readmanga chapters cannot be downloaded. New chapters can be detected from the favourites list and manually checking the manga info via the fav list is also displaying all the chapters.

However the chapters will not download automatically or manually.

**Comment by Slasar41** [comment]
I can download just fine.
![image](https://user-images.githubusercontent.com/28888646/78506979-9a49e800-77a7-11ea-845f-842c7741e88b.png)
Could you provide the manga that can't be downloaded?

**Comment by dustylancer** [comment]
Ok this is wierd. I tried downloading Absolute Duo works fine. Titles like Survival Story of a Sword King in a Fantasy World, Martial Peak, Don's Adventure in another world do not. I also tried adding a random manga like Death March that is not in my fav list and that also failed.

**Comment by Tmp341** [comment]
~~Maybe website changed structure and your favorites list is out of date?~~

Maybe website is having problems?

**Comment by dustylancer** [comment]
No idea. I have restarted FMD, restarted my PC as well, no luck. New chapters are being added when the fav list is checked, you can see the manga info as well but the download gets stuck as shown in the screenshot. Death March was just randomly added to check whether or not it was a problem with the fav list.

![Clipboard02](https://user-images.githubusercontent.com/49733280/78529591-8f22a680-77ff-11ea-80a0-f5ffb78c4aa1.jpg)
.

Also tried a clean install for FMD but no luck.

As Slasar41 checked with Abosulute Duo working, I checked for the same and it worked but that particular series was last updated 3 years ago and all the series I mentioned are updated regularly.

**Comment by elenras** [comment]
I have the same problem. For me it happens e.g. with Other Worlds Warrior and Tales of Demons and Gods.

**Comment by Slasar41** [comment]
Should be fixed.
