### ISSUE TITLE
Add support for website [MeganeBuk]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#89]
https://www.meganebuk.net

![fmd3](https://user-images.githubusercontent.com/45929526/55917707-94640a00-5c1a-11e9-9222-3a00fdc00111.PNG)
![fmd4](https://user-images.githubusercontent.com/45929526/55917708-94640a00-5c1a-11e9-82da-ee2c577480fc.PNG)

**Comment by MIRVOUS** [comment]
download per volume in that site

**Comment by AbidZakaria** [comment]
Itu manga downloader bukan manga reader, FMD hanya bisa download dari manga reader,
Lagian server downloadnya dari server pihak ketiga bukan dari webnya sendiri,
So kalau menurut saya tidak bisa

**Comment by ChocolateOtaku** [comment]
This is not an online reading website.
It already provides download links, which makes the usage of a manga downloader quite obsolete...

**Comment by SDXC** [comment]
There's still a possible need to support such sites as you can collectively download all these file instead of doing it manually. Some users also seem to use FMD as a kind of manga collection manager.

There are also some major pros in downloading archives instead of the images separately, which we should use if we get the chance. Support for that is planned.

**Comment by ChocolateOtaku** [comment]
> There are also some major pros in downloading archives instead of the images separately, which we should use if we get the chance. Support for that is planned.

I would really appreciate if you could also consider another format: videos
With this it would be possible to support download from anime websites #93

**Comment by AbidZakaria** [comment]
@SDXC that site not manga reader_

**Comment by ChocolateOtaku** [comment]
> @SDXC that site not manga reader_

I already mentioned this [3 comments above](https://github.com/fmd-project-team/FMD/issues/89#issuecomment-481973493), but it was decided that websites which provide downloadable archives shall be supported in the future...

**Comment by SDXC** [comment]
Request is now queued here: https://github.com/fmd-project-team/FMD/issues/351
This issue will be closed. You can still post additional infos in this issue.
