### ISSUE TITLE
Manga4life.com certain manga's are not picking up the latest chapters in FMD

### ISSUE THREAD

**Issue by jillybeans** [fmd-project-team/FMD#891]
Certain mangas show all the chapters and certain ones show all of them except the latest chapter in FMD.
-----
this one shows all in FMD:

https://manga4life.com/manga/The-Ride-on-King
------
these are missing the latest chapters on FMD even though they show up on site:

https://manga4life.com/manga/Jichou-Shinai-Motoyuusha
https://manga4life.com/manga/Batuque
https://manga4life.com/manga/Agravity-Boys
https://manga4life.com/manga/Mission-Yozakura-Family

**Comment by Slasar41** [comment]
I see the script got the chapters from RSS Feed like: https://manga4life.com/rss/Jichou-Shinai-Motoyuusha.xml and the last update is from the same time chapters 14 got uploaded to the website.

**Comment by dazedcat19** [comment]
Can't you just get it form the html page instead of rss

**Comment by Slasar41** [comment]
Last time I check it's encrypted, I don't know how to decrypt it.

**Comment by dazedcat19** [comment]
I think it's not encrypted. the chaptes is right there in `vm.Chapter`

**Comment by Slasar41** [comment]
I still can't understand how to do it.
Is there any references in another lua modules?

**Comment by jillybeans** [comment]
so far every chapter shows up now on https://manga4life.com except this chapter for some reason

https://manga4life.com/read-online/Ookii-Kouhai-wa-Suki-Desu-ka-chapter-15.5.html

https://manga4life.com/manga/Ookii-Kouhai-wa-Suki-Desu-ka

**Comment by jillybeans** [comment]
so is it possible to reopen this issue

**Comment by Tmp341** [comment]
You can see a button below, ``Reopen issue``.

**Comment by jillybeans** [comment]
![ryyzyyzyn](https://user-images.githubusercontent.com/52017476/79218726-bb44b580-7e05-11ea-962d-040c52b68e39.png)

sorry im not seeing the reopen issue button

**Comment by jillybeans** [comment]
still having issue with certain chapters not showing up on fmd

https://manga4life.com/manga/Kochou-No-Yumeji

chapters 33-142 arnt showing up
https://manga4life.com/read-online/Kochou-No-Yumeji-chapter-141.html


and a new issue with chapters showing up on FMD that are not on the site

https://manga4life.com/read-online/Mairimashita-Iruma-kun-chapter-99.html

is the latest one but shows a chapter 100 that doesnt exist

**Comment by molitar** [comment]
I have the opposite problem more chapters show up in FMD than their actually is on the site itself.

**Comment by Qizmo** [comment]
Yup I'm having more chapters show up in FMD than their actually is on the site itself too. Also some manga have different chapter name shown on FMD compare to the site itself.
Like Episode or Season become Chapter

Lastest S004 - Chapter 127 turn into Chapter 323 (and can't be loaded. Including older chapter also can't be loaded)
https://manga4life.com/manga/The-Gamer

**Comment by Tmp341** [comment]
Mangalife uses different method i think, we need someone to circumvent it.

**Comment by tomatosoupcan** [comment]
FWIW, I rolled back one commit of the lua on my local install and all "extra chapters" issues seem to be resolved, plus the four manga used as reference for the initial issue here seem to be displaying the right chapters now too, up to date with the site. Also the duplicate issue #913 seems to not be occurring with that version of the script anymore as well.

**Comment by SDXC** [comment]
Should be fixed now. If it still happens to some titles, please open a new issue and also don't forget to mention the affected titles.
