### ISSUE TITLE
Website add Requests

### ISSUE THREAD

**Issue by Rarksoca** [fmd-project-team/FMD#894]
Hi! Thanks for all the improvements and developments!

Would just like to request a few stuff if possible:
Is it possible for FMD to add mangakakalots.com not (mangakakalot.com)
sorry for my bad english

**Comment by Tmp341** [comment]
Our only member who works on fixing websites, Slasar41, couldn't reach the website even with vpn. But, it also looks like mangakakalot fork to me.

**Comment by Slasar41** [comment]
I can access the website now.

**Comment by Slasar41** [comment]
Added.
