### ISSUE TITLE
MangaDex not loading

### ISSUE THREAD

**Issue by ailengt** [fmd-project-team/FMD#897]
cannot load titles on MangaDex after 1.3.1 update. Help pls.

**Comment by Tmp341** [comment]
Random manga i've tried, mangadex works :

![ssss](https://user-images.githubusercontent.com/1683388/78878337-e96b7380-7a5a-11ea-900b-f9ffddf8fe93.png)

**Comment by ailengt** [comment]
Mine ended up N/A. May I know your settings?

![image](https://user-images.githubusercontent.com/63007761/78887420-68c86980-7a92-11ea-80e6-5c17b970e7f7.png)

**Comment by Tmp341** [comment]
![ssss](https://user-images.githubusercontent.com/1683388/78917986-58b38880-7a98-11ea-84e1-19a1136a5886.png)

Nothing set for mangadex, but i have general settings i've shared above.

**Comment by ailengt** [comment]
ok, I managed to figure out how to settle the problem. Had to disable the Advanced website settings for it to work. Although previously it didn't cause any problem. ¯\_(ツ)_/¯ anyways, thank you for following up on this "issue".
