### ISSUE TITLE
Mangahere [mangahere.cc]

### ISSUE THREAD

**Issue by DarkShadowBlood** [fmd-project-team/FMD#898]
Same problem as https://github.com/fmd-project-team/FMD/issues/888

( Mangahere ) chapters cannot be downloaded. New chapters can be detected from the favourites list and manually checking the manga info via the fav list is also displaying all the chapters.

However the chapters will not download automatically or manually.

Sorry i speak french and my english is very bad.

**Comment by dazedcat19** [comment]
should have post the title and chapter. mangahere working fine here.

**Comment by DarkShadowBlood** [comment]
Mangahere works after 10 to 16 attempts per chapter for download after the updates.

working fine now.

**Comment by dazedcat19** [comment]
that can be server issue. either your connection timeout is too low or the server respond too slow.
