### ISSUE TITLE
Website doesn't work [Mangadex]

### ISSUE THREAD

**Issue by Suddow** [fmd-project-team/FMD#90]
I can load any manga through browser (chrome, opera, firefox), and the manga info and downloads were working last night.  Today neither work.  The only thing I changed between then and now was adding cookies and useragent settings to the fallenangels advanced settings, nothing else was changed.  I have tried disabling those settings just in case and dex still doesn't work.

All 3 browsers load through cloudflare and I can browse any manga no issues.

**Comment by krakerz** [comment]
mine working again a while ago
grab the cookies from chrome + not logged
only need
__cfduid
cf_clearance
PHPSESSID

![2c6o1O](https://user-images.githubusercontent.com/8030983/55923542-317d6d80-5c30-11e9-989b-25564c4d3603.png)

**Comment by hypomaniak** [comment]
Same problem here, I can't get the CF workaround to work.

And I don't find any PHPSESSID in the cookies, be it from Firefox or Chrome, logged in or not.

**Comment by krakerz** [comment]
i got no PHPSESSID too in opera
but when i try the chrome ones + this extension
https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg
i got this cookies

**Comment by bloodsign** [comment]
I had the same problem yesterday, but I managed to fix it using the CF work around. 
I wasn't sure which cookies was necessary, so I grab it all
__cfduid
_ga
cf_clearance
mangadex_rememberme_token
mangadex_session

**Comment by AlternativeZero** [comment]
I copied all the cookies over but it isn't working.

Mine only came with __cfduid, cf_clearance, mangadex_rememberme_token & mangadex_session.

**Comment by Suddow** [comment]
I also tried all the cookies yesterday and today (I thought I'd give it a day just in case) and it doesn't work in either case.

**Comment by krakerz** [comment]
well i'm using the mangadex_rememberme earlier but yesterday it won't work suddenly
and tried to try it in chrome, and found there is some new cookies that didn't present in my opera
and somehow by using it, it's works for my end

if you want to try it again, try other browser, IE / Edge / Safari / Chrome / Firefox / Opera / other
and compare the cookies, if you found any new cookies which didn't present in other browser, try it
on my case is, PHPSESSID

**Comment by Suddow** [comment]
I've tried many from different browsers already with no luck.  I'll keep trying though.

**Comment by krakerz** [comment]
try login first, then logout, and check the cookies
i always do that to compare the cookies with each state and browser

**Comment by Suddow** [comment]
I've tried different browsers, logged in, logged out, both before and after erasing cookies from the respective browser.  Only thing left to try is resetting my public IP I suppose, in case dex is somehow limiting me (though the site works in browser so who knows).

**Comment by krakerz** [comment]
oh another note, incase you got some typo for the useragent
mine copied directly from the "about page" on the browser yet it won't work (it's happen on kissmanga for me, since for mangadex i already use it from ipleak ones)
then i try to redo it again, but this time from https://ipleak.net then grab it from "Detected informations" section, and put it in, and it's works fine now

so maybe (just in case, the cookies itself is valid, yet the useragent isn't) it'll works with you this way

and FYI, each time your browser got new update, you need to copy paste it again the new useragent to fmd

**Comment by arbiter9605** [comment]
for me even if i double check, triple check user agent. On top of deleting cookie in browser then reloading the site to get a new one its always been hit but mostly miss.

**Comment by hypomaniak** [comment]
Well, I finally got a solution to this situation:
as Suddow suggested, resetting the modem IP lifts the Mangadex restriction, at least temporarily.

I'm suspecting I get locked (from FMD, not in webbrowser) if I try updating all my favorites, but checking only the new ones who appear in the Follows page is OK.

**Comment by Suddow** [comment]
Interestingly, I tried it again today with all the cookie/user settings disabled and it works again.  I did try this yesterday (settings disabled), but suddenly it works today when it didn't yesterday.  I hadn't changed any settings since I last posted here but it just up and started to work again.  I didn't even have a chance to reset my IP.  Not sure if that helps narrow down the cause or not.

**Comment by SDXC** [comment]
That was probably not really a problem with your IP, even if it seemed so the last time. The Cloudflare workaround has many openings for users to make some small mistakes here and there.

For now I will close this issue. Just re-open it, if you need help again.
