### ISSUE TITLE
Mangadex failed to download some latest chapter from certain mangas

### ISSUE THREAD

**Issue by noering** [fmd-project-team/FMD#900]
It seems FMD failed to download some of the latest chapter/update from certain mangas - even though they show up on site. I don't know if this is just me or the same as the others too. Have been tried so many times with no success.

https://mangadex.org/title/46856/the-careful-empress >failed to download chapter 3
https://mangadex.org/title/43140/the-black-haired-princess >chapter 17 to 20 failed
https://mangadex.org/title/19531/yakusoku-no-neverland >chapter 174 failed
https://mangadex.org/title/46790/the-stereotypical-life-of-a-reincarnated-lady >chapter 04 - 05 failed
https://mangadex.org/title/46603/the-youngest-princess >17 to 22 failed

![Capture](https://user-images.githubusercontent.com/3715548/79060049-ea92df80-7caa-11ea-988c-2b77c701d8d2.JPG)

**Comment by GDXN** [comment]
Are you logged in or have copied the cookies as those are restricted chapters.

**Comment by noering** [comment]
I'm logged in to mangadex, and copy that link from browser's address bar.
![Capture](https://user-images.githubusercontent.com/3715548/79063401-bd0a5e00-7ccb-11ea-85cf-3e6b54a5f44c.JPG)

**Comment by Tmp341** [comment]
@dazedcat19 changed ``Mangadex.lua`` in 81249b7 commit, maybe that will fix your problem. Try to update to v1.3.3.0.

**Comment by noering** [comment]
I have updated my FDM v1.3.3.0 and also that newest Mangadex.lua, still the prolem exist. 
I don't know if this is from the Mangadex server or FDM, but actually this has been happening for several weeks for me.
![Capture](https://user-images.githubusercontent.com/3715548/79067053-e84e7680-7ce6-11ea-88e3-f53b9cb5f6c5.JPG)
Latest Mangadex.lua installed
![01](https://user-images.githubusercontent.com/3715548/79067058-f2707500-7ce6-11ea-9377-b065c7ade9d1.JPG)

**Comment by dazedcat19** [comment]
There's no really effective commit to mangadex. I just changed following httcookiesmanager changes. The mangadex module account feature itself isn't complete yet. There's no automatic login check. User has to manually refresh the account in account manager so the cookies can be stored by cookies manager. I did add module's critical section/guardian, so it should be sufficient to complete the Lua module.

**Comment by noering** [comment]
> User has to manually refresh the account in account manager so the cookies can be stored

O ok, right now I logged in from that FDM account manager, and the problem is solved.

![02](https://user-images.githubusercontent.com/3715548/79090637-7faddb00-7d74-11ea-9128-0d0cb92a667b.JPG)

> Are you logged in or have copied the cookies as those are restricted chapters.

So this is might be what @GDXN mean before? I misunderstood, thinking it logged from their website.

Ok now everything is fine, thanx guys for the replies :)
