### ISSUE TITLE
Webtoons site error when downloading --> (1/1) error

### ISSUE THREAD

**Issue by zillafox** [fmd-project-team/FMD#905]
Hi team,

I tried to download comics from Webtoons. All of them got error 1/1 when downloading
The website is from www.webtoons.com/en/ and they are still working fine. So i tried to download some different comics and all of them got the same error.

Please kindly see the attached

![Capture](https://user-images.githubusercontent.com/24423458/79086263-a1ec2c80-7d65-11ea-8377-9f5ac4ad3159.PNG)

Thank you in advance!

**Comment by revanwolf** [comment]
The problem is that Webtoon added a Age verification page.

https://www.webtoons.com/en/ageGate

**Comment by zillafox** [comment]
> The problem is that Webtoon added a Age verification page.
> 
> https://www.webtoons.com/en/ageGate

I see...

Is there a way to get pass this verification gateway?

Rgrds

**Comment by Slasar41** [comment]
I can still download it without doing anything.
![image](https://user-images.githubusercontent.com/28888646/79113193-8eaf8000-7daa-11ea-9ae9-a2ecc52e4594.png)

**Comment by zillafox** [comment]
> I can still download it without doing anything.
> ![image](https://user-images.githubusercontent.com/28888646/79113193-8eaf8000-7daa-11ea-9ae9-a2ecc52e4594.png)

u were right, somehow i able to download it right now. before i faced issues but for now it seems to work just fine

**Comment by revanwolf** [comment]
I still can't download and i checked the logs and it show only this errors.

> 18:52:10:832 WARNING: TTaskThread, checkforfinish failed=1/1 [Webtoons]"Seed" > "/en/sf/seed/episode-49/viewer?title_no=1480&episode_no=51"
W
18:52:10:832 WARNING: TTaskThread, download failed. "Seed" "Episode 049" "/en/sf/seed/episode-49/viewer?title_no=1480&episode_no=51"

**Comment by zillafox** [comment]
This weird. before it fixed itself as i can download them just fine. Now i got the same errors again..

**Comment by Uroth** [comment]
I am also getting the same error since the update.
![image](https://user-images.githubusercontent.com/11475365/79234248-49528780-7e6a-11ea-8c39-df0c2f8a3804.png)

Other sources seems to work fine, only issue is webtoons. If I visit the site there are no issues, but the download just fails.

**Comment by Tmp341** [comment]
I can download from Webtoons just fine.

**Comment by revanwolf** [comment]
I used the method for Kissmanga (Browser user agent & cookies) and it work (even without it).

It's weird but it works for now.

**Comment by Uroth** [comment]
But this is still a problem, we are many users with this error still..

**Comment by Tmp341** [comment]
But we can't fix something we can't verify/reproduce. Me and Slasar41 can download without a problem. Maybe it is because of your IP or something.

**Comment by zillafox** [comment]
![Untitled](https://user-images.githubusercontent.com/24423458/79521873-737f9180-8084-11ea-9bf7-545fd122a697.png)

Yeah, i dont know why, but sometimes it's working, sometimes it isn't.

I tried different connection as well and got the same errors

08:03:10:992 TTaskThread, download failed. "Hardcore Leveling Warrior" "[Season 002] Ep. 37" "/en/action/hardcore-leveling-warrior/season-2-ep-37/viewer?title_no=1221&episode_no=220"
08:03:17:002 TTaskThread, download failed. "Hardcore Leveling Warrior" "[Season 002] Ep. 37" "/en/action/hardcore-leveling-warrior/season-2-ep-37/viewer?title_no=1221&episode_no=220"
08:03:17:002 TTaskThread, download failed. "I Love Yoo" "Episode 121" "/en/drama/i-love-yoo/episode-121/viewer?title_no=986&episode_no=130"

**Comment by Tmp341** [comment]
Have you tried low settings under ``Advanced`` tab? Like these:

```Lua
MaxTaskLimit:1
MaxThreadPerTaskLimit:1
MaxConnectionLimit:1
UpdateListNumberOfThread:1
```

If you enter high numbers or leave default 0 (if your main defaults aren't 1 already), some sites like Mangadex takes action against your IP.

**Comment by revanwolf** [comment]
> 
> 
> Have you tried low settings under `Advanced` tab? Like these:

Yup no effect, the only working solution is to copy the cookie from my browser.

**Comment by zillafox** [comment]
> > Have you tried low settings under `Advanced` tab? Like these:
> 
> Yup no effect, the only working solution is to copy the cookie from my browser.

Tried low settings too. Its no effect. Also how do you do it with cookie from browser?

**Comment by Slasar41** [comment]
> Yup no effect, the only working solution is to copy the cookie from my browser.

Could you tell the cookie?

**Comment by revanwolf** [comment]
> Could you tell the cookie?

It seems it is simply:

`ageGatePass=true`

With only this it works without error.

**Comment by Slasar41** [comment]
Disable your advanced options and try this:
[WebToons.zip](https://github.com/fmd-project-team/FMD/files/4491179/WebToons.zip)

**Comment by Uroth** [comment]
Doing the manual cookie also seems to work for me as well.
![image](https://user-images.githubusercontent.com/11475365/79546636-09bab400-8093-11ea-917c-857838deec9c.png)
![image](https://user-images.githubusercontent.com/11475365/79546723-2fe05400-8093-11ea-87c9-ad82620afd03.png)

**Comment by revanwolf** [comment]
> 
> 
> Disable your advanced options and try this:
> [WebToons.zip](https://github.com/fmd-project-team/FMD/files/4491179/WebToons.zip)

Tried didn't work(error 1/1).

**Comment by Slasar41** [comment]
> Tried didn't work(error 1/1).

How about this?
[WebToons.zip](https://github.com/fmd-project-team/FMD/files/4495165/WebToons.zip)

**Comment by zillafox** [comment]
> > Tried didn't work(error 1/1).
> 
> How about this?
> [WebToons.zip](https://github.com/fmd-project-team/FMD/files/4495165/WebToons.zip)
> Replace the file and then restart FMD.

Tried. Didn't work too..

![Untitled](https://user-images.githubusercontent.com/24423458/79623741-1baa5e80-8148-11ea-9e4b-5a721eabc908.png)

However, the same method of copying manual cookie seems to work for me
