### ISSUE TITLE
changed domain https://hiperdex.net/

### ISSUE THREAD

**Issue by sadeghp88** [fmd-project-team/FMD#909]
hello
please fix https://hiperdex.net/
thanks a lot

**Comment by Slasar41** [comment]
Besides domain change, I think the chapter list now is encrypted.
I don't know how to decrypt it.

**Comment by sadeghp88** [comment]
any progress?

**Comment by sadeghp88** [comment]
please do something, it's already one month.
thank you

**Comment by Tmp341** [comment]
> 
> 
> please do something, it's already one month.
> HakuNeko has fixed this problem. do the same.
> thank you

Hakuneko has a dedicated developer, we don't have one.

**Comment by sadeghp88** [comment]
hello
do you have any plan to fix this error?

**Comment by Tmp341** [comment]
> 
> 
> hello
> do you have any plan to fix this error?

As i've said, we don't have an active developer nowadays. If SDXC or dazedcat returns (which is unlikely), or dazedcat releases his FMD fork (he dropped this fork and started working on his own) maybe then it will be fixed.

**Comment by Slasar41** [comment]
Should be fixed.
Fixed by @excalibur1010
