### ISSUE TITLE
Cant download from MangaHubIO

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#911]
Everything work just fine until i download it. All failed. It creates folder name without any file in it.

I tried the website and its fine, i can read there.

**Comment by Tmp341** [comment]
Got error too.

``07:14:12:259 WARNING: TTaskThread, checkforfinish failed=1/1 [MangaHubIO]"Honey Kids" > "/chapter/honey-kids/chapter-1"
W
07:14:12:279 WARNING: TTaskThread, download failed. "Honey Kids" "#1 - Vol.01 chapter 001" "/chapter/honey-kids/chapter-1"
07:14:13:773 WARNING: TTaskThread, checkforfinish failed=1/1 [MangaHubIO]"Honey Kids" > "/chapter/honey-kids/chapter-1"
W
07:14:13:773 WARNING: TTaskThread, download failed. "Honey Kids" "#1 - Vol.01 chapter 001" "/chapter/honey-kids/chapter-1"
07:14:14:112 ERROR: Error: TypeError: undefined not callable (property 'italics' of '')
07:14:14:410 ERROR: Error: TypeError: undefined not callable (property 'italics' of '')
07:14:14:699 ERROR: Error: TypeError: undefined not callable (property 'italics' of '')
07:14:14:948 ERROR: Error: TypeError: undefined not callable (property 'italics' of '')
07:14:15:187 ERROR: Error: ReferenceError: identifier 'a' undefined``

**Comment by Slasar41** [comment]
Should be fixed.
