### ISSUE TITLE
Edit: Load more chapter than what the manga site actually have

### ISSUE THREAD

**Issue by Qizmo** [fmd-project-team/FMD#912]
https://manga4life.com/
is still online without any problem and in "Manga Info" page, it also show the manga and chapters properly. However when I download from there it kept getting "Fail".

**Comment by Qizmo** [comment]
Oh! Seems to be some error. Although the chapter is shown in "Manga Info", when I look at the website itself, the manga listed doesn't have the said chapters.

**Comment by molitar** [comment]
The problem is that it is finding chapters that do not exist. One manga shows 78 in FMD but only 74 are actually on site.

**Comment by Qizmo** [comment]
Ah! ok, so it happen to others as well ^^

**Comment by Tmp341** [comment]
Duplicate of #891

**Comment by Tmp341** [comment]
It becomes hard for use to track multiple issues with the same problem on the same site. Please use older issues.
