### ISSUE TITLE
Problem with "Add to favorites"

### ISSUE THREAD

**Issue by Slasar41** [fmd-project-team/FMD#92]
The "Add to favorites" button not became greyed even if I already favorited it.
See the gif link
https://i.imgur.com/Nfoumyb.gifv

**Comment by bloodsign** [comment]
I've managed to replicated the bug doing the following: 
1. Go to Favorites Tab
2. Right-click any manga
3. Select [View manga info]

The [Add to favorites] button is enabled when it should be disabled/grayed out

**Comment by SDXC** [comment]
Version 0.9.163.0 has been released.
