### ISSUE TITLE
earlymanga.website can no longer get the chapter and pages

### ISSUE THREAD

**Issue by ahmadi3d** [fmd-project-team/FMD#920]
Hello
It seems recently earlymanga.website  inside madara doesn't get the chapters, you can see this if you use viewinfo on a manga.

By the way i noticed manhuas.net had the same exact problem, is it possible an update to Madara broke some of the sites ?

**Comment by Slasar41** [comment]
Same issue as https://github.com/fmd-project-team/FMD/issues/909.
