### ISSUE TITLE
Reposted from other

### ISSUE THREAD

**Issue by Silver0549** [fmd-project-team/FMD#927]
Can't load pages from some sites, FMD informs, url not supported, so heres the list:
Manga Kakalot https://mangakakalots.com/ that should have been
there is also this https://manganelo.com/manga/..... that is where some mangas from Kakalot linked to...
these are some know url's with problems.
Thank for the attention

Not downloading from Manganelo at this posting

**Comment by Tmp341** [comment]
* Mangakakalots is added already with 0906b4f commit.
* We can't reroute titles from one site to another. It will cause problems. So, for titles use one site who hosts that title originally.

**Comment by Silver0549** [comment]
Version released 1.3.3.0 works just had to copy over my works folder and now able to download from MangaNelo
