### ISSUE TITLE
Add support for 9anime and KissAnime

### ISSUE THREAD

**Issue by ChocolateOtaku** [fmd-project-team/FMD#93]
It would be nice if FMD could also download anime episodes from one or both of the suggested websites.

Cloned from riderkick#1692

**Comment by rs3mk** [comment]
FAD = Free Anime Downloader

**Comment by AbidZakaria** [comment]
for what kissanime seems like it can be tried

**Comment by SDXC** [comment]
We won't add Anime websites to FMD.
We already have enough work with maintaining Manga websites and all the other requests.
Even if you only meant for one or two websites to be added, it won't stop there.

The new feature to download files other than images would probably allow us to download videos as well, but we won't add modules for these sites to FMD. Users are free to implement and share such scripts by themselves, but we won't add them to the repo and we won't support them if anything doesn't work.
