### ISSUE TITLE
Downloading and checking chapters from Mangadex is really slow for me. Help?

### ISSUE THREAD

**Issue by spamtaztik** [fmd-project-team/FMD#932]
These last few days downloading and checking chapters from MD is excruciatingly slow for me. Often times I have to disable all MD bookmarks in order to finish checking the other ones. Every download added to the list constantly fails, even after several resumes. So the download is not only slow, but almost non-existent. I've added my MD login info, still the same. I've also tried the user-agent & cookies workaround, no go. Closing & reopening FMD doesn't solve the issue as well. I can open MD & read chapters from my browser just fine (speed-wise). I have bookmarks from other websites and FMD can download them just fine.

Someone told me about MD having different image servers in several parts of the world, and the one closest to me might be faulty or something. Does this apply to checking bookmarks as well though? Is this a bug with the new FMD version, and is there a workaround to solve this?

Please help.
Thanks much.

**Comment by Tenome** [comment]
Same, download speeds are abysmal.

**Comment by Tmp341** [comment]
I've been explaining this every **Slow Mangadex** issue. It is slow on purpose, because Mangadex has very low website requests settings. If you download *faster* than those, your IP will be **banned**. You can try your luck if you want though.

**Comment by spamtaztik** [comment]
I understand they're throttling download speeds, but not 0Bps - 16KBps -32 KBps slow right? I'm talking about a 477 KB page taking more than a minute slow (80 seconds actually). And I'm talking about sometimes-it-got-stuck-at-0-Bps-for-several-minutes slow. I can download from other sites at 200-250 KBps, so my connection is fine. Well, I mean if 16-32 KBps is the "normal" download speed from MD, then I stand corrected. 

Now that you mention it, I set maxtasklimit, maxthreadpertasklimit, maxconnectionlimit, updatelistnumberofthread, and updatelistdirectorypagenumber to 1, all of them. Should I have set maxconnectionlimit to 2? How about the other 3 (maxthreadpertasklimit, updatelistnumberofthread, and updatelistdirectorypagenumber)?

**Comment by Tmp341** [comment]
You can change (leave empty too):

```lua
Enabled=Ticked (True)
MaxThreadPerTaskLimit=1
UpdateListNumberOfThread=1
```
This one changes how to update a website list (you can leave empty):
```lua
UpdateListDirectoryPageNumber=x
```
There are hard coded, you can enter high values, but afaik it will be meaningless:
```lua
MaxTaskLimit=1
MaxConnectionLimit=2
```

**Comment by muto4013** [comment]
from mangadex frontpage:

> Servers are at their limit, downtimes should be sparse. Hold tight 

if you go to mangadex forum you will find a lot of posts about server-lags so even if you change something in FMD it won't help, the mangadex-servers don't send quicker. 
This happens a lot for older chapters (e.g older than few weeks/month)
and the "official" workaround from mangadex staff to change the server-cluster won't help, because the setting is per manga and not global.

**Comment by spamtaztik** [comment]
After changing the settings to MaxConnectionLimit to 2, the download finally started moving. Still slow (32-80K), but moving nonetheless. But since it's supposed to be hard-coded into the lua, me setting it to 1 before shouldn't have affected it in any way, right? I dunno, I'm confused.

Well, that solves the problem somewhat (at least for now). Guess I should start moving some titles out of MD. Thanks for all the answers. Stay healthy!

**Comment by Tmp341** [comment]
If you use lower settings than what was defined, it will use the lowest. Like, hardcoded ones are 2 and you put 1, FMD will use 1.
