### ISSUE TITLE
Kissmanga not downloading

### ISSUE THREAD

**Issue by 7godeohs** [fmd-project-team/FMD#934]
Kissmanga is not downloading chapters.  It successfully checks for new chapters, starts the download,  and immediately fails.

Works fine with MangaDex and some other sites tested.

Tried with and without VPN connection. Same result.

Running latest version/revision:  v1.3.3.0   rev. 4253

**Comment by Slasar41** [comment]
KissManga still works with doing cloudflare workaround.
![image](https://user-images.githubusercontent.com/28888646/79897969-a59e4400-8434-11ea-97f9-6c96f58d46df.png)
Looks like cloudflare change something and FMD need to update it.

**Comment by zartzaku** [comment]
slasar41 can you tell me how you do it. i have try https://github.com/fmd-project-team/FMD/wiki#troubleshooting-guides and Cloudflare Workarounds such as https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation but still not working. when i use Cloudflare Workarounds the fdm didnt even begin to download at all.

**Comment by Slasar41** [comment]
@zartzaku I copy all the cookies.
![image](https://user-images.githubusercontent.com/28888646/79907422-c326da00-8443-11ea-9dfb-f6405efcb3e7.png)

**Comment by Thrieze** [comment]
Yea doing any cloudflare workarounds don't work for downloading for me, It Scans for new chapters just fine but wont DL.

**Comment by zartzaku** [comment]
> 
> 
> @zartzaku I copy all the cookies.
> ![image](https://user-images.githubusercontent.com/28888646/79907422-c326da00-8443-11ea-9dfb-f6405efcb3e7.png)

not work for me. still cannot download.

**Comment by Slasar41** [comment]
I can update all of my favorites from KissManga without issue.
![Anotasi 2020-04-22 142616](https://user-images.githubusercontent.com/28888646/79955376-f3549400-84a8-11ea-9e56-fec8d5a646b7.png)
But what I'm doing is a workaround. FMD still need to be updated to reflect the change and the KissManga module is still in Pascal.

**Comment by 7godeohs** [comment]
@Slasar41 I've done the CF workaround before using Firefox without issue, but for whatever reason, I am not getting what I would consider the full string for cookies -(__cfduid=d2eda05cedf261921eb71e482e59c1f931587556103; android=0) - before I always saw a longer string including idtz and cf_clearance, etc.

I go into Firefox, right-click on an image, Inspect Element, Network tab, hit F5 (Refresh), click on a kissmanga.com domain item, select Headers, under 'Request Headers' use slider to change to Raw Headers. Then for Cookies, I'm getting what you see above, and not the full string like usual.

Any thoughts?  From your screenshot above, it looks like you're using the Console in MS Edge.  Can you tell me what element you are clicking on from the site, and also where you are getting that string of the Cookie?

**Comment by Thrieze** [comment]
After talking to Slasar on discord I did this,

Added fullListMode=true before the __CF at the beginning of the cookie, then vns_readType1=0 at the end, I missed a ; after the password string. But after doing that it got the pages and downloaded them. I Did make an accounts on Kissmanga, not sure if needed.

Its a huge pain because I do not get those strings in my cookies, I would have to add them manually every time.

**Comment by Slasar41** [comment]
@7godeohs After doing some testing, looks like only specific cookies is working.
I grab the cookies when in reader mode, the cookies looks like this: `fullListMode=true; __cfduid=d2a882c1cd8126089b9fe0da5a7cefac01587491482; cf_clearance=fb38ba59209c93ed9d826d61d23f1a1cd4e37ca2-1587550630-0-150; idtz=115.178.223.18-814933276; ASP.NET_SessionId=twbaf3ujbbvsflvtue14recu; username=; password=; vns_readType1=0`
And then it'll works.

**Comment by zartzaku** [comment]
> 
> 
> @7godeohs After doing some testing, looks like only specific cookies is working.
> I grab the cookies when in reader mode, the cookies looks like this: `fullListMode=true; __cfduid=d2a882c1cd8126089b9fe0da5a7cefac01587491482; cf_clearance=fb38ba59209c93ed9d826d61d23f1a1cd4e37ca2-1587550630-0-150; idtz=115.178.223.18-814933276; ASP.NET_SessionId=twbaf3ujbbvsflvtue14recu; username=; password=; vns_readType1=0`
> And then it'll works.

been try this. but still cannot work. i have create account and login, still not work.

**Comment by garybempo** [comment]
@Thrieze @Slasar41 thanks, it working for me now after added the extra codes at beginning and ending. :)

**Comment by molitar** [comment]
Ok So what am I missing as I can not even get a manga chapter list.

fullListMode=true;
idtz=72.187.235.69-146696606;
cf_clearance=56b6146beb8246f254b41940ffc8495fe9fd48c3-1587600284-0-150;
__cfduid=d1be5bd402a506cbbe6254e52e31c957b1587600275;
username=; password=; vns_readType1=0

**Comment by newmanism17** [comment]
Using what Slasar has posted, I replaced their cookies with mine and after clicking on a Manga on the list it said "Cannot get manga info. Please check your internet connection and try it again."

**Comment by molitar** [comment]
I tried with and without VPN.. I have a dedicated VPN IP so no worry there and I can login just fine and read but yeah the work arounds are not working anymore in FMD at all.

**Comment by ebvjr** [comment]
Tried @Slasar41 method and it works.

Append this to your cookies
```
fullListMode=true; username=; password=; vns_readType1=0; __test=;...
```

And it will work.

**Comment by alatnet** [comment]
Been trying to do the @Slasar41 method, but it isnt working for me.
cookies:
`idtz=73.57.72.149-661293235;
cf_clearance=2811a6b69eee8fbab321219cba9be3ace7ec6f73-1587647958-0-150;
__cfduid=d9a775adcbb726e9851a1970a85fb8f201587349226;
fullListMode=true;
username=;
password=;
vns_readType1=0;
__test=;`
user agent:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0`

**Comment by alatnet** [comment]
err... on chrome? cus i dont use ff.

**Comment by sardinac** [comment]
I couldn't get fmd 1.3.3.0 to work so downgraded back to 1.2.5.0. Used this **fullListMode=true;** __cfduid=d2a882c1cd8126089b9fe0da5a7cefac01587491482; cf_clearance=fb38ba59209c93ed9d826d61d23f1a1cd4e37ca2-1587550630-0-150; idtz=115.178.223.18-814933276; ASP.NET_SessionId=twbaf3ujbbvsflvtue14recu; username=; password=; **vns_readType1=0**. This is shown in the chrome networking tab where it shows everything but the first and last cookie,

**Comment by molitar** [comment]
> 
> 
> Tried @Slasar41 method and it works.
> 
> Append this to your cookies
> 
> ```
> fullListMode=true; username=; password=; vns_readType1=0; __test=;...
> ```
> 
> And it will work.

Thank you.. Glad you figured out what was wrong. Adding that to the beginning and not end of the cookie fixed the problem.

**Comment by zartzaku** [comment]
didnt seem working to me. dint know what wrong with my fmd.

**Comment by alatnet** [comment]
ok, got it to work with this method: https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-JapScan

did add the additional stuff that @Slasar41 mentioned to the beginning of the cookies.

**Comment by alatnet** [comment]
Looks like this is a temporary measure.
You're going to have to reapply the cookies if it doesnt retrieve anything.

**Comment by brshoemak** [comment]
I'm very familiar with CF workaround and will add that additional text string that @Slasar41 mentioned.  The issue I am currently having is that the text string of my cookies does not include a lot of the information it should have.  I'm not seeing 'idtz' or 'cf clearance' and a lot of other items that I used to see.  All I am seeing for the cookie, even when viewing the raw headers is: '__cfduid=d9bb2dbcac3350ab6326b1dbddb7c0de51587916268; android=0'

Any thoughts?  This is Win 10, running latest version of FF (v75.0).

![Capture](https://user-images.githubusercontent.com/64319332/80312674-6d8c5d80-87b4-11ea-93ad-b054c5c8a0f0.JPG)

**Comment by alatnet** [comment]
@brshoemak try going into the storage tab in the dev window.
not that familier with ff but i assume there's a section in there for cookies that you can look at.

**Comment by Slasar41** [comment]
@brshoemak I have to enter the reader mode and change the `Reading type` to `One page` to have the full cookies string.
If you look at HakuNeko [implemetation](https://github.com/manga-download/hakuneko/commit/64d03b2058877d47ca020b00ce0c2f7997409e73), they just need to add `vns_readType1=0` so I think adding that cookies string to KissManga module should fixed it.
But I can't test it because the module is still in Pascal.

**Comment by alatnet** [comment]
looks like you can keep everything except for the __cfduid when updating the cookie.
which makes it simpler to update it.

**Comment by Mech-cyber** [comment]
For last few days workaround only allows for retrieveing chapters list and manga info, but not downloading: the program only creates folders, but doesn't download any images, and when it finishes creating them, it reports an error.

**Comment by Slasar41** [comment]
> For last few days workaround only allows for retrieveing chapters list and manga info, but not downloading: the program only creates folders, but doesn't download any images, and when it finishes creating them, it reports an error ("Failed to download chapters, try to resume.").

Try this too: https://github.com/fmd-project-team/FMD/wiki#troubleshooting-guides

**Comment by Mech-cyber** [comment]
Sadly, it didn't help. Only key has changed (at least in my case), while vector remained the same.

**Comment by 7godeohs** [comment]
@Mech-cyber I was able to get it working, but it wasn't pretty.  For whatever reason, even on a clean install of Firefox or Chrome with security exceptions I wasn't able to get KissManga to load certain content and allow me to select the one-page reader option.  So I had to use Microsoft Edge.

This is the Cookie format that worked for me:

__cfduid=db13f5e942ef522138516879af84cd5e21587956091; cf_clearance=dd78bcaf536e91b0cb20cd9fcfc769e0cbd26451-1588015486-0-150; idtz=174.60.229.71-786227956; username=; password=; vns_readType1=0

Within Microsoft Edge, I had to browse to KM, open a chapter, right-click on an image, click 'Inspect' to open the console.  Once the console was open, it defaults to the 'Element' tab, you need to click on the 'Application' tab.

Once that opens, you'll see a list of different Name fields like __cfduid and cf_clearance and the values for each one.  You need to take the string of text I pasted above, and replace the values for __cfduid, cf_clearance, and idtz with the values you pull from the list in Microsoft Edge.  That will be your Cookie for FMD.  Copy it and paste it to a text editor.

For the User Agent, from the Console where you found the cookie information, click on the 'Network' tab at the top. The page will initially appear blank.  Press F5 (or whatever) to reload the page.  It will now be populated with multiple entries.  Click on the first item in the list.  A window will appear on the right side of the screen.  Within that new window, make sure you're in the Headers tab, and then look for the User Agent field about 3/4 of the way down.  You want to highlight and copy the user agent string, like this:  

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36 Edg/81.0.416.64

Open FMD.  Go to 'Options' -> 'Websites' -> 'Advanced' -> search for 'Kissmanga'  Then paste the Cookie and User Agent in the appropriate field. Make sure you hit Enter after each paste to make sure the change held.  Then click apply.  **There are not spaces in the cookie or the user agent.

Go back to Favorites and try to Check for Chapter again.  Let me know at what point you're having issues.

**Comment by Mech-cyber** [comment]
@7godeohs No need to copy the whole instruction (thanks for the reply though). After few experiments with cookies format (I used to write them in one line and in a different order, whick worked) I managed to make it work.

**Comment by alatnet** [comment]
Looks like the workaround is dead for me.

**Comment by sardinac** [comment]
@alatnet Have you tried downgrading because the workaround still works for me. I also mentioned it in my previous comment.

**Comment by alatnet** [comment]
No, i havent, but it use to work fine with the current version im using.
i'll give a go with an older version.

**Comment by alatnet** [comment]
So, this is what I currently have for the lualization of the kissmanga module.
https://pastebin.com/Wq58KnP9
Without an api to look up functions, i cant make heads or tails of various things.
Basing some parts of it off of the mangadex lua module to at least get a clue on how to recode the pascal module but... yea...

**Comment by sardinac** [comment]
@alatnet 
![fmd](https://user-images.githubusercontent.com/17863649/81372206-63753380-90bf-11ea-8e4c-21ff1865b9c0.PNG)
![Chrome](https://user-images.githubusercontent.com/17863649/81372224-6f60f580-90bf-11ea-9b6b-4b16f560df89.PNG)

I'm formatting a little weirdly but the second line is all the cookies from the networking tab.

**Comment by 7godeohs** [comment]
@alatnet I'm not sure what browser you're using to pull the headers and cookies, but if it's Edge I had an issue with Kissmanga this afternoon (5/8/20) and it was caused by a change in the user agent string.  Edge doesn't have a simple way to disable auto-updates, but it can be done.  Not saying that's your issue, just that I had similar issues around the same time.

**Comment by alatnet** [comment]
Using chrome.
this is my cookies line:
fullListMode=true; username=; password=; vns_readType1=0; __test=; idtz=73.57.72.149-661293235; __cfduid=d9a775adcbb726e9851a1970a85fb8f201587349226; cf_clearance=e3cb3a5caa1b3aa45e74a9237cd8b11b3d1b44d4-1588882956-0-150
this is my user agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

**Comment by sardinac** [comment]
@alatnet Chrome/81.0.4044.138 and format how I have it because the cookies when copied from the networking tab is one signal line. Also still using fmd 1.2.5.0.

**Comment by alatnet** [comment]
ok, it was the user agent, i was able to get my favorites to check correctly now with the current version. thank you @sardinac.

**Comment by molitar** [comment]
Remember you can't use link breaks anymore in cookies that has been broken in the new version.  Before you could use line breaks.

<cookie part 1>;
<cookie part 2>;
<cookie part 3>;  <---- Does not work 

<cookie part 1>;<cookie part 2>;<cookie part 3>   <----- works

**Comment by HiP1** [comment]
thanks, changing to chrome made it work for me too.

**Comment by SoaringSpoon** [comment]
Is this just something we will have to re apply every time you boot up the app? Is there a way to automate it?

**Comment by alatnet** [comment]
Looking like it.
For the automation, possibly but converting the perl module to lua is the best bet.

**Comment by molitar** [comment]
Right now I find kissmanga not even worth it.. it changes every single day.. ugg

**Comment by Tmp341** [comment]
Kissmanga was my very very last resort, but after their bs everyday, i just changed all the mangas i kept there.

**Comment by Inareous** [comment]
You could automate applying the cookies and chko by editing the modules.json directly.

You could run this script before opening fmd : https://gist.github.com/Inareous/8d6228ec7b4836960dafb6a281e5cd17
add additional parameter --a "fullListMode=true; username=; password=; vns_readType1=0;" to its cookies.

Create a .bat file to save your own parameter and you got yourself a temporary fix. Still need to update cloudscaper every so often tho.

**Comment by Thrieze** [comment]
Welp, Knowing nothing about python lol, Learned how to use pip for cloudscraper install, How to run things correctly, Didnt realize you had to put that py file in the FMD config folder, BAT was simple, done that a ton. But it works well thanks =D Saves me quite a few clicks.

**Comment by revanwolf** [comment]
username & password is not needed (maybe for some 18+ contents).

**Comment by IgnatiusC** [comment]
Cookie fixes favorites check but is there any way to get update manga list to work? Or are there any other sites with similar quality uploads?

**Comment by Inareous** [comment]
@IgnatiusC Raise issue at [FMD-WebsiteDatabases](https://github.com/fmd-project-team/FMD-WebsiteDatabases) to update Kissmanga, after updated, you can get the latest database using "Download manga list from server"

**Comment by zartzaku** [comment]
Starting this morning I cannot download from kissmanga again even after use the cookie trick mention here. its weird, because yesterday I can still download using that trick.

**Comment by Thrieze** [comment]
Yea, Its looks like they implemented their "areyouhuman" check on every single page load. So it cant dl things. Im assuming temporary but its damn annoying.

**Comment by Tmp341** [comment]
Try [FMD2](https://github.com/dazedcat19/FMD2)

**Comment by zartzaku** [comment]
FMD2 same as FMD. It cannot bypass their "areyouhuman" check.

**Comment by Tmp341** [comment]
Nothing can bypass "are you human" except you though.

**Comment by Tmp341** [comment]
Check #1109
