### ISSUE TITLE
Help for Lua script [WebToons]

### ISSUE THREAD

**Issue by AbidZakaria** [fmd-project-team/FMD#94]
![image](https://user-images.githubusercontent.com/19544118/56012306-1e44cd80-5d16-11e9-8390-e2f66e611018.png)
can't get all chapter

```lua
function getinfo()
  if http.get(mangainfo.url) then
    x=TXQuery.Create(http.document)
    mangainfo.title = x.xpathstring('//div[@class="info"]/h1')
    if mangainfo.title == '' then
		mangainfo.title = x.xpathstring('//div[@class="info challenge"]/h3')
		:gsub('Apakah kamu ingin menghapuswebtoon ini?', ''):gsub('DASHBOARD', ''):gsub('Batal',''):gsub('OK',''):gsub('  ',''):gsub('?', '')
	end
	mangainfo.coverlink=x.xpathstring('//meta[@name="twitter:image"]/@content')
    mangainfo.authors=x.xpathstring('//div[@class="info"]//span[@class="author"]')
	mangainfo.genres=x.xpathstring('//div[@class="info"]/h2')
	if mangainfo.genres == '' then
		mangainfo.genres=x.xpathstring('//div[@class="info challenge"]/p')
	end	
	mangainfo.summary=x.xpathstring('//p[@class="summary"]')
	local v=x.xpath('//div[@class="detail_lst"]/ul/li/a')
    for i=1,v.count do
        local v1=v.get(i)
			mangainfo.chapterlinks.add(v1.getAttribute('href'))
			mangainfo.chapternames.add(x.xpathstring('.//span[@class="subj"]', v1))
    end

	pages = tonumber(x.xpathstring('//div[@class="detail_lst"]/div[@class="paginate"]/a[last()]/substring-after(@href, "&page=")'))
	if pages > 1 then
		if pages == nil then pages = 1 end
		local p = 2
		while true do
		  local v=x.xpath('//div[@class="detail_lst"]/ul/li/a')
		  for i=1,v.count do
			local v1=v.get(i)
				mangainfo.chapterlinks.add(v1.getAttribute('href'))
				mangainfo.chapternames.add(x.xpathstring('.//span[@class="subj"]', v1))
		  	end
		  	p = p + 1
		if p >= pages then break end
		  	if http.get(mangainfo.url .. '&page=' .. tostring(p)) then
				x=TXQuery.Create(http.document)
				pages = tonumber(x.xpathstring('//div[@class="detail_lst"]/div[@class="paginate"]/a[last()]/substring-after(@href, "&page=")'))
		  	else
				break
		  	end
		end
	end
    InvertStrings(mangainfo.chapterlinks,mangainfo.chapternames)

    return no_error
  else
    return net_problem
  end
end
```
but I think this is correct
and I think it's the same as the Pascal version

```pascal
function GetInfo(const MangaInfo: TMangaInformation;
  const AURL: String; const Module: TModuleContainer): Integer;
var
  query: TXQueryEngineHTML;
  p, i: Integer;

  procedure getchapters;
  var
    v: IXQValue;
  begin
    for v in query.XPath('//ul[@id="_listUl"]/li/a') do begin
      MangaInfo.mangaInfo.chapterLinks.Add(v.toNode.getAttribute('href'));
      MangaInfo.mangaInfo.chapterName.Add(query.XPathString('span[@class="subj"]/span', v.toNode));
    end;
  end;

  procedure getp;
  begin
    p := StrToIntDef(SeparateRight(query.XPathString('//div[@class="detail_lst"]/div[@class="paginate"]/a[last()]/@href'), '&page='), 1);
  end;

begin
  Result := NET_PROBLEM;
  if MangaInfo = nil then Exit(UNKNOWN_ERROR);
  with MangaInfo.FHTTP, MangaInfo.mangaInfo do begin
    url := FillHost(Module.RootURL, AURL);
    if GET(url) then begin
      Result := NO_ERROR;
      query := TXQueryEngineHTML.Create(Document);
      with query do
        try
          coverLink := XPathString('//meta[@name="twitter:image"]/@content');
          if title = '' then title := XPathString('//div[@class="info"]/h1/text()');
          authors := XPathString('//div[@class="info"]/a/text()');
          genres := XPathString('//div[@class="info"]/h2');
          summary := XPathString('//p[@class="summary"]');
          getchapters;
          getp;
          if p > 1 then begin
            i := 2;
            while (i <= p) and (Thread.IsTerminated = False) do begin
              if GET(url + '&page=' + IntToStr(i)) then begin
                ParseHTML(Document);
                getchapters;
                getp;
              end;
              Inc(i);
            end;
          end;
          InvertStrings([chapterLinks, chapterName]);
          Reset;
          Headers.Values['Referer'] := ' ' + url;
        finally
          query.Free;
        end;
    end;
  end;
end;
```

this file please check @SDXC 
for example link https://www.webtoons.com/id/drama/teenage-mom/list?title_no=1466

[WebToons.zip](https://github.com/fmd-project-team/FMD/files/3071527/WebToons.zip)
update 2019/04/12

**Comment by AbidZakaria** [comment]
when it's done don't pull request
upload again in this issue

**Comment by ChocolateOtaku** [comment]
Please use [fenced code blocks with syntax highlighting](https://help.github.com/en/articles/creating-and-highlighting-code-blocks#syntax-highlighting) instead of copy & pasted images when showing code...

**Comment by AbidZakaria** [comment]
if you want @ChocolateOtaku, 
you can also help too

**Comment by Tmp341** [comment]
>Delete or backup fmd.log file. Then;
>
>`print(StreamToString(http.document))`
>
>Paste this below this line:
>
>`x=TXQuery.Create(http.document)`
>
>inside of the Lua and try again. If your logging is disabled, enable it before trying.
>
>It should look like this:
>
>`    x=TXQuery.Create(http.document)`
>`    print(StreamToString(http.document))`

This is a debug code for Lua scripts. It will log all in the log file. Check if it would be helpful.

**Comment by SDXC** [comment]
The loop is probably one run too short. I'll take a look today.

**Comment by SDXC** [comment]
@AbidZakaria Fixed and optimized the chapter fetching. Added a language option (/en or /id can't distinct between different Website modules, so we have to go by language option). For now it's only EN/ID, but we can add the rest of the languages supported by WebToons.

What's missing for now is the WebToons Discover / Challenge part because it has too many entries (over 300 pages of title overview).

[WebToons.zip](https://github.com/fmd-project-team/FMD/files/3076905/WebToons.zip)
14.04.2019

**Comment by AbidZakaria** [comment]
what if made own lua script for WebToons Discover / Challenge

**Comment by SDXC** [comment]
@AbidZakaria It's not possible if the website is only a subpart of the main:
`https://www.webtoons.com/` -> Website module possible
`https://www.webtoons.com/en/challenge` -> Website module **not** possible
`https://challenge.webtoons.com/` -> Website module possible, but doesn't exist.

**Comment by SDXC** [comment]
challenge is now implemented. there is a technical limitation though. updating manga list stops at page 1000 because the pagination links aren't present anymore:
Has pagination:
https://www.webtoons.com/en/challenge/list?genreTab=ALL&sortOrder=&page=999
Has not pagination anymore:
https://www.webtoons.com/en/challenge/list?genreTab=ALL&sortOrder=&page=1000

There exist about 2650 pages.

**Comment by rs3mk** [comment]
https://translate.webtoons.com/ is also included?

Spanish:
https://translate.webtoons.com/webtoonVersion?webtoonNo=780&language=SPA&teamVersion=0

English:
https://translate.webtoons.com/webtoonVersion?webtoonNo=780&episodeNo=111&language=ENG&teamVersion=0

Portuguese:
https://translate.webtoons.com/webtoonVersion?webtoonNo=780&episodeNo=111&language=POR&teamVersion=17

**Comment by SDXC** [comment]
@rs3mk No. This would be a new website module. Was there an issue with this request? If not, can you create it?

**Comment by rs3mk** [comment]
add it here:: https://github.com/fmd-project-team/FMD/issues/106

**Comment by SDXC** [comment]
Thanks. Will probably be implemented next week.
