### ISSUE TITLE
Add Option to not go directly to Download Tab [Feature Request]

### ISSUE THREAD

**Issue by Von07** [fmd-project-team/FMD#95]
Just as the title says, It would be  better if there's an option that will let you not directly go to Download Tab after you Click " Download " in Manga Info

Ex.
![Request](https://user-images.githubusercontent.com/21298898/56018740-82c35500-5d35-11e9-97a8-f77f84335d11.png)
After you click the Download it will directly go to " Downloads " Tab which is annoying sometimes if you bulk download alot of manga and want to save alot of time.. thank you ^^

Same Request --> https://github.com/fmd-project-team/FMD/issues/27

**Comment by Slasar41** [comment]
I think it's duplicated from this issue https://github.com/fmd-project-team/FMD/issues/27

**Comment by Von07** [comment]
> I think it's duplicated from this issue #27

ohh so it has been requested already.. I guess I need to close this one..

**Comment by SDXC** [comment]
Yes, that's a duplicate. I'll close this issue, so I don't lose sight of my tasks.
I am currently working on this, btw.
