### ISSUE TITLE
"Genshiken" in MangaLife not showing any chapters

### ISSUE THREAD

**Issue by Draw99Gray** [fmd-project-team/FMD#952]
Could you fix it? it's the only site where i found the updated manga with better quality, so i need to download it from there
Maybe it has to do with the website direction? it's manga4life.com, not mangalife.us
https://i.imgur.com/fff7UuD.jpg

**Comment by Slasar41** [comment]
You use old version from riderkick.
Please use latest version: https://github.com/fmd-project-team/FMD/releases
Here's how to migrate the data: https://github.com/fmd-project-team/FMD/wiki#fresh-install

**Comment by SDXC** [comment]
Should be fixed now. If it still happens to some titles, please open a new issue and also don't forget to mention the affected titles.
