### ISSUE TITLE
Cant download from MangaHubIO

### ISSUE THREAD

**Issue by knight109** [fmd-project-team/FMD#953]
Everything fine in website or FMD, but i cant download.

**Comment by Slasar41** [comment]
Could you give some titles that has problem?
I can download random title just fine.
![image](https://user-images.githubusercontent.com/28888646/80522098-338aa980-89b6-11ea-9050-dfb359745101.png)

**Comment by knight109** [comment]
It fine now.
I just deleted the modules and redownload it.
