### ISSUE TITLE
Mangawindow - unable to update directory list and favorite lists

### ISSUE THREAD

**Issue by noering** [fmd-project-team/FMD#954]
Hello, it seems FDM unable to 'update manga list' from mangawindow.net and also failed to check new chapters in favorite.

![02](https://user-images.githubusercontent.com/3715548/80476868-344f1b80-8975-11ea-9bfd-38ea4e55016c.JPG)

**Comment by Slasar41** [comment]
The website have this notice:
![image](https://user-images.githubusercontent.com/28888646/80522442-caeffc80-89b6-11ea-8165-ee0cccedfdc0.png)
So you need to do cloudflare workaround for now, example: https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-PsychoPlay
Then it'll download normally.

**Comment by noering** [comment]
Ok I will try it now :)
And since this has been refered to Batoto #955, I won't close this issue yet (except by admin).
Thanx for the reply :)

**Comment by Slasar41** [comment]
Try again like this: https://github.com/fmd-project-team/FMD/issues/955#issuecomment-621091962

**Comment by noering** [comment]
Ok it work now, following #955 as you pointed.
I found that the cookies must be trimmed, from something like this:
cf_clearance=xxxx;
__cfduid=xxxx;
_ga=GA1.xxxx;
Hm_lvt_xxxx;
Hm_lpvt_xxxx

Into just like this:
cf_clearance=xxxx;
__cfduid=xxxx

So far so good
Thanks for the help :)

**Comment by arbiter9605** [comment]
what ever reason it don't like me even after doing what was said word for word still just a arrow showing its checking but just sites their stalled

**Comment by noering** [comment]
> what ever reason it don't like me even after doing what was said word for word still just a arrow showing its checking but just sites their stalled

For me it only works with cookies in chrome 'incognito mode' - dunno why. Firefox failed, never successful.
If the cookies still failed, i found that sometime simply refresh/F5 the page not working, so we have to close the browser entirely and re start it all over again.

**Comment by noering** [comment]
For mangawindow.net I do like this
1. In chrome incognito, choose network tab
2. Choose 'doc' so it will only show the document files, which make it easier to sort
3. Highlight/choose the file that contain the cookies and user agent. Thankfully for mangawindow, only this one file.
4. Step 4 & 5 We're gonna copy this line latter

![01](https://user-images.githubusercontent.com/3715548/80857276-2d791f00-8c7b-11ea-8070-67d40e5173d0.JPG)

Since the cookies is need to be cut/trim to be work, I copy paste it to notepad temporary
![02](https://user-images.githubusercontent.com/3715548/80856558-60b8af80-8c75-11ea-868e-ce8b00b03d59.JPG)

And tidy it like this, then copy it now for later use
We don't need the other lines that contain GA (analytic) code and what ever those Hmxxx lines.
They will make error for this desperate effort of us, so get rid of them :)
![03](https://user-images.githubusercontent.com/3715548/80856621-96f62f00-8c75-11ea-8c9d-b45bec2ccb54.JPG)

Then choose the site we want - set it like showed in number 2
![04](https://user-images.githubusercontent.com/3715548/80856646-b0977680-8c75-11ea-96db-48f6b26f32d3.JPG)

Then paste the cookie that we copied before, click step 1 and 2 first
![05](https://user-images.githubusercontent.com/3715548/80856654-dc1a6100-8c75-11ea-8db5-3e913871cab7.JPG)

A new window showed up, paste it there, then click ok
![06](https://user-images.githubusercontent.com/3715548/80856681-213e9300-8c76-11ea-97b9-91d2c9aba1c3.JPG)

Click the apply button
![07](https://user-images.githubusercontent.com/3715548/80856691-2c91be80-8c76-11ea-987d-46a57bc73260.JPG)

Do it also for user agent, like we do for the cookies before
![08](https://user-images.githubusercontent.com/3715548/80856699-4206e880-8c76-11ea-9b53-394c63d04942.JPG)

Copy the user agent line and paste it there, click ok
![09](https://user-images.githubusercontent.com/3715548/80856705-4cc17d80-8c76-11ea-912b-3fdaeba50fae.JPG)

Don't forget to click that lovely apply button again :)
![10](https://user-images.githubusercontent.com/3715548/80856716-68c51f00-8c76-11ea-92ef-1d164d9b8dd8.JPG)

If everything works, we could see the chapter list
![11](https://user-images.githubusercontent.com/3715548/80856722-79759500-8c76-11ea-8ab7-912fede74c26.JPG)

Then we could refresh the favorites link and download it.
![12](https://user-images.githubusercontent.com/3715548/80856734-9316dc80-8c76-11ea-8912-247b413f9071.JPG)

This work for me, hope for you all too :)
Since the cookies have limited time, so do whatever you want to do asap, if you found it stalled again, restart the page and get the newest cookie again. ONLY the cookies, no need to change the user agent.

**Comment by arbiter9605** [comment]
when posted first time i did word for word using chrome incognito. Being trying daily using it and still nada

**Comment by HiP1** [comment]
doesn't work now. same as Batoto
