### ISSUE TITLE
Where is all the websites?

### ISSUE THREAD

**Issue by theruleof4** [fmd-project-team/FMD#957]
I downloaded the new version and there are only a few websites available, I tried to update the modules and find nothing.

**Comment by Tmp341** [comment]
If you've overwritten on your previous install, then old and new system might be conflicting.

**Comment by theruleof4** [comment]
No, I'm not, I've deleted the old version
Check the screenshot:


![Capturar](https://user-images.githubusercontent.com/62116034/80810340-fda61a80-8b99-11ea-85a9-887d0eeec9c4.JPG)

**Comment by theruleof4** [comment]
Anyone?

**Comment by Rarksoca** [comment]
Try update modules

**Comment by theruleof4** [comment]
I already tried and found nothing

**Comment by Tmp341** [comment]
Try putting [this](https://github.com/fmd-project-team/FMD/files/4520812/config.zip)

**Comment by theruleof4** [comment]
> Try putting [this](https://github.com/fmd-project-team/FMD/files/4520812/config.zip)

I paste, when I opened the program show me this:

![Capturar](https://user-images.githubusercontent.com/62116034/80917586-4db9e400-8d36-11ea-874b-6d6fd6cffe70.JPG)

I clicked yes, and nothing happens, I tried the modules tab and update, but it seems that the program cannot connect to the server and update, follows the screenshot:

![Capturar2](https://user-images.githubusercontent.com/62116034/80917623-ae492100-8d36-11ea-92d2-a8f4bdfcff12.JPG)

**Comment by Slasar41** [comment]
I just tested download the latest release then I got prompted with this dialog:
![image](https://user-images.githubusercontent.com/28888646/80922047-b049c900-8da4-11ea-9348-6355b273e7e2.png)
I press Yes, waiting until asking to restart, then I got all the website:
![image](https://user-images.githubusercontent.com/28888646/80922105-f56dfb00-8da4-11ea-9d6f-72c7fbff85e5.png)

Try my files
[config.zip](https://github.com/fmd-project-team/FMD/files/4571313/config.zip)

**Comment by theruleof4** [comment]
I replace the files and the same errors appear, but I moved the program folder to another place, put it on the desktop, and for some reason it worked, I managed to update the modules.

**Comment by Tmp341** [comment]
If you have non english characters in your folder name, like ``я`` for example, FMD refuses to work functional.

**Comment by theruleof4** [comment]
> If you have non english characters in your folder name or path (ie `C:\Folder\abcя\name\FMD`) , that `я` effects it, then FMD refuses to work functionally.

It's weird, it was in the Documents folder. A months ago I had a very older version of the program, which does not work anymore, and a deleted and replaced by this new one, for some reason not worked, and I tried in another path and worked. I don't know how, but worked
