### ISSUE TITLE
Reaperscans not working

### ISSUE THREAD

**Issue by traitorAIZEN** [fmd-project-team/FMD#959]
It has cloudflare now, not sure if it already had one previously. I tried using the Kissmanga cf method but it's not working.

**Comment by azraei97** [comment]
It has cloudflare before too. FMD has prebuild cf bypass but cf recently make update. Maybe improve security. That could be the reason why cf bypass in FMD not working properly recenty

**Comment by Slasar41** [comment]
Works fine for me using workaround.
![image](https://user-images.githubusercontent.com/28888646/80922397-03248000-8da7-11ea-9d65-1d442e6b7068.png)
I copy all the cookies string to FMD.
![image](https://user-images.githubusercontent.com/28888646/80922410-20f1e500-8da7-11ea-8ea5-3f895b83dde8.png)
