### ISSUE TITLE
Chapter list missing some chapters [Mangaku]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#96]
![fmd5](https://user-images.githubusercontent.com/45929526/56077835-19157a80-5e0b-11e9-8757-f7de494f3822.PNG)
![fmd6](https://user-images.githubusercontent.com/45929526/56077836-19ae1100-5e0b-11e9-88dd-34d2d7999ea4.PNG)

**Comment by SDXC** [comment]
Created small workaround to fetch missing chapters. Mangaku has some malformed HTML code.
