### ISSUE TITLE
Problems with website [LetItGoScans]

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [fmd-project-team/FMD#97]
I have noticed that my Favorites fail when trying to access LeItGoScans.
When I tried checking the chapters from the list or from a link, it also failed to connect. I have tried the workaround, but there are no cookies whatsoever, so no luck there.
I then tried making sure that the site had not been misplaced from the lua, but both the name and the url are correctly included inside FoOlSlide.lua, so that's also not it. While the stylesheet has been modified, the reader is still a FoOlSlide.
The last thing I did was to check with a different FoOlSlide-based reader, just to see if there was any issue with the entire module, but that did work.

The only thing I can think of, besides a very weird problem from my end, would be that LetItGoScans has done something to the reader that prevents the generic FoOlSlide module to work properly. In order to find the correct one, please someone tell me if the site works for them.

**Comment by Tmp341** [comment]
They've removed some mangas from their reader. Have you checked that? because, none of mine were there.

**Comment by l-l-l-l-l-l** [comment]
I checked aking the first valid url of their reader, which I can access just fine in my browser.

**Comment by SDXC** [comment]
Please upload your favorites.db file (you have to zip it) and give us 2-3 examples where it didn't work and if you have examples where it did work, please also list them.

**Comment by Tmp341** [comment]
It wasn't working for me yesterday, so when i've checked their site, they've removed some of their releases. Today, some of them are back it seems. But i've already transferred my favorites, so it is not a problem for me anymore. 

But your favorites might be checking an old structure (explained here in [wiki](https://github.com/fmd-project-team/FMD/wiki#fresh-install, where i've put a note).

>**Note for data files:** If a manga has changed it's manga pages (from a.com/manga to a.com/mangas/manga for example) your favorites and/or manga database for that site might not work.

So, your favorites file might be wrong. Just send it like @SDXC said.

**Comment by l-l-l-l-l-l** [comment]
OK, after looking around, it seems that most of my favorited series have, for some reason, disappeared from their database (no announcement made, a link uploaded just last week is broken and the few series remaining tendo to have very few chapters). However, the series that still remain are also inaccessible and the software cannot update the list from the reader.

The following DB file has 6 series, and while 4 seem to have been taken down or lost, two of them are still on the 
[favorites.zip](https://github.com/fmd-project-team/FMD/files/3076442/favorites.zip)

site, but also fail to connect:

**Comment by Tmp341** [comment]
From your favorites, only ``Freezing`` and ``Freezing Colur`` are reachable. And only color one contains a couple of chapters. Tried to check your favorites, nothing.

I've copied the links from browser, gives ``N/A``.

**Comment by l-l-l-l-l-l** [comment]
Which is the issue I started with. In fact, the browser link I first tried to see if there was something wrong was the latest chapter they've uploaded.

It looks to me like they have had some issue and their reader was wiped out, since not only they have lost series and have a lot with no chapters, but also from the series that they still have, a couple of them have changed urls.

**Comment by SDXC** [comment]
LetItGoScans moved from FoOlSlide to ComiCake. We probably create a ComiCake.lua and move all ComiCake websites there.

**Comment by SDXC** [comment]
Should be fixed now.

Issue will be closed. Please re-open this issue if you still have problems.
