### ISSUE TITLE
Some feature doesn't work anymore [Komiku]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#970]
when i try to download manhua 'the last human' ch.236 it fail :
![komiku-d](https://user-images.githubusercontent.com/45929526/81354901-f54c6300-90f6-11ea-8f75-6103f23f36dc.PNG)
but the web is still work :
![komiku-k](https://user-images.githubusercontent.com/45929526/81355021-570ccd00-90f7-11ea-89b5-ff216770f667.PNG)
and some feature not work :
![komiku-s](https://user-images.githubusercontent.com/45929526/81355168-c682bc80-90f7-11ea-98b7-bb541786f83b.PNG)
cause in the web :
![komiku-n](https://user-images.githubusercontent.com/45929526/81355212-f5009780-90f7-11ea-8175-98dd93cd8eee.PNG)

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/81436331-86711780-9193-11ea-8b71-edfae022ad37.png)
![image](https://user-images.githubusercontent.com/28888646/81436369-9557ca00-9193-11ea-85a6-2f5a67964699.png)
