### ISSUE TITLE
Save file to CBZ result to empty 0KB cbz file

### ISSUE THREAD

**Issue by wongsaraf** [fmd-project-team/FMD#971]
Version 1.3.3.0

Saving  downloaded chapter to CBZ will randomly having some of them turned into 0KB CBZ file.
This only happen if I set the Connections Option of "Number of downloaded files per task at the same time" to 5.
If I set it to 1 there will be no error when the chapter got converted to CBZ.

**Comment by Tmp341** [comment]
Can you download normal (without CBZ) with that set to ``5``?

**Comment by wongsaraf** [comment]
Downloading file normally without CBZ option enabled doesn't give any error with 5 task at the same time.
But its a problem because I'm using Komga manga webserver, it doesn't detect individual image that are saved inside a folder.

**Comment by Tmp341** [comment]
You don't have that problem with any other sites right?

**Comment by wongsaraf** [comment]
Funny, I tried to reproduce the bug again but so far got nothing.
My setup was like before, with "Auto generate chapter folder" disabled.
I only download from mangadex site.

**Comment by Tmp341** [comment]
Mangadex goes maintenance and/or mitigation modes from time to time.
