### ISSUE TITLE
Downloading from Mangadex always slow

### ISSUE THREAD

**Issue by EPP9849** [fmd-project-team/FMD#975]
Sometimes it's not downloading, with 0Bps speed

**Comment by Tmp341** [comment]
Check your global and mangadex specific settings.

**Comment by SBoyer4** [comment]
> Sometimes it's not downloading, with 0Bps speed

Getting the dame issue more or less but lately its around 24kbps. Only with MangaDex in the last few days. Dont see any issues in settings?

**Comment by Tmp341** [comment]
It is like that on purpose, since Mangadex's ddos protector bans your IP if you download too fast.
