### ISSUE TITLE
Fail to download from Jaiminisbox

### ISSUE THREAD

**Issue by azraei97** [fmd-project-team/FMD#976]
Any download from Jaiminisbox always end up Red Fail Task
![Untitled](https://user-images.githubusercontent.com/40983245/81637682-8601a680-9449-11ea-8d3d-b438c3d7966b.png)

**Comment by 7h3Cub3** [comment]
This has been reported many times already, they enforced a new anti-crawler defense to forbid crawling site (aggregators) or manga downloaders to be able to download.

Fixed in this commit 12 days ago.
https://github.com/fmd-project-team/FMD/commit/d2df852117ba539f93095d570fb7b31ea4f2cedc

**Comment by azraei97** [comment]
Well, their own website download function also doesn't work. That why I try to ask if any news enabling support new JBox

**Comment by 7h3Cub3** [comment]
their sites has been iffy in the last couples of day, even went down, i tried right now and it seems to work fine (direct download of a chapter) but yeah the anticrawler mesures are still here. Usually what i do is that when a new chapter arrive i just go and DL it directly on their site until we get the new FMD version ^^

**Comment by azraei97** [comment]
It's already 2 days their own download function was broken. I report about it in their discord. They take a look and fix it. Works again. Hope their removed anticrawler forever hahaha
