### ISSUE TITLE
Can't download certain websites manga list

### ISSUE THREAD

**Issue by lin4t** [fmd-project-team/FMD#979]
I installed the newest version and all the modules downloaded correctly. But the problem is that I can't download certain websites' .db files. It gets stuck on the downloading part indefinitely at the part where it says downing website.db at https://excellmedia.dl.sourceforge.net/project/newfmd/data/website.7z

Mangafox and Mangahere works but not Mangasee, Mangadoom, Jaiminisbox and so on with more not working than working (unless I'm getting really unlucky).

Should I just drag over the data files I have from an older version to get around this or is this some sort of connection issue on my side?

**Comment by Tmp341** [comment]
Download from [here](https://github.com/fmd-project-team/FMD-WebsiteDatabases/tree/master/packages).
