### ISSUE TITLE
Problem with website [MangaKita]

### ISSUE THREAD

**Issue by MIRVOUS** [fmd-project-team/FMD#98]
![fmd7](https://user-images.githubusercontent.com/45929526/56083803-2145d800-5e54-11e9-993c-064d6f1c6ec7.PNG)

**Comment by MIRVOUS** [comment]
there's nothing there

**Comment by AbidZakaria** [comment]
Mangakita adding cloudfire,
Try adding cookies and useragent

**Comment by MIRVOUS** [comment]
tutorial please

**Comment by riedhows** [comment]
from the info owner, we are in the process of repairing the server so it will be unstable in the next few days
