### ISSUE TITLE
Adding site kkjscans.co (lua provided)

### ISSUE THREAD

**Issue by 7h3Cub3** [fmd-project-team/FMD#980]
[KKJScans.zip](https://github.com/fmd-project-team/FMD/files/4623836/KKJScans.zip)

This LUA for adding support to manga website kkjscans.co, work perfectly (place it in lua\modules)

Cheers.

**Comment by azraei97** [comment]
I just about to ask this website support. Thanks for bring unofficial support here

**Comment by Slasar41** [comment]
The module works fine.
You can make a pull request and someone will review and merge it.
