### ISSUE TITLE
Adding site webnovel.live (Work fine with Madara.lua)

### ISSUE THREAD

**Issue by Rarksoca** [fmd-project-team/FMD#981]
[Madara.zip](https://github.com/fmd-project-team/FMD/files/4631983/Madara.zip)
This LUA for adding support to manga website webnovel.live, work perfectly (place it in lua\modules)

**Comment by Slasar41** [comment]
You can make a pull request and someone will review and merge it.

**Comment by azraei97** [comment]
@SDXC Can you review this?
