### ISSUE TITLE
Adding Comic support for WuxiaWorld [Madara.lua]

### ISSUE THREAD

**Issue by azraei97** [fmd-project-team/FMD#982]
Comic in WuxiaWorld:
https://wuxiaworld.site/comic/

Just add this link in Madara.lua work perfectly
   AddWebsiteModule('WuxiaWorld', 'https://wuxiaworld.site', cat)
![Untitled](https://user-images.githubusercontent.com/40983245/82014073-64edbf80-96ae-11ea-96b4-a5f5a458bbe8.png)

**Comment by azraei97** [comment]
By the way, I also try to add support Martial Scans https://martialscans.com in madara.lua because it same template with other Madara and his brother Disaster Scan but for some reason, adding:

  AddWebsiteModule('MartialScans', 'https://martialscans.com', cat)

Not simply enough because chapter list not loaded
![Untitled](https://user-images.githubusercontent.com/40983245/82014779-e42fc300-96af-11ea-83de-4525486837a6.png)

**Comment by Rarksoca** [comment]
Thanks for bring support here

**Comment by Slasar41** [comment]
You can make a pull request and someone will review and merge it.
Regarding the chapter list is empty, Madara also use another method to provide the chapters and FMD need to adapt the changes. https://github.com/fmd-project-team/FMD/issues/909

**Comment by azraei97** [comment]
I don't understand how to use "pull request". When I click "New Pull Request", it just going to big file change log.
