### ISSUE TITLE
Website changed domain [BacaManga]

### ISSUE THREAD

**Issue by riedhows** [fmd-project-team/FMD#99]
Bacamanga.web.id has change their domain to bacamanga.co

please fix this

thank you

**Comment by MIRVOUS** [comment]
![fmd1](https://user-images.githubusercontent.com/45929526/56084060-c8783e80-5e57-11e9-8f97-2d639f6735dc.PNG)

thanks for the info. I don't know why that is

**Comment by SDXC** [comment]
@AbidZakaria Can you test, if the lua script works when you just change the url? I can't because of Region Lock. If it works you can just make a pull request.

**Comment by AbidZakaria** [comment]
![image](https://user-images.githubusercontent.com/19544118/56086859-8b2ca480-5e89-11e9-8d2b-66358bf92ef2.png)

it's works fine from me

**Comment by MIRVOUS** [comment]
no it's not work from me

![fmd2](https://user-images.githubusercontent.com/45929526/56086911-d4312880-5e8a-11e9-8b8e-adc0430a1914.PNG)
![fmd3](https://user-images.githubusercontent.com/45929526/56086912-d4312880-5e8a-11e9-8c58-a98c8279fbdc.PNG)

**Comment by SDXC** [comment]
Ah cool, bacamanga.co is not region locked. That may be the reason why they changed their domain?

**Comment by SDXC** [comment]
Script has been updated. Issue will be closed.
